### ISSUE TITLE
Wrong time offset for America/Santiago

### ISSUE THREAD

**Issue by sebitoelcheater** [moment/moment-timezone#1001]
### Moment-timezone version which you use:

Version: 0.5.37

### Issue description:

According to this [site](https://www.timeanddate.com/time/map/?p1=232&p1txt=Santiago) (and my clock), time offset for Santiago is `-04:00` right now. But moment-timezone think it's `-03:00`.

```
tz(date + 'T' + time, 'America/Santiago').format();
```
 will have `-03:00` instead of `-04:00`.

[related](https://chocale.cl/2022/09/cambio-de-hora-se-deben-ajustar-los-relojes-este-fin-de-semana/)

**Comment by ichernev** [comment]
Yes, you're right, and it is correct. Not sure where you got `date` and `time` but you got it wrong:

```
moment().tz('America/Santiago').format()
'2022-09-07T03:40:11-04:00'
```

Switch to -3 is on 10th of Sept.

**Comment by sebitoelcheater** [comment]
@ichernev so where does `moment-timezone` takes the timezone from?
