### ISSUE TITLE
[Help] How to add timezone when using from browser

### ISSUE THREAD

**Issue by AlexandreRoba** [moment/moment-timezone#1006]
Dear all,

I have added the following links on the header (timezone with data):
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.4/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment-timezone/0.5.37/moment-timezone-with-data.min.js"></script>

When running my code:
<img width="193" alt="Screenshot 2022-09-20 at 10 45 38" src="https://user-images.githubusercontent.com/60746/191212236-8a421279-2842-457f-9aad-a670713f61e8.png">

I'm getting the errors:
<img width="475" alt="Screenshot 2022-09-20 at 10 47 13" src="https://user-images.githubusercontent.com/60746/191212541-76e00151-48e5-42b7-9721-893fcb417a0e.png">

According to the documentation I need to `add` the zone. But I do not understand how to do this.
I tried `moment.tz.add("Europe/Brussels")` but does not work.
I tried replacing the "Europr/Brussles" with the content from the data file but this seems insane? :( 
"Europe/Brussels|LMT BMT WET CET CEST WEST|-h.u -h.u 0 -10 -20 -10|.........." (Stripped for readability)
Still does not work.		
Why is the added value of adding the data in the link if I have to copy paste the content in the code? Any idea?
How should I do this? Thanks for any help.

**Comment by AlexandreRoba** [comment]
I found a way to add the time zone I guess:
```Javascript
const timezone = "Europe/Brussels";
moment.tz.add(moment.tz.zone(timezone));
```

But Iem still getting the error "Moment Timezone has no data..." Any idea? Thanks

**Comment by gilmoreorless** [comment]
I think the problem is that you're merging two different APIs together. To use Moment Timezone with a fixed date/time, you can do one of these:
```js
// Convert an existing moment to a new time zone
moment(date).tz(zoneName);

// Create a new moment with the right time zone (recommended for this use case)
moment.tz(date, zoneName);
```

Your code is calling...
```js
moment().tz(date, zoneName);
```
...which is trying to find a time zone named `"2022-09-21 07:00:00"`. Try changing `moment().tz` to `moment.tz` and it should work.
