### ISSUE TITLE
Jordhan DST Change

### ISSUE THREAD

**Issue by mrudulraj** [moment/moment-timezone#1008]
Hi,

Jordan's govt has decided to continue with GMT+3 timezone, but the current library Jordan's timezone will be set to GMT+2 from October 28th, 2022.

Do we have any release to address this issue?

Thanks
-Mrudul

**Comment by gilmoreorless** [comment]
We had to wait for the IANA tzdb 2022e update with the Jordan and Syria changes. This has now been released, so there'll be a new Moment Timezone version soon.

**Comment by gilmoreorless** [comment]
The Jordan DST change has been released in version `0.5.38`.
