### ISSUE TITLE
Incorrect Time Zone Future Dates

### ISSUE THREAD

**Issue by jawetzel** [moment/moment-timezone#1028]
**Describe the bug**
When using a future date that is within DST it is outputting the timezone of CST  instead of  CDT

**To Reproduce**
(<any>window)
        .moment((date)Wed Oct 25 2023 18:30:00 GMT-0500 (Central Daylight Time))
        .tz('America/Chicago')
        .format('z')

Outputs: 
CST

**Expected behavior**
When applying past dates it it outputting CDT as it should for future dates.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/13397788/208697446-1c1add02-9235-48b1-b3fa-cc1542b7b7f9.PNG)
![image](https://user-images.githubusercontent.com/13397788/208969504-9eb785db-bef4-437f-b7e7-1976b24b8f5a.png)

**Moment-specific environment**

* The time zone setting of the machine the code is running on
(UTC -06:00) Central Time (US & Canada)
Adjust for daylight savings - ON

* The time and date at which the code was run
9:02 AM CST 12/20/2022

* Other libraries in use (TypeScript, Immutable.js, etc)
Typescript

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)
```
![Outputs](https://user-images.githubusercontent.com/13397788/208698146-31de1d31-575c-4cbf-8512-bcd4303140d3.PNG)

**Comment by gilmoreorless** [comment]
Which version of Moment Timezone are you running, and how are you loading it? For example, `require('moment-timezone')` or `import moment from 'moment-timezone'` in Node, or using one of the pre-built JS bundles such as `moment-timezone-with-data-2012-2022.js`?

When I run this code with the latest Moment Timezone I get the correct value...

```js
// In Node.js via `TZ=America/Chicago node`

let date = new Date(2023, 9, 25, 18, 30);
date.toString();
// 'Wed Oct 25 2023 18:30:00 GMT-0500 (Central Daylight Time)'

moment(date).tz('America/Chicago').format('z');
// 'CDT'
```

...so I wonder if maybe there's some incomplete data in your project.

**Comment by jawetzel** [comment]
your a genius - that's exactly what's going on. 

its importing: 
"node_modules/moment-timezone/builds/moment-timezone-with-data-2012-2022.min.js"
