### ISSUE TITLE
tz function cause one day prior to the actual date

### ISSUE THREAD

**Issue by honglin-signo** [moment/moment-timezone#1032]
### Moment-timezone version which you use:

moment: 2.24.0
moment-timezone version: 0.5.27

_Note: many issues are resolved if you just upgrade to the latest version_

### Issue description:
There is timestamp: `2023-01-14` , I need to convert it according to different timezone. 

```
const testObj = moment('2023-01-14').tz('America/Chicago').format('dddd, MMM Do');
console.log(testObj) 
```
Expect `Saturday, Jan 14th `. When local machine set as PST or CST, I can get expect value.
But when I set local machine to EST, I'll get `Friday, Jan 13th`, there's one day prior to the actual date. 

I've test different timezone in tz(), it's nothing with timezone I input. But once I call tz() function and change local machine to EST, it will cause this bug.

**Comment by gilmoreorless** [comment]
When you provide just a date with no time, like `2023-01-14', it defaults to the start of the day (midnight). If your local time is EST, which is an hour ahead of `America/Chicago`, then converting to that zone will remove the hour's difference — resulting in 11pm on `2023-01-13`.
