### ISSUE TITLE
Moment-timezone Import Cost

### ISSUE THREAD

**Issue by bsaracalign** [moment/moment-timezone#1034]
### Moment-timezone version which you use:

Version: "^0.5.40"

_Note: many issues are resolved if you just upgrade to the latest version_

### Issue description:

Import cost for this package is 836.4k (gzipped:59.2k) that's an extremely large size. I understand there may be many reasons and even current development, Is there any place you share for current developments to decrease import cost of this package? Also I do import by `import moment from 'moment-timezone'` is there a more preferable import that'll help?

**Comment by gilmoreorless** [comment]
The overall package size is discussed at #999 — that's the best issue to follow to get updates.

To answer your other question, I've recently added some extra details into the [Node.js section of the documentation](https://momentjs.com/timezone/docs/#/use-it/node-js/). Specifically, if you want to avoid the default data file, you can do the following:

```js
import moment from 'moment-timezone/moment-timezone';
moment.tz.load(customData);
```

The custom data format is described in the [Data Loading section](https://momentjs.com/timezone/docs/#/data-loading/), and can be created in a local build step using the [filterLinkPack() utility method](https://momentjs.com/timezone/docs/#/data-utilities/filter-link-pack/).
