### ISSUE TITLE
Warn or error if 2012-2022 dataset is used?

### ISSUE THREAD

**Issue by fschwahn** [moment/moment-timezone#1035]
### Moment-timezone version which you use:

Version: 0.5.40

### Issue description:

I just spent a lot of time investigating why suddenly DST were not applied anymore in 2023, but still worked in the prior years (including, but not limited to digging through the [IANA changelog](https://github.com/eggert/tz/blob/main/NEWS)).

I included this file _years ago_, and I wasn't even aware anymore that there's such a thing as a limited dataset. I now replaced it with `moment-timezone-with-data-10-year-range`, which should be future-proof.

Ideally, there would be a way to raise an error, but I get that backwards compatibility concerns make that impossible. But maybe it's possible to at least log a big warning  in case this outdated dataset is used?

**Comment by gilmoreorless** [comment]
That's a great idea. The old 2012-2022 data file hasn't been linked on the project homepage for a long time, but has been kept in the package for backwards compatibility.

But now that it's 2023 that file is 100% obsolete. If there's ever a breaking-change release of this package, that file should be removed completely. Adding a deprecation warning now will help prepare for that. It shouldn't be too hard to modify the build/release process to add a warning to just that file.
