### ISSUE TITLE
Problem with tz methods and daylight change in America

### ISSUE THREAD

**Issue by adrianmarinwork** [moment/moment-timezone#1042]
### Moment version which you use:

Version: "moment": "^2.29.4",

### Moment-timezone version which you use:

Version: "moment-timezone": "^0.5.41"

### Issue description:

Hello, this past 12 of March in America they changed from -5 to -4 because of the daylight change.

Looks like when I run `moment.tz(date, timezone)` or `moment().tz(timezone)` it's still using the old offset (-5) and the date returned is wrong.

As an example, I'm from Spain and I've set my computer timezone to New York. As you will see in the screenshots, when I create the date with moment, it's using the correct offset, but when I use one of the methods mentioned above, it changes to the old offset, returning me a date that I don't want.

<img width="614" alt="Screenshot 2023-03-16 at 10 21 38" src="https://user-images.githubusercontent.com/118568289/225647488-67a44f1f-3829-46da-9cf8-d99b18417998.png">

<img width="366" alt="Screenshot 2023-03-16 at 10 23 53" src="https://user-images.githubusercontent.com/118568289/225647521-bf1d888a-e4f1-4ca2-8092-8b680853dcf1.png">

Do you know If I'm missing something or a way to fix this?
Thank you very much!

**Comment by aphix** [comment]
Hitting the same thing in both Central and Eastern timezones.

**Comment by gilmoreorless** [comment]
I'm having trouble reproducing this, but I'm probably just missing some context. To clarify:

1. Your computer is set to `America/New_York` time zone, then you're also converting the moment objects to that same zone. Is that correct, or have I misread your post?
2. How are you creating the original `moment` objects? Other bug reports have shown there's slightly different (buggy) behaviour depending on how the original object is created (e.g. `startDate = moment()` vs `startDate = moment(someString)` vs `startDate = moment(dateObject)` vs `startDate = moment.tz(date, zoneName)`)

**Comment by adrianmarinwork** [comment]
Thank you for answering @gilmoreorless!!!

Yeah thats right, for me to test it's easier if I move to the timezone that is having problems, so yeah, I'm basically changing the moment to the same timezone that I am. I'm in `America/New_York` and I'm converting the moment objects to the `America/New_York` timezone.

About the second question, I'm creating the original moment from this object doing this: `moment(objectInTheScreenshot).clone()`.  Let me do some tests to check If I'm having the same problem by creating the startDate with different methods as you mentioned.

<img width="1036" alt="Screenshot 2023-03-19 at 03 23 08" src="https://user-images.githubusercontent.com/118568289/226160302-1542708d-8403-4b83-a283-5f0b9ea26317.png">

**Comment by adrianmarinwork** [comment]
Okay I've created the different test to see how it's the behaviour between the way of creating the original moment.
I've probably done it wrong or I'm missing something because I've done it fast, but as you can see in the screenshot, except the last one (example created directly with the timezone) the others examples are using the timezone of my computer and they have an offset of -4, but when I apply the timezone `America/New_York`, the offset changes to -5.

<img width="722" alt="Screenshot 2023-03-19 at 03 36 05" src="https://user-images.githubusercontent.com/118568289/226160889-117cd000-d448-42f3-b394-cea048dd6510.png">

<img width="446" alt="Screenshot 2023-03-19 at 03 36 16" src="https://user-images.githubusercontent.com/118568289/226160896-d656619b-35fa-4243-a134-7382c4c327e8.png">

**Comment by gilmoreorless** [comment]
Hrm that's interesting. I've tried those examples and still get `-04:00` for all of them. I know sometimes there can be weird calculations when something else is interfering with the environment.

To help diagnose this, can you give me the output of these 3 values?

```js
moment.version;
moment.tz.version;
moment.tz.dataVersion;
```

I know you gave the version definitions in the opening description, but dependency weirdness doesn't always produce what we expect ([here's a good example](https://github.com/moment/moment-timezone/issues/982#issuecomment-1119540905)). Also, how are you including `moment-timezone` in your project? (e.g. package manager, CDN script tag, etc)

**Comment by adrianmarinwork** [comment]
Here you go, looks like the problem could be coming from the `moment.tz.version` and the `moment.tz.dataVersion`, but how is it that those two versions are pretty old when I've installed the new versions via NPM?

<img width="236" alt="Screenshot 2023-03-19 at 17 25 19" src="https://user-images.githubusercontent.com/118568289/226189906-c428efc3-8887-4335-ba5f-4ff90cd38611.png">

<img width="379" alt="Screenshot 2023-03-19 at 17 26 32" src="https://user-images.githubusercontent.com/118568289/226189922-60f8467e-6c12-4293-bc1d-0bbb29683b43.png">

**Comment by adrianmarinwork** [comment]
I've read the example that you linked in the message above, and I've run the `npm ls moment` command, this is the packages that use moment and all have the same version.

<img width="265" alt="Screenshot 2023-03-19 at 17 31 23" src="https://user-images.githubusercontent.com/118568289/226190336-9b0d469a-df08-40fc-a284-3e810127fc53.png">

**Comment by gilmoreorless** [comment]
That's odd — your `npm ls` output is showing `moment-timezone@0.5.41`, but `moment.tz.version` is showing `0.5.14`. I wonder if there's a second (older) copy of `moment-timezone` being brought in by another dependency, and that's what's being included? `npm ls moment-timezone` might show the culprit.

**Comment by adrianmarinwork** [comment]
Looks like the only version that I've installed of `moment-timezone` is the `0.5.41`.

<img width="197" alt="Screenshot 2023-03-20 at 08 04 03" src="https://user-images.githubusercontent.com/118568289/226269592-12490bf6-3571-4d5e-9762-3c7e1a51f201.png">

**Comment by adrianmarinwork** [comment]
Heeeeeeeey @gilmoreorless, I managed to update the `moment.tz.version` and `moment.tz.dataVersion`.

To add context, my application runs in Meteor framework, so I decided to do the next to see if it could fix the issue, it's probably no the best solution but it worked 😄. 
I uninstalled `moment` and `moment-timezone` from my project with the following commands:

```
npm uninstall moment
npm uninstall moment-timezone
meteor npm uninstall moment-timezone
meteor npm uninstall moment
``` 

After that I installed `moment-timezone` using the following command:
`meteor npm install moment-timezone`

As `moment-timezone` adds `moment` as a dependency, I have not installed the `moment` package.

Now if I run `npm ls moment`, `npm ls moment-timezone` and the three variables this is how it looks like (I'm also adding screenshots of the package.json and package-lock.json:

<img width="270" alt="Screenshot 2023-03-20 at 03 44 07" src="https://user-images.githubusercontent.com/118568289/226277236-8c586640-c380-47a0-a235-5733d2351c03.png">
<img width="197" alt="Screenshot 2023-03-20 at 03 44 15" src="https://user-images.githubusercontent.com/118568289/226277287-8f4934f2-ddcd-499c-b378-6f1f32260839.png">
<img width="243" alt="Screenshot 2023-03-20 at 03 44 40" src="https://user-images.githubusercontent.com/118568289/226277316-e6171cff-adb3-41b3-bb44-6e4b12223e42.png">
<img width="329" alt="Screenshot 2023-03-20 at 03 44 53" src="https://user-images.githubusercontent.com/118568289/226277340-200a2dd8-2031-4f35-b010-2e8b5f815902.png">
<img width="964" alt="Screenshot 2023-03-20 at 03 45 10" src="https://user-images.githubusercontent.com/118568289/226277356-18709e49-0a89-4298-82df-9393e2928351.png">

**Comment by adrianmarinwork** [comment]
I've reverted the changes to do more testing and see where the problem was and looks like it was that `npm install moment-timezone` updated my `package.json` and `package-lock.json` and was changing the versions installed but wasn't really taking effect in the Meteor version installed or something like that.

Because if I run `meteor npm install moment-timezone` now it shows the correct `moment.tz.version` and `moment.tz.dataVersion`. Things in how Meteor works I suppose.

If I apply this change except of the one I sent in the message above, the thing is that I have installed `moment` with a different version, what do you think is the best solution? I prefer the first one (getting rid of everything and install `moment-timezone`) in the future will give less problems I think.

<img width="268" alt="Screenshot 2023-03-20 at 04 04 57" src="https://user-images.githubusercontent.com/118568289/226281045-c266304e-05c3-437d-a968-17482b08d334.png">
<img width="196" alt="Screenshot 2023-03-20 at 04 05 02" src="https://user-images.githubusercontent.com/118568289/226281069-e59f9af2-dec3-4725-b094-3e497a41f628.png">

**Comment by gilmoreorless** [comment]
Ah good to see you found the issue! Dependency problems are inconsistent in appearance, but consistently annoying. 😆 

I haven't used Meteor before, so I'm not sure how its internal dependency mechanism works. Something to note, though, is that we're planning to [remove the automatic dependency on `moment` at some point](https://github.com/moment/moment-timezone/issues/1039). That would you'll have to add `moment` manually anyway.

**Comment by adrianmarinwork** [comment]
Just to add if someone with the same problem comes here, in order that this fix works, you have to install `moment-timezone` before installing `moment`, for some reason when you install `moment` first the `moment.tz.version` and `moment.tz.dataVersion` are the old ones.

If you install first `moment-timezone` it works fine.

**Comment by leo-li-ls** [comment]
> Just to add if someone with the same problem comes here, in order that this fix works, you have to install `moment-timezone` before installing `moment`, for some reason when you install `moment` first the `moment.tz.version` and `moment.tz.dataVersion` are the old ones.
> 
> If you install first `moment-timezone` it works fine.

Hi @adrianmarinwork, I have the same issue and tried your solution, but it doesn't help.

I found a temporary solution:

```
// Replace this code below
const wrongDatetime = moment.tz(timeZone);

// By this one
const currentTime = new Date().toLocaleString("en-US", {timeZone});
const currentDate = new Date(currentTime);
const correctDatetime = moment(currentDate.toISOString());

console.log({
    wrongToday,
    correctToday
});
```

It will output:

```
{
    "wrongDatetime": "2023-03-27T13:56:09-05:00",
    "correctDatetime": "2023-03-27T14:56:09-04:00"
}
```

**Comment by sslincoco** [comment]
您的邮件已收到,我会尽快给您回复。

**Comment by washu** [comment]
this isnt working for me.

**Comment by adrianmarinwork** [comment]
Right now I'm using the `0.5.41` version of `moment-timezone` and the last version of `moment`, I tried to update my `moment-timezone` to the version `0.5.42` and it's true that the fix that we mentioned in this thread does not work. That's why I haven't updated my `moment-timezone`, I'm not sure what could be happening tbh.
