### ISSUE TITLE
Incorrect offset noticed（PDT）

### ISSUE THREAD

**Issue by lxx17801079147** [moment/moment-timezone#1050]
### Moment-timezone version which you use:

Version: 0.5.42

_Note: many issues are resolved if you just upgrade to the latest version_

### Issue description:
Asia/Beirut 
Switched to UTC+3 / Pacific Daylight Time (PDT) On March 26th, 2023, ❌Not April 21st, 2023

**Comment by gilmoreorless** [comment]
This has been fixed in version `0.5.43`.
