### ISSUE TITLE
Timezone America/Monterrey not properly updated to UTC-5

### ISSUE THREAD

**Issue by perlucas** [moment/moment-timezone#1055]
### Environment

Run on Mac OS Monterey v12.5.1

```
{
  moment: '2.29.4',
  momentTz: '0.5.43',
  date: 'Mon Apr 10 2023 16:43:17 GMT-0300 (Argentina Standard Time)',
  intlZone: 'America/Buenos_Aires'
}
```

### Issue description
On April 2nd, the "America/Monterrey" timezone shifted from UTC-6 to UTC-5, but running the code below still gives me `8:00 AM`. It should be `9:00 AM`.
```
moment("2023-04-04T14:00:00.000Z").tz("America/Monterrey").format('h:mm A')
```

![Screen Shot 2023-04-10 at 16 48 29](https://user-images.githubusercontent.com/58793996/230984828-78e3f851-7e1d-48e5-ae04-069f727943a7.png)

**Comment by aldinicontini** [comment]
Yes, same issue

**Comment by gilmoreorless** [comment]
> On April 2nd, the "America/Monterrey" timezone shifted from UTC-6 to UTC-5

Last year, Mexico got rid of daylight saving time in _most_ (but not _all_) states/regions. https://www.timeanddate.com/news/time/mexico-abolishes-dst-2022.html
Only some of the towns right on the border with USA will continue with DST. Monterrey is not one of those towns, so it is on UTC-6 all year round: https://www.timeanddate.com/time/change/mexico/monterrey
Therefore, this code is correct.

**Comment by mauricio-testa** [comment]
Mexico time is also wrong
![image](https://user-images.githubusercontent.com/14204670/231823150-9fbf92c8-0643-4303-b2f0-96cfe7fb465b.png)

**Comment by gilmoreorless** [comment]
@mauricio-testa That screenshot doesn't really tell me anything. You could be running a completely different version of `moment-timezone` from the opening post in this issue — one that's older and doesn't have the updated zone rules. Running that same code in the console on https://momentjs.com gives the correct offset of `-06:00`.

**Comment by AlejandroAlt** [comment]
@perlucas did you solve it? I have a similar problem with America/Mexico_City.

**Comment by mexchip** [comment]
The minimum required version for the America/Mexico_City update is 0.39.

**Comment by luis83rs** [comment]
Right now Mexico_City is supposed to be -06:00 but moment-timezone is returning -05:00. With .43 version:

![image](https://github.com/moment/moment-timezone/assets/2023710/e062eb79-6aee-42e4-a9f1-b622ccf8db43)
