### ISSUE TITLE
moment.tz returns undefined

### ISSUE THREAD

**Issue by NagarajNN** [moment/moment-timezone#1056]
![image](https://user-images.githubusercontent.com/115421636/232340411-4a0457d3-00a5-41ba-9dc6-14eba5b6a62c.png)

Original Error : 

cannot read properties of undefined (reading 'load')  error TypeError: Cannot read properties of undefined (reading 'load')
 
![image](https://user-images.githubusercontent.com/115421636/232340463-63da209f-aa8d-42ad-87f8-adcbe792c3fb.png)

**Comment by gilmoreorless** [comment]
There isn't much in this report to help diagnose the issue, unfortunately. Given the mention of `ember-moment` in the filepath, I'm guessing this is a problem with the Ember environment. I haven't used Ember at all, though, so I can't be sure what it might be.

**Comment by NagarajNN** [comment]
@gilmoreorless  this is issue is related to target build in ember-js. thanks for your help! I'm closing this now!
