### ISSUE TITLE
Unable to convert Device timezone

### ISSUE THREAD

**Issue by gkasireddy202** [moment/moment-timezone#1060]
Hi,

I have a date: 05/08/23 05:19 PM. I need to convert the date to Asia/Kolkata.
Unable to convert my device's timezone.
My device timezone is Asia/Kolkata

var dateString = "05/08/23 05:19 PM"; - This date and time is in America/Chicago
var dateValue = moment(dateString).tz('Asia/Kolkata').format('DD-MMM-YYYY LT');
console.log(dateValue);- Output is in Asia/Kolkata 08-May-2023 5:19 PM.

**Comment by gilmoreorless** [comment]
If your device is in `Asia/Kolkata`, then the library has no way of knowing the time zone of the input string unless you explicitly tell it. You'll have to provide the zone alongside the input, _then_ convert it to the correct zone:

```js
moment.tz(dateString, 'America/Chicago').tz('Asia/Kolkata');
```

Additionally, when you're parsing a non-standardised format like that input, Moment logs a warning. It's best to [explicitly state the format](https://momentjs.com/guides/#/parsing/known-formats/) of the input when parsing, to avoid cross-platform bugs:

```js
var dateValue = moment.tz(dateString, 'MM/DD/YY LT', 'America/Chicago')
  .tz('Asia/Kolkata')
  .format('DD-MMM-YYYY LT');
// "09-May-2023 3:49 AM" 
```
