### ISSUE TITLE
Egypt now in daylight savings which are not included in TZ data

### ISSUE THREAD

**Issue by donengel** [moment/moment-timezone#1063]
Egypt has regularly changed their rules regarding daylight savings and did so again in March, with the newly established daylight savings having started a few weeks ago on April 28th. Moment does not currently take the new daylight savings into account (i.e., as of 2023c.json). I think this data might get pulled into moment-timezone from the TZDB data file, which (as of this writing) is still on 2023c, as well.

This was an issue previously here: https://github.com/moment/moment/issues/1721
The latest change by Egypt is described here: https://www.timeanddate.com/time/zones/eest

**Comment by gilmoreorless** [comment]
These new rules were added in IANA release `2023b`, which was included in Moment Timezone `0.5.42`: #1047.

```js
moment.tz.version;
// "0.5.43"
moment.tz('2023-04-27', 'Africa/Cairo').format();
// "2023-04-27T00:00:00+02:00"
moment.tz('2023-04-28', 'Africa/Cairo').format();
// "2023-04-28T01:00:00+03:00" 
```
