### ISSUE TITLE
The parser may not ignore non-alphanumeric characters when it is with time zone. 

### ISSUE THREAD

**Issue by worldwidepark** [moment/moment-timezone#1068]
### Environment

system time zone - morocco.
default time zone - japan. 

doc says ↓ but, The parser may not ignore non-alphanumeric characters when it is with time zone. 
![image](https://github.com/moment/moment-timezone/assets/83998627/c6124c48-4ca4-4396-9679-3a3691279a49)

For bug reports, please run the following code in your environment and include the output:

date format diffrence make difference of time zone.
check code below
```javascript
// system time zone - morocco.
// default time zone - japan. 
moment("2023/06/01 00:00:00").format() 
// result "2023-05-31T00:00:00+01:00"
// "2023/06/01" -> dose not follow default time zone. 
moment("2023-06-01 00:00:00").format()
// result "2023-05-31T00:00:00+09:00"
```

**Comment by gilmoreorless** [comment]
The part of the documentation you've quoted only applies when providing a `format` argument after the input, which is not what your code examples are doing. Calling `moment(inputString)` _without_ a known format [can have problems](https://momentjs.com/docs/#/parsing/string/):

> **Warning:** Browser support for parsing strings [is inconsistent](http://dygraphs.com/date-formats.html). Because there is no specification on which formats should be supported, what works in some browsers will not work in other browsers.
>
> For consistent results parsing anything other than ISO 8601 strings, you should use [String + Format](https://momentjs.com/docs/#/parsing/string-format/).

When I try your first example I get a big warning in the console:

```
> moment("2023/06/01 00:00:00").format() 

Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
```

Providing a format argument works as expected
(e.g. `moment("2023/06/01 00:00:00", "YYYY-MM-DD hh:mm:ss").format()`).

Also, when a bug report template says "please run the following code in your environment and include the output", please actually follow the instructions. The debug info makes it much easier to diagnose problems quickly.
