### ISSUE TITLE
Australian timezones not correct?

### ISSUE THREAD

**Issue by mikehdt** [moment/moment-timezone#108]
Hi,

I'm not sure if Moment is using a different standards system, and I'm certainly no expert on timezone systems - but as an Australian, I'm used to referring to the eastern timezone as AEST (UTC+10), so it's not confused with the US EST (UTC-5). For the states such as Victoria and NSW which observe daylight savings (Queensland does not), the timezone becomes AEDT (UTC+11).

At the moment, Moment refers to both as EST, whether daylight savings is being observed or not (EST as +10 and also EST as +11, which is really confusing!).

Official-ish Australian government reference of timezones can be found here:
http://australia.gov.au/about-australia/our-country/time

Thanks!

**Comment by monicaraghuwanshi** [comment]
@timrwood  this issue seems to be happening again. I am getting (+11:00 UTC) Australia/Sydney . Please help me out.

**Comment by cnacode** [comment]
@timrwood we also have the same issue, some Australian states do not observe daylight savings but are included none the less.

**Comment by darrylsepeda** [comment]
and now 2023, I bumped into the same issue from 9 years ago

**Comment by gilmoreorless** [comment]
@darrylsepeda Double check if your project is including a file called `moment-timezone-with-data-2012-2022.js` (or `.min.js`). You might need to switch to a different file source, see https://github.com/moment/moment/issues/6111#issuecomment-1501105788 for more details.
