### ISSUE TITLE
2023d is out

### ISSUE THREAD

**Issue by tmkx** [moment/moment-timezone#1083]
### Issue description

Timezone database 2023d (Released 2023-12-21) is released

https://www.iana.org/time-zones

**Comment by gilmoreorless** [comment]
For anyone else wondering about this, there seems to be a bug in the data update process with this latest release. Some zones in `moment-timezone` are getting changed without a related change in the IANA database. I'm looking into a fix.

**Comment by gilmoreorless** [comment]
Released in `0.5.44`
