### ISSUE TITLE
Canada/Yukon offset before 1967 May 27 is wrong

### ISSUE THREAD

**Issue by hawkchen** [moment/moment-timezone#1087]
### Environment

```js
{
    "moment": "2.29.4",
    "momentTz": "0.5.43",
    "date": "Fri Jan 05 2024 12:14:19 GMT+0800 (Taipei Standard Time)",
    "intlZone": "Asia/Taipei"
}
```

### Issue description
* I load 2023d.json
`moment.tz('1967-04-01', 'Canada/Yukon').utcOffset();` returns -480
but according to https://www.sunrisesunset.com/timezones.asp

1900 Aug 20 | 1967 May 27 | -9:00 | none

it should be -9:00

* Compare the same time zone offset in java
```java
        ZoneId zoneId = ZoneId.of("Canada/Yukon");
        ZonedDateTime dateTime = LocalDateTime.of(1967, Month.MAY, 1, 0, 0).atZone(zoneId);
        System.out.println(dateTime.getOffset().toString());
```
it's `-09:00`

* I have tried 0.5.44, but it has the same problem.

If my finding is correct, is there a way to patch this problem?

**Comment by gilmoreorless** [comment]
The [IANA release 2022g](https://mm.icann.org/pipermail/tz-announce/2022-November/000076.html) updated past timestamps for this region:

```
Changes to past timestamps

    Changes for pre-1996 northern Canada (thanks to Chris Walton):

      Merge America/Iqaluit and America/Pangnirtung into the former,
      with a backward compatibility link for the latter name.
      There is no good evidence the two locations differ since 1970.
      This change affects pre-1996 America/Pangnirtung timestamps.

      Cambridge Bay, Inuvik, Iqaluit, Rankin Inlet, Resolute and
      Yellowknife did not observe DST in 1965, and did observe DST
      from 1972 through 1979.

      Whitehorse moved from -09 to -08 on 1966-02-27, not 1967-05-28.
```

(`Canada/Yukon` is an alias of `America/Whitehorse`)

Moment Timezone is using the latest known data. The other references you've found presumably haven't updated yet.
