### ISSUE TITLE
construct moment in zone

### ISSUE THREAD

**Issue by mattjohnsonpint** [moment/moment-timezone#11]
This creates the moment in local time:

```
moment("2013-01-01T00:00:00")
```

This creates the moment in UTC:

```
moment.utc("2013-01-01T00:00:00")
```

So I would expect to be able to create a moment in a particular zone with:

```
moment.tz("America/New_York","2013-01-01T00:00:00")
```

That gives an error, so I tried this:

```
moment.tz("2013-01-01T00:00:00", "America/New_York")
```

And it works, but gives a result of `2013-01-01T02:00:00-05:00`.  I would expect `2013-01-01T00:00:00-05:00`.

I think it is assuming the input value is in my local offset (-07:00) and then converting it to the time zone specified.

All together, I'd expect to be able to convert from time zone A to time zone B like this:

```
moment.tz("2013-01-01T00:00:00","America/New_York").tz("America/Los_Angeles").format()
```

Also - we need a way to deal with ambiguous or invalid input times.

**Comment by contra** [comment]
How about supporting parsers?

```js
moment.tz('Tuesday 9:00PM', 'dddd hh:mm', 'America/Los_Angeles')
```

I don't think this works currently

**Comment by mj1856** [comment]
@contra - It's supported.  It's [in the documentation actually](http://momentjs.com/timezone/docs/#/using-timezones/parsing-in-zone/):

```javascript
var b = moment.tz("May 12th 2014 8PM", "MMM Do YYYY hA", "America/Toronto");
```

I think the problem is just that your format string doesn't match the input.  Try `'dddd h:mma'`

**Comment by alanhamlett** [comment]
This looks like a bug:

    moment.tz('03/06/2015', 'America/Los_Angeles').format();
    "2015-03-06T00:00:00-08:00"

**Comment by alanhamlett** [comment]
Nevermind, specifying a format string fixes it:

    moment.tz('03/06/2015', 'MM/DD/YYYY', 'America/Los_Angeles').format();
    "2015-03-06T00:00:00-08:00"

**Comment by qbAnu** [comment]
Hi,

To convert a UTC date string to a specified timezone in a formatted manner, I tried the below:
`moment.tz("2016-04-11T03:07:06.000+0000", "MMM DD YYYY hh:mm:ssA", "Europe/Berlin").format()`

But the result was:
`"Invalid date"`

How come!!! As, `new Date("2016-04-11T03:07:06.000+0000")` returns `Mon Apr 11 2016 08:37:06 GMT+0530 (IST)` 

Help me please!!! 

I do not find moment-timezone converting UTC dates to proper timezone-dates. There always seem to be a 1 hr difference. :'( :'(

**Comment by mj1856** [comment]
@qbAnu - Please do not comment on old issues to ask for help.  As you can see, your question was easily overlooked.

For the specific issue you mention, it's because you're supplying an import format that doesn't match the input.  You probably meant that to be an output format, as in:

```javascript
moment.tz("2016-04-11T03:07:06.000+0000", "Europe/Berlin").format("MMM DD YYYY hh:mm:ssA")
// "Apr 11 2016 05:07:06AM"
```

I'm not sure what you mean on the last sentence.  But please, if you need help then either open a new issue or ask on Gitter. Thanks.
