### ISSUE TITLE
Wrong Kazakhstan Timezone in 0.5.45

### ISSUE THREAD

**Issue by m-urukov** [moment/moment-timezone#1100]
Hello!
We are using the latest version 0.5.45. 
Since March 1, 2024, Kazakhstan(Asia/Almaty + Asia/Qostanay) will switch to a single time zone (from UTC+06:00 to UTC+05:00).

`moment.tz("2024-01-01", "Asia/Almaty").format(); // => '2024-01-01T00:00:00+06:00'` (✅)

`moment.tz("2024-05-05", "Asia/Almaty").format(); // => '2024-05-05T00:00:00+06:00'` (❌)

I checked the data in [IANA TZDB 2024a](https://www.iana.org/time-zones), everything is correct:
<img width="801" alt="image" src="https://github.com/moment/moment-timezone/assets/48118446/f06adbb9-f868-41a3-9d7b-cb3098b0f64c">

Did an error occur while preparing `moment-timezone-with-data-10-year-range`?
Thank you.

**Comment by RodiNikolaev** [comment]
@m-urukov Why did you close this issue? Is it correct now?
