### ISSUE TITLE
Getting spilt issue while using moment and moment-timezones

### ISSUE THREAD

**Issue by AdityaSharma1407** [moment/moment-timezone#1104]
useEffect (() => {
      let getZones  =  moment.tz.zonesForCountry('US')
      console.log(getZones)
    },[])  
    
    Just trying to get the US zones   in react project 
    
    
    moment  -v : 2.30.1
    moment-timezone : 0.5.45

**Comment by gilmoreorless** [comment]
You haven't given any details of what the problem is. Your example code (excluding the `useEffect` call) works just fine in the console on https://momentjs.com/timezone/
