### ISSUE TITLE
Weird issue: moment-timezone is subtracting 1 hour from every timezone

### ISSUE THREAD

**Issue by adrianmarinSH** [moment/moment-timezone#1108]
Hello, I have found a weird issue happening in my project with moment-timezone, for some reason when I change the timezone or I want to get the current date formatted in another timezone the date is being returned with 1 hour subtracted.

It seems like if the library or something got stuck in day-light change or something like that and is returning weird dates.

I would like to see if someone could help me and tell me if they have had the same problem or know how to fix it.

I have tried to update the `moment` and `moment-timezone` libraries to the last versions but the problem keeps happening.

In the example I'm using the method `moment(date).tz(timezone).format()` I have also tried using `moment.tz(date, timezone).format()` but the issue is the same.

Thanks!!!

 
![Screenshot 2024-06-13 at 17 40 18](https://github.com/moment/moment-timezone/assets/129066543/527675fe-2b43-4638-9fdd-4869cb2025d0)

**Comment by sslincoco** [comment]
您的邮件已收到,我会尽快给您回复。
