### ISSUE TITLE
2024b

### ISSUE THREAD

**Issue by er0k** [moment/moment-timezone#1119]
Hi there, any ETA on when 2024b will be available? Thanks.

**Comment by gilmoreorless** [comment]
The blunt answer is that there was a problem with the automated build that generates the new data updates, and I haven't had time to look into it properly yet.

Is there an urgency in getting the new data? My understanding is that 2024b only affects historical timestamps, and nothing in the future. There'll also likely be a 2024c soon, as at least 3 countries are putting DST change proposals through their parliaments at the moment.

**Comment by er0k** [comment]
No urgency, just something that got picked up in our automation as IANA released 2024b on 2024-09-04 🤖 I appreciate the quick response, thanks!

**Comment by gilmoreorless** [comment]
`2024b` is now released in version `0.5.46`.

**Comment by er0k** [comment]
Thank you!
