### ISSUE TITLE
Duplicate entry of Prague city, one in Slovakia and other in Czech Republic

### ISSUE THREAD

**Issue by krishna-gokidi** [moment/moment-timezone#1123]
### Issue description

In our production environment we are using latest moment-timezone package and noticed the prague city is visible in 2 different places, so I verified the package repository and found that there are 2 entries in moment-timezone-with-data.js. below are the etry details.
1)  "CZ|Europe/Prague",
2)  "SK|Europe/Prague Europe/Bratislava",

Prague should be under CZ only not in SK.

Can you please verify from your end and do the necesary changes?

![image](https://github.com/user-attachments/assets/a5dfdcde-9191-4880-9e5a-bc2c92985839)  (Correct place)
![image](https://github.com/user-attachments/assets/e2bdbe9b-8939-48e5-93b5-f0c91783916a) (Wrong entry)

Please find the screen shot with 2 entries( Correct and Wrong )

**Comment by gilmoreorless** [comment]
See https://github.com/moment/moment-timezone/issues/1066#issuecomment-1574578959
