### ISSUE TITLE
Moment.cs class for C# .Net

### ISSUE THREAD

**Issue by milocabs** [moment/moment-timezone#130]
I am dealing with a problem on converting the timezones in the backend. The timezone in moment.js doesn't coincide with the .Net TimeZoneInfo when using TimeZoneInfo.FindSystemTimeZoneById

I hope moment can create a class that would support the conversions in the backend

**Comment by mj1856** [comment]
FYI - My [TimeZoneConverter](https://github.com/mj1856/TimeZoneConverter) C# library may be useful to folks working with C# `TimeZoneInfo` on the back end and moment-timezone on the front end.
