### ISSUE TITLE
moment.tz is undefined

### ISSUE THREAD

**Issue by c-project** [moment/moment-timezone#136]
we are using dojo in the project and moment-timezone does not work because it use "define()" method when it should use "require()"
https://bugs.dojotoolkit.org/ticket/16414?cversion=1&cnum_hist=14 this is about moment.js but it works for *-timezone too

**Comment by gilmoreorless** [comment]
I'm closing off stale issues as they're very difficult to reproduce (e.g. the linked Dojo bug report gives a 404), and this project is now in maintenance-only mode. Feel free to open a new issue if this is still a problem.
