### ISSUE TITLE
Get the browsers current time zone.

### ISSUE THREAD

**Issue by niemyjski** [moment/moment-timezone#138]
Unless I'm missing something it seems that there is no way to get the current time zone?? I know there are third party libs to get the olson name.. I just thought this would be included.

   moment.tz().zoneName()
   moment.tz(new Date()).zoneName()
   moment.tz(new Date()).zone()

**Comment by kashifshamaz21** [comment]
@elad Did you get a chance to wire up a working protoype for this feature.. I can give it a shot, if you haven't done a lot of progress on it already. Thanks!

**Comment by elad** [comment]
@kashifshamaz21 please do! Unfortunately I haven't had a chance to get to it yet. :(

**Comment by softBarbarian** [comment]
Hello, 
This feature would be awsome!
+1000

**Comment by RouR** [comment]
Check this code
http://stackoverflow.com/questions/19420582/detect-the-id-of-the-current-user-timezone-using-moment-js
https://github.com/Canop/tzdetect.js

```javascript
var tzdetect = {
    names: moment.tz.names(),
    matches: function(base){
        var results = [], now = Date.now(), makekey = function(id){
            return [0, 4, 8, -5*12, 4-5*12, 8-5*12, 4-2*12, 8-2*12].map(function(months){
                var m = moment(now + months*30*24*60*60*1000);
                if (id) m.tz(id);
                return m.format("DDHHmm");
            }).join(' ');
        }, lockey = makekey(base);
        tzdetect.names.forEach(function(id){
            if (makekey(id)===lockey) results.push(id);
        });
        return results;
    }
};
```

If you just want one timezone id, simply use 
    var tzid = tzdetect.matches()[0];

**Comment by mj1856** [comment]
I love the idea of having a function that can be used directly against the moment-timezone data, rather than jsTimeZoneDetect, which has it's own data.  However, I'm not convinced that the Canop/tzdetect solution is complete enough to be useful.

Running it on my computer, which is Windows 8.1, Chrome latest, in US Pacific time, I get:

```javascript
["America/Dawson", "America/Ensenada", "America/Los_Angeles", "America/Tijuana",
 "America/Vancouver", "America/Whitehorse", "Canada/Pacific", "Canada/Yukon",
 "Mexico/BajaNorte", "PST8PDT", "US/Pacific", "US/Pacific-New"]
```

jsTimeZoneDetect gives the correct result of `America/Los_Angeles`.

I'd love to be proven wrong, but I'm fairly certain that any solution other than the Ecma Intl API (in supported browsers) will have problems.  The mere fact that ECMAScript 5.1 hides all non-current DST transitions makes it near impossible to properly interrogate the `Date` object for time zone information.

**Comment by emorikawa** [comment]
Until this gets fixed you can use `Intl.DateTimeFormat().resolvedOptions().timeZone` on latest Chrome & FF

**Comment by mj1856** [comment]
@emorikawa - Chrome, yes.  FF - no.   I also believe it works in Opera, but not IE.  Not sure about Safari.

**Comment by pierre-b** [comment]
+1 ! with todays SaaS apps displaying analytics everywhere it's a must-have feature. Thank you if you cant make it !

**Comment by austinpray** [comment]
Gonna try and jump in and implement this. I have a lot of docs to read to orient myself though. @elad @timrwood if you have any updates other than what you have specified above let me know!

**Comment by timrwood** [comment]
I opened a PR for this at #220.

**Comment by bcherny** [comment]
@mj1856 good call on `Intl.DateTimeFormat().resolvedOptions().timeZone`!

**Comment by gnansu** [comment]
@timrwood I'm using moment-timezone 0.3.0. Is the capability of getting client/browser timezone implemented? I'm currently using jstz-detect to detect the timezone (Country/City) and using that with moment.tz.* functions.

**Comment by mj1856** [comment]
@gnansu - no, it is not yet implemented in the release.  You can try the code in PR #220, but we've still got some things to work out before we are ready to merge and release it.

**Comment by gnansu** [comment]
@mj1856 Thanks Matt for the information. Looking forward to the new additions.

**Comment by avetisk** [comment]
> Fortunately, this can be a one-time calculation, as the user's timezone won't change without a refresh.

@timrwood that's not true all the time: try on Chrome (OSX), it will update the timezone dynamically without refresh.

**Comment by timrwood** [comment]
@avetisk, that's a bummer, we'll have to add some cache checks to make sure we aren't getting stale data.

**Comment by timrwood** [comment]
Closing in favor of https://github.com/moment/moment-timezone/pull/220

**Comment by argb** [comment]
Have implemented this feature,i noted that is issue have been posted more than one year,but i can find any info about this in moment-timezone's documents.

**Comment by TWiStErRob** [comment]
@argb is right, @timrwood @mj1856 this was closed in favor of #220. #220 is now closed because it was moved to #256 which is merged, but only to [`guess-timezone`](https://github.com/moment/moment-timezone/tree/guess-timezone). I just saw there's progress (#274), but there's no open tracking issue for this as a feature, or is there?

**Comment by timrwood** [comment]
This has been released in `moment-timezone@0.5.0` as `moment.tz.guess()`.

**Comment by Ihs88999** [comment]
@timrwood  I tried using moment.tz.guess() it works however it doesn't detect it automatically the page has to reload first. is there a way to get the timezone immediately without having to reload the page?

**Comment by mj1856** [comment]
@Ihs88999 - There's nothing special about that function in terms of loading.  Perhaps you just aren't loading moment and moment-timezone correctly?  We don't know anything about your code or environment, so it's hard to say.

**Comment by kevinSuttle** [comment]
@timrwood Suggestions for how to use this outside the browser?

**Comment by bcherny** [comment]
@kevinSuttle process.env.TZ

**Comment by Husterknupp** [comment]
@bcherny is there a trick to get TZ on OSX?

    $ node
    > process.env.TZ
    undefined


I'm using OS X 10.11.6

    $ node --version
    v5.4.1

**Comment by bcherny** [comment]
Looks like OSX doesn't define it. I just published [node-timezone](https://www.npmjs.com/package/node-timezone), which I tested on OSX and Ubuntu.

**Comment by kevinSuttle** [comment]
This works for me inside of Webpack: https://github.com/moment/moment-timezone/issues/138#issuecomment-77792958
