### ISSUE TITLE
Abbreviations should disambiguate in fall-back transitions

### ISSUE THREAD

**Issue by mattjohnsonpint** [moment/moment-timezone#144]
Considering that we know about time zone abbreviations - at least as defined by IANA:

``` javascript
moment.tz('2014-07-01T00:00:00','America/New_York').format('z') // "EDT"
```

We _should_ be able to use them to disambiguate:

``` javascript
var format = "ddd MMM D HH:mm:ss z YYYY";
var tz = "America/New_York";
moment.tz("Sun Nov 2 01:00:00 EDT 2014", format, tz).format('z')  // "EDT"
moment.tz("Sun Nov 2 01:00:00 EST 2014", format, tz).format('z')  // "EDT" (wrong)
```

In both cases, the result is `"EDT"`.

Note that if we instead use a numeric offset, then we can disambiguate without issue.

``` javascript
var format = "ddd MMM D HH:mm:ss Z YYYY";
var tz = "America/New_York";
moment.tz("Sun Nov 2 01:00:00 -0400 2014", format, tz).format('z')  // "EDT"
moment.tz("Sun Nov 2 01:00:00 -0500 2014", format, tz).format('z')  // "EST"
```

While time zone abbreviations can be ambiguous, we should at minimum recognize the ones that we use for output - if and only if we are in a fall-back ambiguity.

**Comment by gilmoreorless** [comment]
Closing this given the maintenance mode status of the project.
