### ISSUE TITLE
change default timezone

### ISSUE THREAD

**Issue by fabriziofortino** [moment/moment-timezone#15]
It would be great to have a method to change the default timezone (eg: when the application starts ```moment.tz.setDefault('America/New_York')```). Then, all the subsequent calls to ```moment()``` will automatically set the timezone with the default one.

**Comment by timrwood** [comment]
This has been released as `moment-timezone@0.3.0`.

**Comment by BlueHayes** [comment]
Fantastic, thanks!

The only downside is that for people who just want to make the default timezone UTC such as myself, we have to load in moment-timezone. I'm going to continue using moment.utc() for now, it would be nice if there was a separate option for moment to make UTC the default rather than calling moment.utc() each time. I'm not sure how many people would actually want such functionality though, plus I guess moment-timezone is small enough to pull in without worrying about it much.

**Comment by troydemonbreun** [comment]
Agree with @BlueHayes.  I just need to set default timezone, but have no other need for moment-timezone.  It would be awesome to just have setDefaultTimeZone() in moment.

**Comment by elad** [comment]
@BlueHayes, @troydemonbreun: Please open a different issue for this feature in the moment project, this one is about setting an arbitrary default time zone.

The implementation should be easy and I don't mind doing that as well if it's desired, so feel free ping me from the new issue. :)

**Comment by rinatio** [comment]
Agree with @BlueHayes and @troydemonbreun

**Comment by theguxi** [comment]
+1

**Comment by vladkornea** [comment]
I've been using this for about a year now, works great.

moment.mytz = function(){
	var newArguments = Array.prototype.slice.call(arguments)
	newArguments.push(moment.myTimezone)
	return moment.tz.apply(moment, newArguments)
}
moment.myTimezone = 'America/New_York' // default, change at runtime as needed

Usage example:

var exampleMoment = moment.mytz('2015-05-03 10:03:00')

**Comment by aaronahearne** [comment]
+1

**Comment by coreyzev** [comment]
Updated solution for just in moment.js without moment-timezone:

This is what i'm doing now, right after I call moment, I call this:

```javascript
var tz_offset = -7;
moment.updateOffset = function (m) {
    return m.utcOffset(tz_offset);
};
```

every moment created after that is in the correct timezone.

**Comment by mj1856** [comment]
@coreyzev - be very careful.  A single number can only represent the offset for a specific instant in time.  You server might give you -7 or -8 depending on when DST is *currently* in effect, but that may or may not be the correct offset for the value you are working with in the `moment` object.

Example, in US Pacific Time, it's currently `2015-10-24T13:00:00-07:00`.  If my server sends `-7` to the client, but then in the client I am working with a different date and time, such as `moment('2015-11-02T13:00:00').utcOffset(-7)`, then I have incorrectly applied `-7`, as the correct offset for *that* date should be `-8`.

**Comment by Shobana16** [comment]
hi can someone help me pls? 
Currently we are displaying timestamp in GMT. 
Now I am trying to display the timestamp in PDT format. 
tried with  $('#start_time').val((moment().tz(($('#fStartDate').val()),'America/Los_Angeles').format("YYYY-MM-DDTHH:mm:ss"))+'Z');

here am getting the time and date in UTC. also tried with local time. but in both cases i couldnt get PDT time. if removed UTC in fStartDate func, then i get local time. but even used tz am not getting PDT time. Please help me what need to be done to show the time stamp in PDT with moment timezone. also tried by setting default timezone but that too doesnt work.

**Comment by mj1856** [comment]
@Shobana16 - I see many things wrong in that code. But commenting on a unrelated and closed issue is not the way to ask for help.  Your best bet is to ask at stackoverflow.com and tag your question with `[momentjs]`.  If you prefer Github, open a new issue.  Thanks.

**Comment by dmsouza** [comment]
+1

**Comment by mj1856** [comment]
This feature was completed in 0.3.0.  See http://momentjs.com/timezone/docs/#/using-timezones/default-timezone/
