### ISSUE TITLE
Get potential timezone name from regular moment or js Date

### ISSUE THREAD

**Issue by fourzerooneunauthorized** [moment/moment-timezone#16]
I realize getting a timezone name from a JS date object is generally impossible.  If I recall, that was why the 'z' token was originally removed from moment.js.  Even with moment-timezone.js, one gmt offset value could map to a dozen timezone names.  But, would it still be possible to add a function (maybe named and applied to moment.zoneNames()) to get a list of possible timezone matches using gmt offset or any other usable properties of the moment or date instance?

This would allow the programmer to set a default date for the client (see issue 15) by selecting the very first match or instead work with an array of possible matches to further work on.

Example use: you're in New York and you visit a page.  `var m = moment();` would get your current date/time with utc offset -4.  Then, use `m.zoneNames()` to get a list of possible timezone matches.  The page could just use the first match, use other methods to narrow down the matches further, or prompt the user to select from this narrowed list their current timezone.

I noticed the 'z' format modifier was restored for moment-timezone.js.  Understood that likely it wouldn't work for my suggestion due to issues with mapping to multiple zones.

I'm sorry, I'm not too familiar with the tz database zones and rules to provide a suggested code example or commit.

**Comment by AzeemAnsari** [comment]
How can i get the timezone name using below values:

Unix timestamp = 1594542039
Timezone = -14400

I am using moment.js library
