### ISSUE TITLE
Expose list of zone links: moment.tz.zoneLinks()

### ISSUE THREAD

**Issue by kashifshamaz21** [moment/moment-timezone#165]
Looking at the code in `moment-timezone-with-data-2010-2020.js`, the `loadData` invocation loads the complete bundle of zone data. 
Per the following lines of code:

```
function loadData (data) {
   addZone(data.zones);
   addLink(data.links);
   tz.dataVersion = data.version;
}
...
tz._zones       = zones;
tz._links         = links;
```

After loading the moment-timezone.js, inspecting `moment.tz._zones` gives the list of zone objects.
But `moment.tz._links` returns empty hash({}). 
It would be great if we can have an API that returns the links between zones which are aliases to each other.

**Comment by rchanou** [comment]
It looks like `moment.tz._links` now actually lists the links as of 0.5.0.

**Comment by gilmoreorless** [comment]
`moment.tz._links` does expose the internal data structure as stated, but be aware that it can have some subtle bugs when multiple links point at each other: https://github.com/moment/moment-timezone/issues/301#issuecomment-466765295
