### ISSUE TITLE
/etc/gmt+XX zones are reversed

### ISSUE THREAD

**Issue by santiagozky** [moment/moment-timezone#167]
Im just looking at moment timezone for the first time and it seems like some timezones are incorrect.
I downloaded the package with 2010-20 data and I tried to render some dates in Spanish local time (GMT+1)

moment().tz('Etc/Gmt+1').format('YYYY-MM-DD HH:mm ZZ')
which returns:
"2014-12-18 11:22 -0100"
but 
moment().tz('Europe/Madrid').format('YYYY-MM-DD HH:mm ZZ')
returns 
"2014-12-18 13:22 +0100"

Unless I'm misunderstanding how timezones work (which might be the case to be honest). It seems that the etc/Gmt+X zones are reversed.

**Comment by DanielSWolf** [comment]
I wrote the following function that creates 25 new time zones (`UTC-12`..`UTC+12`) that behave as expected. Maybe it can save someone some time.

```js
// Adds support for time zones 'UTC-12'..'UTC+12'
function addUtcTimeZones() {
  // Moment.js uses the IANA timezone database, which supports generic time zones like 'Etc/GMT+1'.
  // However, the signs for these time zones are inverted compared to ISO 8601.
  // For more details, see https://github.com/moment/moment-timezone/issues/167
  for (let offset = -12; offset <= 12; offset++) {
    const posixSign = offset <= 0 ? '+' : '-';
    const isoSign = offset >= 0 ? '+' : '-';
    const link = `Etc/GMT${posixSign}${Math.abs(offset)}|UTC${isoSign}${Math.abs(offset)}`;
    moment.tz.link(link);
  }
}
```
