### ISSUE TITLE
new moment 2.9.0 causes deprecation warnings with moment-timezone

### ISSUE THREAD

**Issue by leider** [moment/moment-timezone#172]
plz update  :)

**Comment by claudioc** [comment]
:+1:

**Comment by owenallenaz** [comment]
From looking at the source this is already completed, there hasn't been an NPM publish and version bump since #168 was pulled in.

**Comment by ssetem** [comment]
yeah please update/publish thanks :)

**Comment by timrwood** [comment]
This has been released as `moment-timezone@0.3.0`.
