### ISSUE TITLE
contribution docs need correction: there's no "tests/moment-timezone-utils" folder

### ISSUE THREAD

**Issue by kashifshamaz21** [moment/moment-timezone#174]
Under the contribution docs, the following line is incorrect:
```
Additions to moment-timezone-utils.js should have matching tests in /tests/moment-timezone-utils/
```
There is no folder at the location `/tests/moment-timezone-utils/`, all tests are included under the `/tests/moment-timezone/` directory.

Along with this correction, we should remove `"tests/moment-timezone-utils/*.js"` from the config for the `nodeunit` grunt task in the Gruntfile.

**Comment by timrwood** [comment]
Good point, addressed in 7be749ebae748d9a511a8b2b8611b53b75c0e166.
