### ISSUE TITLE
Please add packaging for Meteor.js

### ISSUE THREAD

**Issue by awhitford** [moment/moment-timezone#178]
The _official_ support for Meteor for `moment` is fantastic, but `moment-timezone` is missing.

Could we please get the same Meteor integration for `moment-timezone` as we enjoy with `moment`?

**Comment by dalgard** [comment]
As I pointed out in the other thread, a package like `aldeed:autoform` is using Timezone in the form of `mrt:moment-timezone` which still relies on mrt:moment, and as a result, two versions of Moment.js are bundled with my project

**Comment by D1no** [comment]
+1
momentjs without timezone is... almost useless

**Comment by evenfrost** [comment]
That would be awesome, as I'm facing same issue as @dalgard and `mrt:moment-timezone` is a bit outdated.

**Comment by jerefrer** [comment]
+1. I just can't use the meteor package without i18n ...

**Comment by peterchoo** [comment]
Another :+1: here

**Comment by lbroadley** [comment]
:+1:

**Comment by robertpitt** [comment]
:+1: - UK is currently BST and with UTC based timestamps from the server all the timestamps are 1 hour behind, would be great if you guys added the timezone stuff so that we can cleanly implement a fix.

**Comment by mj1856** [comment]
@robertpitt moment.js is capable of converting from UTC to local without moment-timezone.

**Comment by robertpitt** [comment]
@mj1856, thanks for the reply, a developer of ours messaged me shortly after I wrote the message and said it was possible, my apologies.

**Comment by Sikwan** [comment]
:+1:

**Comment by rgnevashev** [comment]
+1

**Comment by Atu** [comment]
+1

**Comment by joetidee** [comment]
+1

**Comment by abernix** [comment]
This issue should no longer be relative as Meteor now offers native NPM support.  You should have no problem including `moment-timezone` using ES6 import syntax.

```javascript
import moment from 'moment';
import 'moment-timezone';
```

**Comment by mitar** [comment]
A Meteor package would still be helpful to minimize duplicates. I do not want to have `momentjs:moment` copy and NPM copy of moment library included. Meteor packages much better make sure that you do not have duplicates.

**Comment by maggiepint** [comment]
I"m going to close this issue. Going forward our team is not interested in Meteor support given that you can just use NPM.
