### ISSUE TITLE
Question: Can an offset (in hours) be passed in as a param to get a string?

### ISSUE THREAD

**Issue by TeardropInc** [moment/moment-timezone#179]
To clarify, are there any APIs in moment-timezone that accept an hour offset (-8 or +11) to convert times based on that or even a Base 60 version hour or minutes? With the Base 60 part it is not clear to me if this is supported.

I am wanting to store the offset in a DB column and I'm not sure if that or a string is better to store.

**Comment by mj1856** [comment]
You don't need moment-timezone to work with fixed offsets. you can just use moment by itself.  See the docs for the [`utcOffset`](http://momentjs.com/docs/#/manipulating/utc-offset/) function.

Do keep in mind though that a time zone is not a the same thing as an offset. Time zones can have *multiple* offsets.  For example, US Pacific Time, represented by the `America/Los_Angeles` identifier, has a standard offset of UTC-8, but switches to UTC-7 when daylight saving time is in effect.

**Comment by TeardropInc** [comment]
Thanks for your response, it was helpful. :+1:
