### ISSUE TITLE
Cannot read property 'tz' of undefined

### ISSUE THREAD

**Issue by tzookb** [moment/moment-timezone#181]
found many questions about it but still didn't find any solution, except of some talks on strict mode.

How do I solve this issue where I always get this error:

     Cannot read property 'tz' of undefined

**Comment by kashifshamaz21** [comment]
@tzookb  What is the issue you are facing? Can you add more info about what APIs you are calling and the code snippets..

**Comment by tzookb** [comment]
sorry, don't do anything yet...

just installed it with bower, than included the full build with data, or even only the moment-timezone alone it gives me the error above.

Didn't do nothing yet.....

**Comment by mj1856** [comment]
If you call `moment.tz(...)` and get "can't read property tz of undefined" - that means that `moment` is undefined.

You simply need to install *both* moment and moment-timezone.  See [these docs](http://momentjs.com/timezone/docs/#/use-it/).
