### ISSUE TITLE
Syntax of method is a little confusing

### ISSUE THREAD

**Issue by LockTar** [moment/moment-timezone#182]
I like your plugin but the syntax of the moment timezone is a little bit confusing. Can you change or add a shortcut for it:

Now you have line 1 for setting the current timezone and line 2 for displaying it in the desired timezone:
```javascript
moment.tz("2015-05-03 13:00", "Etc/UTC|UTC").format();
moment("2015-05-03 13:00").tz("Africa/Ceuta|Europe/Amsterdam").format();
```
This could be changed into more meaning method names like:
```javascript
moment.tz("2015-05-03 13:00").set("Etc/UTC|UTC");
moment.tz("2015-05-03 13:00").to("Africa/Ceuta|Europe/Amsterdam");
```
or
```javascript
moment("2015-05-03 13:00").setTz("Etc/UTC|UTC");
moment("2015-05-03 13:00").toTz("Africa/Ceuta|Europe/Amsterdam");
```

**Comment by mj1856** [comment]
This is based on the patterns used by moment, for example in the `utc` function.

```javascript
moment(string).utc()  // parse string as local time, convert to utc
moment.utc(string)    // parse string as utc directly
```

While I hear your feedback, the API design is relatively stable at this time.  Changing it now would cause trickle-down changes in the design of moment.
