### ISSUE TITLE
2015-3-8 isn't ambiguous but date needs to be formatted as 2015-03-08

### ISSUE THREAD

**Issue by aviynw** [moment/moment-timezone#185]
moment.tz("2015-03-08 12:00", 'America/New_York').toString() 
Sun Mar 08 2015 12:00:00 GMT-0400

moment.tz("2015-3-8 12:00", 'America/New_York').toString() 
Sun Mar 08 2015 08:00:00 GMT-0400

The worst part is that it doesn't fail, but instead returns a bad date.  If it can't be certain that the date provided is properly format it should fail hard, no?

Running in Node 0.10.32 moment version 0.3.0

**Comment by aviynw** [comment]
Also...64-bit version on windows in case that makes a difference.

**Comment by mj1856** [comment]
You probably saw a warning in your console.  `YYYY-M-D HH:mm` isn't one of the standard ISO8601 formats supported by moment.  [Read this part of the moment docs](http://momentjs.com/docs/#/parsing/string/).

It's not a moment-timezone issue.  You'd get the same behavior with `moment("2015-3-8 12:00")`.
