### ISSUE TITLE
Date Formatting Example Gives Incorrect Timezone in 2015

### ISSUE THREAD

**Issue by jlouthan** [moment/moment-timezone#188]
When I run the first example listed on the Moment Timezone homepage http://momentjs.com/timezone/ in my browser, I get the expected output for the timezone:

```
    var jun = moment("2014-06-01T12:00:00Z");
    var dec = moment("2014-12-01T12:00:00Z");

    jun.tz('America/Los_Angeles').format('ha z');  // 5am PDT
    dec.tz('America/Los_Angeles').format('ha z');  // 4am PST
```

However, if I change only the years in the date strings used to initialize the moments from 2014 to 2015, the December time zone is incorrect. It should be in PST but gives PDT:

```
    var jun = moment("2015-06-01T12:00:00Z");
    var dec = moment("2015-12-01T12:00:00Z");

    jun.tz('America/Los_Angeles').format('ha z');  // 5am PDT
    dec.tz('America/Los_Angeles').format('ha z');  // 5am PDT
```

Any clue what's going on here? I'm using moment-with-locales.min.js version 2.9.0 and moment-timezone-with-data.min.js 0.3.0 in Chrome 41. Any help would be appreciated! Thanks!

**Comment by mj1856** [comment]
Works for me.  Opened a console window right on the moment-timezone home page in Chrome (latest) and got this:

![image](https://cloud.githubusercontent.com/assets/1396388/6654097/554c14c4-ca6b-11e4-9a79-031b2d0a8b5b.png)

Can you please try again?

**Comment by jlouthan** [comment]
Revisiting this, it does work on the moment-timezone home page for me as well. Looks like the problem was in my own code that I wrote based on the moment-timezone docs. The problem comes from trying to set a default timezone. Some time ago, at the top of my script, I put


        moment.tz.setDefault("America/Los_Angeles");

but then got the error `Moment Timezone has no data for America/Los_Angeles. See http://momentjs.com/timezone/docs/#/data-loading/.` So I followed the link [http://momentjs.com/timezone/docs/#/data-loading/](http://momentjs.com/timezone/docs/#/data-loading/) and added the line shown in the docs right before my call to `setDefault`:

        moment.tz.add('America/Los_Angeles|PST PDT|80 70|0101|1Lzm0 1zb0 Op0');
        moment.tz.setDefault("America/Los_Angeles");

Then the errors went away, but it looks like it's this incomplete packed zone string that's causing my problem. If I update it to include data for years between 2014 and 2018 (found in the docs [here](http://momentjs.com/timezone/docs/#/data-formats/packed-format/)), everything works!

        moment.tz.add('America/Los_Angeles|PST PDT|80 70|01010101010|1Lzm0 1zb0 Op0 1zb0 Rd0 1zb0 Op0 1zb0 Op0 1zb0');
        moment.tz.setDefault("America/Los_Angeles");

My bad for blindly copy-pasting without reading a bit about the packed data first, but I hope this helps someone else. Maybe the docs in the Data Loading#Adding a Zone section should be updated to show a more current packed string?

**Comment by mj1856** [comment]
Interesting.

@timrwood  - Perhaps we should update all the examples?

**Comment by gilmoreorless** [comment]
The data loading section of the docs was updated with this warning:

> Note: The above zone data is sample data and is not up to date. Reference the [moment-timezone source](https://github.com/moment/moment-timezone/blob/develop/data/packed/latest.json) for up to date data.
