### ISSUE TITLE
Parsing a local timestamp and identifying timezone

### ISSUE THREAD

**Issue by givan** [moment/moment-timezone#189]
Hello,

Our API receives a string parameter with a given local time. We need to parse the date time and the timezone. Sample string format - 2015-03-03T21:28:20-12:00. We need to determine the time zone name corresponding to -12:00. Is there a way to do that with moment.js? I wonder if the timezone offset (-12:00) uniquely identifies a given timezone?

Thanks,
- George

**Comment by mj1856** [comment]
No.  Offsets do not uniquely identify time zones.  Time zones *have* offsets.   It's a 1-to-N relationship.

Read "Time Zone != Offset" in [the timezone tag wiki on StackOverflow](http://stackoverflow.com/tags/timezone/info).

See also [the list on Wikipedia](http://en.wikipedia.org/wiki/List_of_tz_database_time_zones) containing time zones and their offsets.
