### ISSUE TITLE
Etc/GMT issue (confusion)

### ISSUE THREAD

**Issue by shawnjacobson** [moment/moment-timezone#191]
I'm not understanding why GMT-5 shows a positive offset.  This can easily be seen comparing the following 2 formatted zones, which should be equivalent...

moment.tz([2012, 5], 'America/Chicago').format('Z z');  // -05:00 CDT
moment.tz([2012, 5], 'Etc/GMT-5').format('Z z');  // +05:00 GMT-5

...can someone explain to me what is going on here.

**Comment by mj1856** [comment]
This is normal.  Those zone IDs have the sign inverted.  This isn't our decision - it comes from the source data.  See also [for a more detailed explaination](http://stackoverflow.com/a/23643847/634824).

And really, if you are working with fixed-offset time zones, you don't need moment-timezone at all.  You can just use the [`utcOffset`](http://momentjs.com/docs/#/manipulating/utc-offset/) function in the main moment.js.
