### ISSUE TITLE
Performance issue momentjs tz is 1200 times slower than Date

### ISSUE THREAD

**Issue by vallettea** [moment/moment-timezone#192]
here is simple benchmark script:

```
"use strict";


var moment = require('moment-timezone');


var t1 = Date.now();
for (var i = 0; i < 100000; i++) {
   moment.tz("2014-01-09T03:00:00.000Z", "Europe/Paris");
}
var t2 = Date.now();

console.log("momentjs", (t2-t1)/1000.0)

for (var i = 0; i < 100000; i++) {
   new Date("2014-01-09T03:00:00.000Z");
}
var t3 = Date.now();

console.log("date", (t3-t2)/1000.0)
```

which outputs:

```
momentjs 5.342
date 0.03
```

**Comment by mj1856** [comment]
That's not exactly a fair comparison.  The equivalent moment operation would just be:

    moment("2014-01-09T03:00:00.000Z");

Even then it's slower - sure.  But that's to be expected.  `Date` does its parsing in native c code of the browser, while `moment` is interpreted through JavaScript.  It couldn't ever possibly be as fast as native code.

Could it be faster?  Sure.  But I doubt the current speed poses a problem for most implementations.

If you have specific performance improvements to submit, then please send a PR.  Thanks.
