### ISSUE TITLE
Compiled files aren't included via npm.

### ISSUE THREAD

**Issue by allanhortle** [moment/moment-timezone#195]
It's really nice to be able to use npm to install dependencies even if you don't plan to bundle them in with requires. Quite frequently I will use a build tool to just concat my core dependencies and bring that in before my app code.

**Comment by mj1856** [comment]
Sorry, I'm not sure I fully understand what you would like to have changed.  Educate me please. :smile:

**Comment by allanhortle** [comment]
You may have fixed it already. Moment has a `min` folder that contains a standalone version of moment. 
https://github.com/moment/moment/blob/develop/min/moment.min.js
I was just looking for something like that in moment-timezone.

I often use npm to manage front end dependencies, but won't actually use the modular version of the package. I'll use something like Grunt to concatenate the standalone versions of these dependencies into one file. It's just useful to have the standalone version packaged along with it's modular friend.

**Comment by csvan** [comment]
+1, would be really nice to have the current TZ data available as a compiled file when installing via NPM.

**Comment by SpaceBeers** [comment]
I'd +1 that too. We switched from Bower to NPM for dependancies and now have to bundle the data in somehow.
