### ISSUE TITLE
Give the ability to display the non abbreviated version of the abbreviation

### ISSUE THREAD

**Issue by nathanv** [moment/moment-timezone#196]
Currently you can only load abbreviations; how about The non abbreviated version of the abbreviation?

E.g. instead of this:

```JSON
{
    name    : 'America/Los_Angeles',
    abbrs   : ['PST', 'PDT','PST', 'PDT', 'PST', 'PDT', 'PST', 'PDT', 'PST', 'PDT', 'PST'],
    untils  : [1394359200000, 1414918800000, 1425808800000, 1446368400000, 1457863200000, 1478422800000, 1489312800000, 1509872400000, 1520762400000, 1541322000000, null],
    offsets : [480, 420, 480, 420, 480, 420, 480, 420, 480, 420, 480]
}
```

Can we also have 

```JSON
non-abbrs   : ['Pacific Standard Time', 'Pacific Daylight Time','Pacific Standard Time', 'Pacific Daylight Time', 'Pacific Standard Time', 'Pacific Daylight Time', 'Pacific Standard Time', 'Pacific Daylight Time', 'Pacific Standard Time', 'Pacific Daylight Time', 'Pacific Standard Time'],
```
?
If this is not possible, is there a library out there (javascript or otherwise) that enables this?

The reason we want to do this is because abbreviations are not accessible. As seen [here](http://accessibility.psu.edu/abbreviations/): "In general, screen readers do not recognize abbreviations and acronyms, and generally read them as if they were typical English words. For instance the phrase "ITS at PSU" would not be read by screen readers as the intended "I.T.S. at P.S.U.", but as "It’s at Sue"."

**Comment by mj1856** [comment]
This is out of scope.  It would require CLDR time zone data.

Thus far, I have yet to see a solid js lib for this.  The only one I know of is [here](https://github.com/anamartinez/js-cldr-timezones), and I'm uncertain as to its viability or current status.

I wrote and maintain one for .NET in a library called [TimeZoneNames](https://github.com/mj1856/TimeZoneNames).  There are probably similar things out there for other languages.

The big issue with this is localization.  The IANA tz database only provides English abbreviations, but when you start with CLDR, you have a lot more human languages to consider.  It would be a very heavy thing to put in a JS library.
