### ISSUE TITLE
Incorrect output when valid shorthand UTC offset values are used. 

### ISSUE THREAD

**Issue by lozandier** [moment/moment-timezone#198]
For some strange reason, valid shorthand UTC offset values applied to datetime values such as `2015-03-30T00:00:00-07` instead of `2015-03-30T00:00:00-07:00` do *not* provide the same time.

**Since such a format is outlined in the  ISO 8601 standard, there's value in general for moment.js to account for this style of defining a specific UTC offset.**

## Reproducing the Error
Based on what I'm familiar with when it comes to inputting timezone formats in either style in PostgreSQL (`timestamptz`, `timetz`, `tstzrange`, & etc.)—as well as datetime standard libs in Ruby, Go, & Python—the current behavior of moment.js when shorthand UTF shorthand values are used seems like an error…

```js
let sf = moment("2015-03-30T00:00:00-07");
//undefined
let sf2 = moment("2015-03-30T00:00:00-07:00");
//undefined
sf2.tz('America/Los_Angeles').format('ha z');
//"12am PDT"
sf.tz('America/Los_Angeles').format('ha z');
//"9pm PDT" <-- This is a confusing result
```

In comparison, consider the result of the more ISO-Compliant handling of timezones by PostgreSQL (9.4 used in the following example on a server using East Coast time):
![screen shot 2015-03-30 at 11 47 44 am](https://cloud.githubusercontent.com/assets/1223224/6900192/e323096a-d6d2-11e4-9d8a-c883b139c7c9.png)

## Implications of this bug / How problematic is this bug
Since popular databases such as PostgreSQL always by default output and take account daylight savings by default with the timezone offset formatted the *shorthand* way with their datetime types that do take account UTC offsets, this can lead to surprising results.

This is especially true when valid ISO datetime values with shorthand UTC offsets are results of   `JSON` & `JSONB` data from columns of such types from tables within relational databases such as PostgreSQL. 

If not known ahead of time to take preemptive steps of altering the datetime/time values to have offsets moment.js can understand, it can lead to perhaps life-altering mistakes.

## Fiddle Gist
Fiddle doesn't or no longer seems to have a CDN copy of moment-timezone listed. I accept any scolding accordingly of not using a fiddle gist to reproduce this problem if necessary according to the issue guidelines of this project.

**Comment by mj1856** [comment]
Thanks for the feedback.

This is a moment problem, and is currently being tracked in moment/moment#2142
