### ISSUE TITLE
CDN for moment-timezone with data

### ISSUE THREAD

**Issue by 9dev** [moment/moment-timezone#199]
At this moment, official website provides moment-timezone in version 0.3.0, along with its extended version with data (moment-timezone-with-data-2010-2020.js). However, at cdnjs there is only the basic version. Could you add the bundled version as well?

http://cdnjs.com/libraries/moment-timezone

**Comment by PeterDaveHello** [comment]
I'm Peter from cdnjs to fix it :smile:

**Comment by PeterDaveHello** [comment]
@moment Is it possible to put `moment-timezone-utils.js` and `moment-timezone.js` into builds? Thanks.

**Comment by mj1856** [comment]
Ping @timrwood

**Comment by mj1856** [comment]
This was done a long time ago.
