### ISSUE TITLE
List of timezones

### ISSUE THREAD

**Issue by dawnerd** [moment/moment-timezone#20]
I'm looking for a way to output all added timezones, preferably ordered correctly. I didn't see any possible way right now.

Before I fork and patch, I wanted to ask if there was some way that maybe I looked past.

**Comment by brewhk-dev** [comment]
There's now [`moment.tz.names()`](http://momentjs.com/timezone/docs/#/data-loading/getting-zone-names/)

    moment.tz.names(); // ["Africa/Abidjan", "Africa/Accra", "Africa/Addis_Ababa", ...]

**Comment by aaronmagi** [comment]
@brewhk-dev  is this change checked into the latest release?  

moment.tz.names()

**Comment by brewhk-dev** [comment]
@aaronmagi A quick check on the [changelog.md](https://github.com/moment/moment-timezone/blob/eda36cb2c5ed62b7082593c3aeaff9b94204aa1a/changelog.md#010-2014-06-23) tells me it was added in version `0.1.0` on 23rd June, 2014
