### ISSUE TITLE
Timezone via timestamp + offset only

### ISSUE THREAD

**Issue by mbsmith** [moment/moment-timezone#200]
I'm currently trying to work with iso-8601 timesets that contain offsets.  These are currently fetched from a remote server.  Basically a menu for changing time settings on the remote device.  However when I instantiate the zone object using a timestamp containing offsets moment-timezone still seems to use my local timezone for everything.

If there is a way for this to 100% disregard my browsers timezone and only use the timestamp given I can't see it.

**Comment by mj1856** [comment]
Offsets aren't the same as time zones.  If you need to parse an ISO string containing an offset and keep the offset in tact, you don't need the moment-timezone add-on.  Moment can handle this with the [`parseZone`](http://momentjs.com/docs/#/parsing/parse-zone/) function.

```javascript
var m = moment.parseZone("2013-01-01T00:00:00-13:00");
```
