### ISSUE TITLE
moment.tz is undefined

### ISSUE THREAD

**Issue by abbasikov** [moment/moment-timezone#202]
I have loaded the following files in my index.html page.

1-moment.js
2-moment-timezone-with-data-2010-2020.js

but when i access moment.tz ... i am getting error tz is undefined.

**Comment by theninthnode** [comment]
I'm also getting this using the example on the readme

**Comment by matthewoates** [comment]
You can use this branch of my fork.

https://github.com/matthewoates/moment-timezone/tree/requirejs_fix

how to include it in bower:
`"moment-timezone": "git://github.com/matthewoates/moment-timezone.git#84d32d1bc0348941cd7d777b0f8d590fd84223b9"`

**Comment by matthewoates** [comment]
This is also assuming you're using requirejs, which moment-timezone doesn't seem to handle correctly.

**Comment by mj1856** [comment]
@abbasikov - Can you clarify?  Are you indeed using requirejs, or just loading the raw files?  Can you give us an example?

Here's a simple html example (without require) that works just fine:

```html
<script src="http://momentjs.com/downloads/moment.js"></script>
<script src="http://momentjs.com/downloads/moment-timezone-with-data-2010-2020.js"></script>

<div id="output"></div>

<script type="text/javascript">

var m = moment.tz('2015-01-01 12:00:00','America/New_York');
var s = m.format();

document.getElementById("output").innerHTML = s;

</script>
```

**Comment by mj1856** [comment]
@matthewoates - The code in your fork removes code needed by other loading mechanisms.

I'm not entirely certain there is a problem with requirejs loading anyway - but I will check it out.

**Comment by matthewoates** [comment]
@mj1856 It does break other environments, but I was just mentioning it as it might help the other guys solve their issues.

Upon further investigation, i realized that moment and moment-timezone have issues with `almond.js`, but probably not `require.js`.

**Comment by mj1856** [comment]
@matthewoates - My experience with the various loaders is limited.  If you have time to investigate and send a PR, that would be greatly appreciated!

**Comment by mj1856** [comment]
Just as a sanity check, I tried in nodejs with require and it seems to be ok.
![image](https://cloud.githubusercontent.com/assets/1396388/7174081/b4ecebce-e3b6-11e4-92ae-af9766b7d59e.png)

I'm closing for now.  If you can demonstrate it failing, please do - and I'll reopen.  Thanks.
