### ISSUE TITLE
abbrs, untils, and offsets contains too many items

### ISSUE THREAD

**Issue by bcherny** [moment/moment-timezone#203]
for example,

```js
> moment.tz.zone('US/Mountain')
Zone {name: "US/Mountain", abbrs: Array[158], untils: Array[158], offsets: Array[158]}
```

the contents of each array are hugely redundant-

```js
> abbrs
[
  0: "MST",
  1: "MDT",
  2: "MST",
  3: "MDT",
  4: "MST",
  5: "MDT",
  6: "MST",
  7: "MDT",
  8: "MST",
  9: "MWT",
  10: "MPT",
  11: "MST",
  12: "MDT",
  ...
  157: "MST"
]
```

is this expected behavior?

**Comment by mj1856** [comment]
Yes, this is the current design.  The data is not stored that way though.  It's packed, into a different format, then unpacked like this into memory.

Each entry represents the time between two specific transitions, as can be seen in the `untils` array.

The data formats are described [in this part of the documentation](http://momentjs.com/timezone/docs/#/data-formats/)

**Comment by skeggse** [comment]
The [Zone Object](http://momentjs.com/timezone/docs/#/zone-object/) documentation doesn't document this, perhaps it should?

**Comment by mj1856** [comment]
@skeggse Sure.  You could do that, using one of the techniques described here: http://stackoverflow.com/questions/1960473/unique-values-in-an-array

If that doesn't work for you, then please open a new item for the request.
