### ISSUE TITLE
GMT+/- values have incorrect offsets

### ISSUE THREAD

**Issue by trip30** [moment/moment-timezone#204]
GMT offsets seem to be reversed from what they should be

> moment.tz('2015-04-15', 'Etc/GMT+9').format()
< "2015-04-15T00:00:00-09:00"

> moment.tz('2015-04-15', 'Etc/GMT-9').format()
< "2015-04-15T00:00:00+09:00"

It looks like iana has the correct values, but at some point during gathering and parsing the data using your scripts they are inverted. 

This is easily corrected manually, what we are doing now, but it seems that if you want to keep using your iana YYYY[a-z].json schema for your data bug in your import scripts will need to be found and fixed.

**Comment by mj1856** [comment]
This is by design choice of IANA.

See dup #167 and #191
