### ISSUE TITLE
Convert zone abbreviation to timezone

### ISSUE THREAD

**Issue by pennybuster** [moment/moment-timezone#209]
Hi! Can you help me convert a zone abbreviation to a timezone? I'm using the Yahoo Weather API to get the current weather condition and forecast for a given location and only have access to the local zone abbreviation. Thank you very much

**Comment by mj1856** [comment]
Sorry, but it's not possible.  There are too many ambiguities, such as 5 different interpretations of "CST".  See http://en.wikipedia.org/wiki/List_of_time_zone_abbreviations
