### ISSUE TITLE
"America/Santiago" timezone problem 

### ISSUE THREAD

**Issue by gv-rayalab** [moment/moment-timezone#210]
Chile is now excempt from the Daylight Saving time, so the time in the new 0.3.1 version is wrong.

**Comment by mj1856** [comment]
This was done in [tzdb 2015a](http://mm.icann.org/pipermail/tz-announce/2015-January/000028.html).  This isn't linked from the home page, but is available if you pull from [the github repo](https://github.com/moment/moment-timezone/tree/develop/data/packed).

Admittedly, we need to do a better job of staying on top of tzdb updates.  #205 is still pending for 2015c, and already 2015d is out and needs packaging.

**Comment by yankopetrov** [comment]
Is this fixed?
I am getting wrong offset for America/Santiago with 0.5.23

```
utc: 2019-04-22T12:00:00Z
America/Santiago: 2019-04-22T08:00:00-04:00
```

At the moment the correct DST offset is -03:00
```
Chile Summer Time
Time zone in Santiago, Chile (GMT-3)
Tuesday, 2 April 2019, 05:05
```

**Comment by NoureldeanSaed** [comment]
This problem is still live, going for `moment().tz('America/Santiago').format('z')` returns `-3` instead of the actual abbreviation for the country, unlike all other timezone ids that I'd tested for.

**Comment by tomerb15** [comment]
I'm using the latest moment and moment-timezone:
"moment": "^2.29.1",
"moment-timezone": "^0.5.32"

and 
```
moment().tz("America/Santiago").format()
```
Is returning `2021-01-08T19:28:30-03:00` while its actually `2021-01-08T18:28:30-04:00`

**Comment by mj1856** [comment]
@yankopetrov - In 2019 the change from UTC-3 to UTC-4 occurred on April 7th, so the conversion is correct.
https://www.timeanddate.com/time/zone/chile/santiago?year=2019

@tomerb15 - In 2021, the offset for January is indeed UTC-3, so again the conversion is correct.
https://www.timeanddate.com/time/zone/chile/santiago?year=2021

**Comment by PQMISSCMP** [comment]
La hora de verano en Chile se produce el primer sábado de septiembre y finaliza el primero sábado de abril. Moment con timezone me entrega una isDST equivocado.
