### ISSUE TITLE
Guard against loading moment-timezone twice

### ISSUE THREAD

**Issue by mj1856** [moment/moment-timezone#212]
A few reports from the wild, such as in #193 and [on StackOverflow](http://stackoverflow.com/q/29877791/634824) (and others) have shown that it's easy to accidentally load moment-timezone twice, which creates some problems.

Usually, it's a misunderstanding that moment-timezone-with-data already contains moment-timezone.

We should either guard against this, or at least prevent it from causing problems.

**Comment by timrwood** [comment]
This is released in `0.4.0`.
