### ISSUE TITLE
Using add() with timezones

### ISSUE THREAD

**Issue by henrywright** [moment/moment-timezone#218]
Imagine the moment is slightly before the change from UTC+1 to UTC 

`var d = '2015-10-24T23:59:00Z';`

`moment(d).tz('Europe/London').format('HH:mm z'); // 00:59 BST`

Now add 2 hours using `add()`:

`moment(d).add(120, 'm').tz('Europe/London').format('HH:mm')`

During the 2 hours that has been 'added' by add(), the time has been adjusted from UTC+1 to UTC. So, what would be displayed: 02:59 or 01:59?

**Comment by timrwood** [comment]
It will display `01:59 GMT`.

Check out the section at the end of http://momentjs.com/docs/#/manipulating/add/ about daylight saving time considerations.

**Comment by henrywright** [comment]
Thanks @timrwood - I did read through the docs, but seemed to have missed that section. Thanks again.
