### ISSUE TITLE
For Africa/Cairo timezone, moment tz is using EEST(UTC+3) whereas everywhere else it's EET(UTC+2)

### ISSUE THREAD

**Issue by manimis902** [moment/moment-timezone#223]
Because of the above, there's a difference of 1 hour.
http://www.zeitverschiebung.net/en/timezone/africa--cairo

**Comment by mj1856** [comment]
Our data comes directly from the [IANA tz database](http://en.wikipedia.org/wiki/Tz_database).

Egypt has changed several times.  The last rule change was made [in version 2015d](http://mm.icann.org/pipermail/tz-announce/2015-April/000031.html), which you can get for [moment-timezone from here](https://github.com/moment/moment-timezone/tree/develop/data/packed).

It will eventually be published on the main moment-timezone website as well, (which currently has version 2015a).

**Comment by mj1856** [comment]
2015d is now published with moment-timezone version 0.4.0.
http://momentjs.com/timezone/

**Comment by davidglbr** [comment]
Sorry to come up with that, but after updating the time zone data (using moment-timezone v0.4.0 with 2015d as data) timezone conversion to 'Africa/Cairo' still coverts to GMT+3.
However, the offset for the zone object is 180 (GMT+2).

    moment.tz("2015-08-14T00:00:00Z", "Africa/Cairo").format()
    >> 2015-08-14T03:00:00+03:00

    moment.tz("2015-08-14T00:00:00Z", "Africa/Cairo")._offset
    >> 180

Am I doing something wrong?
