### ISSUE TITLE
moment-timezone Error

### ISSUE THREAD

**Issue by LMart15** [moment/moment-timezone#224]
Hello I am using moment-timezone in an application and some times are coming back wrong. I checked http://momentjs.com/timezone/ to confirm and it is reporting the same erroneous time so it is not an issue with my code. For example Cairo Egypt is reported as an hour ahead of the true time both on the momentjs.com/timezone/ map and in my application.

**Comment by manimis902** [comment]
@LMart15 Even I'm facing the same issue, and I have raised the same bug with #223

**Comment by mj1856** [comment]
See my notes on #223.

**Comment by mj1856** [comment]
2015d is now published with moment-timezone version 0.4.0.
http://momentjs.com/timezone/
