### ISSUE TITLE
moment.tz() causes deprecation notice

### ISSUE THREAD

**Issue by anantn** [moment/moment-timezone#228]
With the latest `moment-timezone` and `moment` packages, simple usage of `moment.tz()` throws a deprecation warning.

```
> moment().tz("America/Los_Angeles").format("YYYY-MM-DD");
Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. https://github.com/moment/moment/issues/1779
Error
    at deprecate (node_modules/moment-timezone/node_modules/moment/moment.js:738:42)
    at node_modules/moment-timezone/node_modules/moment/moment.js:2554:37
    at node_modules/moment-timezone/node_modules/moment/moment.js:8:85
    at Object.<anonymous> (node_modules/moment-timezone/node_modules/moment/moment.js:11:2)
    at Module._compile (module.js:444:26)
    at Object.Module._extensions..js (module.js:462:10)
    at Module.load (module.js:339:32)
    at Function.Module._load (module.js:294:12)
    at Module.require (module.js:349:17)
    at require (module.js:368:17)
```

What's the right way to get the current time in a particular timezone?

**Comment by pchng** [comment]
Using the following syntax should work:

    var d = moment.tz(""America/Los_Angeles");
    console.log(d.toString());
    console.log(d.format());

In general, `moment.tz()` acts like `moment()`, but just taking the timezone name as the last argument.

**Comment by mj1856** [comment]
I'm unable to reproduce this.  According the commit history, moment-timezone switched from the `zone` to the `utcOffset` function in version 0.3.0.  The last version of moment-timezone that should get this warning is 0.2.5.

Can you please check:

```javascript
moment.version
moment.tz.version
```

Thanks.

**Comment by anantn** [comment]
```
> var moment = require("moment-timezone");
undefined
> moment.version
'2.10.3'
> moment.tz.version
'0.2.5'
> moment().tz("America/Los_Angeles").format("YYYY-MM-DD")
Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. https://github.com/moment/moment/issues/1779
Error
    at deprecate (/Users/anant/Code/go/src/github.com/jackmobile/one/appserver/node_modules/moment/moment.js:738:42)
    at /Users/anant/Code/go/src/github.com/jackmobile/one/appserver/node_modules/moment/moment.js:2554:37
    at /Users/anant/Code/go/src/github.com/jackmobile/one/appserver/node_modules/moment/moment.js:8:85
    at Object.<anonymous> (/Users/anant/Code/go/src/github.com/jackmobile/one/appserver/node_modules/moment/moment.js:11:2)
    at Module._compile (module.js:444:26)
    at Object.Module._extensions..js (module.js:462:10)
    at Module.load (module.js:339:32)
    at Function.Module._load (module.js:294:12)
    at Module.require (module.js:349:17)
    at require (module.js:368:17)
'2015-06-18'
> moment.tz("America/Los_Angeles").format("YYYY-MM-DD")
'2015-06-18'
> moment(Date.now()).tz("America/Los_Angeles").format("YYYY-MM-DD")
'2015-06-18'
```

The trick seems to be to call `moment.tz(...)` instead of `moment().tz(...)`. The alternative is to call `moment(Date.now()).tz(...)`. Thanks!

**Comment by mj1856** [comment]
@anantn - The only issue is that you have an older version of moment-timezone.  You have the current moment version, but moment-timezone is at 0.4.0 now.  Upgrade and the warning will go away.

However, you are correct that `moment.tz("zone")` is prefered.  The `moment().tz("zone")` syntax starts out in the local time zone, then *converts* it.  The result is the same either way.

**Comment by ambassadeurdejesus** [comment]
I got the same problem could you help me please

**Comment by mj1856** [comment]
@ambassadeurdejesus - without any details, I'm afraid there's not much I can do to help.  Feel free to open a new issue, or chat with us on Gitter.
