### ISSUE TITLE
Error in Docs on difference between `moment.tz(time, zone)` and `moment(time).tz(zone)`

### ISSUE THREAD

**Issue by camillef** [moment/moment-timezone#232]
In the Docs it states
###### Parsing in Zone

> Using `moment.tz(Number|Date, zone)` is functionally equivalent to `moment(Number|Date).tz(zone).`

However I have found this to be misleading.
The following example provides evidence that the two commands behave differently.    

I want to set up a time in BST (British Summer Time) and convert to UTC.
First, create the date string.
```javascript 
var today = new Date((new Date()).getFullYear(), (Number((new Date()).getMonth())), (new Date()).getDate()); // Fri Jul 10 2015 00:00:00 GMT+0000 (UTC)
var todayString = moment(today).format('YYYY-MM-DD'); // '2015-07-10'
```

Using `moment(time).tz(zone)`:
```javascript
var startTimeMoment = moment(todayString).tz('Europe/London');
var startTimeUTC = startTimeMoment.tz('UTC').format(); // '2015-07-10T00:00:00+00:00'
```
This gives me no time difference.

Using `moment.tz(time, zone)`:
```javascript 
var startTimeMoment = moment.tz(todayString, 'Europe/London');
var startTimeUTC = startTimeMoment.tz('UTC').format(); // '2015-07-09T23:00:00+00:00'
```
This correctly gives me an hour difference.

**Comment by mj1856** [comment]
The docs are correct, as indicated by `Number|Date` in the input parameters.  In your example, you're providing a string, which does have a key difference, as described in the docs in the ["Using Timezones" header](http://momentjs.com/timezone/docs/#/using-timezones/):

> `moment.tz(..., String)` is used to create a moment with a timezone, and `moment().tz(String)` is used to change the timezone on an existing moment.

**Comment by mj1856** [comment]
If you have a suggested rewording to make the documentation clearer, feel free to send a pull request to [the documentation](https://github.com/moment/momentjs.com/tree/master/docs/moment-timezone).  Thanks!
