### ISSUE TITLE
"America/Havana" id gets converted to CDT instead of EDT

### ISSUE THREAD

**Issue by dhruvp** [moment/moment-timezone#233]
Currently, America/Havana is placed as CDT even though it should be EDT!

**Comment by mj1856** [comment]
Time zone abbreviations are not always what you think they are.  CDT in this case stands for Cuba Standard Time.

See:  
- http://www.timeanddate.com/time/zone/cuba/havana
- https://en.wikipedia.org/wiki/List_of_time_zone_abbreviations

FYI - our data comes from the IANA tz database.  We don't invent or assign the abbreviations, they do.
