### ISSUE TITLE
Change In Moment 2.10.5 Causes Null Pointer Exception

### ISSUE THREAD

**Issue by svozza** [moment/moment-timezone#235]
There seems to be an issue with a change that's been made to the moment constructor function in 2.10.5 that has badly impacted moment-timezone. This actually took our production server down this morning: it's probably not a good idea for moment.tz to always take the latest version of moment.js, each version should be shrinkwrapped to a specific version of moment.js. 

Here's the testcase:

```javascript
moment('01-01-1970', moment.ISO_8601).isValid()
// moment.js 2.10.3 => false

moment('01-01-1970', moment.ISO_8601).isValid()
// moment.js 2.10.5 =>
TypeError: Cannot read property 'getTime' of undefined
    at new Moment (/home/stefano/git/p3.1-api/node_modules/moment-timezone/node_modules/moment/moment.js:178:37)
    at createFromConfig (/home/stefano/git/p3.1-api/node_modules/moment-timezone/node_modules/moment/moment.js:1307:19)
    at createLocalOrUTC (/home/stefano/git/p3.1-api/node_modules/moment-timezone/node_modules/moment/moment.js:1385:16)
    at local__createLocal (/home/stefano/git/p3.1-api/node_modules/moment-timezone/node_modules/moment/moment.js:1389:16)
    at utils_hooks__hooks (/home/stefano/git/p3.1-api/node_modules/moment-timezone/node_modules/moment/moment.js:16:29)
```

It seems like it's related to this change in moment.js:

```javascript
//moment.js 2.10.3
function Moment(config) {
       copyConfig(this, config);
       this._d = new Date(+config._d);
       // ...
   }

//moment.js 2.10.5
function Moment(config) {
        copyConfig(this, config);
        this._d = new Date(config._d.getTime());
        // ...
    }
```

**Comment by mj1856** [comment]
Since this can be reproduced without moment-timezone, it isn't a moment-timezone bug.  I'll log it for moment proper.

**Comment by mj1856** [comment]
It's already been reported actually: moment/moment#2512

**Comment by svozza** [comment]
Well there's a `moment-tz` issue too in that the version of `moment.js` that 0.4.0 depends should be locked down and not change silently. When Elastic Beanstalk spun up new instances it ran `npm install` so we had a situation where old EC2 instances were running with moment 2.10.3 and newer ones with 2.10.5. At first we didn't notice the reduced capacity from the new versions crashing out but as ELB scaled up and down older working instances got removed and we had a complete outage. That would never have happened if the dependency was shrinkwrapped.

**Comment by mj1856** [comment]
I disagree that it should be locked down to a strict version. They should be able to be versioned independently - at least with regard to minor and patch numbers.  If there's a compatibility problem from one version to the next, that's a bug.

I think the bigger problem is that moment isn't fully following [SemVer](http://semver.org/).  We should be able to take a dependency on any 2.x.x version.  I'll write something up over in the moment repo.

**Comment by svozza** [comment]
Yes, that's a good point, a patch release should not break anything.

**Comment by mj1856** [comment]
WRT this specific issue, there wasn't any breaking change in the way moment-timezone works with moment.   It was simply a bug in moment that propagated through.   It should have been caught with testing.

Still, better SemVer adherance is important, and I've logged that in moment/moment#2516.
