### ISSUE TITLE
"Britain (UK)" should be "United Kingdom"  

### ISSUE THREAD

**Issue by olegzhoglo** [moment/moment-timezone#236]
Technically, the country "Britain" doesn't exist.  There is only "Great Britain" which is composed of England, Scotland and Wales and "United Kingdom" which is Great Britain and Northern Ireland.  Most time zone selectors use "United Kingdom."

**Comment by mj1856** [comment]
What part of moment-timezone specifically is this in regard to?

**Comment by mj1856** [comment]
I think you're referring to the country names in one of the meta files, such as [here](https://github.com/moment/moment-timezone/blob/develop/data/meta/2015d.json#L611).   These aren't exposed anywhere in the moment-timezone API, nor are they included with moment-timezone releases.  The meta files are just there to help with the time zone builder that we used to have, and will have again some day (see #9).

Besides, we don't author the data, we just pull it in from the tzdb.  We use the [iso3166.tab](https://github.com/eggert/tz/blob/master/iso3166.tab) file.  If you have an issue with those, you can take it up with IANA on the [tz mailing list](https://mm.icann.org/mailman/listinfo/tz).
