### ISSUE TITLE
setDefault cannot be undone

### ISSUE THREAD

**Issue by moses-seeq** [moment/moment-timezone#239]
I am using setDefault for testing purposes and generally like to return my environment to it's previous status prior to running further tests.  However, I do not see a way to 'undo' a setDefault, essentially returning the system to an unspecified time zone.  Am I missing it?

**Comment by moses-seeq** [comment]
It looks like using moment.tz.setDefault() with no arguments might do the trick?

**Comment by mj1856** [comment]
Yes, it would appear `moment.tz.setDefault()` clears the default time zone, setting it back to the user's local zone.  This should be documented.
