### ISSUE TITLE
How to get name of current time zone?

### ISSUE THREAD

**Issue by TWiStErRob** [moment/moment-timezone#240]
`moment().format()`: "2015-08-10T02:25:52+02:00"
`moment().format()`: "2015-08-10T02:25:52+02:00"
`moment().format('Z')`: "+02:00"
`moment().format('z')`: ""
`moment.parseZone(moment().format()).format('z')`: "UTC"
`moment.parseZone(moment().format()).format('Z')`: "+02:00"

Is there any way to get `Europe/Budapest` from just knowing `+02:00`?
Is there any way to get `CEST` from just knowing `+02:00`?

There's some ambiguity here, because Paris, Rome and Budapest are in the same time zone, I would be fine with any of those. My only idea is to leverage `moment.tz.names` and create a hash map from `moment.tz(valueFromNamesArray)..format('Z')` to `moment.tz(valueFromNamesArray).format('z')` which will give me one of those names. Is there any built-in method or combination of methods to achieve this in a less hacky way?

**Comment by alFReD-NSH** [comment]
This is a duplicate of #138, which has a pull request #220. In the mean time you can use https://bitbucket.org/pellepim/jstimezonedetect

**Comment by TWiStErRob** [comment]
Thanks for the heads up! Subscribed to those.

**Comment by vdpdev** [comment]
Hello! Are you planning to implement this feature or is it already implemented?

**Comment by ellenaua** [comment]
@vdpdev moment.tz.guess() returns name of current timezone

**Comment by vdpdev** [comment]
@ellenaua as i understood the solution for this issue were resolved as usage of
`moment.tz.guess`
function which is described in related issue #138.
But author of this issue asked for some solution like this
`moment.tz.getTimezoneName("2015-08-10T02:25:52+02:00") // Europe/Budapest`
and i'm not sure i saw something like this in moment's documentation.

**Comment by ellenaua** [comment]
That is not possible now. 
Many timezones have +02:00 offset.
See here https://en.wikipedia.org/wiki/UTC%2B02:00
+02:00 it may be Europe/Budapest, Europe/Zurich, Europe/Malta, Africa/Tunis, Africa/Ceuta - we cannot guess which one is mentioned in that datetime string

**Comment by vdpdev** [comment]
Also i have one question which is partially related to this thread. I need to know whether the date (moment('some date in ISO 8601 format')) had timezone identifier or not. This why i need to know timezone.
I can't use format('z')\format('Z') because they change during the year(Europe/Kiev is very good example).
And i can't rely on some timezone which is currently doesn't shift because due to politicians solution it may change in future 
 -> moment will update library -> my code will work wrong.
