### ISSUE TITLE
`builds` being excluded on npm

### ISSUE THREAD

**Issue by hyunlim** [moment/moment-timezone#241]
Is there any reason to exclude `builds` directory from npm?

https://github.com/moment/moment-timezone/blob/develop/.npmignore#L12

There are times when pre-built packages would be easier to load in unit test environments like karma, and I don't see any drawbacks from including this in npm packages.

**Comment by swissmanu** [comment]
+1

**Comment by timrwood** [comment]
Fixed with https://github.com/moment/moment-timezone/pull/237
