### ISSUE TITLE
wrong timezone data?

### ISSUE THREAD

**Issue by everdimension** [moment/moment-timezone#243]
I'm trying to calculate time between different timezones and I'm testing a simple case. I'm getting a wrong result which looks like the problem in the timezone data.

```javascript
var moscow = moment.tz("2015-08-24 11:55", "Europe/Moscow");
var london = moment.tz("2015-08-24 11:55", "Europe/London");
moment.duration({ milliseconds: london.diff(moscow) } ).hours();
// 2 [hours]
```

But moscow is [UTC+03:00](https://www.google.ru/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=moscow%20timezone), so I should be getting 3 hours.

What's wrong with the above calculations?

**Comment by alvinsiu** [comment]
I believe London is currently on DST, so it's UTC+1, making 2 hours the correct calculation.

**Comment by everdimension** [comment]
Wow, right... Should have been the first thing to think about.

Sorry about that then! And thanks for the answer.
