### ISSUE TITLE
moment.utc() deletes time-zone info

### ISSUE THREAD

**Issue by gerpres** [moment/moment-timezone#247]
when calling utc() on a moment-object, the timezone-info gets deleted.
so when calling local() on the same-object, it's in fact broken when using get/set afterwards.

the timezone has to be saved in resetZoneWrap()

**Comment by mj1856** [comment]
`.local()` explicitly projects the moment to the local zone.  There is no promise that the original zone is retained, nor should there be.

Note that it doesn't even mean "return it to the default time zone" - as the default zone may have been changed by `moment.tz.setDefault`, which changes how new moments get created, but doesn't change how "local" is defined.
