### ISSUE TITLE
moment().tz(...) return value is inconsistent with moment function chaining.

### ISSUE THREAD

**Issue by syrnick** [moment/moment-timezone#248]
All moment() methods return `this`, so the method calls can be chained. moment().tz(zoneName) returns the new zone name if it was set (https://github.com/moment/moment-timezone/blob/develop/moment-timezone.js#L383).

**Comment by mj1856** [comment]
Good catch!  This will be a breaking change, but given our 0.x status, I think that's fine.

**Comment by timrwood** [comment]
Closing in favor of #272

**Comment by syrnick** [comment]
Oops. Looks like this issue is invalid. The setter returns `this` and the getter returns then name if set.

**Comment by mj1856** [comment]
Not sure how I missed that, but I agree with @timrwood.
