### ISSUE TITLE
Support for half hour and 45 min ETC tz

### ISSUE THREAD

**Issue by lvegerano** [moment/moment-timezone#257]
Thanks for the plugin! 

I have a Wordpress integration they allow etc half hour and 45 min timezones. It would be nice if they were natively supported. :+1:

**Comment by mj1856** [comment]
They are.

Can you show where they are not?

**Comment by lvegerano** [comment]
I was looking in (here)[https://github.com/moment/moment-timezone/blob/develop/data/packed/latest.json#L266] for something like `Etc/GTM+5:30` for instance. But I maybe looking in the wrong place :smile:

**Comment by mj1856** [comment]
Moment-timezone only works with standard tzdb time zone identifiers.  For India, that would be `Asia/Kolkatta`.

If you only are working with fixed offsets, you don't need moment-timezone.  You can just use `.utcOffset('+05:30')` on a `moment` object.

**Comment by mj1856** [comment]
Also note that `Etc/GMT`... zones are in whole hours only, and have their offsets inverted.  This is explained in the tzdb [here](https://github.com/eggert/tz/blob/3a337b12e81595c328c414cc2ac68f214da3d841/etcetera#L29-L35).  I would only use these zones when absolutely necessary, such as for POSIX compatibility, or when referring to a fixed whole-hour offset that might apply to many different time zones while you're in some context that expects a full ID.

**Comment by lvegerano** [comment]
I understand the issue for me is that not having those in the library causes a lot more headaches :disappointed: So basically you're saying I should not define a Zone like 
```js
    {
        name:    'Etc/GMT+5:30',
        abbrs:   ['GMT+5:30'],
        untils:  [null],
        offsets: [330]
    }
```

**Comment by mj1856** [comment]
No, you probably shouldn't do that.  Nobody else will be able to use it but you, and there's no point of all that overhead just for fixed offsets.  Most time zones have to contend with DST, historical changes, etc.

If for some reason you still wanted to do it, it would actually look like this:

```
{
    name:    'Etc/GMT-5:30',
    abbrs:   ['GMT+5:30'],
    untils:  [Infinity],
    offsets: [-330]
}
```

Notice the differences in sign, which would fit the various conventions.  But I'm not recommending you do this, because nobody but you would know what `Etc/GMT+5:30` is, since it's not defined in the tzdb.

**Comment by lvegerano** [comment]
@mj1856 Thanks and I understand you point. But because of my integration with WordPress I need to add these fixed offsets (because they do). I appreciate all your help :+1: Thanks!

**Comment by mj1856** [comment]
Could you elaborate on that please? Where in WordPress are you having to align to? Can you send a link or attach a screenshot?

If WordPress has a static list of fixed offsets, that's a shame, but if so then you should not be using moment-timezone, especially not with custom zones.  Just make a list of the offsets you want to use and use the `utcOffset` function from the `moment` object instead.

```javascript
// these are all current offsets in use worldwide
var offsets = ['-12:00','-11:00','-10:00','-09:00','-09:30','-08:00','-07:00','-06:00','-05:00','-04:30','-04:00','-03:30','-03:00','-02:30','-02:00','-01:00','+00:00','+01:00','+02:00','+03:00','+03:30','+04:00','+04:30','+05:00','+05:30','+05:45','+06:00','+06:30','+07:00','+08:00','+08:30','+08:45','+09:00','+09:30','+10:00','+10:30','+11:00','+12:00','+12:45','+13:00','+13:45','+14:00'];

// for example, printing the current time in each offset
for (var i=0; i < offsets.length; i++) {
	console.log(moment().utcOffset(offsets[i]).format());
}
```

It's only if WordPress had a list of actual TZDB time zones that you would use moment-timezone.  You seem to be describing a mixed list, some being time zones and some being just offsets.  I would be very surprised to see that.  In other words, if `Etc/GMT-5:30` is actually an entry in some list on WordPress, then someone else further upstream has made a grave error and I would hope you would not propagate that mistake.

**Comment by lvegerano** [comment]
@mj1856 I have an application that integrates with WP and syncs post along some other data and some blog settings (including the TZ of the WP site). Because of this the application must respect all the TZ provided from WP.  [Here] (http://quick.as/ZbV3UYJdY) is a screencast of these manual offsets that they allow a user to select. 

Your solution would be a huge undertaking and at the moment I don't have the resources. That's why Im just basically applying these manual offsets the same way WP is.

**Comment by mj1856** [comment]
Ok, you made me dig a bit deeper into wordpress.... :smile:

If you view-source to look at all the time zones that they have in their list, you'll see what I have copied and pasted to [here](https://gist.github.com/mj1856/f0eaa302d56cd7b3dd3e).

The list contains both valid TZDB time zones that will work in moment-timezone (such as `"Asia/Kolkata"`) and it *also* contains fixed offsets.  :confused:   These are at the bottom of the list, in the "Manual Offsets" group, andappear to be in the form `"UTC+5.5"`.   There are none that use the `Etc/` prefix.

So to meet your goal of working with any time zone from WordPress, you would need to test for their custom format.  For example, to get a moment with the current time in a WP time zone:

```javascript
function nowInTZ(wptz) {
    var re = /UTC([\+\-]\d+(\.\d{1,2})?)/;
    if (re.test(wptz)) {
        var offset = wptz.match(re)[1] * 60;
        return moment().utcOffset(offset);
    }
    return moment.tz(wptz);
}

// example usage:
nowInTZ('America/Los_Angeles').format()  // "2015-10-12T13:19:14-07:00"
nowInTZ('UTC+5.5').format()  // "2015-10-13T01:49:14+05:30"
```

**Comment by lvegerano** [comment]
I was under the impression that `Etc/GMT` is the same as `UTC`. What I've been doing is getting what `"UTC+5.5"` and turning them into `"Etc/GMT+5:30"` so I could work with `moment-timezone`.

**Comment by mj1856** [comment]
The prefix "Etc/" has special meaning.  It means that it is defined in the *etcetera* file in the tzdb, and that the sign of the number will be inverted.  There are no decimal offsets in this format.

If you really want to handle this by adding zone entries, then just leave them in the format you get them from WP.

```javascript
function addWPZone(o) {
	var zone = new moment.tz.Zone();
	zone.name = 'UTC' + (o >= 0 ? '+' : '') + o;
	
	var h = o | 0;
	var m = Math.abs((o % 1) * 60);
	if (m == 0) m = "00";
	zone.abbrs = ['UTC' + (o >= 0 ? '+' : '') + h + ':' + m];

	zone.offsets = [-60 * o];
	zone.untils = [Infinity];

	var name = zone.name.toLowerCase();
	moment.tz._zones[name] = zone;
	moment.tz._names[name] = zone.name;
}

// add whole and half-hour zones
for (var i = -12; i <= 14; i+= 0.5) {
	addWPZone(i);
}

// add 45-minute zones
var others = [5.75,8.75,12.75,13.75]
for (var i = 0; i < others.length; i++) {
    addWPZone(others[i]);
}
```

Now you can just use them.
```javascript
moment.tz('UTC+8.75').format() // "2015-10-13T06:11:52+08:45"
```

Also note that WP's assumption that *all* of those half-hour zones exist in the real world is false.  Ther are only a handful.  But the above matches WP's list.
