### ISSUE TITLE
Add zone in unpacked format

### ISSUE THREAD

**Issue by mattjohnsonpint** [moment/moment-timezone#259]
There is currently no public API for adding an unpacked zone.  `moment.tz.add` only supports the packed format.

That leaves only two options:
1. Using the functions in `moment-timezone-utils.js` to build and pack a zone, just to unpack it again
2. Appending to the `_names` and `_zones` objects manually, which are private fields.

In #257 I had to resort to the second option.

**Comment by gilmoreorless** [comment]
This isn't likely to be added with the project in maintenance mode.
