### ISSUE TITLE
No data for GMT-X timezones after updating 

### ISSUE THREAD

**Issue by 9dev** [moment/moment-timezone#262]
I followed the [contributing guide](https://github.com/moment/moment-timezone/blob/develop/contributing.md) and discovered that the first step is wiping some data out.

In the original repo file `/data/unpacked/latest.json` contains data for timezones like `Etc/GMT+10`, but after running `grunt data` these data become empty arrays with no information at all.

Steps to reproduce:
- Pull the recent version of the moment-timezone
- `> npm install`
- `> grunt data`

Is there a step missing in the guide to obtain the data for these timezones?

**Comment by gilmoreorless** [comment]
I found several discrepancies in how `zdump` produces output across different systems, and how our build system handled it. On some Linux flavours it resulted in fixed-offset zones being reported as the same as `UTC`.

I've (hopefully) fixed that with #1059. 🤞
