### ISSUE TITLE
Moment.tz fails to correct for DST for America/Los_Angeles

### ISSUE THREAD

**Issue by aseckel** [moment/moment-timezone#264]
When I call `moment.tz('2015-11-05T21:00:00.000Z', 'America/Los_Angeles').format()` I am returned `2015-11-05T13:00:00-08:00`.

Until next week, I believe I should be returned `2015-11-05T14:00:00-07:00`? As 'America/Phoenix' returns.

Did not appear to be a problem last week. Though I only discovered thanks to user bug reports this week.

Using the code provided above, the bug is reproducible on latest moment.tz release

**Comment by mj1856** [comment]
DST is tied to the timestamp in question, not the current time.

It changes back on Nov 1st, and your date is Nov 5th, so it is in the standard time period.

**Comment by aseckel** [comment]
Thanks for the clarification!
