### ISSUE TITLE
Use of .zone is deprecated. Update to .offset.

### ISSUE THREAD

**Issue by adsteel** [moment/moment-timezone#267]
https://github.com/moment/moment/pull/2074

**Comment by mj1856** [comment]
Yes.  But what specifically are you asking about in this issue?

**Comment by adsteel** [comment]
No questions. It's just an issue. Is there another way to report an issue like this?

**Comment by mj1856** [comment]
I'm not sure what the issue is.  Are you saying that moment-timezone is using `zone` and shouldn't, and if so, where?

Or are you saying your own code is giving the deprecation message?  If so, there's no issue with moment-timezone, but rather you need to update your own code to reflect the change.

**Comment by adsteel** [comment]
Sorry, I thought moment-timezone was using it, but as I look closer it's not. Not sure where my deprecation errors are coming from then, but that's not a moment-timezone issue. Thanks!

**Comment by mj1856** [comment]
Sure, no problem.
