### ISSUE TITLE
Parsing in Zone Documentation shows invalid example

### ISSUE THREAD

**Issue by drakej** [moment/moment-timezone#268]
Specifically the example below the description text of "The offset is only taken into consideration when constructing with an array, string without offset, or object." is invalid.

From the documentation:

```
var arr = [2013, 5, 1],
    str = "2013-12-01"
    obj = { year : 2013, month : 5, day : 1 };

moment.tz(arr, "America/Los_Angeles").format(); // 2013-06-01T00:00:00-07:00
moment.tz(str, "America/Los_Angeles").format(); // 2013-06-01T00:00:00-07:00
moment.tz(obj, "America/Los_Angeles").format(); // 2013-06-01T00:00:00-07:00

moment.tz(arr, "America/New_York").format();    // 2013-06-01T00:00:00-04:00
moment.tz(str, "America/New_York").format();    // 2013-06-01T00:00:00-04:00
moment.tz(obj, "America/New_York").format();    // 2013-06-01T00:00:00-04:00
```

ACTUAL results

```
var arr = [2013, 5, 1],
    str = "2013-12-01"
    obj = { year : 2013, month : 5, day : 1 };

moment.tz(arr, "America/Los_Angeles").format(); // 2013-06-01T00:00:00-07:00
moment.tz(str, "America/Los_Angeles").format(); // 2013-12-01T00:00:00-08:00
moment.tz(obj, "America/Los_Angeles").format(); // 2013-06-01T00:00:00-07:00

moment.tz(arr, "America/New_York").format();    // 2013-06-01T00:00:00-04:00
moment.tz(str, "America/New_York").format();    // 2013-12-01T00:00:00-05:00
moment.tz(obj, "America/New_York").format();    // 2013-06-01T00:00:00-04:00
```

Note that the second call's result for both America/New_York and America/Los_Angeles should show 2013-12-01 not 2013-06-01 which is what is shown in the documentation. It also has the wrong offset for them as well.

Reference page: http://momentjs.com/timezone/docs/#/using-timezones/parsing-in-zone/

**Comment by MartynDavis** [comment]
Documentation is wrong, the str variable should be set to "2013-06-01" (i.e. June 1st rather than December 1st)

**Comment by mj1856** [comment]
Agreed.  A PR to https://github.com/moment/momentjs.com would be appreciated.

Thanks.
