### ISSUE TITLE
How to create tz-aware objects from Moment objects without a timezone attached? 

### ISSUE THREAD

**Issue by kevinburkeshyp** [moment/moment-timezone#270]
Say I create a Moment object before loading moment-timezone

```javascript
var moment = require('moment');
var now = moment();
try {
    console.log(now.tz('America/New_York').format());
} catch (err) {
    console.log('caught err', err);
}

var tz = require('moment-timezone');
console.log(now.format());
console.log(now.tz('America/New_York').format());
```

what's the best way to convert that to a tz-aware object I can call `.tz()` on?

**Comment by mj1856** [comment]
It should work if you clone it by wrapping in a new moment

```javascript
now = moment(now).tz('America/New_York');
```

**Comment by timrwood** [comment]
Calling `require('moment-timezone')` will attach the `tz` method to the `moment` prototype. You will then be able to use `.tz` on those moments.

**Comment by mj1856** [comment]
@timrwood - I think the problem is that modifying the prototype doesn't affect objects already created.

**Comment by mj1856** [comment]
I'm not sure that we can do anything about this.  In general, put all your `require` statements at the top.  If you can't for some reason, the workaround I gave above should do the trick.
