### ISSUE TITLE
invalid parsing of Do

### ISSUE THREAD

**Issue by OceanWolf** [moment/moment-timezone#273]
```javascript
fmt = "MMMM Do YYYY, h:mm:ss a";
console.log(moment("February 26th 2016, 07:00:00 pm", fmt).format(fmt));
```

gives
```
February 1st 2016, 7:00:00 pm
```

**Comment by mj1856** [comment]
Works for me.

![image](https://cloud.githubusercontent.com/assets/1396388/11492081/29f59160-979d-11e5-844a-04cde727958b.png)


This wouldn't be a moment-timezone issue anyway.
