### ISSUE TITLE
Support for Arizona America/Shiprock

### ISSUE THREAD

**Issue by katherine-barn2door** [moment/moment-timezone#276]
I noticed that a timezone code for the Navajo Nation of Arizona is missing.

**Comment by timrwood** [comment]
It is supported as an alias to `America/Denver`. See [here](https://github.com/moment/moment-timezone/blob/c3983eaab28c18d54969800fec43c3c693b6cd2c/data/packed/latest.json#L455).

```js
moment.tz('America/Shiprock').format('Z z'); // -07:00 MST
```

**Comment by katherine-barn2door** [comment]
Excellent - I didn't see those. Thanks!
