### ISSUE TITLE
Etc/GMT+-X offsets are wrong

### ISSUE THREAD

**Issue by jorupp** [moment/moment-timezone#277]
The offsets are inverted.  Ie. New York is currently in GMT-5, offset: 300.  GMT-5 is configured with offset -300.

**Comment by jorupp** [comment]
Per https://en.wikipedia.org/wiki/Tz_database#Area, it looks like it's supposed to work that way for POSIX compatibility.  Etc/GMT-5 means 5 hours ahead of GMT per POSIX.

I guess the question is which makes more sense - POSIX compatibility or making sense.

**Comment by mj1856** [comment]
We must adhere to the tz database conventions - even the quirky ones.

**Comment by farsightsoftware** [comment]
If `Etc/GMT+1` is required by this foolishness to be GMT-0100, then Moment-Timezone should add its own `Sane/GMT+1` or similar. And yes, absolutely, as flagged up in #278 this should be boldfaced in the documentation.

**Comment by mj1856** [comment]
@farsightsoftware - We should absolutely not implement our own time zone identifiers.  We are simply one of many implementations that use the IANA time zone database.  If you want to propose fixed offsets with different naming conventions, then the place to do it is on the TZDB discussion mailing list at http://iana.org/time-zones
