### ISSUE TITLE
Explain the confusing use of inverted GMT offsets

### ISSUE THREAD

**Issue by minj** [moment/moment-timezone#278]
``` js
moment(new Date()).tz('Europe/Zurich').format() // "2015-12-04T14:12:54+01:00"
moment(new Date()).tz('Etc/GMT+1').format() // "2015-12-04T12:13:06-01:00"
moment(new Date()).tz('Etc/GMT-1').format() // "2015-12-04T14:13:30+01:00"
```

Erm... What?

https://en.wikipedia.org/wiki/GMT%2B1

**Comment by minj** [comment]
Ah, sorry I missed #277.

This should really be added in bold somewhere in the docs

**Comment by timrwood** [comment]
Good point. Would you mind opening a PR for the docs here? https://github.com/moment/momentjs.com

**Comment by skeggse** [comment]
👍  on @timrwood's comment
