### ISSUE TITLE
Asia/Taipei tz name

### ISSUE THREAD

**Issue by focworkshop** [moment/moment-timezone#282]
moment-timezone/data/packed/2015g.json#226 should be TST TDT instead of CST/CDT

**Comment by timrwood** [comment]
The data comes from the standardized IANA Time Zone Database. https://www.iana.org/time-zones

Any changes like this would need to be made upstream there.

**Comment by mj1856** [comment]
Though this is not the correct place to ask, the request seems legitimate, given [the history described on Wikipedia](https://en.wikipedia.org/wiki/Time_in_Taiwan).   I will ask on the IANA tz mailing list.

**Comment by mj1856** [comment]
http://mm.icann.org/pipermail/tz/2015-December/023038.html

**Comment by mj1856** [comment]
As a follow up, the reply on the tz list was:

> This is an area where no abbreviation is perfect.
>
> As I understand it part of the confusion is that although CST typically stands for China Standard Time in international English, in Taiwan among the few people who care about these things in English it also stands for Chungyuan Standard Time, which is partly a Wade-Giles romanization of, and partly an English translation of, "中原時區" ("Central Plain Standard Time"); this is what the 
Nationalist government called the UTC+8 time zone that was partly implemented in China before 1949. This latter, more-specialized use of CST was never intended in the tz database. So, although from the point of view of a Taiwanese time nerd the abbreviation "CST" may seem politically obsolete, from an international viewpoint "CST" is still a quite common abbreviation.
> 
> We are concerned only with English-language abbreviations. Of course if usage changes the abbreviation should too (that is what happened with Australia). That being said, in looking at what is published in English-language books and so forth, my impression is that "CST" still predominates, if only due to inertia. I'm a fan of inertia.

http://mm.icann.org/pipermail/tz/2015-December/023039.html
