### ISSUE TITLE
BST not supported(?)

### ISSUE THREAD

**Issue by philip-peterson** [moment/moment-timezone#283]
Hey there, I'm not sure if this is a bug or if I'm just missing something, but... when I do a calculation across the change to British Summer Time (BST) which is supposed to happen on March 27, 2016, I do not seem to be getting the right interval.

```
var x = moment.tz('2016-03-01', 'Europe/London');
var y = moment.tz('2016-03-31', 'Europe/London');

console.log(y.diff(x)/1000/60/60/24) // yields 30
```

As you can see here, I am diffing two dates (one before BST begins, one after) and finding the number of 24-hour periods that have passed. One would expect that the number be slightly below 30 because of the hour that was skipped in the transition to BST, but 30 is the exact result. Is BST-sensitive time construction not supported yet -- or am I doing something wrong?

**Comment by philip-peterson** [comment]
Interesting, now I see that this works:

```
var x = moment('2016-03-01').tz('Europe/London');
var y = moment('2016-03-31').tz('Europe/London');

console.log(y.diff(x)/1000/60/60/24) // 29.958333333333332
```

I suppose it's a matter of the moment.tz constructor not working the way I think it does... Sorry about that!

**Comment by mj1856** [comment]
Actually your first code example was correct, and I do indeed get slightly less than 30:

![image](https://cloud.githubusercontent.com/assets/1396388/12007795/c9da555e-abc9-11e5-9f79-dfbaa68a76f1.png)

If you get exactly 30, I'd love to know more about your environment - browser, version, os, local time zone, etc.

The difference between the two forms you showed is that `moment.tz('2016-03-01', 'Europe/London')` parses the input as belonging to the provided time zone, while `moment('2016-03-01').tz('Europe/London')` parses the input as *local time* and then *converts* it to the provided time zone.

**Comment by philip-peterson** [comment]
Strange... Here's a link to the fiddle that produces 30 for me:

https://jsfiddle.net/9bovp8L9/

Version of moment is 2.10.6 (hosted by cdnjs) and moment-timezone is 0.4.1 (also on cdnjs)

**Comment by timrwood** [comment]
@philip-peterson, if you open the dev console on that jsfiddle, you will see an error stating that the `Europe/London` data is not loaded.

**Comment by philip-peterson** [comment]
Aha! Completely missed that whole loading step, it explains a lot of things. Thanks!
