### ISSUE TITLE
Guess timezone name for custom date

### ISSUE THREAD

**Issue by mqklin** [moment/moment-timezone#287]
I know that I can get browser timezone name: `moment.tz.guess()`

How can I guess timezone for custom date? e.g. `moment("2020-12-30T14:17:40+11:00").tz.guess()` ?

**Comment by timrwood** [comment]
I'm not sure what you are looking for here. Are you trying to find a timezone that matches `+11:00`?

There are likely dozens of timezones that could match each offset, see the `Time Zone != Offset` section here http://stackoverflow.com/tags/timezone/info

**Comment by mqklin** [comment]
thx
