### ISSUE TITLE
Should the documentation for zone.offset indicate that it accepts a timestamp in milliseconds?

### ISSUE THREAD

**Issue by CovertIII** [moment/moment-timezone#288]
I was trying to use zone.offset and the documentation didn't make it clear that the timestamp it accepted was in milliseconds not seconds.  I was passing moment().unix() into it and it wasn't adjusting for daylight savings and I couldn't figure out why until I realized it took a timestamp in milliseconds.

**Comment by gilmoreorless** [comment]
The [Zone object docs](https://momentjs.com/timezone/docs/#/zone-object/offset/) have updated to say the timestamp is in milliseconds.
