### ISSUE TITLE
GMT+03:00 Asia/Baghdad instead of Europe/Moscow

### ISSUE THREAD

**Issue by alealex** [moment/moment-timezone#290]
I have 
moment.js version : 2.11.1 
moment-timezone.js version : 0.5.0
os windows 7

If I set timezone to UTC+3 Moscow, St.Petersburg, Volgograd (RTZ 2) then the following code
`"GMT" + moment().format('Z') + ":" + moment.tz.guess()`
will produce `GMT+03:00:Asia/Baghdad`

expected result is `GMT+03:00:Europe/Moscow`

http://jsfiddle.net/3javhx7k/2/

navigator.appVersion is "5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.91 Safari/537.36"

**Comment by mj1856** [comment]
@timrwood - While some guesses will certainly be wrong, in this particular case we can fix the problem by using the `Intl` api when available.

**Comment by sompylasar** [comment]
Be careful, the `Intl` API returns `Asia/Riyadh` in Chrome, so we cannot actually rely on the `Intl` API, that being a shame for Chrome, but nevertheless.
```
> Intl.DateTimeFormat().resolvedOptions().timeZone
"Asia/Riyadh"
```

Note that none of the guessed candidates in `zoneScores` is `Europe/Moscow`, so there's something wrong with guessing.

**Comment by sompylasar** [comment]
http://pellepim.bitbucket.org/jstz/ did this right somehow, resolves to `Europe/Moscow`.

**Comment by mj1856** [comment]
Intl APIs in newer Chrome does work now.  They used to resolve incorrectly, but that was fixed awhile back (not sure exactly when).

Also, I tested against latest (0.5.13) in IE - which uses the guessing algorithm - and it does now return `Europe/Moscow`.

**Comment by sompylasar** [comment]
@mj1856 Chrome bug here but marked as Started, not Fixed as of now. https://bugs.chromium.org/p/v8/issues/detail?id=3547

**Comment by mj1856** [comment]
@sompylasar  - Yeah, that bug is still present.  However, I don't think it affects our guessing algorithm since Chrome still correctly returns `Europe/Moscow` for the default time zone via `Intl`.
