### ISSUE TITLE
"Time zone" is misspelled "timezone" in the documentation

### ISSUE THREAD

**Issue by dharcourt** [moment/moment-timezone#292]
Steps to reproduce:

1. Go to http://momentjs.com/timezone/docs/.
2. Search for "time zone" (case insensitive) in that page. Note that there are a number of places in the documentation where time zone is spelled "time zone".
3. Search for "timezone" (lowercase) in that page. Note that there are a number of places in the documentation where time zone is spelled "timezone" in addition to the places where the documentation refers to "Timezone" (uppercase) as part of the name "Moment Timezone".
4. Look for "time zone" and "timezone" in a number of references (like Merriam-Webster's at http://www.merriam-webster.com/dictionary/timezone, the more authoritative new oxford american dictionary available in Mac OS X's Dictionary app, or wikipedia  at https://en.wikipedia.org/wiki/Time_zone). Note that all of these document the one and only spelling of time zone as "time zone". "timezone" is not even provided as a secondary or alternate spelling of "time zone".

Expected behavior:

- The spelling of time zone in the English documentation and API matches the official spelling of that term in English.

Actual behavior:

- The spelling is correct in the API (as far as I can tell) and in some of the documentation, but it's incorrect in other parts of the documentation.

Notes:

- It's fine for Moment Timezone to spell "time zone" as a single word in its name, since this is a name, and names can be arbitrary.
- Using that misspelling in API and documentation, however, will increase the likelihood that developers using Moment Timezone will propagate that framework's misspelling in their API, and when multiple developers in a project use Moment Timezone this will make it likely that some developers use the correct spelling and some don't, leading to inconsistencies and hard to predict APIs.

**Comment by mj1856** [comment]
Thanks.  Will track in moment/momentjs.com#266.  Feel free to submit a PR there if you like.
