### ISSUE TITLE
Update to tzdb 2016a

### ISSUE THREAD

**Issue by pahud** [moment/moment-timezone#296]
Is there any utils available so I can  update the` latest.json` by myself?

**Comment by mj1856** [comment]
The tools are all available and [described here](https://github.com/moment/moment-timezone/blob/develop/contributing.md#compiling-data), but yes, we need to build and publish a new release.  (ping @timrwood)

**Comment by mj1856** [comment]
@pahud  be sure to see the section at the very bottom of the page labeled "All tasks"
