### ISSUE TITLE
Wrong result for local week number (format('w') for timezone "Europe/Stockholm"

### ISSUE THREAD

**Issue by TobbeLino** [moment/moment-timezone#305]
I'm getting all wrong local week numbers when using format('w').
At least with timezone "Europe/Stockholm"...

For example:
d = moment.tz('2016-01-03T00:00:00+01:00', 'Europe/Stockholm');
console.log(d.format('w'));

Gives week number 2 (should actually be 53)

Here's a fiddle with a range of dates:
http://jsfiddle.net/TobeLino/wk0sLex5/3/

**Comment by mj1856** [comment]
It's working as designed.

`.format('w')` and `.week()` give you the locale-based week number.  You are probably looking for `.format('W')`, which like `.isoWeek()` gives you the ISO8601 week number.

See:
http://momentjs.com/docs/#/get-set/week/
http://momentjs.com/docs/#/get-set/iso-week/

**Comment by TobbeLino** [comment]
Hmm - ok, but in that case, exactly what is "locale-based week number"?
In Europe/Stockholm it was week 53 at the time 2016-01-03T00:00:00  (not week 2)
And  2016-01-02 is the start of week 1...
We actually use the same week numbering as ISO8601 in Sweden, so I would expect .week() and .isoWeek() to return the same number for "Europe/Stockholm"

.format('w') and .week() makes no sense to me if it's not supposed to return the specified timezone's local-based week number. Or what am I missing? 
Where does the '2' come from in:
moment.tz('2016-01-03T00:00:00', 'Europe/Stockholm').week()

**Comment by TobbeLino** [comment]
And check this out: http://jsfiddle.net/hmokk7gm/7/

I'm, looping through every single timezone, writing the local week number for the date "2016-01-03T00:00:00" for each, and ALL of them returns '2'! That is surely not correct...

It seems to me that .week() always returns the week number according to North American standard (used in "Canada, USA, China, Japan, Israel, South Africa, most of Latin America" according to the "Week numbering" section of Wikipedia on "Week": https://en.wikipedia.org/wiki/Week).

**Comment by mj1856** [comment]
Sorry for the delayed response.

Locale and time zone are two different things.  Locale is part of the core of moment.js.  Timezone is supplied by moment-timezone.  You can use any locale you want, in any time zone you want.  They are not bound together.

If you are using the default US-English local, then Sunday is the first day of the week.  If you are using the Swedish locale, then Monday is the first day of the week.

See more in http://momentjs.com/docs/#/i18n/

**Comment by mj1856** [comment]
BTW - locale and time zone are *always* separated, even on other platforms, such as Java and .NET.  Operating systems separate them as well.

As an example, I might be a US-English speaking person visiting Japan.  Or I might be sitting in Africa but converting times for events in Canada.  They have different reasons for change, and are thus always separated.

**Comment by TobbeLino** [comment]
Ahh ok, I realize that now...
Thanks a lot for taking the time to explain in detail!
