### ISSUE TITLE
Time zone not reflected in creation data

### ISSUE THREAD

**Issue by mattjohnsonpint** [moment/moment-timezone#313]
The [`moment.creationData` function](http://momentjs.com/docs/#/parsing/creation-data/) is supposed to return all values used to create the moment.

However, the time zone is not reflected in the creation data when using moment-timezone, as in:

``` javascript
moment.tz('2015-01-01 00:00:00', 'America/New_York').creationData();
```

It also returns `isUTC: true`, which is misleading.

**Comment by mj1856** [comment]
Agreed. :+1:

**Comment by gilmoreorless** [comment]
Closing this given the maintenance mode status of the project.
