### ISSUE TITLE
POSIX-style TZ string support?

### ISSUE THREAD

**Issue by pahud** [moment/moment-timezone#314]
Hello,

I am looking for a way to generate [Posix TZ Strings](http://www.di-mgt.com.au/wclock/tz.html) with given timezone.  Is it possible to generate with **moment-timezone**?

**Comment by mj1856** [comment]
Nope, and not recommended, for the reasons described in the [timezone tag wiki on StackOverflow](http://stackoverflow.com/tags/timezone/info).  (Scroll down to the second-to-last section titled "POSIX style time zones")

I'm curious though - what is the use case?  Why do you want them?

**Comment by mj1856** [comment]
Also, the advice on the link you gave is highly applicable:

> Caution: edit this file at your own risk. We have provided some TZ values that we believe are correct but we offer no guarantees on their validity.

> It's up to you to derive the correct POSIX.1 TZ string for any new time zones you want to add. If the politicians in the zone in question mess around with the timing of daylight saving every year, you will have to edit the file to suit every year, too.

And guess what - politicians do indeed do this each and every year!

**Comment by pahud** [comment]
Hello, 

Thanks.  We are working on IoT devices which have no TZ database built inside and we have make them timezone-aware, especially for the DST.  I am planing to build a service with _moment-timezone_ on _AWS Lambda_ and _API Gateway_ for IoT devices, when devices query with relevant timezone, the service return POSIX-style timezone for them and the firmware in the device will configure itself properly.  Is it a good solution or is there any other recommended approaches?

Thanks again.

**Comment by mj1856** [comment]
Ok, I can understand that use case.  I'll post some code shortly.

**Comment by mj1856** [comment]
Ok, so here is a whole bunch of code to throw at you. :smile: 

A few caveats first:

1. I really only recommend POSIX time zones for scenarios like the one you described.  If you are working with smarter devices (like raspberry pi, arduino, etc.) then please just use tzdb zones.

2. With the POSIX string, the device will be able to keep local time correctly.  Don't expect the device to be accurate with regard to *past* timestamps.

3. If you're just collecting data with these devices, then consider that you might not need time zones on the device at all.  You might just work with UTC, and do all local time conversions with the data afterwards.

4. One place this makes a lot of sense is if the device itself has a physical display showing a clock.

5. Make sure your device regularly checks for an updated POSIX definition.  Time zones can change, and when they do the POSIX string will be different from one year to the next.

6. There are some superficial assumptions being made, such as that all time zone transitions are for DST.  Indeed we know that not to be the case, as some time zones have changed their base offsets.  That would be picked up as DST here, but would probably have the same effect on the device.

7. Some cases simply can't be handled correctly, such as when there are more than two transitions in a single year  (Morocco presently, Egypt in past years).

Ok, here's the code already.

```javascript
function getPosixStringForCurrentYear(tz) {
    var jan = moment.tz({month: 0, day: 1}, tz);
    var jun = moment.tz({month: 5, day: 1}, tz);
    var janOffset = jan.utcOffset();
    var junOffset = jun.utcOffset();
    var stdOffset = Math.min(janOffset, junOffset);
    var dltOffset = Math.max(janOffset, junOffset);
    var std = stdOffset === janOffset ? jan : jun;
    var dlt = dltOffset === janOffset ? jan : jun;

    var s = std.format('z').concat(formatOffsetForPosix(stdOffset));

    if (stdOffset !== dltOffset) {
	    s = s.concat(dlt.format('z'));
	    if (dltOffset !== stdOffset + 60) {
	    	s = s.concat(formatOffsetForPosix(dltOffset));
	    }

	    s = s.concat(',').concat(formatTransitionForPosix(tz, std));
	    s = s.concat(',').concat(formatTransitionForPosix(tz, dlt));
    }

    return s;
}

function formatOffsetForPosix(offset) {
	var h = -offset / 60 | 0;
	var m = Math.abs(offset % 60);
	return h + (m === 0 ? '' : ':'.concat(m < 10 ? '0' : '').concat(m));
}

function formatTransitionForPosix(tz, m) {
	var zone = moment.tz.zone(tz);
	var ts = zone.untils[zone._index(m)];
	var transition = moment(ts).utcOffset(-zone.offset(ts - 1));
	var n = transition.date() / 7 | 0 + 1;
	var s = transition.format('[M]M.[n].d').replace('n', n);
	var time = transition.format('[/]H:mm:ss').replace(/\:00$/, '').replace(/\:00$/, '');
	if (time !== '/2') {
		s = s.concat(time);
	}
	return s;
}
```

Some examples:
```javascript
getPosixStringForCurrentYear('America/New_York') // "EST5EDT,M3.1.0,M11.1.0"
getPosixStringForCurrentYear('Australia/Sydney') // "AEST-10AEDT,M10.1.0,M4.1.0/3"
getPosixStringForCurrentYear('America/Sao_Paulo') // "BRT3BRST,M10.3.0/0,M2.3.0/0"
getPosixStringForCurrentYear('Europe/London') // "GMT0BST,M3.3.0/1,M10.5.0"
getPosixStringForCurrentYear('Australia/Lord_Howe') // "LHST-10:30LHDT-11,M10.1.0,M4.1.0"
getPosixStringForCurrentYear('Pacific/Chatham') // "CHAST-12:45CHADT,M9.3.0/2:45,M4.1.0/3:45"
```

**Comment by mj1856** [comment]
@timrwood - Do you think we should include this in moment-timezone directly?  I can see this being useful for others.

**Comment by mj1856** [comment]
Note, I updated the code above to handle some edge cases.  Really this should be unit tested.  :wink:

**Comment by pahud** [comment]
THANK YOU SO MUCH!!!!

**Comment by mj1856** [comment]
After some discussion with the moment core team, we've decided not to include this in the moment-timezone API at this time.  However, we will move it to a separate utility script and add some unit tests.  That way we can be sure we don't break it in future releases.  You'd still need to download the script separately to use it.

**Comment by pahud** [comment]
I understand. Thank you!

**Comment by mj1856** [comment]
Note - there was a bug in the code above in the `formatTransitionForPosix` function.  I have updated it, and the examples.

**Comment by alizeegtd** [comment]
@mj1856 you said "I really only recommend POSIX time zones for scenarios like the one you described. If you are working with smarter devices (like raspberry pi, arduino, etc.) then please just use tzdb zones."
What do you mean? What's the difference?

**Comment by raldone01** [comment]
Awesome! Thank you!

**Comment by mj1856** [comment]
Given [Moment's project status update](https://momentjs.com/docs/#/-project-status/) and the age of this issue, I am closing this issue.  You can still use the code above, but we won't be adding it to the repository in the way I suggested [above](#issuecomment-200915775).
