### ISSUE TITLE
Reliable way to search for timezone by name

### ISSUE THREAD

**Issue by JulianLaval** [moment/moment-timezone#316]
Hi all,

Thanks for the great work on Moment Timezone!

I'm building a service that relies heavily on accurately displaying time to the user. To this end, although `moment.tz.guess()` is sufficient to provide an initial suggestion, I require the ability change the selected timezone by searching for a city name, for example.

Is this a use case that has already been examined? If so, is there an intuitive way to compute an array of timezone names that match a search string? Would this make sense as an additional method in Moment Timezone, e.g. `moment.tz.search('Paris')`?

Thanks in advance!

**Comment by timrwood** [comment]
You could use `moment.tz.names()` to do search, but it is probably not ideal, as each timezone would likely only match 1 city.

Maintaining a mapping of cities to timezones is outside the scope of this project, so we will probably not add something like this to the library, but you could probably use a third party service for this. Google Maps supports looking up a timezone from a latitude and longitude, perhaps you could use that? https://developers.google.com/maps/documentation/timezone/intro#Introduction

**Comment by JulianLaval** [comment]
Yep, `moment.tz.names()` wouldn't be sufficient since parsing it would indeed only map to one city.

I'll have a think about the best way to compile a list of cities (presumably caching results from Google's Timezone API would be a no-no) and post here with any updates!
