### ISSUE TITLE
iteration variable in unpackBase60()

### ISSUE THREAD

**Issue by jangreis** [moment/moment-timezone#317]
Note: this is more of a style issue so certainly not crucial, but Closure Compiler complained when running over it and when trying to figure out what was going on I found the syntax a little bit confusing. 

Line 73 (inside function unpackBase60()) reads
for (i; i < whole.length; i++) {
Since i is initialized previously and argument 1 in a for loop is optional, wouldn't it be better if this was
for (; i < whole.length; i++) {
?

**Comment by timrwood** [comment]
Yeah, I noticed this as well when working on converting the source to es6.

The es6 version now uses `for (let i` instead.

https://github.com/moment/moment-timezone/blob/689734d7030d00ddc4631975e3ae6e800a386efa/src/unpack/unpack-base-60.js#L14

**Comment by jangreis** [comment]
Sorry, this might be a very stupid question, but does this mean the next version of moment-timezone will no longer be compatible with anything that's red here?
http://caniuse.com/#feat=let

**Comment by timrwood** [comment]
@jangreis, no, we will transpile down to es5 with [babel](https://babeljs.io/), so browser support will remain the same.
