### ISSUE TITLE
Documentation includes function filterYears but most recent version does not

### ISSUE THREAD

**Issue by dodtsair** [moment/moment-timezone#319]
Am I missing something?

I do the following:

```
var momentTZ = require('moment-timezone');



var currentDate = new Date();
var currentYear = currentDate.getFullYear();
var zoneNames = momentTZ.tz.names();
var unpackedZones = [];
zoneNames.forEach(function(zoneName) {
  unpackedZones.push(momentTZ.tz.zone(zoneName));
});
var relevantZones = momentTZ.tz.filterYears(unpackedZones, currentYear);
```

This errors calling momentTZ.tz.filterYears because it does not exist.  Was this function removed?

How do I get a list of zones and relevant information to the present?

**Comment by timrwood** [comment]
As noted at the top of the section in http://momentjs.com/timezone/docs/#/data-utilities/, these utilities are available in `moment-timezone-utils.js`. I think you should be able to load them for use by changing the first lines to something like this.

```js
var momentTZ = require('moment-timezone');
require('moment-timezone/moment-timezone-utils');
```

These will be moved around a bit with the conversion to es6 modules in #310. What are you trying to accomplish when using `filterYears`, is there a way we could make this easier to use for you?

**Comment by dodtsair** [comment]
I was trying to get a list of TZ names that are current.  I didn't want a list that includes TZs that never existed or were no longer used.
