### ISSUE TITLE
after changing the timezone, object change Zone incorrectly

### ISSUE THREAD

**Issue by aliaksandr-pasynkau** [moment/moment-timezone#323]
const d1 = moment('Thu Oct 22 2015 00:50:48 GMT-0700');
const d2 = moment('Thu Dec 31 2015 00:21:04 GMT-0800');

d1.format('Z') // "+03:00"
d1.format('Z') // "+03:00"

d1.tz('America/Toronto').format('Z') // "-04:00"
d2.tz('America/Toronto').format('Z') // "-05:00"

// BUT

const dd2 = moment.tz('Thu Oct 22 2015 00:50:48 GMT-0800', 'America/Toronto');
const dd1 = moment.tz('Thu Oct 22 2015 00:50:48 GMT-0700', 'America/Toronto');

dd1.format('Z') // "-04:00"
dd2.format('Z') // "-04:00"

may be I use this wrongly ?

**Comment by maggiepint** [comment]
On October 22nd 2015, Toronto was observing DST, making their UTC offset -4.
On December 31 2015, they were not observing DST, making their UTC offset -5.

That appears to be exactly what is going on with your code here.
Note that you have October 22 twice in your second set of code.

As an additional note, the date format you are using falls back to JS date construction. This is something that we advise against. Using the following format will stop the date construction deprecation warning and ensure consistency across browsers:

```js
moment('Thu Dec 31 2015 00:21:04 GMT-0800', 'ddd MMM DD YYYY HH:mm:ss [GMT]Z' )
```
