### ISSUE TITLE
Never returns a proper converted time in chosen Europe zone! 

### ISSUE THREAD

**Issue by qbAnu** [moment/moment-timezone#329]
Hi,

I am trying to convert a UTC date to my chosen timezones in my application and seems that Europe/-any- zones never have a proper data.

Code :
`moment("2016-04-07T04:44:51.000+0000").tz(myTz).format('DD MMM YYYY hh:mm:ssA')`

> myTz has string values Europe/Amsterdam OR America/New_York OR Asia/Calcutta OR Indian/Mauritius

Results :
GMT (+00:00)= 2016-04-07 04:44:51AM
Europe/Amsterdam (+02:00)= 07 Apr 2016 12:48:03AM [WRONG]
America/NY (-04:00)= 07 Apr 2016 12:44:51AM [CORRECT]
Asia/Calcutta (+05:30) = 07 Apr 2016 10:14:51AM [CORRECT]
Mauritius (+04:00)= 07 Apr 2016 08:44:51AM [CORRECT]

What am I doing wrong here. Please help. :'(

**Comment by mj1856** [comment]
Works for me. https://jsfiddle.net/692p2v8a/
Are you sure you're loading the time zone data correctly?

**Comment by mj1856** [comment]
Since it works in the fiddle I provide, I'm closing the issue.  Please let me know if you still need assistance.  Thanks.
