### ISSUE TITLE
How to use the regular moment format('h:mm A') on timezone object ?

### ISSUE THREAD

**Issue by pravin-d** [moment/moment-timezone#330]
I'm using moment.tz for converting the time from one timezone to another. However after the data is converted to another timezone I would like to use it like a regular moment obj. Currently I'm getting the following error 
moment.min.js:6 Uncaught TypeError: this.localeData(...).meridiem is not a function
    at n.<anonymous> (http://localhost:3000/admin/app/bower_components/moment/min/moment.min.js:6:20166)
    at Object.h:mm A (http://localhost:3000/admin/app/bower_components/moment/min/moment.min.js:6:4401)

**Comment by maggiepint** [comment]
I'm not sure what syntax you are using, but this should work fine. 

```js
moment.tz('2016-01-01', 'America/New_York').format('h:mm A')
"12:00 AM"
```

I would need to know exactly what code you are running, and based on the error message the locale you are using, to be able to advise further.

**Comment by maxfi** [comment]
I had the same error occur due to deep cloning an object with a nested moment and then using the cloned nested moment in a new moment's constructor:

```
var obj = { m: moment() };
var clone = lodash.cloneDeep(obj);
var m = moment(clone.m);

m instanceof moment; // => true
m.format('ha'); // => Uncaught TypeError: this.localeData(...).meridiem is not a function
```
