### ISSUE TITLE
Momentjs timezones for each UTC offset.

### ISSUE THREAD

**Issue by im1dermike** [moment/moment-timezone#331]
I'm attempting to allow users to select a timezone from a manageable list where there is one for each UTC offset.  I'm trying to determine the momentjs timezone name that matches the list I've come up with (from Windows time zones), but I'm having trouble completing the list.  Here is what I have:

(UTC-12:00) International Date Line West: Pacific/Wallis
(UTC-11:00) Coordinated Universal Time-11: Pacific/Pago_Pago
(UTC-10:00) Hawaii: US/Hawaii
(UTC-09:00) Alaska: US/Alaska
(UTC-08:00) Pacific Time (US & Canada): America/Pacific
(UTC-07:00) Mountain Time (US & Canada): America/Mountain
(UTC-06:00) Central Time (US & Canada): America/Central
(UTC-05:00) Eastern Time (US & Canada): America/Eastern
(UTC-04:00) Atlantic Time (Canada): Canada/Atlantic
(UTC-03:00) Buenos Aires: America/Argentina/Buenos_Aires
(UTC-02:00) Coordinated Universal Time-02: America/Godthab
(UTC-01:00) Azores: Atlantic/Azores
(UTC) Coordinated Universal Time: UTC
(UTC+01:00) Brussels, Copenhagen, Madrid, Paris: Europe/Paris
(UTC+02:00) E. Europe: Europe/London
(UTC+03:00) Baghdad: Asia/Baghdad
(UTC+04:00) Moscow, St. Petersburg, Volgograd: Europe/Moscow
(UTC+05:00) Islamabad, Karachi: Asia/Karachi
(UTC+06:00) Astana: Asia/Tehran
(UTC+07:00) Bangkok, Hanoi, Jakarta: Asia/Bangkok
(UTC+08:00) Taipei: Asia/Taipei
(UTC+09:00) Seoul: Asia/Seoul
(UTC+10:00) Brisbane: Australia/Brisbane
(UTC+11:00) Solomon Is., New Caledonia: Pacific/Guadalcanal
(UTC+12:00) Coordinated Universal Time+12: Pacific/Fiji
(UTC+13:00) Samoa: Pacific/Samoa

Alternatively, is there a way to specify the timezone using base UTC offset?

**Comment by mrmkamranmalik** [comment]
How to use this list?

**Comment by sanathpathiraja** [comment]
ex:
npm install moment-timezone --save
 or 
include moment-timezone.min.js

moment().tz('Asia/Calcutta').format('MM/DD/YYYY')

Thanks.

**Comment by niravlogistic** [comment]
just for update

US Mountain Standard Time 
from: America/Mountain
to: US/Mountain

Pacific Standard Time
from: America/Pacific
to: US/Pacific
