### ISSUE TITLE
get timezoneId from lat lng without?

### ISSUE THREAD

**Issue by nasr18** [moment/moment-timezone#332]
First of all Thanks for this js. It really reduced my time to find time of a location. But how do i get timezoneId of a location from its `lat, lng`? Already I'm using node-timezoner to find timezoneId of a location from `lat, lng`. But it taking little bit time to fetch data. Is that possible with this js???

**Comment by mj1856** [comment]
http://stackoverflow.com/questions/16086962/how-to-get-a-time-zone-from-a-location-using-latitude-and-longitude-coordinates

**Comment by nasr18** [comment]
I got what i want using google timezone api. Anyway thanks for your reply.

**Comment by prashantpsg** [comment]
Hi nasr18

> I got what i want using google timezone api. Anyway thanks for your reply.

Can you share the timezone api which worked for you.
I got below api 
TimeZone tz = TimeZone.getTimeZone("America/Los_Angeles");

but here the timezoneID must be passed as a parameter.I want to know how to get the Timezone ID from latitude and longitude to use the above API

Actually iam looking to get the timezone from latitiude and longitude in java/Android .If you know any way let me know

**Comment by prashantpsg** [comment]
iam looking to get the timezone(IANA timezone and DST) from latitiude and longitude in java/Android .I found some of paid libraries If anybody knows any free  working API let me know
