### ISSUE TITLE
moment.tz.guess() logs an error when `Intl.DateTimeFormat().resolvedOptions().timeZone` is undefined

### ISSUE THREAD

**Issue by sanisoclem** [moment/moment-timezone#334]
In IE9 and IE11, moment.tz.guess() always logs an error when `Intl.DateTimeFormat().resolvedOptions().timeZone` is undefined. I'm not sure if this is the intended behaviour but if possible, it would be nice to just let it fall back silently without showing users any errors in the console.

**Comment by timrwood** [comment]
This has been fixed in `moment-timezone@0.5.4`.
