### ISSUE TITLE
Adding a link of an official time zone link does not work

### ISSUE THREAD

**Issue by clayzermk1** [moment/moment-timezone#339]
**What happened?**
Attempting to create a link of an official time zone link will not resolve the zone when queried. I referenced https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the links.

**What did you expect to happen?**
I would expect links to official linked time zones to work since there isn't anything in the documentation saying otherwise.

**Minimal Reproducible Example**
Fiddle demonstrating the problem: https://jsfiddle.net/clayzermk1/6y2nro7j/
```javascript
moment.tz.link([
  // Non-linked time zones
  'London Town|Europe/London',
  'Aloha|Pacific/Honolulu',
  
  // Linked time zones
  'The Best Cows|Europe/Jersey', // official link of Europe/London
  'Island Style|Pacific/Johnston' // official link of Pacific/Honolulu
]);

// moment.tz.zone() will resolve to a Zone - no problem
var london = (moment.tz.zone('London Town') instanceof moment.tz.Zone);
var honolulu = (moment.tz.zone('Aloha') instanceof moment.tz.Zone);

// moment.tz.zone() returns null - here's the problem
var jersey = (moment.tz.zone('The Best Cows') instanceof moment.tz.Zone);
var johnston = (moment.tz.zone('Island Style') instanceof moment.tz.Zone);

console.log(london, honolulu, jersey, johnston);
// true, true, false, false
```

**Environment**
moment@2.13.0 
moment-timezone@0.5.4

**Use Case**
I have a mapping of Rails time zone aliases that I pass into `moment.tz.link()` so that I can create proper time zone names from them. Some of those links are links to official links, for example: "Midway Island" (Rails) -> "Pacific/Midway" (official TZ link) -> "Pacific/Pago_Pago" (actual TZ).

**Code Responsible For Issue**
The bit of code that is causing this behavior seems to be https://github.com/moment/moment-timezone/blame/master/moment-timezone.js#L408, which was created as a result of #216, which in turn was in response to #211.

**Workaround**
As a workaround, I have changed the links I am making to map to their actual time zone names instead of the official link names.

Thank you for your time and such an excellent tool!

**Comment by mj1856** [comment]
Thanks, but the `link` function is really more about creating links to `zone` entries, not links to links, or links for arbitrary names.  In other words, it's there such that moment-timezone can link `Europe/Jersey` to `Europe/London`, thus reducing the amount of `zone` data that has to be shipped.

I'd suggest performing the Rails to IANA mapping earlier.  Either do it in JavaScript before using moment, or preferably do it in Rails where you can just use the `MAPPING` constant, as described [here](http://api.rubyonrails.org/classes/ActiveSupport/TimeZone.html).

See also my notes in [the StackOverflow timezone tag wiki](http://stackoverflow.com/tags/timezone/info) towards the bottom in the section "Rails Time Zone Identifiers".

**Comment by mj1856** [comment]
BTW, that's an excellent issue report.  I wish all of them were so thorough!  Thanks!

**Comment by clayzermk1** [comment]
Thanks, but apparently it wasn't thorough enough 😉 

I'm not using Rails, I'm using Node. I was able to construct my mapping by grabbing the mapping info from the Rails source (I believe, it's been a while). Granted, it was an older version of Rails (3.2), but there were close to a dozen mapped links that I extracted that were mappings to official links (`Midway Island|Pacific/Midway` for example).

In my workaround, I've cleaned those up such that they point to the official time zones instead - `Midway Island|Pacific/Midway` -> `Midway Island|Pacific/Pago_Pago`. I think this has basically the same effect as what you are proposing.

Also, do I have the link format correct? Should it be `Midway Island|Pacific/Midway` or `Pacific/Midway|Midway Island`?

Thank you for your time and the help!

**Comment by mj1856** [comment]
Don't do it through the moment-timezone `link` API.  Create a simple dictionary instead.  Rails time zones haven't been updated since their inception, and it doesn't look like they will any time soon.  So you can literally just copy the mapping off of the doc page and convert to JSON by replacing `=>` with `:`.  Load the JSON into a JS object with `JSON.parse` and you can easily convert like so:

```javascript
// load the map once
var json = // your JSON containing the mappings
var railsTimeZoneMap = JSON.parse(json);

// then do the conversion before using with moment-timezone
var ianaTZ = railsTimeZoneMap['Midway Island'];  // ianaTZ is now `"Pacific/Midway"`
var m = moment.tz(ianaTZ); // etc...
```

I've already converted the mapping to JSON for you, which you can download [here](https://gist.github.com/mj1856/581d563e0a19bbc77b683ec5c5448dfa).

**Comment by mj1856** [comment]
See also http://stackoverflow.com/questions/10011011/using-node-js-how-do-i-read-a-json-object-into-server-memory if you need samples of how to load the JSON file.

**Comment by mj1856** [comment]
BTW, I'm just curious, are you getting the Rails time zones from some public API?  Twitter perhaps? :)

**Comment by clayzermk1** [comment]
Wow, you didn't have to do all that 🎩  (but thank you for taking the time to do so).
I have things working with the new links. Ultimately, I think I just need to get around to deprecating the Rails time zones in my code.

> BTW, I'm just curious, are you getting the Rails time zones from some public API? Twitter perhaps? :) 

They are stored in a database that previously was used by Rails. At this point, I'm wondering why I haven't just run through them and updated them with a script. I'm sure I had a good reason for not doing so at the time 😉 

Thanks again for your help. Cheers!
