### ISSUE TITLE
calendar() ignores tz value when calculating today/tomorrow/etc. 

### ISSUE THREAD

**Issue by jonpincus** [moment/moment-timezone#34]
As I write this, 1379227209982 is yesterday at 11:40 p.m. in 'America/Los_Angeles', today at 7:40 a.m. in London.

On a computer running in London, 

```
 > moment(1379227209982).tz('America/Los_Angeles').calendar()
'Today at 11:40 PM'
```

which seems wrong to me.

On a computer running in the 'America/Los_Angeles' timezone, i get the expected result
    'Yesterday at 11:40 PM'

Is this a bug or am I using it incorrectly?

**Comment by maurusrv** [comment]
following the discussion here, i assume that it was a bug and was fixed in the updated versions, but right now, calendar function is undefined in moment-timezone object. or am i doing it wrong?

https://stackoverflow.com/questions/55998660/how-to-use-moment-calendar-with-timezone

thank you
