### ISSUE TITLE
Add typescript definitions

### ISSUE THREAD

**Issue by mattjohnsonpint** [moment/moment-timezone#341]
Since moment now has `moment.d.ts`, we should probably add `moment-timezone.d.ts` here.

We can start with this one, and update it:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/moment-timezone/moment-timezone.d.ts

**Comment by jocull** [comment]
+1

**Comment by jtbairdsr** [comment]
+1

**Comment by marcobisio** [comment]
+1

**Comment by Thiyagarajan-A** [comment]
+1

**Comment by Thiyagarajan-A** [comment]
May be this is the updated link:
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/moment-timezone/

**Comment by gilmoreorless** [comment]
This was done in version `0.5.29`.
