### ISSUE TITLE
Bulk-converting lots of timestamps

### ISSUE THREAD

**Issue by sjlongland** [moment/moment-timezone#342]
Hi all,

Silly question, we have an application in NodeJS that spends a lot of time converting timestamps between different timezones, e.g. receiving a timezone in `UTC` and emitting it as `Australia/Brisbane`.  (These are stored in a custom date/time object, I'm considering what to do about that.)

Aside from the naïve approach of converting each date/time object back to milliseconds then passing that to `moment.tz`, is there a way to do bulk conversions?

As an example, in Python you might do:

```
import pytz

my_tz = pytz.timezone('Australia/Brisbane')
# …
raw_data = {…} # Data obtained from some method: a dict of timestamp -> value
out_data = {}
for (ts, value) in raw_data.items():
    out_data[ts.astimezone(my_tz)] = value
```

I can do this with Moment of course, but as-is, it'd have to look up `Australia/Brisbane` every time, whereas in the above example, the time-zone is declared as an object and is referenced directly when a conversion needs to be made, saving the need of a look-up.

What's the recommended approach when you've got a lot of date/time objects to work with?

**Comment by mj1856** [comment]
I'm not sure that this scenario has been thought through 100%, but you could try some things around using `moment.tz.zone('Australia/Brisbane')` to get the time zone object, and then use the `.offset(ts)` method - assuming that `ts` is already a raw numeric timestamp.  It might get a bit trickier if you're working with strings.

**Comment by sjlongland** [comment]
On 13/05/16 08:43, Matt Johnson wrote:
> I'm not sure that this scenario has been thought through 100%, but you
> could try some things around using
> |moment.tz.zone('Australia/Brisbane')| to get the time zone object, and
> then use the |.offset(ts)| method - assuming that |ts| is already a raw
> numeric timestamp. It might get a bit trickier if you're working with
> strings.

Ahh okay, so that would tell you what the offset is for that timezone
given numerical timestamp.  Indeed, strings are the tricky bit, as I'd
ultimately need an ISO-8601 date from that.  But it's a start. :-)

Maybe if `moment.tz` could take a Zone object in directly when given one
instead of performing a look-up?  Then you'd still get the benefit of
being able to directly reference a zone (skipping the
normalisation/lookup steps) and still benefit from the other functions.
-- 
Stuart Longland (aka Redhatter, VK4MSL)

I haven't lost my mind...
  ...it's backed up on a tape somewhere.

**Comment by mj1856** [comment]
Yep, I was thinking the same thing.  Send a PR if you have the time. ;)
