### ISSUE TITLE
Guessing user/server zone

### ISSUE THREAD

**Issue by jdnichollsc** [moment/moment-timezone#346]
Hi guys,

Is possible to know the server zone like **moment.tz.guess()** ?

Thanks, Nicholls

**Comment by mj1856** [comment]
That will work in whatever environment you're running in.  If you're running in node.js on the server, then yes - that's the server's time zone.

If you mean can you guess the server's time zone while running on the client? No. That would be impossible.

Besides, if you've coded your application correctly, you shouldn't care what the time zone of the server is.

**Comment by jdnichollsc** [comment]
But the function **guess** doesn't exist using Node.js :/

**Comment by mj1856** [comment]
If you're running the latest versions of moment and moment-timezone, you have `moment.tz.guess()`.

We don't produce a separate version for node.  If you don't see that function, then you likely have a version older than the one we introduced that function in.
