### ISSUE TITLE
moment.tz() not parsing ambiguities as expected

### ISSUE THREAD

**Issue by jeffkenney** [moment/moment-timezone#354]
When parsing a time that doesn't exist, moment is not behaving as described in the [Parsing Ambiguities](http://momentjs.com/timezone/docs/#/using-timezones/parsing-ambiguous-inputs/) section of the docs:

> 
If you try to parse a time that never existed, it will round down an hour.

In the docs, the expected output is listed as follows:

```javascript
moment.tz("2012-03-11 02:00:00", "America/New_York"); // 2012-03-11T01:00:00-05:00
moment.tz("2012-03-11 02:59:59", "America/New_York"); // 2012-03-11T01:59:59-05:00
```

However, the actual output (as tested on the moment-timezone docs page) is:
```javascript
moment.tz("2012-03-11 02:00:00", "America/New_York").format();
"2012-03-11T03:00:00-04:00"

moment.tz("2012-03-11 02:59:59", "America/New_York").format();
"2012-03-11T03:59:59-04:00"
```

Browser: Chrome 51.0.2704.63 (64-bit)
Moment version: 2.13.0
Moment Timezone version: 0.5.4

**Comment by mj1856** [comment]
This is a documentation error, the code is working as designed.

See moment/momentjs.com#226 and issues linked from there.
