### ISSUE TITLE
Huge file size when using webpack

### ISSUE THREAD

**Issue by loremipson** [moment/moment-timezone#356]
Hey everyone,

This has been boggling my mind for the majority of the day. I'm getting several hundreds of kb added to my output file when importing moment-timezone.

A couple of quick mentions to get out of the way. I am already using both: `devtool: 'source-map'`, and setting the `NODE_ENV` to production in Webpack.

Without `moment-timezone`, my javascript file output size is 35.9kb, but once I import it, it jumps up to 700kb. This is bizarre, because even when I just require the `moment-timezone-with-data-2010-2020.min` file, I'm getting the same result, even though that file is only ~35kb itself. Is this then just coming from other dependencies at that point?

I've tried importing it the following ways:
```javascript
import moment from 'moment-timezone'; // Adds ~640kb to my output
import moment from 'moment-timezone/builds/moment-timezone.min'; // Adds ~475kb to my output
import moment from 'moment-timezone/builds/moment-timezone-with-data-2010-2020.min'; // Adds ~503kb
```
The first one should only be pulling in `moment-timezone.js` (13.5kb) and then loads in `data/packed/latest.json` (176kb), which is expectedly high, but not 500kb+ high. I'm just not sure where the rest of that is coming in.

To me, I have to be missing something obvious here. I hope I am, anyways. 700kb will force me to go a different route for what I'm trying to do. Is anyone else experiencing this large of an output?

Thanks ahead of time.

**Comment by goldensunliu** [comment]
@loremipson by requiring 'moment-timezone' it will also pulls in 'moment'

https://github.com/moment/moment-timezone/blob/eda36cb2c5ed62b7082593c3aeaff9b94204aa1a/moment-timezone.js#L14

in order to keep the bundle small make sure when you are requiring `moment` also add this to ur webpack plugins:
`new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/)` 
http://stackoverflow.com/questions/25384360/how-to-prevent-moment-js-from-loading-locales-with-webpack

**Comment by loremipson** [comment]
Thank you for that. This has brought it down to ~200kb now. Still not ideal, but I'll do some further playing around to see if I'm pulling too much data in from here. This is a definite start.

Thanks again

**Comment by goldensunliu** [comment]
@loremipson chance is it is gonna be a lot smaller after minification and gziping. I wouldn't worry about it as much.

**Comment by rpeden** [comment]
@loremipson If you don't need to use all of the time zones in the world, you could also try excluding the **latest.json** file that moment-timezone uses, and use your own that only includes the time zones you need. Doing this reduced my minified JavaScript by 280k. 

Apologies for the late reply, but this issue came up on Google when I encountered the same thing you did, so I just wanted to mention it in case it's useful to any future visitors.

**Comment by ParishKhan** [comment]
Still, the size is huge. It's good for server side. But not as a client side.

**Comment by Peleg** [comment]
@rpeden great solution! fwiw, this is what we ended up adding to `config.plugins` in our webpack config file:

```js
new webpack.NormalModuleReplacementPlugin(
  /moment-timezone\/data\/packed\/latest\.json/,
  require.resolve('./misc/timezone-definitions')
)
```
and then we just added a custom `timezone-definitions.json` file with only the timezones we were using.

**Comment by orzechowskid** [comment]
I think you handle it by including European timezones in your custom definitions file (or loading it via code-splitting somehow).

**Comment by mclassdesigns** [comment]
Hm, loading through code-splitting... you might be on to something.

**Comment by pretorianec** [comment]
@Peleg Could you give an example of your timezone-definitions.json? - whenever I edit the packed version it breaks

**Comment by nitely** [comment]
Here is another solution that does not require a plugin. It avoids loading the tz json file altogether, I only included UTC zulu, but anything in the original json is valid:

```javascript
import moment from 'moment';
import 'moment-timezone/moment-timezone'
moment.tz.load({
  "version": "2018g",
  "zones": ["Etc/UTC|UTC|0|0|"],
  "links": [
    "Etc/UCT|UCT",
    "Etc/UTC|Etc/Universal",
    "Etc/UTC|Etc/Zulu",
    "Etc/UTC|UTC",
    "Etc/UTC|Universal",
    "Etc/UTC|Zulu"
  ]
})
moment.tz.setDefault('UTC')
```

**Comment by noppa** [comment]
I have a simple Webpack loader that basically does what @nitely suggested, but using the data from moment-timezone's latest.json so the data gets updated with the library: [noppa/moment-timezone-loader](https://github.com/noppa/moment-timezone-loader).

**Comment by Abraham-william** [comment]
> @rpeden great solution! fwiw, this is what we ended up adding to `config.plugins` in our webpack config file:
> 
> ```js
> new webpack.NormalModuleReplacementPlugin(
>   /moment-timezone\/data\/packed\/latest\.json/,
>   require.resolve('./misc/timezone-definitions')
> )
> ```
> 
> and then we just added a custom `timezone-definitions.json` file with only the timezones we were using.

Can you provide sample timezone file ,we are also facing the same issue, if possible we could reduce some size

**Comment by welll** [comment]
@Abraham-william https://github.com/moment/moment-timezone/blob/develop/data/packed/latest.json
