### ISSUE TITLE
Wrong offset in "America/Santiago" timezone

### ISSUE THREAD

**Issue by alexissaez** [moment/moment-timezone#358]
I'm using version 0.5.4 (latest) With Node.js version 0.10.36, i'm trying to run the next code snippet.

```javascript
var moment = require('moment-timezone');

// currently America/Santiago real offset is UTC-4
var santiago = moment.tz("2016-06-13 01:25", "America/Santiago").format();

// but this line is showing 2016-06-13T01:25:00-03:00
console.log(santiago);
```

So, the output is wrong, because is showing UTC-3 instead UTC-4 for America/Santiago.

**Comment by maggiepint** [comment]
I get the proper -4 when I run it in chrome console on momentjs.com:

```js
moment.tz("2016-06-13 01:25", "America/Santiago").format();
"2016-06-13T01:25:00-04:00
```

**Comment by mj1856** [comment]
This change was made in tzdb 2016c (moment-timezone 0.5.3).  Are you sure you have the most current version loaded, including data?

**Comment by alexissaez** [comment]
Ok, you have reason, thank you.
