### ISSUE TITLE
Moment returned is different depending on input format

### ISSUE THREAD

**Issue by kreinan** [moment/moment-timezone#367]
moment.tz("June 30, 2016 11 PM", "MMMM Do YYYY hhA", "Pacific/Auckland") produces the expected behavior and returns Thu Jun 13 2016 23:00 GMT+1200. However moment.tz("6/30/2016 23:00", "Pacific/Auckland") returns Fri Jul 1 2016 11:00 GMT+1200.

**Comment by maggiepint** [comment]
You are using deprecated functionality that does not work correctly. You should be seeing a warning that moment construction falls back to JS date in the console. If you specify a format, then your code will work fine:

```js
moment.tz("6/30/2016 23:00", 'MM/DD/YYYY HH:mm', "Pacific/Auckland").format()
"2016-06-30T23:00:00+12:00"
```
