### ISSUE TITLE
Minified moment-timezone.min.js does not work.

### ISSUE THREAD

**Issue by rockerest** [moment/moment-timezone#37]
Take the following example to force a user's browser to a business' HQ time.

``` javascript
var hqTz        = "America/Chicago",
    rightNow    = moment.tz( hqTz ),
    opens       = moment.tz( hqTz ).hour( 8 ).minute( 30 ).second( 0 ).millisecond( 0 ),
    closes      = moment.tz( hqTz ).hour( 20 ).minute( 0 ).second( 0 ).millisecond( 0 );

console.log( "Local time: " + moment().format() );
console.log( "HQ time: " + rightNow.format() );
console.log( "HQ opens: " + opens.format() );
console.log( "HQ closes: " + closes.format() );
```

When using the non-minified version, the output is as expected:

```
Local time: 2013-09-30T07:07:42-10:00
HQ time: 2013-09-30T12:07:42-05:00
HQ opens: 2013-09-30T08:30:00-05:00
HQ closes: 2013-09-30T20:00:00-05:00
```

However, when using the minified version (the only change made between page loads), the output is incorrect (perhaps as if the timezone data never got loaded):

```
Local time: 2013-09-30T06:58:27-10:00
HQ time: 2013-09-30T16:58:27+00:00
HQ opens: 2013-09-30T08:30:00+00:00
HQ closes: 2013-09-30T20:00:00+00:00
```

**Comment by bitoiu** [comment]
I got the same issue and I followed what you said @jacwright, I never even assumed these files could work together so I kept the second version only. If I just try to use the normal `moment` everyone works fine, and I'll stick to that until I in fact need the timezone feature.
