### ISSUE TITLE
America/caracas changed

### ISSUE THREAD

**Issue by HERRKIN** [moment/moment-timezone#375]
Hello, I was trying node-cron that uses moment-timezone as its dependency, I noticed that the timezone was before 30 minutes, venezuelan government decided some months ago that we are using the same zone as America/Asuncion meaning gmt-4 I don't know how to fix it. I am sure it will  be easy for you to do it.

**Comment by mj1856** [comment]
This was implemented in [TZBD 2016d](http://mm.icann.org/pipermail/tz-announce/2016-April/000038.html).  Moment-timezone is currently built using data from TZDB 2016f, so it has been included for some time.

Simply update the data to the current version, and it shouold work fine.
