### ISSUE TITLE
How to resolve the 'tz' build error.

### ISSUE THREAD

**Issue by redmember** [moment/moment-timezone#385]
Error below :

```
ERROR in [default] /home/myubuntu/work/angular_cli_webpack/src/app/app.log.component.ts:264:31
Property 'tz' does not exist on type 'Moment'.

[environment]
angular2: 2.0.0
angular-cli webpack : 1.0.0-beta.14
moment": "^2.14.1
moment-timezone": "^0.5.5

[angular-cli.json]
...
......
  "scripts": [
        "../node_modules/moment/moment.js",
        "../node_modules/moment-timezone/builds/moment-timezone-with-data-2010-2020.min.js",
        "../node_modules/locomote-video-player/dist/locomote.min.js"
      ],
......
...

[app.log.component.ts]

import * as moment from 'moment';
import 'moment-timezone';
...
...
class AppLogComponent {
   constructor() {}
   public func() {
      var utc_time = moment.utc(unix_tm_sec*1000);
      var camera_time = utc_time.tz(timezone);    <--- error position.
   }
}
...
```

**Comment by joelbanzatto** [comment]
Same issue here.

`Property 'tz' does not exist on type 'typeof moment'.`

**Comment by MingyuJeon** [comment]
Does anyone solve this issue now?

**Comment by wceolin** [comment]
@MingyuJeon Installing `@types/moment-timezone` should solve this issue:

`npm i @types/moment-timezone --save-dev`

**Comment by damsorian** [comment]
the `@types/moment-timezone` not works for me :(

**Comment by Gizrah** [comment]
I somehow got it to work as this:
`npm install moment moment-timezone --save --global`

Then in the relevant file:
```
import moment from "moment";
import "moment-timezone";
 
...
 
let timezone = moment.tz.guess();
```

**Comment by nickion** [comment]
We came across this and it was because the package maintainers had created a breaking change by removing the 2010-2020 file and replacing it with 2012-2022 rather than adding a new file for the different time range.

**Comment by damsorian** [comment]
I resolved this issue using `moment.tz(myDate, myTimezone)` instead of `myDate.tz(myTimezone)`

**Comment by vincebanzon** [comment]
since we are both from angular, this is how I did it. 

`npm install moment-timezone --save --global`

`import moment from "moment-timezone";`

**Comment by BMalaichik** [comment]
May help somebody:
Faced issue using local own npm package, which `had` dependency on `@types/moment-timezone`, but no imports was done with `from "moment-timezone"`, but package consumer - had
So, as a result type casting failed since dependency used `moment`(because of no imports), but package consumer - `moment-timezone`

**Comment by inlightmedia** [comment]
I could not import moment-timezone@0.5.14 with moment@2.20.1. They were apparently incompatible.

However, changing moment to version 2.18.1 fixed it for me. 

I used the this import syntax:

```
import moment from 'moment'; 
import 'moment-timezone'; 
import 'moment-range';
```

**Comment by rubimazaki** [comment]
With 2018 typescript use:

npm install @types/moment-timezone -S

**Comment by Raju** [comment]
You need to update the dependencies tz-offset module from version 0.0.1 to version 0.0.2

Here is the link for tz-offset module,
https://www.npmjs.com/package/tz-offset

**Comment by nikhil2007rock** [comment]
> Verify that you're referencing a version of the moment-timezone typings that is compatible with your version of TypeScript. I recently ran into this and downgrading the version of @types/moment-timezone corrected the build errors.
Worked for me!
Ref: https://stackoverflow.com/questions/61247263/how-to-fix-this-error-in-node-modules-types-moment-timezone-moment-timezone-d-t#comments-61247263

**Comment by kapilSoni101** [comment]
hi guys i got below error in console
**: zonesForCountry<T extends true>(country: string, with_offset: T): T extends true ? MomentZoneOffset[] : never;?**
i have also post in moment/moment-timezone but nothing error help me for me.please helpe me any one for fix above issue?

**Comment by rtp4jc** [comment]
It looks like the `@types/moment-timezone` package has been deprecated according to #858 

I fixed it by uninstalling that package and using this code (from above): 
```
import * as moment from 'moment';
import 'moment-timezone';
```

**Comment by Pronoy999** [comment]
The solution is: 
Add these in the Package.json 
"@types/moment": "^2.13.0",
"@types/moment-timezone": "^0.5.30",
"moment": "^2.27.0",
"moment-timezone": "^0.5.31",   

Then in the relevant file: 

import moment from "moment";
import "moment-timezone";

After this you can use moment and tz functions.

**Comment by carlosananias** [comment]
> já que ambos estamos usando angular, foi assim que fiz.
> 
> `npm install moment-timezone -S`
> 
> `import moment from "moment-timezone";`

this worked well for me!

**Comment by ismaelguerrib** [comment]
> The solution is: Add these in the Package.json "@types/moment": "^2.13.0", "@types/moment-timezone": "^0.5.30", "moment": "^2.27.0", "moment-timezone": "^0.5.31",
> 
> Then in the relevant file:
> 
> import moment from "moment"; import "moment-timezone";
> 
> After this you can use moment and tz functions.

This is the only solution that works for me !

**Comment by gilmoreorless** [comment]
You shouldn't need to import both `moment` and `moment-timezone` — one already imports the other. Importing both could be causing problems if there are multiple versions of a dependency in your project. See https://github.com/moment/moment-timezone/issues/982#issuecomment-1119540905 for more details.
