### ISSUE TITLE
Creating a time using a specific time zone

### ISSUE THREAD

**Issue by navhomayoun** [moment/moment-timezone#387]
Trying to create a time for Australia using a computer in London

1. I choose a specific time in date/time picker (i.e. 30 Sep 2016 18:00)
2. I then want moment to recognise this as a time in Australia/Sydney, NOT convert it... so I go

`var userTime = moment.tz("30 Sep 2016 18:00", "Australia/Sydney").format()`

3. The end result gives me 2016-10-01T04:00:00+10:00 which is a conversion...
4. I have also tried `moment.tz.setDefault("Australia/Sydney");` but it still converts it and shows 2016-09-30T04:00:00+10:00

Could you kindly highlight how can I achieve this? I basically need to create a new time object and let moment know that this is an Australian time so that when I do ` var currentDate = "30 Sep 2016 18:00"; moment.tz(currentDate, "Australia/Sydney");` it shows me 2016-09-01T18:00:00+00:00

Keywords: How to create time in a specific time zone with moment.js/moment-timezone.js?

**Comment by maggiepint** [comment]
You need to specify a format. Right now you are getting a warning that moment construction falls back to JS Date. When that happens, we can't properly handle timezones with moment timezone.

Instead do this:

```js
moment.tz("30 Sep 2016 18:00",'DD MMM YYYY HH:mm', "Australia/Sydney").format()
"2016-09-30T18:00:00+10:00"
```

**Comment by navhomayoun** [comment]
@maggiepint thanks for the quick reply.  It would have been great if this was mentioned on the docs   somewhere.
