### ISSUE TITLE
When can we get the migrated version of the moment-timezone with latest angular 2.0 ?

### ISSUE THREAD

**Issue by monica11** [moment/moment-timezone#388]
Since angular 2.0 is now released, we need to upgrade our app for which we need latest version of this library too. Please do it asap.

**Comment by maggiepint** [comment]
I guess I don't know what you mean? This library releases when changes to the IANA timezone database occur, or when we fix bugs or implement new features. It has nothing to do with the release cycle of angular 2. Did you mean urish/angular2-moment?
