### ISSUE TITLE
Wrong date when parsing time string

### ISSUE THREAD

**Issue by tanhauhau** [moment/moment-timezone#390]
My current local time `moment().format('YYYY-MM-DD HH:mm:ss Z')` is:
`"2016-10-05 01:27:38 +02:00"`

Current time in Singapore `moment.tz('Asia/Singapore').format('YYYY-MM-DD HH:mm:ss Z')` is:
`"2016-10-05 07:27:38 +08:00"`

My issue is when i tried to parse `"HH:mm:ss"` in Singapore Time, i got:
```
moment.tz('12:13:14', 'HH:mm:ss', 'Asia/Singapore').format('YYYY-MM-DD HH:mm:ss Z');
>> "2016-10-04 12:13:14 +08:00"
```

Shouldn't it be `2016-10-05` ?

**Comment by mj1856** [comment]
Yes.  You are correct.  This is the bug described in #297.  I will get to this at some point, but have not started working on it yet.  For now, try to avoid constructing a moment with time-only input.
