### ISSUE TITLE
Unexpected date on moment initialize with argument

### ISSUE THREAD

**Issue by Serfenia** [moment/moment-timezone#393]
Hello,

We're currently facing an unexpected initialize issue with moment timezone.
Currently we're always setting the default timezone to `Europe/Amsterdam` using `moment.tz.setDefault('Europe/Amsterdam');`.

Time of execution: 5 October 22.43 (+00:00 UTC)
Timezone time of execution: 6 October 00.43 (+02:00 CEST)

This is the actual execution:
```
> moment().date()
6
> moment({hour: 12, minute: 0, seconds: 0, milliseconds: 0}).date()
5
> moment().hour(12).minutes(0).seconds(0).date()
6
> moment({hour: 12, minute: 0, seconds: 0}).date()
5
> moment({hour: 12, minute: 0, seconds: 0, milliseconds: 0}).toISOString()
'2016-10-05T10:00:00.000Z'
> moment().hour(12).minutes(0).seconds(0).toISOString()
'2016-10-06T10:00:00.733Z'
```

This was the expected result:
```
> moment().date()
6
> moment({hour: 12, minute: 0, seconds: 0, milliseconds: 0}).date()
6
> moment().hour(12).minutes(0).seconds(0).date()
6
> moment({hour: 12, minute: 0, seconds: 0}).date()
6
> moment({hour: 12, minute: 0, seconds: 0, milliseconds: 0}).toISOString()
'2016-10-06T10:00:00.000Z'
> moment().hour(12).minutes(0).seconds(0).toISOString()
'2016-10-06T10:00:00.733Z'
```

As you can see when you initialize moment with an object argument specifying the time directly, it does not calculate it with the timezone data (As the date is 5 October and not 6 October). 

If you initialize moment first and use the methods to set the time data, it works as expected.

moment-timezone: 0.5.5
moment: 2.15.0
Node.js: 6.1.0

Regards,
Patrick van Vuuren

**Comment by mj1856** [comment]
Yes, we are aware of this.  See dup #297. There will be a fix at some point, but I'm not actively working on it right now.  For the time being, try to avoid constructing a moment with time-only information.  Thanks.

**Comment by Serfenia** [comment]
Allright, thanks for your response!
