### ISSUE TITLE
Breaking change for timezone formatting in version 0.5.6

### ISSUE THREAD

**Issue by vahnag** [moment/moment-timezone#395]
Wrong behaviour for `z` token in the latest version. See the JSFiddle demos below.

**Version 0.5.5**. (Right behavior):

https://jsfiddle.net/kt3xv694/1/

`z` is formatted as `AMT`.

 **Version 0.5.6**. (Bug):

https://jsfiddle.net/kt3xv694/

`z` is formatted as `+04`.

**Comment by mj1856** [comment]
This is part of the changes to the underlying data set, not something that we have any control over.  The same changes are being rolled out across many other platforms as well.  The [2016g release announcement](http://mm.icann.org/pipermail/tz-announce/2016-September/000041.html) has some commentary on this, and it includes the zone you used in your fiddle.

You can read more in the discussion list at http://www.iana.org/time-zones.

**Comment by mj1856** [comment]
Just to summarize, the tzdb maintainers have basically decided to phase out any abbreviations that were invented by the tzdb and are not actually in use by people in the region.  If you think they are wrong for some particular zone, please post your concerns on the tzdb mailing list.  Thanks.

**Comment by vahnag** [comment]
Thanks for clarification. Don't you think it should at least be noted in changelog as a breaking change. Updating docs will help too, they state that `z` will give you the timezone name which isn't always true now. A warning line will help lots of people.

**Comment by mj1856** [comment]
Sure.  I added a task for this as moment/momentjs.com#372.

Thanks.
