### ISSUE TITLE
moment.tz() offset & timezone are incorrect in regards to DST. 

### ISSUE THREAD

**Issue by theerickramer** [moment/moment-timezone#396]
https://jsfiddle.net/0Lx9oyj1/5/

Docs say "This constructor is DST aware, and will use the correct offset when parsing." but that doesn't seem to be the case anymore? In my tests it seems to work correctly for 2014 but not 2015+

**Comment by maggiepint** [comment]
I don't know where you're getting your timezone data from, but it is incomplete. If I take the ``America/New_York`` timezone data from the 2010 to 2020 build, and put it in your JS Fiddle as follows, everything is fine:

```js
moment.tz.add([
  "America/New_York|EST EDT|50 40|01010101010101010101010|1BQT0 1zb0 Op0 1zb0 Op0 1zb0 Op0 1zb0 Op0 1zb0 Op0 1zb0 Rd0 1zb0 Op0 1zb0 Op0 1zb0 Op0 1zb0 Op0 1zb0|21e6"
]);
```

**Comment by theerickramer** [comment]
Ahha! Got that data from the docs when I started and didn't realize it needed to be updated. I knew I was missing something dumb ;P Thanks!
