### ISSUE TITLE
Sao Paulo timezone off by 1 hour

### ISSUE THREAD

**Issue by mwbrooks** [moment/moment-timezone#399]
I've noticed that the Sao Paulo time zone shifted by one hour today:
https://www.timeanddate.com/time/change/brazil/sao-paulo

Unfortunately, Moment is having an issue working with this time zone. Here is the example that I've experienced:

```javascript
// Today is Sat Oct 15 2016

// Expect "Sat Oct 16 2016 00:00:00 GMT-0300"
moment().tz('America/Sao_Paulo').startOf('day').add(1, 'day').toLocaleString()
// Return "Sat Oct 15 2016 23:00:00 GMT-0300"
```

On the other hand, a time zone such as New York is correct:

```javascript
// Today is Sat Oct 15 2016

// Expect "Sun Oct 16 2016 00:00:00 GMT-0400"
moment().tz('America/New_York').startOf('day').add(1, 'day').toLocaleString()
// Return "Sun Oct 16 2016 00:00:00 GMT-0400"
```

Using `moment-timezone@0.5.6`

Cheers,
Michael

**Comment by maggiepint** [comment]
This bug is known and is in moment core. moment/moment#3132

**Comment by mwbrooks** [comment]
@maggiepint great, thanks Maggie!
