### ISSUE TITLE
Add country to the Zone object

### ISSUE THREAD

**Issue by acrodrig** [moment/moment-timezone#400]
Sorry if I misunderstanding the way to use the library. I have a requirement to get the country code from the time zone name (for example `US` would correspond to `America/Los_Angeles`. Currently the country is not percolating through in the `Zone` object as described here:

```
http://momentjs.com/timezone/docs/#/zone-object/
```

Am I missing something? Is it possible to put a request to add it?

Thanks.

**Comment by alexgrace95** [comment]
Hi,
Yes this is what is being achieved with PR 377 (https://github.com/moment/moment-timezone/pull/377). This is my first pull request and it needs to be adjusted a little before it is merged, I plan on completing it soon but have been very busy with University and another project recently. I will finish this Pull Request ASAP. Alex

**Comment by mj1856** [comment]
This is one of two APIs that will be in Alex's #377.  Will keep this open for now as a reminder.  Thanks.

**Comment by acrodrig** [comment]
Thanks. I am really interested in this, so let me know if I can contribute (tests/docs/whatever).

**Comment by acrodrig** [comment]
If it helps anyone I ended up doing patching `moment-timezone` in a manner similar to the following gist: https://gist.github.com/acrodrig/9c10ef9ba69f2da2b74c05400fd5eaed.

**Comment by alexgrace95** [comment]
Hi Andres,
I am hoping to get this done this weekend :)

**Comment by alexgrace95** [comment]
Pull Request has been submitted and is passing all checks:
#410

Appreciate any feedback!

**Comment by Soullighter** [comment]
> If it helps anyone I ended up doing patching `moment-timezone` in a manner similar to the following gist: https://gist.github.com/acrodrig/9c10ef9ba69f2da2b74c05400fd5eaed.

Are you available to find that gist and share again with us?
