### ISSUE TITLE
Changes in time system in Turkey

### ISSUE THREAD

**Issue by kemalmuderrisoglu** [moment/moment-timezone#402]
Hi,

There is a new time system in Turkey. Normally the clock should be taken 1 hour back as 30 Oct 2016 04:00am. With new system they are not going to take it back. How your system is working? Is there any problem about that?

**Comment by mj1856** [comment]
This was implemented in version 2016g of the TZDB that we import from http://iana.org/time-zones.

We released it with version 0.5.6.  We're now at version 0.5.7.  If you are using data from 0.5.6. or greater then you will have this change.
