### ISSUE TITLE
timezone conversion by taking care of dst

### ISSUE THREAD

**Issue by prashantegmat** [moment/moment-timezone#408]
I am trying to convert PST into IST: -

http://codepen.io/prashantsrs/pen/pEXYOX

 var phoenix_time=moment.tz("2016-11-15 07:00:00","America/Phoenix");
var india_time=phoenix_time.clone().tz("Asia/Calcutta");
document.write('indian time is '+india_time.format()+'<br>');
var gmt_time=phoenix_time.clone().tz("Etc/UTC");
document.write('gmt time is '+gmt_time.format());

But the output is not taking care of DST

**Comment by butterflyhug** [comment]
America/Phoenix is in Arizona, which [does not observe DST](https://en.m.wikipedia.org/wiki/Time_in_Arizona).  America/Los_Angeles is the TZDB name for Pacific Time in the U.S.

**Comment by prashantegmat** [comment]
Thanks a lot!
