### ISSUE TITLE
Timezone conversion sets offset but doesn't convert time

### ISSUE THREAD

**Issue by aecolley** [moment/moment-timezone#412]
The example on [the homepage](http://momentjs.com/timezone/#convert-dates-between-timezones) shows construction of a moment in the EDT timezone and correct conversion of it to PDT and BST. However, the code doesn't match: instead, it updates the offset without changing the hour, effectively changing the time unexpectedly. Here's the self-explanatory output of my test case (attached):

```
test: moment.tz("2014-06-01 12:00", "America/New_York").clone().tz("Europe/London").format()
expected: 2014-06-01T17:00:00+01:00
actual: 2014-06-01T12:00:00+01:00
FAIL
Version info: moment.version=2.15.2 moment.tz.version=0.5.7 moment.tz.dataVersion=2016h
Browser info: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.35 Safari/537.36
```
[test-moment-timezone.html](https://github.com/moment/moment-timezone/files/568860/test-moment-timezone.txt)

**Comment by mj1856** [comment]
Hmmm..... your code works on my box without modification.

![image](https://cloud.githubusercontent.com/assets/1396388/20017105/70a7088a-a27f-11e6-861b-3038bd0f9a86.png)

I don't see anything browser or platform specific in your code, and it looks like you have current versions, so I'm not quite sure what's going on here.

Do you see any warnings or errors in the debug console?

**Comment by aecolley** [comment]
Never mind, I'm just an idiot. I added some `console.log` lines to `moment.js` to try to figure out what was going on, and, well, I commented out something I shouldn't have. I'm very sorry for wasting your time.

**Comment by mj1856** [comment]
No problem.  Glad you got it working. 😄
