### ISSUE TITLE
Issue In get timezone

### ISSUE THREAD

**Issue by satkamar** [moment/moment-timezone#415]
I have loaded data like this,

moment.tz.add('America/Los_Angeles|PST PDT|80 70|0101|1Lzm0 1zb0 Op0');

but always moment returns the timezone is PDT not PST.

var dec = moment("2016-12-01T12:00:00Z");
dec.tz('America/Los_Angeles').format('ha z');  // 4am PST
Result : "5am PDT"

In this result is 4am PST but always returns PDT.

If I switch the place of PST and PDT , its returning always PST . The problem is i'm not getting the time zone according to current time format

**Comment by mj1856** [comment]
You can find the full definition for that zone here:
https://github.com/moment/moment-timezone/blob/0.5.9/data/packed/latest.json#L98

Or a truncated version of it here:
https://github.com/moment/moment-timezone/blob/0.5.9/builds/moment-timezone-with-data-2010-2020.js#L633

I think your data is from one of the examples in the docs?  We should probably make sure that all examples are consistent.  It think it was just there as a sample of how to load data, not to be used for the actual data for this zone.

**Comment by mj1856** [comment]
We'll track in #419
