### ISSUE TITLE
Timezone does not match with startOf('month') endOf('month')

### ISSUE THREAD

**Issue by plcgi1** [moment/moment-timezone#416]
1 Go to http://momentjs.com/timezone/
2 Open chrome console
3 Type:
`
now = new Date()
console.info([
  now,
  moment.tz(now, 'America/Halifax').startOf('month').format(), 
  moment.tz(now, 'America/Halifax').endOf('month').format()
])
`

result:

1: Tue Nov 08 2016 13:22:40 GMT-0400 (AST)

2: "2016-11-01T00:00:00-03:00"

3: "2016-11-30T23:59:59-04:00"

**Comment by maggiepint** [comment]
I'm not sure what you think is wrong here. That time zone moved clocks back one hour this past Sunday. It was -3 at the start of the month, and it will be -4 at the end of the month.

**Comment by plcgi1** [comment]
ok - not problem
