### ISSUE TITLE
Moment with Timezone tz format seems bit confusing

### ISSUE THREAD

**Issue by kothari775** [moment/moment-timezone#420]
Moment with Timezone tz format seems bit confusing. I tried couple of commands with tz conversion on the fly. But result seems differ like with h m s & HH MM SS. Please see attach screenshot. Please help me which one should I trust small case hms or uppercase one
![screen shot 2016-11-17 at 1 01 39 pm](https://cloud.githubusercontent.com/assets/2212415/20380150/4e17693a-acc6-11e6-9296-36e0f1a91746.png)

**Comment by butterflyhug** [comment]
Minutes and seconds can only be formatted with lowercase tokens.  Uppercase `M` is month; uppercase `S` is fractional seconds.  You might want to refresh your memory of the formatting token docs:  http://momentjs.com/docs/#/displaying/
