### ISSUE TITLE
guess() docs should mention that it uses the International API where possible

### ISSUE THREAD

**Issue by philfreo** [moment/moment-timezone#421]
The docs for [guess()](http://momentjs.com/timezone/docs/#/using-timezones/guessing-user-timezone/) mention _guessing_ based on `Date#getTimezoneOffset` and `Date#toString` however don't mention (but should) that it actually will use the International API (`Intl.DateTimeFormat().resolvedOptions().timeZone`) where supported.

**Comment by maggiepint** [comment]
Would be happy to take a docs pull on this. If you don't want to make a pull can you raise this issue on moment/momentjs.com?

**Comment by philfreo** [comment]
Thanks - opened https://github.com/moment/momentjs.com/pull/377
