### ISSUE TITLE
Need main zones list without based on cities

### ISSUE THREAD

**Issue by mallikarjuna909** [moment/moment-timezone#424]
I need list of timezones which are based main time zone list. The dropdown with cities taking long list, i don't need every city's timezone. 

Is there any way in moment timezone?

**Comment by mj1856** [comment]
Moment-timezone doesn't list every city in the world.  It simply implements [the IANA time zone database](https://en.wikipedia.org/wiki/Tz_database) with support for [all valid time zone identifiers](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones).  Time zones are typically identified by the city with the largest population in the geographic region where the time zone is in effect.

There is some discussion of adding some filters to only show modern canonical zones in #227.  However, these *would* be the city based zone identifiers.  For example, the Pacific time zone in the US has a canonical identifier of `America/Los_Angeles`.  The filter would remove its alias, `US/Pacific`.

We have no plans to add support for any other non-tzdb aliases, or functionality for producing a reduced list.  However, you can do this yourself by deciding which zones you are interested in and keeping a simple key/value pair.  For example, if you only care about the USA and only use English names, you could do something like this:

```js
var zones = {
    "Eastern": "America/New_York",
    "Central": "America/Chicago",
    "Mountain": "America/Denver",
    "Arizona": "America/Phoenix",
    "Pacific": "America/Los_Angeles",
    "Alaska": "America/Anchorage",
    "Aleutian": "America/Adak",
    "Hawaii": "Pacific/Honolulu"
};
```
