### ISSUE TITLE
When local timezone is undefined guess() is still returning some random zones

### ISSUE THREAD

**Issue by fjcero** [moment/moment-timezone#426]
In some scenarios, local timezone could be undefined. That could be related to some browser lack of features, or even the local machine does not have any TZ defined at all.

The problem is that using `moment.tz.guess()` it manages to return a timezone either way, instead of returning something like 'UTC' like http://pellepim.bitbucket.org/jstz/ does. 

In the `rebuildGuess` method the zonesScores are created anyway after the try/catch skips undefined values. I don't know if there is a way to check if local TZ is completely undefined and fallback with a specific zone, something like

```js
let timezone = moment.tz.guess() || 'America/Cordoba'
```

**Comment by mj1856** [comment]
Can you give me an example of how local time would be completely undefined?  I mean, by ECMAScript spec, for the `Date` object to work, it has to have awareness of the host OS's local time zone.  If somehow there is none, then it would still have to do *something*, such as to use UTC - which moment's guessing algorithm should pick up on.
