### ISSUE TITLE
Please support Time Zone Full

### ISSUE THREAD

**Issue by kentonbmax** [moment/moment-timezone#427]
Please add support for all Time Zone Full names and abbv, Central Standard Time, CST. If you are using a asp.net web api web service its the TimeZoneInfo object in C# supports this. The issue becomes supporting pure JS and HTML front end where all back-end times are UTC. 

ex. var localDatetime = moment(<utc datetime>).toZone("Central Standard Time).format(<your format>)

**Comment by mj1856** [comment]
Dup of #281.

**Comment by mj1856** [comment]
See also #130
