### ISSUE TITLE
long-form names with "zz" don't seem to work

### ISSUE THREAD

**Issue by UnsungHero97** [moment/moment-timezone#428]
The docs say to use `"zz"` to format the timezone with long-form names, like "Central Standard Time". However, the output is `"CST"` instead of `"Central Standard Time"`.

<img width="657" alt="screen shot 2016-12-05 at 1 57 46 pm" src="https://cloud.githubusercontent.com/assets/440299/20904089/e3f72636-baf2-11e6-980c-b4f5646b86c2.png">

**Comment by mj1856** [comment]
Actually, the docs [here](http://momentjs.com/timezone/docs/#/using-timezones/formatting/) say:

> Moment.js also provides a hook for the long form time zone name. Because these strings are generally localized, Moment Timezone does not provide any long names for zones.
> 
> To provide long form names, you can override moment.fn.zoneName and use the zz token.

It goes on to show examples of how to provide such names.

**Comment by UnsungHero97** [comment]
Ah, got it. I thought those were the defaults. Thanks for clarifying!
