### ISSUE TITLE
Is the "ignoreCache" arg of `guess` part of its public interface?

### ISSUE THREAD

**Issue by emmettnicholas** [moment/moment-timezone#429]
`guess` accepts `ignoreCache` as an arg, which is very useful: https://github.com/moment/moment-timezone/blob/3e9abbf0e817134c6d03b4cb541f96471238d96c/moment-timezone.js#L358

Is this documented somewhere, i.e. is it safe to use? I don't see it here: http://momentjs.com/timezone/docs/#/using-timezones/guessing-user-timezone/

Ideally I'd like to depend on ignoreCache, since our app needs to periodically detect time zone changes.

If this aspect of `guess`'s interface is stable, it'd be nice to document it.

**Comment by maggiepint** [comment]
This is covered by the tests: https://github.com/moment/moment-timezone/blob/develop/tests/moment-timezone/guess.js

Actually, at a glance, it appears that we don't test the cache. LOL!

I would call it safe to use. A docs PR would be welcome.

**Comment by gilmoreorless** [comment]
The parameter has been added to the docs:

> You can call `moment.tz.guess()` with an optional boolean argument "ignoreCache". If set to true, the cache will be ignored and overwritten with the new value.
