### ISSUE TITLE
I don't see a way to get an easy list of the available timezones

### ISSUE THREAD

**Issue by hughlomas** [moment/moment-timezone#43]
My use case is populating a select element with options for the available timezones so the user can set their timezone. I was hoping for something along the lines of 

`moment.tz.getTimezones()`
which would return something like

``` javascript
[
    {
        name: "Eastern Standard Time"
      , locale: "America/New_York"
      , abbreviation: "EST"
      , offset: "-5"
    }
  , {
        name: "Central Standard Time"
      , abbreviation: "CST"
      , locale: "America/Chicago"
      , offset: "-6"
    }
]
```

**Comment by elewin** [comment]
Using moment.tz.names() returns a list of over 500 elements, is it possible to condense that down so that there is just one for each zone? If this were to be used to populate a drop down to allow a user to select their timezone, then it would be completely impractical

**Comment by mj1856** [comment]
@elewin see #227.  But also, listing out the IANA identifiers isn't so great anyway.  One needs CLDR data to do it right.  There's certainly room for a javascript-only version of something like [my demo here](http://timezonepickerdemo.azurewebsites.net/).

Oh, and please don't make a habit of commenting on years-old-closed issues.  ;)

**Comment by psagar5** [comment]
@markuso - what is '_' in your solution?

**Comment by markuso** [comment]
@psagar5 Use the new `moment.tz.names()` instead for latest version. See the comment right after my old one [here.](https://github.com/moment/moment-timezone/issues/43#issuecomment-47001742) I have switched to that. So you don't need my solution anymore. The underscore `_` is the reference to `lodash`, but I changed my old comment right now to use plain JS `.map()` method.

**Comment by psagar5** [comment]
@markuso - ERROR TypeError: moment.tz.zones is not a function, i am getting this error if I use moment.tz.names(). Moreover, i am getting list either 500 or 365 entries. Is there any way to use standard timezone, smaller list?

**Comment by psagar5** [comment]
@markuso - please let me know if there is any way to filter the list to get less than 50 timezones?

**Comment by markuso** [comment]
@psagar5 I am not aware of any smaller list or a specific way to filter the list to some sort of standard short list. To cover worldwide time zones, you need the full list. In our application, we just show the full list to our users grouped by the first section of each name. Like "America" heading for all the "America/***" zones, etc.

Sorry, maybe someone else could have a better answer about a standard short list you speak of.

**Comment by elewin** [comment]
What we ended up doing was mapping the IANA time zones to Windows time zones, then we let the user select a windows time zone to narrow things down, then drill down further and list all the IANA time zones that fall under it so they can select the IANA time zone that applies specifically to them. It is much easier to quickly narrow down the time zones you present to the user that way.

**Comment by psagar5** [comment]
@elewin - can you share code snippet of your implementation?

**Comment by elewin** [comment]
@psagar5 Sure,
So first we create a big array of objects, each object is a Windows time zone. Within each object, it then has its own array of IANA time zones that map to it
```
 [
// . . .
   {
   "value": "Pacific Standard Time",
   "abbr": "PDT",
   "offset": -7,
   "isdst": true,
   "text": "(UTC-08:00) Pacific Time (US & Canada)",
   "utc": [
     "America/Dawson",
     "America/Los_Angeles",
     "America/Tijuana",
     "America/Vancouver",
     "America/Whitehorse",
     "PST8PDT"
   ]
 }, {
   "value": "US Mountain Standard Time",
   "abbr": "UMST",
   "offset": -7,
   "isdst": false,
   "text": "(UTC-07:00) Arizona",
   "utc": [
     "America/Creston",
     "America/Dawson_Creek",
     "America/Hermosillo",
     "America/Phoenix",
     "Etc/GMT+7"
   ]
 }, {
   "value": "Mountain Standard Time (Mexico)",
   "abbr": "MDT",
   "offset": -6,
   "isdst": true,
   "text": "(UTC-07:00) Chihuahua, La Paz, Mazatlan",
   "utc": [
     "America/Chihuahua",
     "America/Mazatlan"
   ]
 }, {
   "value": "Mountain Standard Time",
   "abbr": "MDT",
   "offset": -6,
   "isdst": true,
   "text": "(UTC-07:00) Mountain Time (US & Canada)",
   "utc": [
     "America/Boise",
     "America/Cambridge_Bay",
     "America/Denver",
     "America/Edmonton",
     "America/Inuvik",
     "America/Ojinaga",
     "America/Yellowknife",
     "MST7MDT"
   ]
 },
// . . .
]		
```
Then, on the UI we have a drop-down that shows the `text` property of each element of the above array of Windows time zones, and when the user selects one of those, a second part of the UI then displays the array of IANA time zones (the `utc` array in the selected object) and then the user can select the specific time zone that belongs to them.

**Comment by stasinua** [comment]
@elewin Maybe this one:
https://github.com/dmfilipenko/timezones.json

**Comment by Dipesh-Das97** [comment]
Hi, is there a way to get the list of common timezones alone, just as pytz.common_timezones(basically just sends a list of timezones which are commonly used other than UTC as well as maintains the non deprecated list)? This is something I have looked for sometime but had no luck. Any ideas?
