### ISSUE TITLE
Create moment with tz from format

### ISSUE THREAD

**Issue by amitaymolko** [moment/moment-timezone#430]
I have this string: `Thu 12 08 10:02:06 EST 2016`
And its in this format: `ddd MM DD HH:mm:ss z YYYY`
But when i create an object it losses the timezone
`let mo = moment.tz(published, dateFormat, "");`
I realize that the tz is UTC because im sending `""`

So how do i create a moment object with the tz from the string?

**Comment by maggiepint** [comment]
What you are trying to do can't be done because those abbreviations are not unique. For instance, CST could be Central Standard time in the US, or China Standard Time. You would have to create a manual map between those abbreviations, and the IANA timezone identifiers that we use.
