### ISSUE TITLE
IST/Indian Standard Time/India Standard Time/UTC+5.30 missing/not working

### ISSUE THREAD

**Issue by lope** [moment/moment-timezone#433]
I've tried to use the following timezones but none work:
```
IST
Indian Standard Time
India Standard Time
UTC+5.30
```

moment-timezone 0.5.9

**Comment by maggiepint** [comment]
You need an [IANA time zone identifier](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones). In this case, it would be Asia/Kolkata.
