### ISSUE TITLE
For testing purposes please include UTC-11...UTC+13

### ISSUE THREAD

**Issue by silkentrance** [moment/moment-timezone#435]
Having to test the behavior of say AngularJS date/datetime transformations (parsers, formatters), it would be nice to have a defined common scheme that does not adhere to DST or whatever political/commercial decisions being made on the exact nature of a give point in time.

That being said, I would like moment-timezone to also include time zones such as UTC-11 to UTC+13 for testing purposes alone. These timezones should not apply any DST whatsoever, so that the test results are reproducible.

Perhaps, this could also be extracted into a separate for test only database?

Or is there another way to achieve this without having to say moment().tz('UTC-11')?

I know that I can register custom time zones, however, it would be **very nice** of you to provide such common testing patterns into the library or at the least into a common for test only database.

**Comment by maggiepint** [comment]
What testing pattern is this for? I'm certainly quite familiar with clock mocking patterns, and you can do that by overriding moment.now with a function that returns a fixed value. I guess I'm just not sure what you're asking for. Can I get some sample tests?

**Comment by silkentrance** [comment]
Well, I have here an AngularJS parser/formatter that are called using a ``transform-datetime`` directive. This is then used for parsing user input with datetime in local timezone and locale into a format that can be sent to the server, i.e. UTC and say `YYYY-MM-DDTHH:mm:ssZ`. For testing purposes, I need to make sure that the tests run regardless of the current time, that is, having defined timezones with no DST transitions would help in making sure that the test results are always the same.

**Comment by silkentrance** [comment]
@maggiepint I see that under Etc/ there are GMT+1 .. and so on. This will suffice. Closing.
