### ISSUE TITLE
Different result in browser, nodejs

### ISSUE THREAD

**Issue by bsdo64** [moment/moment-timezone#437]
In nodejs with npm, time zone is activated.
Test code is here 
https://runkit.com/586def3949273b00132432dc/586def3a0b602700145e7911

In browser, however, time zone is not active.
http://jsfiddle.net/uq99udc9/882/

I'm confused what makes these different. Is this bug? 
This same code makes presentation of time in server / client always different.

**Comment by mj1856** [comment]
I'm not sure what you mean "time zone is not active"

I get the same results when I run these myself.  Though note a couple of things:

- You're using older versions in your jsfiddle
- Runkit output is as-of the time it was originally run.  You have to re-execute it manually if you want the output to be similar to the jsfiddle.
