### ISSUE TITLE
Openweathermap

### ISSUE THREAD

**Issue by qroft** [moment/moment-timezone#438]
Hi everyone,
i am having problems in making momentJS and its timezone plugin to work with the openweathermap api.
Currently i have this line in my script to show the sunrise of an
unix UTC timestamp (weatherData.sys.sunrise):
`$(".wSunrise").html( moment.unix( weatherData.sys.sunrise ).format("HH:mm:ss" ) );`
The result is that the sunrise happens at 23:00 o'clock in the night :(

So what i tried was:
`$(".wSunrise").html( moment.unix( weatherData.sys.sunrise ).tz("Asia/Singapore").format("HH:mm:ss" ) );`
But it also showed a sunrise in the middle of the night.
Can anyone suggest me what to change to make the UTC timestamp be correct?
Thanks in advance!

**Comment by qroft** [comment]
Ok, just found it, as i realized that i have to add the timezone difference by myself manually.
Thanks a lot for this nice plugin and greetings from this corner of the planet!

**Comment by mj1856** [comment]
Your code looks fine as is, and you should not have to add the time zone difference manually.

I just tried this for myself.
```
http://api.openweathermap.org/data/2.5/weather?lat=1.283333&lon=103.85&appid=<my app id>
```
```json
{
    "coord": {
        "lon": 103.85,
        "lat": 1.29
    },
    "weather": [
        {
            "id": 701,
            "main": "Mist",
            "description": "mist",
            "icon": "50d"
        }
    ],
    "base": "stations",
    "main": {
        "temp": 300.09,
        "pressure": 1008,
        "humidity": 88,
        "temp_min": 298.15,
        "temp_max": 301.15
    },
    "visibility": 10000,
    "wind": {
        "speed": 1
    },
    "clouds": {
        "all": 75
    },
    "dt": 1483835400,
    "sys": {
        "type": 1,
        "id": 8146,
        "message": 0.0081,
        "country": "SG",
        "sunrise": 1483830582,
        "sunset": 1483873973
    },
    "id": 1880252,
    "name": "Singapore",
    "cod": 200
}
```

```js
moment.unix(1483830582).tz('Asia/Singapore').format()
// "2017-01-08T07:09:42+08:00"
```

This all looks fine to me.  Perhaps either your coordinates were off, or you don't have the moment-timezone data loaded properly.
