### ISSUE TITLE
Convert to tz keeping wall time

### ISSUE THREAD

**Issue by mj1856** [moment/moment-timezone#440]
The `moment.utcOffset` function has an optional boolean parameter to keep the local wall time.

```js
var a = moment('2017-01-01T00:00:00');
var b = a.clone().utcOffset('-05:00', true);
a.format() // "2017-01-01T00:00:00-08:00"
b.format() // "2017-01-01T00:00:00-05:00"
```

However, this flag is not available on the `moment.tz` function.  It should work similarly, as follows:

```js
var a = moment('2017-01-01T00:00:00');
var b = a.clone().tz('America/New_York', true);
a.format() // "2017-01-01T00:00:00-08:00"
b.format() // "2017-01-01T00:00:00-05:00"
```

**Comment by alanqthomas** [comment]
+1. I was just looking for a way to do this. Unfortunate that it's not already implemented.

**Comment by mj1856** [comment]
Probably the simplest workaround is:

```js
var b = moment.tz(a.toArray(), "America/New_York");
```

The real implementation would be similar to this.

**Comment by infinityl00p** [comment]
Is this appropriate for beginners? If so i would love to take on this issue! @mj1856

**Comment by mj1856** [comment]
@infinityl00p - Yes, we accept PRs from all levels of developers.

**Comment by Redarcher9** [comment]
Hey, I am a beginner and I wish to contribute. Can I get assigned for this?

**Comment by mj1856** [comment]
Looks like it was already completed in #505.  It will be out in the next release.  Thanks.

**Comment by chrisbutler** [comment]
holy shit, this is all i ever wanted moment-timezone to do.... and the package has existed for years without this functionality :man_facepalming:
