### ISSUE TITLE
Trouble parsing US Timezone abbreviations

### ISSUE THREAD

**Issue by EyePulp** [moment/moment-timezone#445]
Howdy and sorry for what's likely a dumb question.  I'm using moment-timezone via npm under Node.js (so I've got all the data files I think).  I'm trying to parse a bunch of differently formatted date strings and having trouble figuring out one format: `Sun, 05 Feb 2017 11:38:14 PST` and `Sun, 05 Feb 2017 19:39:49 EST`-- I'm getting stuck on how to handle the `PST|EST|etc` variants.

Is there a parsing token for this?  I tried variations with lowercase `z` but I'm pretty sure that's deprecated.  I also see the native Date.parse() (es5+ and under newer node.js) seems to understand US Timezones, but I'd rather have something strict like moment.js so I can throw an error on incoming patterns that fail and address them specifically.

Thanks for the work on this fantastic library.

**Comment by maggiepint** [comment]
We don't support those time zone abbreviations as they are ambiguous. CST could as easily be 'China Standard Time'. Now, you are working with RFC2822 date format there, so YOU can assume that you have US time zones and not Chinese. That said, this pull on the main moment repo might be of interest to you: https://github.com/moment/moment/pull/3708.

Until that pull is released, the easiest way to handle this is probably to simply take a substring of the last three characters of your date, and match it to the appropriate offset, as is done here: https://github.com/moment/moment/pull/3708/files#diff-e3f27469204308066d413adbf4fe72dfR138

Then you can use the utcOffset function with 'keep time' to  get the date you need: http://momentjs.com/docs/#/manipulating/utc-offset/

No moment timezone needed in all of that, which will save you some file size.

**Comment by TracyGJG** [comment]
@EyePulp, as indicated by @maggiepint, three-letter time zones can be ambiguous in some formats. However, in the RFC2822 format they have prescribed values according to the specification. I have been trying to get my Pull Request for issue #2530 accepted for some time but have a problem to overcome.

**Comment by EyePulp** [comment]
Thanks to both @maggiepint and @TracyGJG  for the thorough answers - that gives me plenty to work around the issue with.

Appreciate all the work that goes into this and the core moment.js library.  =)
