### ISSUE TITLE
What is the core logic behind calculating a time in a specific zone during dst

### ISSUE THREAD

**Issue by elldawg** [moment/moment-timezone#446]
I'm writing a function that converts a date to a specific timezone. I have a source of offsets for the target timezone. I have a function that mostly works, but falls apart around dst. How does moment handle this?

**Comment by elldawg** [comment]
I'm submitting this because I unfortunately am not allowed to use moment to do the conversion.

**Comment by mj1856** [comment]
Sorry, this question is off topic here.  Dig in to the documentation and source code if you want to learn how it works.  Ask about specifics, not generalities.
