### ISSUE TITLE
The "moment.format" makes the incorrect date

### ISSUE THREAD

**Issue by Claud** [moment/moment-timezone#447]
**Description of the Issue and Steps to Reproduce:**

```js
"use strict";

const moment = require('moment-timezone');
moment.tz.setDefault('UTC');
moment.defaultFormat = 'YYYY-MM-DD HH:mm:ss.SSS';
console.log(moment.tz('Etc/GMT+0').format());
```
Result: `2017-02-01T10:38:18Z`

i see this trouble also with Etc/GMT, Etc/GMT-0, but Etc/GMT-1... is working.

**Environment:**

Nodejs 6.9.1x64, windows 10 x 64 (tz: Europe/Moscow), moment.js 2.17.1, moment-timezone 0.5.11

**Other information that may be helpful:**

```js
console.log( (new Date()).toString()); // Wed Feb 01 2017 13:50:10 GMT+0300 (RTZ 2 (зима))
console.log((new Date()).toLocaleString()); // 2017-02-01 13:50:10
console.log( (new Date()).getTimezoneOffset()); // -180
```

**Comment by mj1856** [comment]
I'm really not sure what you are describing.  What result did you expect?

```js
console.log(moment.utc().format());  // 2017-02-28T01:29:06Z
console.log(moment.tz('Etc/GMT+0').format());  // 2017-02-28T01:29:06Z
```

They appear to be the same.

**Comment by Claud** [comment]
It is my default format: `moment.defaultFormat = 'YYYY-MM-DD HH:mm:ss.SSS';` It is not worked.

**Comment by marwahaha** [comment]
Oh, I understand.
```
moment.tz.setDefault('UTC');
moment.defaultFormat = 'YYYY-MM-DD HH:mm:ss.SSS';
console.log(moment.tz('Etc/GMT+0').format()); // 2017-03-18T17:55:24Z
console.log(moment.tz('Etc/GMT+1').format()); //  2017-03-18 16:55:24.977
console.log(moment.tz('Etc/GMT-1').format()); // 2017-03-18 18:55:24.977
```

Probably, this is a bug.

**Comment by mj1856** [comment]
Ok, it's not a bug, but it's poorly documented.

It comes down to [this change](https://github.com/moment/moment/commit/c593737a6f7d2972507694c145a19e43494b98bb) that was made for moment 2.13.0, which adds a `defaultFormatUtc` setting.  Since those other time zone all are equivalent to UTC, they also pick up on this.

The solution is to also set `moment.defaultFormatUtc` in addition to `moment.defaultFormat`.

**Comment by MojoSmit07** [comment]
Have Different kind of issue, but anyone can help?

https://github.com/moment/moment/issues/6290
