### ISSUE TITLE
moment.tz.guess() in chrome is different from moment.tz.guess() in IE

### ISSUE THREAD

**Issue by mallikarjuna909** [moment/moment-timezone#453]
Hi,

moment.tz.guess() is giving "Asia/Calcutta" in Chrome, where as moment.tz.guess() is giving "Asia/Kolkata" in IE. So my dropdown is not setting my timezone value?

Thanks.

**Comment by maggiepint** [comment]
This is actually a product of the Intl APIs in ECMA 402 that are used to produce the result. There wouldn't be much we could to to standardize that, but those are both an alias for the same zone, with Asia/Kolkata being the canonical name. Both identifiers should set the time zone correctly.
