### ISSUE TITLE
Strict parsing for moment.tz (just like moment)

### ISSUE THREAD

**Issue by futpib** [moment/moment-timezone#454]
`moment` has a last boolean option that enables strict parsing (as advertised in documentation at http://momentjs.com/docs/#/parsing/string-format/)

I think `moment.tz` should have a strict parsing option too.

**Comment by maggiepint** [comment]
This works. Just use it.

**Comment by futpib** [comment]
Ok, thank, I just got it, you have to pass `true` right after format and before timezone arguments.

Should http://momentjs.com/timezone/docs/ at least mention this?

I did not find it in the docs, then tried this:
```js
moment.tz("May 12th 20 8PM", "MMM Do YYYY hA", "America/Toronto", true)
```
and got an error, which led me to believe that it's not supported ._.

**Comment by futpib** [comment]
Issued a pull request here moment/momentjs.com#397
