### ISSUE TITLE
Moment Timezone has no data for UTC+08:00

### ISSUE THREAD

**Issue by xushuo** [moment/moment-timezone#455]
Moment Timezone has no data for UTC+08:00

what is Beijing’s Timezone ？

**Comment by maggiepint** [comment]
Moment uses the [IANA time zones](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones). For Beijing that would be Asia/Shanghai

**Comment by xushuo** [comment]
ok

**Comment by saturneric** [comment]
thanks.
