### ISSUE TITLE
DST ambiguity handling for invalid time

### ISSUE THREAD

**Issue by abhijit945** [moment/moment-timezone#456]
Docs mention the way to handle duplicate hour is to pass the offset. What are the ways to obtain the offset? For "America/Chicago", the zone object has 23 offsets and 23 zones. Since `moveAmbiguousForward` flag is false the previous hour is selected, which leaves us guessing for the other offset.

**Comment by mj1856** [comment]
It's expected that if you're parsing, you will already have the offset.  Such as if you are taking input such as `'2017-11-05T01:00:00-07:00'`, that is distinct from `'2017-11-05T01:00:00-08:00'`, though both are valid in the `America/Los_Angeles` time zone.

As far as getting the offset if you don't have it, if you only pass us the date and time, we can give you back a single offset, but we'll have to pick one in the case of ambiguity.

As far as _testing_ for ambiguity, I answered you with a function for that here:
http://stackoverflow.com/questions/42682560/moment-timezone-detect-if-given-time-is-ambiguous

This should probably be built in.  I'll keep this item open as a feature request.

**Comment by sjlongland** [comment]
> It's expected that if you're parsing, you will already have the offset.

I've been mentally grappling with this expectation for some time now.  Here's my situation:
* I'm entering time-stamped records which are collected manually and transmitted over radio to a base station to be entered into a web application.
* The remote station is logging in local time.  In most cases, this is `Australia/Brisbane` (where sanity prevails), but there has been talk of events which would have the time-zone `Australia/Sydney`, for which DST applies.
* For the sake of argument, suppose an event is in this latter time zone, let's suppose there is logged data to be entered from `01:00` through to `04:00` on the 5th April 2019 from this station (at 0300 AEDT; the offset moves from UTC+11 to UTC+10).  The operator has helpfully told me which of the `02:xx` entries happened _before_ the switch-back from DST took place, so I know which have `isDST=True` and which have `isDST=False`
* My application does not know the offset for `isDST=True` or `isDST=False`, that is why it is using `moment-timezone` in the first place.

In Python, the `pytz` utility has an `is_dst` parameter that can be used to specify which (https://pythonhosted.org/pytz/#problems-with-localtime) and modern Python `datetime` has a `fold` parameter that amounts to the same thing.

The StackOverflow solution above seems to be to "test" the offset at given times and see which fall at what offset, which seems an inefficient way to test the ambiguity.  I'd much rather tell it, "yes, DST was in effect" or "no it is normal time".

Are there plans to address this, or should I get my hands dirty with the innards myself?

**Comment by gilmoreorless** [comment]
This isn't likely to be supported. It would require a change to the parsing API, which is out of scope for Moment Timezone's [maintenance-only status](https://momentjs.com/docs/#/-project-status/).
