### ISSUE TITLE
Lost summer time  for `Europe/Zurich`

### ISSUE THREAD

**Issue by mrix** [moment/moment-timezone#457]
Could you please explain me why these examples return different results?

```js
moment.tz('2026-07-27', 'Europe/Zurich').utcOffset();
moment.tz('2040-07-27', 'Europe/Zurich').utcOffset();
```

The first example shows 120, which is correct (60 min TZ offset plus 60 min summer time offset).
The second example shows 60, which is not correct, I assume summer time offset got lost.

**Comment by mj1856** [comment]
We only project data so far into the future.  The reality of time zones is, they are a political construct.  Politicians can and do change them all the time.  Nobody can tell you what the time zones offset will be in Zurich in 2040, 2026, or even next year really.
