### ISSUE TITLE
Add support for standard names

### ISSUE THREAD

**Issue by kentonbmax** [moment/moment-timezone#462]
Ex. Standard time name:           Pacific Standard Time

Difficult to transition from existing .net to js without support for existing standards. 

Current .net object [c#](https://msdn.microsoft.com/en-us/library/bb397769(v=vs.110).aspx)

**Comment by mj1856** [comment]
Those aren't standard names.  Those are Microsoft Windows invented IDs.  IANA is the closest thing to a standard.  Use [NodaTime](http://nodatime) to work with these in C#, or if you must do conversions to Windows identifiers, you can use my [TimeZoneConverter](https://github.com/mj1856/TimeZoneConverter) library.

See also: http://stackoverflow.com/tags/timezone/info

Dup of #281
