### ISSUE TITLE
Winter hour 1986 Europe/Paris is not valid

### ISSUE THREAD

**Issue by Xen3r0** [moment/moment-timezone#463]
In France (Europe/Paris), summer hour 1986 ends on 27/10/1986 and not on 24/09/1986.

More details: http://www.cedra.net/ENS/heuredete.html

**Comment by maggiepint** [comment]
If this is the case, the issue needs to be raised with the [IANA time zone database](https://www.iana.org/time-zones) mailing list if you believe the data is incorrect. This is where we source our data from. 

Additionally, it doesn't look to me like your source says what you are saying:

1986 : du 30/3 à 1h au 28/9 à 1h 

Does that not say that summer time ended on September 28 in 1986?

In 1996 it shows October 27

**Comment by mj1856** [comment]
Yep, everything is working correctly.

![image](https://cloud.githubusercontent.com/assets/1396388/25402745/9219c122-29ae-11e7-984f-0856760bddc2.png)

https://www.timeanddate.com/time/zone/france/paris?year=1986
