### ISSUE TITLE
Update main in bower.json with new filename

### ISSUE THREAD

**Issue by jishaal** [moment/moment-timezone#466]
Latest 0.15.12 releases updated and renamed `moment-timezone-with-data-2010-2020.js` to `moment-timezone-with-data-2012-2022.js`, however the [main field entry point when using bower](https://github.com/moment/moment-timezone/blob/develop/bower.json#L5) needs to be updated as well.

**Comment by QuentinFchx** [comment]
Also, could we avoid patch releases for _breaking_ changes like this one?

**Comment by Multiply** [comment]
Same issue for us. It shouldn't have been done in a patch release :(

**Comment by igor-shevchenko** [comment]
If you want to temporarily work around the problem, you can add an override to your `bower.json`:
```
{
  "name": ...,
  "dependencies": ...,
  ...
  "overrides": {
    "moment-timezone": {
        "main": "builds/moment-timezone-with-data-2012-2022.js"
    }
  }
}
```

**Comment by mj1856** [comment]
Fixed the `bower.json` file.  My mistake.  Apologies.

WRT breaking changes - please keep in mind that moment-timezone is still 0.x.  Per [SemVer #4](http://semver.org/#spec-item-4), anything may change at any time.

Still, sorry for the confusion.  In retrospect, I believe we will change this before 1.0 to not have years in the file name, thus avoiding breaking changes from one year to the next.

**Comment by mj1856** [comment]
Also, if you're still having problems because Bower cached the previous copy, do a `bower cache clean moment-timezone` and reinstall.  It should then work fine.

**Comment by tkarls** [comment]
Thanks. Works now!
