### ISSUE TITLE
moment(...).tz is not a function

### ISSUE THREAD

**Issue by KusumaShree** [moment/moment-timezone#468]
I've updated my bower components to the latest version of moment-timezone(0.5.12). After which I'm getting below error. 

TypeError: moment(...).tz is not a function

**Comment by Multiply** [comment]
Same issue for us.

**Comment by foucdeg** [comment]
@KusumaShree  @Multiply 
I think the problem is in file bower.json : the indicated parameter
    "main": "builds/moment-timezone-with-data-2010-2020.js"
does not relate to an existing file.

@mj1856 can you fix your update pease?

**Comment by Multiply** [comment]
@foucdeg See our temp fixes in #466

**Comment by foucdeg** [comment]
Thanks!

**Comment by tkarls** [comment]
Same issue here. I think this issue is pretty critical.

**Comment by Jiish** [comment]
Build broken here too, I would also say that this is a critical issue.

**Comment by mj1856** [comment]
Should work now.  Please try again.  Thanks.

Dup #466

**Comment by kheengz** [comment]
If you're using Node.js, you may accidentally be using

`const moment = require('moment'); //moment`

instead of

`const moment = require('moment-timezone'); //moment-timezone`

Also, make sure you have installed moment-timezone with

`npm install moment-timezone --save`

**Comment by gusaiani** [comment]
If you are using `yarn`, removing `yarn.lock`, `node_modules` dir and running `yarn install` has solved this for me.

**Comment by himansuahm** [comment]
Shown same error in browser
