### ISSUE TITLE
main property in bower.json need to be  updated 

### ISSUE THREAD

**Issue by someshrathi02** [moment/moment-timezone#471]
bower.json refers to   "main": "builds/moment-timezone-with-data-2010-2020.js",
whereas release  0.5.12 file is moment-timezone-with-data-2012-2022.js. 

both are not in sync. bower.json need to be updated

**Comment by luckydev** [comment]
I'm facing the same issue. Please update.

**Comment by joestein216** [comment]
Workaround provided in #466

**Comment by mj1856** [comment]
Dup #466.  Thanks.
