### ISSUE TITLE
moment-timezone bower.json still pointing to old file "-data-2010-2020.js" not 2012-2022

### ISSUE THREAD

**Issue by ginamdar** [moment/moment-timezone#472]
I see this issue was fixed today [HERE](https://github.com/moment/moment-timezone/commit/73941fd0250a7e8fad5fe9ba282e1b8377c944fc#diff-0a08a7565aba4405282251491979bb6b) but i am still seeing old value, will there be new version?

Causing issues in wiredep and bower: grunt task since its referring to this main file to insert into index html for me

**Comment by mj1856** [comment]
I just updated the 0.5.12 tags.  Please try again and let me know if it works for you now.

**Comment by ginamdar** [comment]
Thanks..just deleted moment-timezone/ and did bower update but still old value, will try again later and update here

**Comment by mj1856** [comment]
You may have to also do a `bower cache clean moment-timezone` first.

**Comment by ginamdar** [comment]
Yep working now! closing the issue thank you for your support!
