### ISSUE TITLE
Updated to moment-timezone 0.5.12 and now webpack fails to build.

### ISSUE THREAD

**Issue by kalimar** [moment/moment-timezone#473]
Hi folks,
Just updated our dependencies and ran into problems with `moment-timezone`. We're using `npm` but tried an analogous solution to https://github.com/moment/moment-timezone/issues/472 with no luck. Any suggestions?

Thanks

**Comment by mj1856** [comment]
Does it help if you clear your bower cache?

```
bower cache clean moment-timezone
```

**Comment by kalimar** [comment]
We're not using `bower`, our app runs with `npm` and I tried clearing the cache. No luck yet. :frowning_face:

**Comment by mj1856** [comment]
Well, the only problem we had with the 0.5.12 release is that the `bower.json` wasn't updated on inital release, and we changed the `moment-timezone-with-data-2010-2020.js` to `moment-timezone-with-data-2012-2022.js`, so people using Bower didn't pick up on this change initially.

The npm build doesn't use that file.  It uses the full `moment-timezone-with-data.js` file (no year truncation).

So what errors specifically are you seeing?  FWIW, I just tried using moment-timezone in an npm project and it worked without error.

**Comment by mj1856** [comment]
I'm testing with webpack now...

**Comment by mj1856** [comment]
Seems to work fine for me under webpack also.

**Comment by kalimar** [comment]
@mj1856 thanks for checking all of that. So when I run `npm start` I get 
```Module not found: Error: Can't resolve 'moment-timezone'```. I see that our node package contains the `moment-timezone-with-data.js`. Any suggestions for tracing this further?

**Comment by kalimar** [comment]
@mj1856 Problem solved! I didn't realize that one of our engineers configured `moment-timezone` to point to the truncated file to reduce the load. We updated our `webpack.config` file and we are good to go. Thanks for looking into this.  Cheers!
