### ISSUE TITLE
Cache clean required with 0.5.12

### ISSUE THREAD

**Issue by dscerri** [moment/moment-timezone#474]
It appears that the issue with the bower.json file which existed between commits 78eb6be and 73941fd is resulting in a lot of broken versions sticking around in bower caches.

The workaround is to do 
`bower cache clean moment-timezone`
but there are automated builds set up which don't do this.

Perhaps a bump to 0.5.13 is a good idea?

**Comment by 9mm** [comment]
thanks for pointing this out, this killed me :o

**Comment by mj1856** [comment]
Done.  Thanks.
