### ISSUE TITLE
zoneAbbr for some countries stopped working

### ISSUE THREAD

**Issue by omargon** [moment/moment-timezone#479]
Hi, I just updated the library from `v0.5.11` to the latest `v0.5.13` and noticed that `zoneAbbr()` method is now returning the numeric representation for some zones like `America/Bogota` used to return `COT` now returns `-05`. Was this change intended and if so is there a different way to obtain the previous expected values? This is at least happening with all non US cities in America(Central and South).

**Comment by maggiepint** [comment]
Duplicate of #477 

Let me know if you need any further explanation.

**Comment by omargon** [comment]
Thanks. @maggiepint
