### ISSUE TITLE
Constructing a new Moment object causes a TypeError in Node

### ISSUE THREAD

**Issue by cjduncana** [moment/moment-timezone#480]
When using `moment-timezone` in Node everything functions fine if I use `moment(new Date()).tz("America/Los_Angeles")`, but if I use `moment().tz(new Date(), "America/Los_Angeles")` as described in the documentation I get the following TypeError: `(name || "").toLowerCase is not a function`.

**Comment by maggiepint** [comment]
You have a syntax error. It should be `moment.tz()` - no parentheses after moment.

Also, you don't need to pass `new Date()`, and in fact this works against you. Moment assumes the current point in time if it's not passed a date string. If you are passing it a date string, then moment's parser works significantly better than the built-in JS parser. See the parsing guide for details: http://momentjs.com/guides/#/parsing/

**Comment by jEnbuska** [comment]
cjduncana's example seems to work for me on one node 8. imported or required moment-timezone seems to work differently on every platform...
