### ISSUE TITLE
Abbreviated zone name changes since 0.5.13

### ISSUE THREAD

**Issue by fabiomargarido** [moment/moment-timezone#481]
Hi there,

Up until version 0.5.11, calling ```moment().tz('America/Sao_Paulo').format('z')``` would give 'BRT' as a result. Since 0.5.13, I'm seeing '-03'.

I know the documentation says "Please note that the z formatting token will not always show the abbreviated time zone name, instead, will show the time offsets for each region", but it seems strange that this changed. I've also observed this behavior with other zones.

Is this some sort of regression or expected behavior?

Thanks.

**Comment by maxy4u** [comment]
What was the resolution of this ? I tried all three option below i am not able to see Abbreviation 
<img width="511" alt="Screen Shot 2021-08-30 at 9 37 30 AM" src="https://user-images.githubusercontent.com/6682288/131339997-7dbd8202-fef8-4c1b-b893-1298fac0fb9e.png">

**Comment by uhrohraggy** [comment]
I know this is old, but is there a way to get BRT back without our own crosswalk?
