### ISSUE TITLE
Format offsets should not be Z for local time zones

### ISSUE THREAD

**Issue by mattjohnsonpint** [moment/moment-timezone#484]
We changed moment such that UTC formats with `Z` instead of `+00:00`.  That's fine, but the consequence of the current implementation is that *any* offset of zero is being formatted with `Z` in moment-timezone.

For moment-timezone, `Z` should only appear for UTC zones and equivalents.  We can check this with offset=0 and population=0.

In other words, `Europe/London` should get `+00:00`, but `Etc/GMT` should get `Z`.

Note that we don't hit this with regular moment when the local time zone is London (or Iceland, etc), because the `Z` doesn't get output when the moment object is in local mode.

**Comment by maggiepint** [comment]
Isn't there already a bug tracking this in core? I thought we hunted this down and it lived there. Must have been a year ago though.

**Comment by mj1856** [comment]
Yes, moment/moment#3117.  However, it's slightly different with moment-timezone, due to how some named time zones have UTC equivalence.  Both need to be addressed.

**Comment by gilmoreorless** [comment]
Closing this given the maintenance mode status of the project.
