### ISSUE TITLE
Incorrect Timezone format for Malaysia and Singapore

### ISSUE THREAD

**Issue by brendonco** [moment/moment-timezone#490]
Why is it when timezone is set to either Malaysia or Singapore, the format is different from Shanghai?

```
var momentTimezone = require('moment-timezone');
var moment = require('moment-timezone');
moment.tz.setDefault("Asia/Shanghai");
console.log(moment("1979-03-30T16:00:00Z").format());
moment.tz.setDefault("Asia/Singapore");
console.log(moment("1979-03-30T16:00:00Z").format());
moment.tz.setDefault("Asia/Kuala_Lumpur");
console.log(moment("1979-03-30T16:00:00Z").format());
```

Output
```
1979-03-31T00:00:00+08:00 - Correct - Expected
1979-03-30T23:30:00+07:30 - Wrong
1979-03-30T23:30:00+07:30 - Wrong
```

**Comment by icambron** [comment]
Singapore's offset has changed. In 1979, it was +7:30. https://en.wikipedia.org/wiki/Singapore_Standard_Time#History

I don't have a handy link for Kuala Lumpur, but I suspect it's the same thing.

**Comment by brendonco** [comment]
@icambron No, if you look at 1982 to present it should be +8:00.

**Comment by icambron** [comment]
Yes, but your dates are in 1979

**Comment by brendonco** [comment]
@icambron No, the UTC offset should be +8:00 for both Singapore/Malaysia.

https://www.timeanddate.com/time/zones/sgt
https://www.timeanddate.com/time/zones/myt

**Comment by brendonco** [comment]
Also check https://en.m.wikipedia.org/wiki/UTC%2B07:30

**Comment by icambron** [comment]
Scroll to the top of this page. You have posted an example. The example uses dates in 1979. We both agree that Singapore didn't switch to +8 until 1982. 1982 is after 1979, so both agree that behavior is correct. So what is the problem?

**Comment by brendonco** [comment]
@icambron  Thanks for highlighting that. totally missed that out.

**Comment by brendonco** [comment]
@icambron What if I want to use moment for Birthdate and I don't want to send the offset to API? How do I configure moment to not send the offset? Or is it advisable to do that?

e.g Data.

```
moment.tz.setDefault("Asia/Singapore");
moment("1979-03-29T16:00:00Z").format();
```

**Comment by icambron** [comment]
See the formatting options [here](http://momentjs.com/docs/#/displaying/format/) and pick a format that doesn't have the offset in it. Whether it's a good idea or not, I'm not sure, depends on what you're planning to do with the date.

**Comment by yogithesymbian** [comment]
```
// ------------------------------ UTILITIES
global.moment = require('moment-timezone');
moment().locale("id");
moment().tz("Asia/Makassar").format(); // should use UTC default, if your apps plains to global location
const time = moment().local().format();
console.log('current time server: ', time);
```
what i expected is GMT + 08:00
but the output is ... ( on server VPS )
` current time server:  2022-09-15T11:45:38+07:00` **GMT + 07:00**

but ... on my laptop ( local server ) is already on **GMT +08:00** .

so what ever we use the code is not work right ??? because its override by server ??? or how ???
