### ISSUE TITLE
format('X'),format('x'), unix() ignores the set timezone

### ISSUE THREAD

**Issue by simone86** [moment/moment-timezone#491]
In my laptop I have set America/Sitka time zone.

```
var m = moment().tz("Europe/Berlin")
console.log({
    format: m.format(),
    formatx: m.format('x'),
    formatX: m.format('X'),
    unix: m.unix(),
})
```

output
```
{
    format: "2017-05-05T10:23:42+02:00", 
    formatx: "1493972622948", 
    formatX: "1493972622", 
    unix: 1493972622
}
```

the unix values are returned with America/Sitka timezone and not with Europe/Berlin

**Comment by mj1856** [comment]
Unix timestamps are _always_ UTC based.  They do not change for time zone in any usage on any platform.  The Unix Epoch is 1970-01-01 00:00:00.000 UTC.

**Comment by mj1856** [comment]
Note that they are not based on `America/Sitka` either.  You are seeing the same values in both places because they are both using UTC as a basis.
