### ISSUE TITLE
diff doesn't work per the moment.js documentation

### ISSUE THREAD

**Issue by mats-ahlgren** [moment/moment-timezone#492]
https://jsfiddle.net/spzmwx0v/2/

According to the moment.js docs, the difference should be rounded towards zero. For example if the difference is say 1.5 days, then the result of .diff(..., 'days') should be 1. With timezones, the answer may be wrong.

**Comment by maggiepint** [comment]
Well, for starters your `base` variable was not in ISO8601 format - that format requires two zeroes in the hours place. Thus, I'm not entirely sure what date the date object was parsing. In any case, moment wasn't parsing that string.

Changing the string to 00:00 gives expected results. If you change your format do things appear correct?

**Comment by mj1856** [comment]
Updating your fiddle to use `00:00` instead of `0:00` in the hours field, resolves the problem.
https://jsfiddle.net/spzmwx0v/4/
