### ISSUE TITLE
2017b timezone data for EET is incorrect

### ISSUE THREAD

**Issue by rajvengala** [moment/moment-timezone#494]
2017b timezone data for EET is incorrect.

Expected - UTC+2
Showing as of today - UTC+3

**Comment by rajvengala** [comment]
Looks like I have to use Africa/Cairo instead of EET for Egypt timezone.

**Comment by maggiepint** [comment]
Closing - Africa/Cairo is the correct time zone for egypt.

Note - EET is not a valid IANA time zone identifier. Thus it will not work with moment-timezone.
