### ISSUE TITLE
America/La_Paz timezone comes back as BOT (Bogota)

### ISSUE THREAD

**Issue by roymap** [moment/moment-timezone#495]
Moment().tz('America/La_Paz').format('z') => 'BOT'

Bogota is -5, while La Paz is -4 GMT.

This happens both in nodeJS as well as in the browser.

**Comment by maggiepint** [comment]
I don't get this with moment timezone - I just get `moment().tz('America/La_Paz').format('z')
"-04"`. In addition - -04 is what is shown in the IANA TZDB as of the current version.
.
Maybe check your configuration?
