### ISSUE TITLE
GMT offsets wrong

### ISSUE THREAD

**Issue by dsimerly** [moment/moment-timezone#497]
GMT+x actually subtracts by x. Alternatively, GMT-x adds x. Is this not backwards?

More specifically, when converting a timezone (ex: 2012-03-10T00:00:00Z) from GMT0 to GMT+7 ends up resulting in 7 hours being SUBTRACTED (ex: Friday, March 9, 2012 5:00PM [Etc/GMT+7]).

**Comment by mj1856** [comment]
Dup: #436 #277 #191 #167
