### ISSUE TITLE
US/Pacific-New is not a valid timezone

### ISSUE THREAD

**Issue by JeffAtPropeller** [moment/moment-timezone#498]
You should consider removing the US/Pacific-New timzone from monent.tz.names() 

In 1989 the US House of representatives passed a bill to add "Pacific Presidential Election Time' AKA US/Pacific-New to lessen the effect of broadcast news election projections on last minute voters. It never made it to congress and was never signed into law by a president. But it seems someone preemptively added it to the timezone list in the event it became active and different libraries over time have it in their list.
https://mm.icann.org/pipermail/tz/2009-February/015448.html

No one should realistically be using that timezone as it is not valid.

**Comment by maggiepint** [comment]
I can see that you are already aware of the IANA time zone database, as you are referencing their mailing list. We take their data as-is, and do not make alterations. The complexity of maintaining actual time zone data is far beyond us. If you think this should be removed from the list, you are welcome to re-open the discussion with them, but it's out of scope for this project.
