### ISSUE TITLE
Singapore & Turkey Timezone Abbreviation Missing

### ISSUE THREAD

**Issue by Sundarasan** [moment/moment-timezone#500]
```javascript
moment.tz('Asia/Singapore').format('z');
/**
 * Expected Output: SGT
 * Actual Output: +08
 */
```
<img width="322" alt="screen shot 2017-06-09 at 2 37 42 pm" src="https://user-images.githubusercontent.com/5617015/26968968-add66ffa-4d21-11e7-91d9-2b947518496a.png">

I have tried changing my machine timezone to Singapore,
<img width="668" alt="screen shot 2017-06-09 at 10 59 03 am" src="https://user-images.githubusercontent.com/5617015/26969014-d55042c2-4d21-11e7-98c2-838193c0ea06.png">

Then I tried printing the date object via node process...
<img width="547" alt="screen shot 2017-06-09 at 10 59 24 am" src="https://user-images.githubusercontent.com/5617015/26969029-e1d54222-4d21-11e7-804f-d4413fe9ec70.png">
👆 You can see that node process returns the date with proper timezone abbreviation. But moment-timezone is not able to give me, instead it returns the offset value.

**Comment by mj1856** [comment]
Dup #477.

Regarding the two cases you mentioned:

- `Asia/Singapore` had its `SGT` abbreviation dropped in tzdb 2017a. [commit](https://github.com/eggert/tz/commit/1b99dcde6342dd10969041b32b00b813d4f4a36e).  [announcement](http://mm.icann.org/pipermail/tz-announce/2017-February/000045.html)

- `Turkey` is a link to `Europe/Istanbul`, which had its `EET`/`EEST` abbreviations dropped when it went to permanent UTC+3, in tzdb 2016g.  [commit](https://github.com/eggert/tz/commit/3e31dbe52b8730ed762880e88bf4c68ac00b8cc3). [announcement](http://mm.icann.org/pipermail/tz-announce/2016-September/000041.html)

In general, we do not invent data, we import the tzdb - like everyone else.  In your node example, likely your OS simply has time zone data older than 2017a.  Update your time zone data and you will see consistent results.
