### ISSUE TITLE
Safari not providing updated timezone based on system changes( Internationalization API issue?)

### ISSUE THREAD

**Issue by jerbio** [moment/moment-timezone#502]
The timezone property in the Internationalization API in safari OSX is not updated when the system timezone is changed; thereby causing moment.tz.guess() to generate the wrong(stale) timezone.

I have tried refreshing the browser, and disabling the cache. The only way I can get it to change, is if I kill/restart safari.
This works as expected in Google Chrome & Firefox

I modified one of your [demos](http://jsfiddle.net/bvjxt7jr/72/) to use the latest moment-timezone and error occurs in Safari but works as expected in Safari

Safari Version
Version 10.1 (12603.1.30.0.34)
Release 32 (Safari 11.0, WebKit 12604.1.23.0.4)

**Comment by mj1856** [comment]
That's a Safari issue, which could be considered either a bug, or just a missing feature.  There's nothing we can do about it in this library.

Safari bugs can be reported to Apple using [Apple Bug Reporter](https://developer.apple.com/bug-reporting/).
