### ISSUE TITLE
Timezone difference between Firefox Vs. Chrome

### ISSUE THREAD

**Issue by mumashankar** [moment/moment-timezone#504]
When I use moment.tz.guess() to get my timezone, Chrome (and Opera) returns "Asia/Calcutta"; while Firefox (and Edge) returns "Asia/Kolkata". The moment.tz.names() array has both names. Is this a bug? Or is there another way to fetch the client's timezone using this plugin which is common across all browsers and OS?
Similar result is seen with Europe timezones as well -- Firefox returns Europe/Paris while Chrome gives Europe/Berlin.

**Comment by mj1856** [comment]
`Asia/Calcutta` is the older name in the tzdb, and is now a link to `Asia/Kolkata`.  Either will use the same data, but the latter is the preferred form of the zone name.

`Europe/Paris` and `Europe/Berlin` are two different time zones.  They may be similar in recent years, but they have historical differences.

As far as consistency - sorry, but there are so many variations of how browsers implement things that we cannot guarantee any consistency.  Even when `Intl` is available, we're not guaranteed it is implemented through the same mechanism in the browser, and there are also OS-level differences even within the same browser.

We called it "guess" for this reason.  If we could be certain, then we would have called it "detect".
