### ISSUE TITLE
Different behaviour of parsing function(s)

### ISSUE THREAD

**Issue by dentuzhik** [moment/moment-timezone#506]
According to the [docs](https://momentjs.com/timezone/docs/#/using-timezones/parsing-in-zone/):
>  Using `moment.tz(Number|Date, zone)` is functionally equivalent to `moment(Number|Date).tz(zone)`

For me this is not true, here's the code which causes the issue:
```javascript
const moment = require('moment-timezone');
const sourceTimeZone = 'Europe/Helsinki';
const targetTimeZone = 'Pacific/Fiji';
const timestamp1 = moment.tz('2017-06-27 18:00', sourceTimeZone).unix();
const timestamp2 = moment('2017-06-27 18:00').tz(sourceTimeZone).unix();

const formatTime = function(timestamp, timezone) {
    return moment.unix(timestamp).tz(timezone).format('h:mma');
}

assert.equal(
    formatTime(timestamp1, targetTimeZone), // should be 3:00am
    formatTime(timestamp2, targetTimeZone)
);
```

If machine, which this test is run on is in the same timezone as `sourceTimeZone` test passes successfully, as soon as I change the timezone of my machine, test fails because formatting of timestamp2 produces different result. I discovered it because test failed in CI for me.

I will attach a PR with a failing test.

**Comment by gilmoreorless** [comment]
I agree the documentation is a bit confusing here, but it is correct. It says that the two behaviours are equivalent only when using numbers or `Date` objects as inputs:

> Unix timestamps and `Date` objects refer to specific points in time, thus it doesn't make sense to use the time zone offset when constructing. Using `moment.tz(Number|Date, zone)` is functionally equivalent to `moment(Number|Date).tz(zone)`.

Your example is using strings, which go through the parsing behaviour to read/convert offsets.
