### ISSUE TITLE
moment.tz.guess() could return a collection instead of a single result 

### ISSUE THREAD

**Issue by raulfelix** [moment/moment-timezone#509]
A potential improvement to this method would be to return the collection of IANA timezone codes sorted as per the current logic so that the consumer of the library can choose the timezone that best fits their needs.
line 355: ```return zoneScores.length > 0 ? zoneScores[0].zone.name : undefined;``` 

The need not currently being met is that a specific set of IANA timezone codes are accepted by a third party system and passing the one with the highest population leads to an error as it is outside the regions accepted.

**Comment by mj1856** [comment]
Sorry, but I'll pass on this.

IMHO, in the use case you described, it's the third-party system that is at fault.  Time zone is not something that should control an accept/reject scenario.  Anyone trying to do that is just asking for trouble.
