### ISSUE TITLE
Different dates when using .tz method on different timezones for same date

### ISSUE THREAD

**Issue by ashutosh8** [moment/moment-timezone#510]
Hi,

I faced an issue when I ran into this scenario which I am not quite sure about whether it is a bug or expected functionality.

The issue was that when a date string is supplied to moment timezone for 'America or Europe' and 'Asia or Australia', it returns the different date (previous date and current date respectively). The date string used was only date without time fragment.  The following illustrates the issue: -

- moment("2017-07-13").tz("Europe/Rome").format('LL')
=> "July 12, 2017"

- moment("2017-07-13").tz("Europe/Rome").format('LT')
=> "8:30 PM"

- moment("2017-07-13").tz("Asia/Colombo").format('LL')
=> "July 13, 2017"

- moment("2017-07-13").tz("Asia/Colombo").format('LT')
=> "12:00 AM"

The difference in dates is not understood since no time fragment is provided.
Also, the date supplied does not contain the time fragment then how is the time evaluated from that string.

Please let me know if this is a bug or there is something missing from my end.

Thanks,
Ashutosh

**Comment by mj1856** [comment]
`moment("2017-07-13")` creates a moment at the start of day in your *local* time zone.  You'll get a different point in time depending on where you execute the code.

Then you're converting it to another time zone with `.tz(...)`.  Indeed, it could easily be two different dates in two different time zones.

Basically the above is showing that Rome is 3 hours and 30 minutes behind Colombo for that particular date and time.

**Comment by ashutosh8** [comment]
Thanks for the explanation @mj1856 !
