### ISSUE TITLE
Tree shaking not working

### ISSUE THREAD

**Issue by ghost** [moment/moment-timezone#516]
Is there any benefit to doing:
```
import { tz } from 'moment-timezone';

...

tz(...);
```

Instead of:
```
import * as Moment from 'moment-timezone';

...

Moment.tz(...);
```

It seems like importing only the relevant functions should allow Webpack tree shaking to reduce bundle size but I'm not noticing any difference. Does Moment support tree shaking?

**Comment by TJTorola** [comment]
The _vast_ majority of the size of moment timezone is all within the single `latest.json` file contained in one object. There is no immediately apparent way to select out of that just the locales that are relevant to you.

**Comment by mvirbicianskas** [comment]
Hello,

I've stumbled across same problem, anyone found a workaround?

**Comment by gilmoreorless** [comment]
Shameless self-promotion here, but I've just built a webpack plugin to reduce how much data is loaded when using moment-timezone: https://github.com/gilmoreorless/moment-timezone-data-webpack-plugin

The zones and year ranges for the data are configurable, so you can include as much or as little data as you need.

**Comment by superandrew213** [comment]
You can also do this:
`import moment from 'moment-timezone/builds/moment-timezone-with-data-2012-2022.min'`

**Comment by gilmoreorless** [comment]
I've updated the Node.js and webpack sections of the [Moment Timezone documentation](https://momentjs.com/timezone/docs/#/use-it/node-js/). There are now some more details about using alternative data bundles to cut down on the size.
