### ISSUE TITLE
Wrong timezone for China/Schanghai

### ISSUE THREAD

**Issue by philipp-serfling** [moment/moment-timezone#517]
According to [wiki](https://en.wikipedia.org/wiki/List_of_time_zone_abbreviations)
The abbr. **CST** stands both for **Central Standard Time (North America)** and **China Standard Time**

If you set your timezone on your PC to Shanghai, moment determines timezone: 
`America/Chicago`

**System**
Ubuntu, FF or Chrome
`"moment": "2.18.1", "moment-timezone": "0.5.13"`

![chrome-console](https://user-images.githubusercontent.com/463137/28564999-2010d704-712b-11e7-94be-4ec3cc6b503b.png)

![timezone](https://user-images.githubusercontent.com/463137/28565010-275296ce-712b-11e7-81f1-57d8ce5c859b.png)

**Comment by maggiepint** [comment]
Would this be the same as #503?

**Comment by mj1856** [comment]
Can you please tell me what you get in your browser debug console for:

```js
Intl.DateTimeFormat().resolvedOptions().timeZone
```

**Comment by looser** [comment]
Yes, of course. 
For my real position in germany i get `CET`

If i set my timezone to Shanghai i get `America/Chicago`
![timezones](https://user-images.githubusercontent.com/463137/28659067-516829f4-72ae-11e7-8b5e-cb23c8d9bfe3.png)

**Comment by mj1856** [comment]
That is really bizarre.  You should get `Europe/Berlin` for Germany, and `Asia/Shanghai` for China.

Are you on the current release of Chrome?  Can you give me the result of `navigator.userAgent` in each?

Can you try to update and see if you still have the problem?

**Comment by mj1856** [comment]
And again, what does `printenv TZ` show in the linux shell?

**Comment by looser** [comment]
Oh sorry, i've overseen your comment about `printenv TZ`
No, i did override this. So the result is an `empty string` 

 `navigator.userAgent`
In Chrome:
`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"`

In FF
`"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0"`

Ubuntu version 16.04.2

This might be an issue of the Ubuntu though, 
i have also tried with Chrome on Windows 10 and the results are as you expect
`Europe/Berlin`, `Asia/Shanghai`

**Comment by mj1856** [comment]
Ok, so with the Intl API returning strange results, there's not a lot Moment-timezone can do... Still I want to dig deeper on this to see if I can figure out what's going on.  I need to take the time to spin up some of this environment to try to reproduce your results.  My guess is it has to do with ICU version.  IDK if libicu is distributed independently or just with Chrome.  I'll leave this open for now until I can figure it out.

**Comment by looser** [comment]
It is no blocking issue for me, so that works perfectly fine.
Tell me, if i can help you with something.

Thank you very much for caring!

**Comment by avdv** [comment]
Hi, we run into the same issue. The problem is indeed a bug in libicu: http://bugs.icu-project.org/trac/ticket/12770

just my 2¢

**Comment by bolasblack** [comment]
I encountered this issue too, on Chrome 60, 61 for Mac, I found if I switch timezone to another timezone and then switch back, Intl.DateTimeFormat().resolvedOptions().timeZone will return the correct value. But new Date().getTimezoneOffset() will be 0...

**Comment by iffy** [comment]
A user of mine is encountering this same problem in an Electron app (I don't know what version of Chrome is uses).

| thing | value |
|---|---|
| `moment.tz.guess()` | `America/Chicago` |
| `moment.tz(guess).format()` | `2018-04-18T09:19:14-05:00` |
| `moment.utc().format()` | `2018-04-18T14:19:14Z` |
| `(new Date()).getTimezoneOffset()` | `-480` |
| `(new Date()).toString()` | `Wed Apr 18 2018 22:19:16 GMT+0800 (CST)` |
| `(new Date()).toLocaleString()` | `4/18/2018, 10:19:16 PM` |
| `moment.version` | `2.18.1` |

**Comment by maoqxxmm** [comment]
I have the same problem in QQBrowser. I'm in China.  The user agent is 
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.82 Safari/537.36 QQBrowser/4.0.4035.400`

thing | value
--- | ---
`moment.tz.guess()` | America/Chicago
`new Date().getTimezoneOffset()` | -480
`moment.version` | 2.6.0

**Comment by avdv** [comment]
> Chrome/48.0.2564.82

If that's the correct version number, this is too old -- as it was released 2016-01-20.

AFAICS, QQBrowser's latest version is 10, which uses Chrome 65. Try to upgrade.

**Comment by marswong** [comment]
wrong time for `CST`. the `CST` time should be 8 hours later than `UTC`, but actually it performs 12 hours.

<img width="443" alt="screen shot 2018-06-03 at 11 39 32" src="https://user-images.githubusercontent.com/10388933/40882918-f874b21c-6722-11e8-9ba2-d9f362511e36.png">

**Comment by mbm-rafal** [comment]
Since there is a single time offset in entire China 
https://en.wikipedia.org/wiki/Time_in_China

when using moment library for different time zones (based on PHP entires) like:

{code}
  moment.tz('2016-01-01', 'Asia/Shanghai').format('ZZ'),
  moment.tz('2016-01-01', 'Asia/Urumqi').format('ZZ')
{code}

even though they should be UTC +8 

there is +8:00 and +6:00 because of geo offset 

![image](https://user-images.githubusercontent.com/19263109/46233195-13c27800-c372-11e8-8ce1-4b51b9fcaecb.png)

**Comment by avdv** [comment]
@mbm-rafal this is a completely different problem, right? Would you please open a new issue?

**Comment by ccorcos** [comment]
I'm having this same issue with electron v2.0.5.

In Chrome, I get what I would expect.

```
> new Date()
Wed Apr 24 2019 07:54:56 GMT+0800 (Philippine Standard Time)

> Intl.DateTimeFormat().resolvedOptions()
{locale: "en-US", calendar: "gregory", numberingSystem: "latn", timeZone: "Asia/Manila", year: "numeric", …}calendar: "gregory"day: "numeric"locale: "en-US"month: "numeric"numberingSystem: "latn"timeZone: "Asia/Manila"year: "numeric"__proto__: Object

> moment.tz.guess()
"Asia/Manila"
```

However in Electron, it's wrong.

```
> new Date()
Wed Apr 24 2019 07:56:25 GMT+0800 (PST)

> Intl.DateTimeFormat().resolvedOptions()
{locale: "en-US", numberingSystem: "latn", calendar: "gregory", timeZone: "America/Los_Angeles", year: "numeric", …}calendar: "gregory"day: "numeric"locale: "en-US"month: "numeric"numberingSystem: "latn"timeZone: "America/Los_Angeles"year: "numeric"__proto__: Object

> moment.tz.guess()
"America/Los_Angeles"
```

The interesting thing is that the UTC offset is correct, but the timezone label is wrong.

If I skip this line and let moment do the timezone guessing, I actually get the correct timezone.

https://github.com/moment/moment-timezone/blob/c377ac8fd7ff6c2fc52e2f432034ac5727dba1d8/moment-timezone.js#L337

Perhaps we should consider the native timezone logic unreliable, especially since what we're really after is UTC offsets for computing the correct dates...

I would like to just skip the native call to `Intl.DateTimeFormat().resolvedOptions()` entirely because it appears to be unreliable. However, maybe it gives more accurate time zones when it is correct. So maybe we should just to a sanity check if the UTC offset is consistent with the timezone and if not, fall through to the zone scoring logic. `Date.getTimezoneOffset` returns the correct value so I think this should work. 

```
> (new Date()).getTimezoneOffset()
-480
```

**Comment by ccorcos** [comment]
OMG. PST = Pacific Standard Time = Philippines Standard Time! Lol. That was a lot of wasted time!

**Comment by ccorcos** [comment]
OMG. Pacific Standard Time and Philippines Standard Time also have the same abbreviation -- PST!

**Comment by gaodeng** [comment]
any news?

**Comment by ichernev** [comment]
I don't think moment-timezone uses offset names (PST, CST) to determine which timezone you're in. It uses offsets (the numbers) of different dates, and tries to match that to existing timezones.

It's cool to debug libicu from moment-timezone, but not really the right place for it. Check https://github.com/moment/moment-timezone/issues/873#issuecomment-1228473648

If we had way to tell guess to not use Intl at least we could close issues that are based on buggy Intl support (and shield users from them...).
