### ISSUE TITLE
Wrong abbreviation/name for Asia/Manila

### ISSUE THREAD

**Issue by mishless** [moment/moment-timezone#518]
The zone abbreviation and the zone name for Asia/Manila seems to be incorrect - `moment.tz('Asia/Manila').zoneAbbr()` gives as a result `+08` where it should be `PHT`. The same behavior is observed with `zoneName()` as well.

**Comment by mj1856** [comment]
Duplicate #477.  Working as designed.  Let me know if you need further explanation.  Thanks.
