### ISSUE TITLE
Setup a custom locale is not working with moment

### ISSUE THREAD

**Issue by anandafit** [moment/moment-timezone#521]
I am sorry if this question has been addressed with another closed issue but I could not find an exact answer for that. My Problem is following,

Following code explain how I am going to set a locale with moment which is  documented as https://momentjs.com/docs/#/i18n/changing-locale/. Here my intention is to set the week that contains Jan 4th is the first week of the year. But it seems to be not appearing work correctly. See the below code

```
import moment from 'moment';
//function
export const getConfiguredOldMoment = ({ timeStamp,startOfWeek }) => {
 moment.locale('en-ot', {
    week: {
      // startOfWeek is the first day of the week.
      dow: startOfWeek,
      // The week that contains Jan 4th is the first week of the year.
      // https://en.wikipedia.org/wiki/ISO_8601
      doy: 4,
    },
  });
  return moment(timeStamp);
};


//Unit test 
it('Test moment', () => {
    const merchantStartOfWeek = 0;
    const timestamp = 1451968956000; // (GMT): Tuesday, January 5, 2016 4:42:36 AM
    const moment0 = getConfiguredOldMoment({value: timestamp, startOfWeek: merchantStartOfWeek});
    expect(moment0.format('gggg-w')).to.be.equal('2016-1');
  });

Moment test Test moment:
      AssertionError: expected '2015-53' to equal '2016-1'
      + expected - actual

      -2015-53
      +2016-1
```
According to the above code expect to get 2016-1 but it returns  2015-53.  I would be really thankful if some one can heads up on this.

**Comment by mj1856** [comment]
See https://github.com/moment/momentjs.com/issues/279 and https://github.com/moment/moment/issues/3056
