### ISSUE TITLE
GetCountries Method

### ISSUE THREAD

**Issue by evertondanilo** [moment/moment-timezone#522]
Hello, Guys, I have been trying to access the countries property of latest.json file through moment.tz, then I realized that this property doesn't exist. I think it would be quite useful.
Today we have moment.tz.zones property, how about a new property called moment.tz.countries and a getCountries method?

**Comment by mj1856** [comment]
Country functionality is tied up in PR #410

**Comment by alexgrace95** [comment]
Have resolved the conflicts, awaiting review and then merge. Hope you find it useful
