### ISSUE TITLE
moment.tz.guess() is not able to guess the Asia/Calcutta time zone

### ISSUE THREAD

**Issue by Thiyagarajan-A** [moment/moment-timezone#523]
When I call **moment.tz.guess()** it is not able to identify the time zone "Asia/Calcutta".  May be because of the spelling change "Calcutta" to "Kolkata". 

But when I do the following code, it is able to recognize the timezone.
```
var timezoneName = Intl.DateTimeFormat().resolvedOptions().timeZone; // Gives "Asia/Calcutta"
moment.tz.setDefault(timezoneName);
```
And the below one returns "Asia/Calcutta".
`moment().tz();`

**Comment by mj1856** [comment]
You say it's not able to identify it, but what does it return?  What browser/os/moment version/moment-timezone version?  Please clarify.  Thanks.

**Comment by Thiyagarajan-A** [comment]
Yes, it is not able to identify it.
```
moment.tz.guess()
console.log(moment().tz()); //returns undefined. 

```

> browser/os/moment version/moment-timezone version


**Chrome | Windows 10 | ver: 2.18.1 | ver: 0.5.13**

**Comment by mj1856** [comment]
That is expected.  Calling `moment()` creates a moment in local mode, which is unaware of the time zone name, so `moment().tz()` will always return `undefined` unless you've set it with `moment.setDefault`.

```js
moment.tz.guess()  // gives the time zone name, but doesn't set anything  
console.log(moment().tz());  // this logs undefined, because no zone was set

moment.tz.setDefault(moment.tz.guess()) // now we've set the default time zone
console.log(moment().tz()); // should give the time zone name
```

**Comment by Thiyagarajan-A** [comment]
Thanks for your answer.
