### ISSUE TITLE
Inconsistant timezone parsing

### ISSUE THREAD

**Issue by andy9775** [moment/moment-timezone#526]
I'm having an issue with moment/moment-timezone parsing and formatting dates correctly. I have a react app with redux and saga. In one saga I fetch user details including a timezone and do `moment.tz.setDefault(user.timezone);`. Then in other parts of the application I create dates via `moment(dateInUtc).format("...")` and the issue is that some dates are formatted correctly (correct timezone offset and display) while others are an hour off. 

The same issue occurrs if I use `moment.tz(utcDate, 'Europe/Berlin')`. The date comes from a rails app so the format is `"2017-09-13T16:15:28.000Z"`

I'm using:
```
    "moment": "^2.18.1",
    "moment-timezone": "^0.5.13",
```

**Comment by andy9775** [comment]
One thing I noticed is that it tends to happen when the time is 00:00 UTC. In those cases, one timezone gets formatted to the correct offset and time while another is incorrect even if both dates are the same.

**Comment by mj1856** [comment]
Could you please provide a clear example of the input, code, and output that is incorrect?

**Comment by andy9775** [comment]
:man_facepalming: 

I was just writing up an example and realized that I didn't account for DST offsets and dates - oops. 

It happens to be that most of the times were set as 00:00 UTC but the dates were months apart hence why I thought that it was an issue parsing from midnight times.

thanks @mj1856 :duck:
