### ISSUE TITLE
Abbreviation is a number for some timezones

### ISSUE THREAD

**Issue by elinake** [moment/moment-timezone#527]
moment.tz('America/Argentina/Buenos_Aires').zoneAbbr()
and
moment.tz('America/Argentina/Buenos_Aires').zoneName()
and 
moment.tz('America/Argentina/Buenos_Aires').format('zz')
and 
moment.tz('America/Argentina/Buenos_Aires').format('z')

all result '-03' instead of 'ART'. Same results for Minsk and Istanbul, for all other timezones abbreviation is correct.

**Comment by mj1856** [comment]
Yes indeed.  This is correct per the TZDB.  We don't make this stuff up - it comes from IANA.

Dup #477, #479, #500, #518, #525
