### ISSUE TITLE
Creating date with specific time in a time zone

### ISSUE THREAD

**Issue by rsarili** [moment/moment-timezone#532]
Hi,
I have time information "2017-09-23T19:30:00" which is local time for "Europe/Istanbul". I want to create time moment object like
`Sat Sep 23 2017 19:30:00 GMT+0300 (+03)`
but I can not achieve that result with
`moment.tz("2017-09-23T19:30:00", moment.ISO_8601,'Europe/Istanbul');`
I got
`Sat Sep 23 2017 22:30:00 GMT+0300 (+03)`
What is the correct way to create moment object with local time string?

**Comment by mj1856** [comment]
You're doing it correctly.  You could also skip the middle parameter `moment.ISO_8601`, as it's the default.

You probably either are not loading the time zone data, or you're not calling a function like `.format()` when evaluating the results.  Note that you cannot use `.toDate()`, as the `Date` object does not support non-local time zones.
