### ISSUE TITLE
Eastern Standart Time - daylight time

### ISSUE THREAD

**Issue by galyech** [moment/moment-timezone#534]
Hi, 
In your documentation, EST has no DST, although there are places in EST that observe daylight savings. is it correct? and if so, why there is EST in moment-timezone (maybe is it too general?) and how can we refer it when it comes to DST?

**Comment by andrewboerema** [comment]
@galyech - Two points here. First, EST stands for Eastern Standard Time and is only used to talk about the non-DST time of year. EDT (Eastern Daylight Time) is used the rest of the year. Second point is that EST/EDT are, for the above reason, not super fun to use. I would suggest using the more flexible `America/New_York` (or whatever is appropriate) timezone
