### ISSUE TITLE
Moment Timezone: Formatting with DST NodeJs 

### ISSUE THREAD

**Issue by 360disrupt** [moment/moment-timezone#535]
Expected is that the formatted date is in the selected time zone. The time zone has summer and winter time. 

```
var format = 'YYYY-MM-DD HH:mm:ss';
var dateSummer = "1949-05-01T22:00:00.000Z";
var dateWinter = "1949-01-01T23:00:00.000Z";
console.log(moment(dateSummer).tz("Europe/Amsterdam").format(format));
console.log(moment(dateWinter).tz("Europe/Amsterdam").format(format));
```

This works in the fiddle:
https://jsfiddle.net/0yc49dtn/2/

But fails with npm packages:

>     "moment": "^2.18.1",
>     "moment-timezone": "^0.5.13",

```
  it('should convert a ISO date to local date', () ->
    format = 'YYYY-MM-DD HH:mm:ss'
    dateSummer = "1949-05-01T22:00:00.000Z"
    convSummerTime = moment(dateSummer).tz("Europe/Amsterdam").format(format)
    expect(convSummerTime).toBe("1949-05-02 00:00:00")
  )

Expected '1949-05-01 23:00:00' to be '1949-05-02 00:00:00'.
```

**Comment by andrewboerema** [comment]
@360disrupt - The Europe/Amsterdam timezone didn't utilize DST from 1946 to 1976. So the period you are asking for would have a consistent UTC+1 offset. So it is correctly reporting 1949-05-01 23:00:00. I rolled back to 1945 when DST was in use and you can see DST reflected as expected: https://jsfiddle.net/p259nmw8/

Refer to https://www.timeanddate.com/time/zone/netherlands/amsterdam for current and historical timezone information.

**Comment by 360disrupt** [comment]
@andrewboerema 

I get the point that times have been handled diff. through history. But there is still a difference how `moment-timezone` behaves in the unit test (npm package) and in the jsfiddle. So in that case, the version https://momentjs.com/downloads/moment-timezone-with-data.js has a bug.

Sorry, I didn't understand your fiddle it shows 1949 like mine if I change to 1945 I still get `00:00:00` for both examples: https://jsfiddle.net/u94dqfnw/1/

**Comment by mj1856** [comment]
The fiddles have their external resources loaded incorrectly.  Always load moment (or moment-with-locales) first.  Then load moment-timezone-with-data second.  The order matters, and don't load moment-timezone (without data) if you're also going to load moment-timezone-with-data.

The only purpose for moment-timezone (without data) is if you are going to load your own data with `moment.tz.add`.  Since this is already done for you in the with-data version, you don't need to bring in the actual moment-timezone code twice.

**Comment by mj1856** [comment]
Your fiddle, with resources loaded correctly: https://jsfiddle.net/0yc49dtn/5/
