### ISSUE TITLE
Allow compilation without dynamic requires

### ISSUE THREAD

**Issue by stantoncbradley** [moment/moment-timezone#536]
In the `moment` dependency, The current master build of metro-packager/react-native really doesn’t like dynamic require statements. Importing the current version of moment produces the error

```TransformError: /.../moment/moment.js: require() must have a single string literal argument```

https://github.com/moment/moment/pull/4187 fixes the issue in `moment.js`.

I'm opening this issue because once that PR is merged, the `moment` dependency in `moment-timezone` needs to be updated to capture these changes.

thanks for the awesome lib!

**Comment by lnikkila** [comment]
I’m getting `moment.version is undefined` when trying to use moment from the linked PR with moment-timezone.

**Comment by vincejah** [comment]
I am also interested in seeing this problem fixed. What could be done to speed up things?

**Comment by gilmoreorless** [comment]
Moment Timezone doesn't contain any dynamic requires. Any lingering problems with core Moment not being updated could be due to package manager oddities. See https://github.com/moment/moment-timezone/issues/982#issuecomment-1119540905 for more details.
