### ISSUE TITLE
TypeError: Cannot read property 'format' of undefined

### ISSUE THREAD

**Issue by jofftiquez** [moment/moment-timezone#538]
I have a code like this : 

`const T = moment().tz(process.env.TZ).format('YYYY-MM-DD');`

which was being converted by babel to ES5 with the output like : 

```
var _momentTimezone = require('moment-timezone');
var _momentTimezone2 = _interopRequireDefault(_momentTimezone);

const T = (0, _momentTimezone2.default)().tz(process.env.TZ).format('YYYY-MM-DD');
```
**Error**

> TypeError: Cannot read property 'format' of undefined

**Comment by mj1856** [comment]
What is `process.env.TZ` in this case?  If it is `undefined` (or `null`, ``, etc.) it will produce this result.

**Comment by mj1856** [comment]
If you're just looking for the local time zone, you probably don't want to guess that it will be well-formed and in the `TZ` environment variable.  That's not a guarantee on most systems.  A better approach is to just use moment's local-time functionality, which is the default.  You don't need moment-timezone for that.  In other words, you'd have the same effect with:

```js
const T = moment().format('YYYY-MM-DD');
```

**Comment by DCtheTall** [comment]
> What is process.env.TZ in this case? If it is undefined (or null, ``, etc.) it will produce this result.

Is there a motivation behind this behavior?
