### ISSUE TITLE
yarn install example for moment-timezone 

### ISSUE THREAD

**Issue by chrisdrackett** [moment/moment-timezone#542]
on the moment timezone page (http://momentjs.com/timezone/) the install example for yarn does not seem to match the other examples, it says `yarn add moment` while the others seem to suggest this should be `yarn add moment-timezone`

**Comment by claughlin-r7** [comment]
When adding a package via yarn the [add](https://yarnpkg.com/lang/en/docs/cli/add/) command is used. Checking the link you added shows the instructions:
```
yarn add moment
```

**Comment by chrisdrackett** [comment]
@claughlin-r7 yes, you are correct, typo on my end, I updated my original issue!

**Comment by SecondeJK** [comment]
yarn add moment-timezone

This just wasted my morning, please please correct it. Thanks!

**Comment by mj1856** [comment]
Fixed in moment/momentjs.com#461.  Thanks.
