### ISSUE TITLE
__WEBPACK_IMPORTED_MODULE_0_moment___default.a.tz is not a function

### ISSUE THREAD

**Issue by samcambridge** [moment/moment-timezone#544]
After installing the moment-timezone via yarn (`yarn add moment`), should the `tz` methods be automatically callable?

I'm seeing the error message:
```
Error in render function: "TypeError: __WEBPACK_IMPORTED_MODULE_0_moment___default.a.tz is not a function"
```

When trying to call it the same way as given in examples:

```
moment.tz("Europe/London").unix(timestamp)
```

I scoured the internet and it was recommended require it like 

```
import moment from 'moment'
moment.tz = require('moment-timezone')
```
but this came with it's own host of problems and didn't seem to be chainable (i.e calling `format()` method caused errors).

I'll be the first to admit my front end chops aren't the best, so any help would be greatly appreciated!

Versions:
moment-timezone@0.5.13
moment@2.18.0

webpack@2.1.0-beta.22

**Comment by Sieabah** [comment]
Webpack 2 went stable forever ago and they're on version 3 now.

**Comment by samcambridge** [comment]
aaaaaaaand I'm an idiot. I assumed seeing as you only had to `yarn add moment` I only had to `import moment from 'moment'`.

After chatting to someone helpful on webpack IRC they pointed out that i needed to
`import moment-timezone from 'moment-timezone'`

... couldn't see the wood through the trees, can't believe i didn't try that sooner!

**Comment by Sieabah** [comment]
@samcambridge 

`import moment-timezone from 'moment-timezone'` Would be invalid syntax.
