### ISSUE TITLE
Deprecation Warning while using moment-timezone

### ISSUE THREAD

**Issue by NehaSharma2304** [moment/moment-timezone#546]
I am trying to use moment.tz(new Date(), 'Etc/UTC').format('MM-DD-YYYY HH:mm') format to get the date and time in GMT but its giving me warning, how to resolve this warning?

**Comment by mj1856** [comment]
That shouldn't give a deprecation warning with the current versions.  However, it's also unnecessary to use moment-timezone for this, or to use the `Date` object at all.  Just do:

```js
moment.utc().format('MM-DD-YYYY HH:mm')
```
