### ISSUE TITLE
Strict mode and Unix timestamp.

### ISSUE THREAD

**Issue by prototype23** [moment/moment-timezone#555]
// Correct
moment.tz(1509383108 * 1000, 'America/Caracas').format(); // "2017-10-30T13:05:08-04:00"
moment.tz(1509383108 * 1000, 'Europe/Athens').format(); // "2017-10-30T19:05:08+02:00"

// Wrong
moment.tz(1509383108, 'X', true, 'America/Caracas').format(); // "2017-10-30T17:05:08-04:00"
moment.tz(1509383108, 'X', true, 'Europe/Athens').format(); // "2017-10-30T17:05:08+02:00"

I was expecting a time shift with the last two examples but only tz is changed is that a bug?

moment version: 2.18.1
moment.tz version: 0.5.13

**Comment by mj1856** [comment]
I can't reproduce this.  It returns the correct results in both cases.  Can you please create a jsFiddle (or similar) to reproduce?

Thanks.

**Comment by mj1856** [comment]
Also, have you changed the default time zone?  We have a bug open on that in #338.

**Comment by prototype23** [comment]
Hi Matt, thanks for the feedback.

No i did not changed the default time zone. Here is a jsbin example https://jsbin.com/yumosen/edit?js,output and here a screen shot of the results my computer:

![moment-tz_00](https://user-images.githubusercontent.com/14275025/32329205-fe77bcf8-bfe4-11e7-9769-d0585c186cf4.png)

Maybe is a missaderstanding, on my part. On the docs i can see now clearly:

"There are two interfaces for using time zones with Moment.js.moment.tz(..., String) is used to create a moment with a time zone, and moment().tz(String) is used to change the time zone on an existing moment."

Maybe i confused by this part:
"Unix timestamps and Date objects refer to specific points in time, thus it doesn't make sense to use the time zone offset when constructing. **Using moment.tz(Number|Date, zone) is functionally equivalent to moment(Number|Date).tz(zone).**"
Which the later, refers in case of unix timestamps only!

Aris

**Comment by prototype23** [comment]
Hmm but wait on both cases (1,2 and 3,4) i'm using the moment.tz() method. On the 1,2 shifts the time and on the (3,4) is not.

**Comment by mj1856** [comment]
Ok, I'm dumb..  This was indeed fixed already in moment-timezone 0.5.14 and missed in the release notes.  PR #348 fixed it.  Please upgrade.

(Also I note your moment 2.18.1 can upgrade to 2.19.1 also)
