### ISSUE TITLE
Missing correct default abbreviations for timezones

### ISSUE THREAD

**Issue by LiuVII** [moment/moment-timezone#557]
Some timezones do not have correct abbreviations.

[Time Zones in Wiki](https://en.wikipedia.org/wiki/List_of_time_zone_abbreviations)

For example, "Niue/Pacific" the default one should be "NUT", not "-11".

In "/data/packed/2016j.json" it was:
`
"Pacific/Niue|NUT NUT NUT|bk bu b0|012|-KfME 17y0a|12e2"
`

But currently in "/data/packed/latest.json" ("1 Updated data to IANA TZDB 2017c"):
`
"Pacific/Niue|-1120 -1130 -11|bk bu b0|012|-KfME 17y0a|12e2"
`

And it's not the only one.

**Comment by mj1856** [comment]
It is valid.  Wikipedia is not authoritative.

Dup #477, #479, #500, #518, #525, #527.

**Comment by mj1856** [comment]
Regarding your specific example, the invented abbreviation for `Pacific/Niue` was removed by Paul Eggert, the IANA TZ Database maintainer, in tzdb 2017a.  You can read his [announcement](http://mm.icann.org/pipermail/tz-announce/2017-February/000045.html), and review the [actual commit](https://github.com/eggert/tz/commit/a25d615495c57081297939b4befe6f9b6bf438ea) if you like.

**Comment by LiuVII** [comment]
Sir, thank you very much for the explanation!
