### ISSUE TITLE
Timezone of Hermosillo wrong

### ISSUE THREAD

**Issue by gitramro** [moment/moment-timezone#558]
Looking for Hermosillo time is one hour ahead, is it a bug? How can I get the hour right?

[https://www.google.com.mx/search?q=hermosillo+time&oq=hermosillo+time&aqs=chrome..69i57j69i60l3j69i61l2.1480j0j7&sourceid=chrome&ie=UTF-8](url)

Hermosillo is in Northwest-México (in the moment timezone map is right under Phoenix (USA))

[https://momentjs.com/timezone/](url)

**Comment by mj1856** [comment]
Not sure what error you're reporting, but both `America/Hermosillo` and `America/Phoenix` use UTC-7 year-round.  If you are seeing an hour off, then you'll need to show what code you're using to get that result.

**Comment by gitramro** [comment]
I think I didn't explained myself, right now is 5:37 pm in Hermosillo (I live here) and in Moment Timezone marks 6:37 pm, you can check the map in here (is 1 hour ahead)

[https://momentjs.com/timezone/](url)

Hermosillo is located in Northwest Mexico

**Comment by mj1856** [comment]
Looks right to me (20 min later)...

![image](https://user-images.githubusercontent.com/1396388/32471717-98f03e14-c313-11e7-94b3-31949d234521.png)

My guess is your computer's clock or time zone is set incorrectly.

**Comment by mj1856** [comment]
If on Linux/Mac, you should be using `America/Hermosillo` as your actual system time zone.  If on Windows, it should be set to `(UTC-07:00) Arizona`.

**Comment by gitramro** [comment]
Fixed, thank you very much
