### ISSUE TITLE
Incorrect offsets

### ISSUE THREAD

**Issue by gerfboy** [moment/moment-timezone#560]
moment.tz("1965/8/3", "US/Mountain").utcOffset() returns -360 as expected.
moment.tz("1964/8/3", "US/Mountain").utcOffset() returns -420 instead of -360.

I've searched online to see if this was due to some DST shift, but I don't think it was.

When conducting a similar test with "US/Eastern" I found I had to go back to 1917 and 1918 for the offsets to change, which makes more sense as DST began back then.

Am I doing something wrong?

**Comment by mj1856** [comment]
The data is correct.  Mountain Time (at least in Denver, Colorado) did not adopt DST until 1965.

We import data directly from the tzdb.  You can read about US time zones in the [NorthAmerica](https://github.com/eggert/tz/blob/master/northamerica) file.

Another good place to confirm this is [here](https://www.timeanddate.com/time/zone/usa/denver?syear=1900&eyear=1970).

As to why, see [1916–1966: Early, inconsistent use](https://en.wikipedia.org/wiki/Daylight_saving_time_in_the_United_States#1916%E2%80%931966:_Early,_inconsistent_use) in Wikipedia's article about DST in the US.

**Comment by mj1856** [comment]
(Sorry for the delayed response.)
