### ISSUE TITLE
Force formatting to use letter based abbreviations

### ISSUE THREAD

**Issue by Azmisov** [moment/moment-timezone#561]
So for some timezones, I'm getting UTC offsets instead of the letter-based abbreviations. For example:
```
moment.tz("Europe/Samara").format("z")
```
will give me `+04`, when I'd expect something like `SAMT` or `SAMST` based on [this list](https://www.timeanddate.com/time/zones/) and [this list](https://en.wikipedia.org/wiki/List_of_time_zone_abbreviations). Why is that the case? Is it because the abbreviation list moment is using is incomplete; or perhaps this abbreviation has not been standardized yet? If this isn't a bug, do you have any recommendations on getting a letter-based abbreviation from a moment object? My use case requires letter-based timezone abbreviations wherever possible, and is primarily targeted at english speakers from the US.

**Comment by 21110027781** [comment]
Hi Azmisov

I think your issue duplicate with [#500](https://github.com/moment/moment-timezone/issues/500), [#469](https://github.com/moment/moment-timezone/issues/469) .
I hope it can help you.

**Comment by Azmisov** [comment]
Ah yes, it is a duplicate. Sorry about that... searched the existing issues, but nothing was coming up.
