### ISSUE TITLE
setDefault() does nothing

### ISSUE THREAD

**Issue by vladkornea** [moment/moment-timezone#563]
alert(moment.tz.guess()) // America/New_York
moment.tz.setDefault(moment.tz.guess()) // America/New_York has now been set as the default timezone
alert(moment.tz().format('z')) // shows UTC

version 0.5.14

**Comment by mj1856** [comment]
Use `moment().format()`, not `moment.tz().format()`

**Comment by KennyEng12** [comment]
Hi,

I'm wondering if I'm using moment.tz.setDefault() function, is it only affect to the particular page or all of the pages?

Thanks.
