### ISSUE TITLE
Wrong offset calculations

### ISSUE THREAD

**Issue by mikevercoelen** [moment/moment-timezone#565]
I am converting a date to another timezone, but the daylight savings are not calculated.

In the example below: I convert an Europe/Amsterdam (GMT+2) date to an Asia/Bangkok (GMT+7) date.

There is one hour missing in this convertion, the Amsterdam time is 9:00 and the converted bangkok time is 14:00, which is wrong and it should be 15:00 (https://www.timeanddate.com/worldclock/converter.html?iso=20171130T080000&p1=28&p2=16)

```js
    import moment from 'moment-timezone';
    
    // Europe/Amsterdam = GTM+2
    const amsterdamDate = moment('2014-06-09T09:00:00+02:00')
      .clone()
      .tz('Europe/Amsterdam')
    
    // Asia/Bangkok = 7:00
    const amsterdamToBangkokDate = amsterdamDate
      .clone()
      .tz('Asia/Bangkok')
    
    // The output missed the Day light saving
    
    // It should be: 15:00 - "2014-06-09T15:00:00+07:00"
    // IT IS WRONG: 14:00 - 2014-06-09T14:00:00+07:00
    console.log(amsterdamToBangkokDate.format())
```

See a live example: https://codesandbox.io/s/xjz7lo70vq

Am I doing it wrong?

**Comment by mj1856** [comment]
The conversion is correct.

https://www.timeanddate.com/worldclock/converter.html?iso=20140609T070000&p1=16&p2=28

But also, understand that because you provided an offset in the original value, that it belongs to Amsterdam is irrelevant.
