### ISSUE TITLE
How to edit style of text in moment-timezone ?

### ISSUE THREAD

**Issue by kilaniba** [moment/moment-timezone#567]
I created a time of zone ` moment.tz(id_zone).hour(v).format('hh:mm:ss a')`  .I want to handle this time , for example , the hour displayed on a big size and minute on small size . Please is it possible with moment and moment-timezone ?

**Comment by mj1856** [comment]
It returns a JavaScript string.  How you display it (ie. HTML) is not something we have any control over.  Use normal HTML/CSS techniques as you would any other string.  If you need it in two parts, either split the string, or format two separate strings.
