### ISSUE TITLE
Wrong behavior when creating a moment with timezone

### ISSUE THREAD

**Issue by Arashikage** [moment/moment-timezone#57]
According to the documents:

``` JavaScript
moment.tz("2013-11-18 11:55", "America/Toronto").format(); // "2013-11-18T11:55:00-05:00"
```

But running this code in my browser with locale UTC +0100 gives me this

``` JavaScript
moment.tz("2013-11-18 11:55", "America/Toronto").format();
"2013-11-18T05:55:00-05:00"
```

seems to me that it first creates a new Moment with my systems locale and then change the timezone which does not provide the expected behavior. 

If however I use my own timezone it works as expected and I think that's what the author of the docs did.

**Comment by BrantApps** [comment]
Hey @timrwood - I have come across this thread having experienced a similar issue to that originally described here. I am running moment 2.9.0 and moment-timezone 0.2.5. When I parse times greater than 10.00hrs the the timezone I am applying to that moment is unexpectedly added/subtracted from the moment I am parsing. Here are my test cases;

````javascript
var assert = require("assert");
var dateUtils = require("../../app/util/dateUtils.js");

describe("dateUtils", function() {

		describe("#successfulTimeZoneAddition", function() {
			// Given.
			var testTime = "2014-09-11 11:44 PM EDT   4.92 feet  High Tide";
			var testTimeZoneId = "America/New_York";

			// When.
			var dateTime = dateUtils.convertDate(testTime, testTimeZoneId);

			// Then.
			it("The provided time should have a time zone added.", function(done) {
				 assert.deepEqual("2014-09-11T23:44:00-04:00", dateTime.format());

				 done();
			})
		})

		describe("#failingTimeZoneAddition", function() {
			// Given.
			var testTime = "2014-09-15  9:36 AM EDT   Sunrise";
			var testTimeZoneId = "America/New_York";

			// When.
			var dateTime = dateUtils.convertDate(testTime, testTimeZoneId);

			// Then.
			it("The provided time should have a time zone added.", function(done) {
				 assert.deepEqual("2014-09-15T09:36:00-04:00", dateTime.format());

				 done();
			})
		})
})
````

The ```dateUtils``` function is shown below - you can see it's a relatively simple ```moment("ISO Date", "tz")``` usage.

````javascript
var moment = require("moment-timezone");

var dateUtils = function dateUtils() {

	/**
	 * Format <code>YYYY-MM-DD hh:mm aa z</code> date format,
	 * for example, '2014-09-11  7:11 PM EDT'.
	 */
	var convertDate = function(dateString, tzId) {
		// 2011-07-21  7:36 PM
		var twentyFourHourTime = convertTo24Hour(dateString.substring(11, 19));
		var dateTime = dateString.substring(0, 10) + " " + twentyFourHourTime;
		var eventWithTz = moment.tz(dateTime, tzId);
		return eventWithTz;
	};


	function convertTo24Hour(time) {
	    var hours = parseInt(time.substr(0, 2));
	    if (time.indexOf("AM") != -1 && hours == 12) {
	        time = time.replace("12", "0");
	    }
	    
	    if (time.indexOf("PM") != -1 && hours < 12) {
	    	time = time.replace(hours, (hours + 12));
	    }

	    // Remove any white space.
	    time = time.replace(" ", "");

	    return time.replace(/(AM|PM)/, "");
	}


  	return {
  		convertDate: convertDate
	};
};

module.exports = dateUtils();
````

It appears that all times below 10.00am are affected by this unexpected behaviour. Should I raise a separate tracker for this?

**Comment by chandwer** [comment]
I am still having this issue where no matter what time zone I parse a date with the moment object is still created with my local time zone instead. I am using moment version 2.10.2 and moment-timezone version 0.3.0

**Comment by timrwood** [comment]
@BrantApps, I think this is probably a bug with `convertTo24Hour` returning `9:00` instead of `09:00`.

You could just use moment's parser to parse the time with something like this instead.

```js
var convertDate = function(dateString, tzId) {
    return moment.tz(dateString.substring(0, 19), 'YYYY-MM-DD h:mm A', tzId);
};
```

**Comment by andymcfee** [comment]
I am still running into this bug and I believe I'm using all the latest versions of the moment libraries:
```
    "moment": "~2.10.6",
    "moment-timezone": "~0.4.0"
```

Essentially, I was creating a moment from a string `var m = moment.tz('30/09/2015 10:00 am', 'Europe/Dublin')` and the output was "30/09/2015 11:00 am IST" instead of the expected output ""30/09/2015 10:00 am IST". 

As @dhilgarth pointed out, in Firefox, I got the expected output of "30/09/2015 10:00 am IST", but had the bug in Chrome.

I had to use the hack provided by @dhilgarth.

**Comment by mj1856** [comment]
@andymcfee - you don't need the hack. You simply need to provide a format string.  Moment only recognizes ISO8601 unless you tell it otherwise.  You'll notice your code throws a deprecation warning onto the console telling you it's reverting to the date constructor.

You should do:

````javascript
moment.tz('30/09/2015 10:00 am', 'DD/MM/YYYY h:mm a', 'Europe/Dublin')
```

Also note that the "output" at this state is a `moment` object, not a string.  You need to then call `format`, and provide the output format you'd like.

**Comment by andymcfee** [comment]
@mj1856 ah! That works.  I can't believe I didn't try that at any point in my battle with timezones.

**Comment by CareerFairPlus** [comment]
I'm noticing that when providing an array of format strings, the moment object is first created with UTC as the timezone and then shifted by the timezone provided.  So given this array of formats:
```
validTimeFormats:             [
            'YYYY-MM-DD HH:mm a', 'YYYY-MM-DD hh:mm a', 'YYYY-MM-DD H:mm a', 'YYYY-MM-DD h:mm a',
            'YYYY-MM-DD HH:m a', 'YYYY-MM-DD H:m a', 'YYYY-MM-DD hh:m a', 'YYYY-MM-DD h:m a', 'YYYY-MM-DD HH:mm A',
            'YYYY-MM-DD hh:mm A', 'YYYY-MM-DD H:mm A', 'YYYY-MM-DD h:mm A', 'YYYY-MM-DD HH:m A', 'YYYY-MM-DD H:m A',
            'YYYY-MM-DD hh:m A', 'YYYY-MM-DD h:m A', 'YYYY-MM-DD HH:mm', 'YYYY-MM-DD hh:mm', 'YYYY-MM-DD H:mm',
            'YYYY-MM-DD h:mm', 'YYYY-MM-DD HH:m', 'YYYY-MM-DD H:m', 'YYYY-MM-DD hh:m', 'YYYY-MM-DD h:m'
        ]
```
And this code:
```
moment.tz('2016-10-24 12:00 PM', _this.validTimeFormats, true, 'America/New_York');
```

results in this moment object: 
```
Mon Oct 24 2016 04:00:00 GMT-0400 (EDT)
```

**Comment by CareerFairPlus** [comment]
Sorry!  This is where Google led me.  I upgraded to the latest version of moment and moment-timezone and am not seeing the issue anymore.

**Comment by jainnitin2411** [comment]
If a date string passed to moment, moment assume it as locale date so convert date into local timezone and then create moment object. To avoid conversion into local timezone, valid ISO date string should have 'z' as suffix.
e.g. '2014-09-11T23:44:00z'
