### ISSUE TITLE
Newfoundland Time Zone Incorrect

### ISSUE THREAD

**Issue by Corona688** [moment/moment-timezone#571]
The Canadian island of Newfoundland lives in its own unique time-zone of UTC minus three-and-a-**half**.  Moment-timezone incorrectly links Newfoundland to Canada/Atlantic. 

his is a headache yes, but headaches are what Moment was built to solve.  Wouldn't it be nice to be compatible with - well - the planet?

**Comment by mj1856** [comment]
We pull our data from the [tz database](https://www.iana.org/time-zones), like everyone else.

There is no zone or link called `Newfoundland`.  There is however, `Canada/Newfoundland`, which is a link to `America/St_Johns`, which does indeed have an offset of UTC-03:30 in the winter and UTC-02:30 in the summer.

```js
moment.tz('2018-01-01', 'Canada/Newfoundland').format()  // "2018-01-01T00:00:00-03:30"
moment.tz('2018-07-01', 'Canada/Newfoundland').format()  // "2018-07-01T00:00:00-02:30"
```

If you are seeing something else, please provide a code example, and include `moment.version` and `moment.tz.version`.
