### ISSUE TITLE
moment-timezone prefers to declare itself as an amd style module

### ISSUE THREAD

**Issue by CharlesWall** [moment/moment-timezone#572]
Moment-timezone first checks to see if `define` is a `"function"` then checks to see if it is being declared in a module by checking for exports. This is not ideal. In situations (like mine) where your code ends up in a place where `window.define` is set and you are requiring moment-timezone as a node style dependency, the require returns an empty object and causes subsequent errors.

**Comment by CharlesWall** [comment]
I added a PR that fixes this issue. PR#573

**Comment by gilmoreorless** [comment]
I see from #573 that this was released in `0.5.18`.
