### ISSUE TITLE
Consider taking Luxon's approach

### ISSUE THREAD

**Issue by benmccann** [moment/moment-timezone#575]
This library is quite large to download. Luxon's approach is superior because it does not require packaging tzdb. Is it possible to take the same approach here?

**Comment by TJTorola** [comment]
There are some good thoughts on this in Luxon's documentation. https://moment.github.io/luxon/docs/manual/why.html

**Comment by mj1856** [comment]
If you want Luxon's approach, then use Luxon.  :)  I'd recommend it actually.
