### ISSUE TITLE
Unintentional behavior on specifying only hours or minutes?

### ISSUE THREAD

**Issue by acomagu** [moment/moment-timezone#578]
On specifying only `hours` or `minutes`, without `days` to `moment.tz` then it can return yesterday's date, it seems strange behavior for me, so my question is that is it correct behavior?

For example, at Feb 22, 00:30 AM:
```
> moment.tz({ h: 1 }, 'Asia/Tokyo')
moment.parseZone("2018-02-21T01:00:00.000+09:00")
```

It shows Feb 21, but I think it should be 22.

**Comment by gilmoreorless** [comment]
This is a bug, covered in more detail in #297
