### ISSUE TITLE
utcOffset function is not working at CentOS 7

### ISSUE THREAD

**Issue by KyouhyunHwang** [moment/moment-timezone#580]
I tested as below at Ubuntu 16 and CentOS 7.3 to get utc offset.

const moment = require('moment-timezone');
const timezoneName = moment.tz.guess();
const timezone = moment.tz.zone(timezoneName);
const now = Date.now();
console.log(timezone.utcOffset(now));

It worked well at Ubuntu.
But timezone.utcOffset(now) returned error at CentOS as below.

TypeError: timezone.utcOffset is not a function
    at Object.<anonymous> (/opt/pcn/test.js:8:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

And timezone.offset(now) worked well without any deprecation message.

**Comment by Matthijn** [comment]
Doesn't seem to work for me on Mac OS either. 

I literally copied and pasted this from the moment-timezone website

moment.tz.zone('America/Los_Angeles').utcOffset(1403465838805)

But the error is that the function utcOffset does not exist.

**Comment by gilmoreorless** [comment]
I'm closing off stale issues as they're very difficult to reproduce, and this project is now in maintenance-only mode. Try upgrading to the latest version of Moment Timezone, but feel free to open a new issue if this is still a problem.
