### ISSUE TITLE
timezone from America/Sao_Paulo

### ISSUE THREAD

**Issue by xDveGax** [moment/moment-timezone#583]
Hi all, i'm having a problem with the zone from Sao_Paulo.

If you see the example (http://jsfiddle.net/uq99udc9/3340/), when im loading with the moment-timezone-with-data-2010-2020.min.js the "z" return BRT or BRST, but with the new library if you load https://cdnjs.cloudflare.com/ajax/libs/moment-timezone/0.5.14/moment-timezone-with-data-2012-2022.min.js instead https://cdnjs.cloudflare.com/ajax/libs/moment-timezone/0.4.1/moment-timezone-with-data-2010-2020.min.js this will be return (-02) or (-03).

Thanks in advance.
Regards.

**Comment by Pyrolistical** [comment]
still an issue in 0.5.21

**Comment by uvuwolverine** [comment]
still and issue in 0.5.23 as well

**Comment by mj1856** [comment]
This is not an issue, but rather related to changes in the source data from IANA.  
https://github.com/eggert/tz/commit/c9e6ef07cc6f1062ddd032c96c5172f403c0058f

**Comment by mj1856** [comment]
TZDB 2017a release notes:

http://mm.icann.org/pipermail/tz-announce/2017-February/000045.html

> Switch to numeric time zone abbreviations for South America, as
> part of the ongoing project of removing invented abbreviations.
