### ISSUE TITLE
Can't format a literal Z

### ISSUE THREAD

**Issue by bhumin3i** [moment/moment-timezone#585]
i'm selecting :  date :  2018-03-11T15:00Z  // this format come with i'm selecting date and which is not changes because framework give me ISO 8601 Datetime Format: YYYY-MM-DDTHH:mmZ 

after convert 

moment('2018-03-11T15:00Z' ).format("YYYY-MM-DDTHH:mm");
output // 2018-03-11T21:00Z  
my time zone is IST

**my simple question is  :  how to convert 2018-03-11T16:00:00Z to  2018-03-11T16:00**

**Comment by ellenaua** [comment]
Hi @bhumin3i, I just tried 
```
moment('2018-03-11T15:00Z' ).format("YYYY-MM-DDTHH:mm");
``` 
and it returns `2018-03-11T17:00`

**Comment by mj1856** [comment]
If you want to leave it in UTC, just:

```js
moment.utc('2018-03-11T15:00Z' ).format("YYYY-MM-DDTHH:mm");
```
