### ISSUE TITLE
Antarctica/Casey time being different with timezone

### ISSUE THREAD

**Issue by Syncret** [moment/moment-timezone#586]
The Antarctica/Casey should be located at +8 timezone, however the result of momentjs is different with other +8 timezone areas.

Reference:
https://www.timeanddate.com/worldclock/antarctica/casey

**Comment by ellenaua** [comment]
Hi @Syncret, Antarctica/Casey has Daylight Saving Time changes, see calendar here https://www.timeanddate.com/time/zone/antarctica/casey. So, on some dates its timezone is +11.
