### ISSUE TITLE
method for determining nodejs vs browser fails when using ace-builds 1.3.2

### ISSUE THREAD

**Issue by brimimc** [moment/moment-timezone#592]
ace-builds just made an update which break the logic for determining if you should call require or not

https://github.com/ajaxorg/ace-builds/blob/f6d04a60793e887b507b4e33b7de075c78cd4e4f/src/theme-xcode.js

causes module.exports to be set

causing this error

Uncaught ReferenceError: require is not defined
    at moment-timezone-with-data.js?compile=false:1

**Comment by ellenaua** [comment]
@brimimc Is this still actual? I see that ace-builds fixed that already
https://github.com/ajaxorg/ace-builds/blob/master/src/theme-xcode.js#L91
