### ISSUE TITLE
Minified files in 0.5.15 release not updated

### ISSUE THREAD

**Issue by Schnark** [moment/moment-timezone#600]
The minified files `moment-timezone-0.5.15/builds/moment-timezone-with-data.min.js` and `moment-timezone-0.5.15/builds/moment-timezone-with-data-2012-2022.min.js` in the latest release still include the 2017c data, while their unminified counterparts are updated. So you probably just forgot to re-build the minified files before releasing the new version.
Also, now that we have 2018, shouldn't the year range be 2013 to 2023 rather than 2012-2022?

**Comment by ellenaua** [comment]
@Schnark - Just released 0.5.16 with two fixes. Minified files are up-to-date now. Thanks.
