### ISSUE TITLE
TimeZone change detector 

### ISSUE THREAD

**Issue by Sudalaiyandi** [moment/moment-timezone#603]
Our ionic browser application is running in Dubai timezone.If user change timezone in their system, how to detect that time zone is changed.Once user change timezone, need to give some message to them.Is it possible in ionic ?

**Comment by mj1856** [comment]
In general, this is out of scope for this library.

You could call `moment.tz.guess()` on some interval timer, but there is nothing built in for that, nor any event that is guaranteed to fire when the user changes their time zone.

Also note that not all browsers will pick up a time zone change immediately.  Some (especially older versions) will not see the change until the browser is restarted.
