### ISSUE TITLE
trying to call moment.tz(TIMESTAMPE, TZ); fails

### ISSUE THREAD

**Issue by elad2109** [moment/moment-timezone#605]
I followed the documentation and try to run similar code to this

    var c = moment.tz(1403454068850, "America/Toronto");

but when I run it, the moment-tz seems to parse the first arg as a tz name.

How should i use this differently in my code:

    return function(milliSeconds, timeZoneId) {
        if (milliSeconds == 0) {
            return "";
        }
        var now = moment();

        return now.tz(milliSeconds, timeZoneId).format('MMM d, y H:mm:ss z');  // 5am PDT
..

for example with this input:

    milliSeconds = "112343243"
    
    timezoneId = "GMT-08:00"

it fails for:

	function normalizeName (name) {
		return (name || '').toLowerCase().replace(/\//g, '_');
	}

as:

    angular.js:14700 TypeError: (name || "").toLowerCase is not a function
        at normalizeName (moment-timezone.js:375)

**Comment by ellenaua** [comment]
Hi @elad! A couple of comments: 
1) `GMT-08:00` is not a valid timeZoneId. This is a time offset. Multiple timezones can be in this time offset - `Pacific/Pitcairn` or `America/Los_Angeles`.
You can add there this check
```
if (moment.tz.zone(timeZoneId) === null) {
    throw new Error("Unknown time zone ID: " + timeZoneId);
}
```
2) You should change this code 
```
var now = moment();
return now.tz(milliSeconds, timeZoneId).format('MMM D, Y H:mm:ss z'); 
```
to this
```
return moment.tz(milliSeconds, timeZoneId).format('MMM D, Y H:mm:ss z'); 
```
3) Minor: format should use uppercase D and Y - `MMM D, Y H:mm:ss z`

I agree that moment-timezone error messages should explain more clearly what went wrong!

**Comment by elad** [comment]
Hey @ellenaua, you mentioned the wrong username, and it took me a moment (no pun intended) to realize because I [contributed](https://github.com/moment/moment-timezone/pull/152) to this project in the past! :)

**Comment by mam-ijinus** [comment]
the same error here with:

import moment from "moment-timezone";
...
moment.tz(new Date().getTime(), "Europe/Paris").format()

=> Uncaught TypeError: (name || "").toLowerCase is not a function
