### ISSUE TITLE
Feature request: creating a Date object adjusted for timezone information.

### ISSUE THREAD

**Issue by timothyarmes** [moment/moment-timezone#606]
When converting a `moment` to a `Date` the timezone information in stripped. This is generally sensible, since we wish to have the actual date. When we need to display a `moment` in a given timezone, we use `moment`'s formatting features.

However, we are sometimes forced to pass a Date object, **for display purposes**, to another library that isn't `moment`-aware. In my case I'm using react-intl. I therefore need to create a date object that is adjusted for the timezone that I wish to display.

I think that this feature should be provided by this module. Currently I do this myself:

```
// `moment` objects contain timezone information that gets stripped away when converting them to a `Date`.
// For this reason, `moment` objects should be formatted directly. If then are converted to a date first
// then they'll be displayed for the user's local timezone.
//
// However, we sometimes have to pass a Date object for display (such as we do for react-intl. So,
// for display purposes *only* this function will create a Date object based on the current moment,
// taking into account the timezone information.

export function toDisplayableDate(m) {
  return new Date(m.year(), m.month(), m.date(), m.hours(), m.minutes(), m.seconds(), m.milliseconds());
}
```

**Comment by gilmoreorless** [comment]
With this project now in maintenance-only mode, it's unlikely that this feature will be added.
