### ISSUE TITLE
Browser: Chrome: Uncaught TypeError: Cannot read property 'version' of undefined

### ISSUE THREAD

**Issue by starrychloe** [moment/moment-timezone#607]
Cannot use this library in the browser. It gives an error. 

JSFiddle: https://jsfiddle.net/rjvaz0or/ (use F12 to see the error in console)

![image](https://user-images.githubusercontent.com/1039276/39437327-80dc75e2-4c6e-11e8-8fea-906dbffb4654.png)

http://momentjs.com/timezone/docs/#/use-it/browser/

**Comment by ellenaua** [comment]
Hi @starrychloe, in browser you should also import moment.js before importing moment-timezone.js. It's reflected in docs https://momentjs.com/timezone/docs/#/use-it/browser/ so your imports should be: 
```
<script src="https://momentjs.com/downloads/moment.min.js"></script>
<script src="https://momentjs.com/downloads/moment-timezone.min.js"></script>
```
or 
```
<script src="https://momentjs.com/downloads/moment.min.js"></script>
<script src="https://momentjs.com/downloads/moment-timezone-with-data-2012-2022.min.js"></script>
```
(I think you need moment-timezone-with-data)
