### ISSUE TITLE
Ignore builds directory

### ISSUE THREAD

**Issue by jehy** [moment/moment-timezone#609]
I know that there was PR https://github.com/moment/moment-timezone/pull/237 but I don't think that it is really necessary in 2018 - everyone uses bundling tools which do pretty same things and may work even better then current optimizations.

If you remove /builds, module will be 460KB lighter, which can seem a small number, but with million weekly installations it is already 460GB worldwide weekly...

**Comment by gilmoreorless** [comment]
> everyone uses bundling tools

Absolute statements like that are rarely correct. When changes were previously made to the pre-built ranged files there were many complaints about broken workflows.
