### ISSUE TITLE
Suggest: Change the pyongyang timezone

### ISSUE THREAD

**Issue by JungWinter** [moment/moment-timezone#611]
Until `2018-05-04T23:59:59+09:00`, Pyongyang timezone is set **UTC+08:30**. But it's changed to **UTC+09:00** after `2018-05-05T00:00:00+09:00`. So I suggest changing [`zones/asia/pyongyang.js` code](https://github.com/moment/moment-timezone/blob/11df2a83eeb75b995e30255acc4b9c59c2fbbaa3/tests/zones/asia/pyongyang.js).

## Reference
- [North Korea Turns Its Clocks to Align with South](https://www.timeanddate.com/news/time/north-korea-aligns-with-south.html)

**Comment by ellenaua** [comment]
Thanks! A new release will be coming soon, with this change.

**Comment by ellenaua** [comment]
@JungWinter moment-timezone 0.5.17 is released, this change is there
