### ISSUE TITLE
Issue converting a local datetime (in 1968) to UTC

### ISSUE THREAD

**Issue by luisjotapepe** [moment/moment-timezone#615]
We started getting issues when converting the date 1968-06-17T00:00:00 to UTC. Our location correlates to Americas/Edmonton. As per the link https://www.timeanddate.com/time/change/canada/edmonton?year=1968, MST wast kept all year around.

Our code is as follows:
`return moment(new Date('1968-06-17T00:00:00')).utc().format('YYYY-MM-DD[T]HH:mm:ss[Z]');`

This outputs 1968-06-17T06:00:00Z which is incorrect. The correct output should be 1968-06-17T07:00:00Z

We also added to the test case the following which failed as well.
```
"1968" : helpers.makeTestYear("America/Edmonton", [
        ["1967-04-30T08:59:59+00:00", "01:59:59", "MST", 420],
        ["1967-04-30T09:00:00+00:00", "02:00:00", "MST", 420],
        ["1967-10-29T07:59:59+00:00", "00:59:59", "MST", 420],
        ["1967-10-29T08:00:00+00:00", "01:00:00", "MST", 420]
    ]),
```

This is also shown by  worldtimebuddy.com
<img width="1114" alt="screen shot 2018-05-11 at 4 31 23 pm" src="https://user-images.githubusercontent.com/1677063/39949588-ece7ff86-5538-11e8-90db-701d7cd9e368.png">

**Comment by ellenaua** [comment]
Hi @luisjotapepe! I tried to debug it and this is what I found:

1) Pls notice `1967` in tests you provided. If you change `1967` to `1968`, tests pass
```
"1968" : helpers.makeTestYear("America/Edmonton", [
        ["1967-04-30T08:59:59+00:00", "01:59:59", "MST", 420],
        ["1967-04-30T09:00:00+00:00", "02:00:00", "MST", 420],
        ["1967-10-29T07:59:59+00:00", "00:59:59", "MST", 420],
        ["1967-10-29T08:00:00+00:00", "01:00:00", "MST", 420]
    ]),
```
2) In this piece of code, moment-timezone library is not participating. 
It's only `moment` being used here
```
return moment(new Date('1968-06-17T00:00:00')).utc().format('YYYY-MM-DD[T]HH:mm:ss[Z]');
```
and - as I understand - it's a bug not in `moment` but in JavaScript engine because this ```new Date('1968-06-17T00:00:00Z').toString()``` returns  ```Sun Jun 16 1968 18:00:00 GMT-0600 (MDT)``` which is wrong.

3) All these lines below return `Sun Jun 16 1968 17:00:00 GMT-0700` - as expected - because `moment-timezone` sets correct offset -07:00
```
console.log(moment('1968-06-17T00:00:00Z').tz('America/Edmonton').toString());
console.log(moment(new Date('1968-06-17T00:00:00Z')).tz('America/Edmonton').toString());
console.log(moment.tz('1968-06-17T00:00:00Z', 'America/Edmonton').toString());
```

**Comment by ellenaua** [comment]
@luisjotapepe I recommend you to use this:
```
moment.tz('1968-06-17T00:00:00', 'America/Edmonton').utc().format('YYYY-MM-DD[T]HH:mm:ss[Z]');
```
this way you 
- specify that `1968-06-17T00:00:00` belongs to 'America/Edmonton'
- use moment.tz() which sets correct offset

**Comment by ellenaua** [comment]
I found this issue discussion - _timezone offset is incorrect for the past/future date for a timezone whose offset has changed over time_  https://bugs.chromium.org/p/v8/issues/detail?id=3547
