### ISSUE TITLE
moment-timezone returns wrong formatted string in version 0.5.17

### ISSUE THREAD

**Issue by LeoPapais** [moment/moment-timezone#618]
Hello,

A recent update broke ".format" method in summer time.

Exemple:

``` javascript
const moment = require('moment-timezone')
moment.tz.setDefault('America/Sao_Paulo')
const timestamp = 1540555200000.0
moment(timestamp).format('HH:mm') // version 0.5.14 returns '10:00' correctly
moment(timestamp).format('HH:mm') // version 0.5.17 returns '09:00' wrongly
```
Can you check it out? This timestamp is in Brazillian Summer Time, if it helps.

Thank you.

**Comment by ellenaua** [comment]
Hi @LeoPapais 
Brazil's DST will now start on November's first Sunday.
Timestamp you provided is a timestamp of `2018-10-26T12:00:00.000Z`.
Moment-timezone `0.5.14` used older database (`iana2017c`) in which DST change in Sao Paolo in 2018 was supposed to happen on `2018-10-21`. 
Moment-timezone `0.5.17` is using newer database (`iana2018e`) in which DST change in Sao Paolo in 2018 is supposed to happen on `2018-11-04` (and it's correct).

**Comment by LeoPapais** [comment]
Hello,

Thank you! And I'm sorry for taking your time!
