### ISSUE TITLE
Travis CI build failing

### ISSUE THREAD

**Issue by aadityakulkarni** [moment/moment-timezone#624]
It looks like Travis CI build is failing. I have seen a couple of pull requests where build failed for the same error as below: 

`1.26s$ npm test
> moment-timezone@0.5.17 test /home/travis/build/moment/moment-timezone
> grunt
/home/travis/build/moment/moment-timezone/node_modules/grunt/node_modules/grunt-legacy-log/node_modules/grunt-legacy-log-utils/node_modules/chalk/index.js:2
const escapeStringRegexp = require('escape-string-regexp');
^^^^^
SyntaxError: Use of const in strict mode.`

Following is the link to my PR where the build failed: 
[Travis build](https://travis-ci.org/moment/moment-timezone/builds/388401187?utm_source=github_status&utm_medium=notification)

Can someone take a look and help me with this?

**Comment by ellenaua** [comment]
@aadityakulkarni just use `var` there instead of `const`

**Comment by aadityakulkarni** [comment]
Hi @ellenaua - Actually it's not me. It seems grunt uses npm package "chalk" which uses const instead of var and that is causing the build to fail. 

`/home/travis/build/moment/moment-timezone/node_modules/grunt/node_modules/grunt-legacy-log/node_modules/grunt-legacy-log-utils/node_modules/chalk/index.js:2
const escapeStringRegexp = require('escape-string-regexp');
^^^^^
SyntaxError: Use of const in strict mode.`

The following PR and its corresponding build also had the same issue: 

PR: https://github.com/moment/moment-timezone/pull/622
Travis CI: https://travis-ci.org/moment/moment-timezone/builds/388735890?utm_source=github_status&utm_medium=notification

**Comment by gilmoreorless** [comment]
Fixed in #1002
