### ISSUE TITLE
moment.tz giving wrong values

### ISSUE THREAD

**Issue by ravisuryawanshi18** [moment/moment-timezone#627]
If I pass one date to different time zone, I am getting wrong values.

**console.log(momentTimeZone.tz('2018-06-11T14:12:43', 'America/Mexico_City')); //1528744363000
console.log(momentTimeZone.tz('2018-06-11T14:12:43', 'America/New_York'));//1528740763000 console.log(momentTimeZone.tz('2018-06-11T14:12:43', 'America/Los_Angeles'));//1528751563000**

If I convert above milliseconds into Date.
**new Date(1528744363000);//Mexico->Tue Jun 12 2018 00:42:43 GMT+0530 (India Standard Time)
new Date(1528740763000);//New York->Mon Jun 11 2018 23:42:43 GMT+0530 (India Standard Time)
new Date(1528751563000);//Los_Angeles->Tue Jun 12 2018 02:42:43 GMT+0530 (India Standard Time)**

As you I am getting wrong values.
**1. As we all know,New York is 1 hours ahead of Mexico but new Date showing New York is 1 hr behind.
2.. As we all know,Los Angeles is 2 hours behind of Mexico but new Date showing Log Angeles is 2 hr ahead.**

Can any one help?

**Comment by ellenaua** [comment]
@ravisuryawanshi18 as I see, you use moment-timezone in invalid way.
Please show how do you create `momentTimeZone` variable?
Is it created this way? 
```
const momentTimeZone = require('moment-timezone');
```

**Comment by ellenaua** [comment]
New York is 1 hour ahead of Mexico, so:
- when it's 14:12:43 in New York, it's 13:12:43 in Mexico, and 23:42:43 in India
- when it's 14:12:43 in Mexico, it's 15:12:43 in New York, and 00:42:43 in India
- when it's 14:12:43 in Los Angeles, it's 17:12:43 in New York, and 02:42:43 in India
so your code is correct.

see here https://www.worldtimebuddy.com/?qm=1&lid=3530597,30,5128581,5368361&h=3530597&date=2018-6-17&sln=14-14.12
