### ISSUE TITLE
Missing version on GitHub? (Compare to npm registry)

### ISSUE THREAD

**Issue by PeterDaveHello** [moment/moment-timezone#631]
I found that v0.5.18/0.5.19 were released on npm registry, but it's still v0.5.17 on GitHub, something is missing?

Thanks!

**Comment by rpellerin** [comment]
https://github.com/moment/moment-timezone/blob/develop/package.json
![image](https://user-images.githubusercontent.com/5323445/41527026-31b97ca0-72e6-11e8-8e6a-3be9e6695e2e.png)

**Comment by PeterDaveHello** [comment]
Not tagged or released here: https://github.com/moment/moment-timezone/releases
