### ISSUE TITLE
Undocumented BC (Return error if timezone name is not a string)

### ISSUE THREAD

**Issue by znarf** [moment/moment-timezone#634]
I think this commit could have been marked as a breaking change: https://github.com/moment/moment-timezone/commit/02a4a9e296ef6cbfbaebad13629c56f89a6e2583

It was not documented as it in the changelog and the package didn't got a major version number update. For sure, passing a `null` or `undefined` timezone was never supported, but it's important that error handling remains stable in minor versions.

It's effectively breaking our app when upgrading from `moment-timezone@0.5.17` to `moment-timezone@0.5.20`.  No worries, this was fortunately caught by our CI, https://github.com/opencollective/frontend/pull/527

**Comment by awkaiser** [comment]
Yup, stumbled on same problem with an older application lacking a package lockfile.

This should be considered a breaking change.

**Comment by zmillman** [comment]
Ditto. Luckily caught this with testing before going to prod, but this change would mean we have to update all of our timezone-handling code to never pass non-string timezones or our app would start crashing.

**Comment by gilmoreorless** [comment]
This change was reverted in `0.5.21`.
