### ISSUE TITLE
Date information lost when calling display functions

### ISSUE THREAD

**Issue by danderson00** [moment/moment-timezone#635]
Version: 0.5.20
Repro:

```
moment("2018-06-13T07:30:00", 'Etc/GMT').toArray()
Array(7) [2018, 5, 1, 0, 0, 0, 0]

moment("2018-06-13T07:30:00", 'Etc/GMT').format()
"2018-06-01T00:00:00+10:00"

moment("2018-06-13T07:30:00", 'Etc/GMT').toDate()
Fri Jun 01 2018 00:00:00 GMT+1000 (AEST) {}

moment("2018-06-13T07:30:00", 'Etc/GMT')
Moment {_isAMomentObject: true, _i: "2018-06-13T07:30:00", _f: "Etc/GMT", _isUTC: false, _pf: Object, …}
_a:Array(7) [2018, 5, 1, …]
_d:Fri Jun 01 2018 00:00:00 GMT+1000 (AEST) {}
_f:"Etc/GMT"
_i:"2018-06-13T07:30:00"
_isAMomentObject:true
_isUTC:false
_isValid:true
_locale:Locale {_calendar: Object, _longDateFormat: Object, _invalidDate: "Invalid date", …}
_pf:Object {empty: false, unusedTokens: Array(0), unusedInput: Array(3), …}
_z:null
__proto__:Object {add: , calendar: , clone: , …}
```

This is not just a time shift issue - the day of the month is also reset to 1.

**Comment by ellenaua** [comment]
@danderson00 
But when I use moment.tz then everything is OK:

console.log(moment.tz("2018-06-13T07:30:00", 'Etc/GMT').toArray())
//Array(7) [ 2018, 5, 13, 7, 30, 0, 0 ]

console.log(moment.tz("2018-06-13T07:30:00", 'Etc/GMT').format())
//2018-06-13T07:30:00Z

console.log(moment.tz("2018-06-13T07:30:00", 'Etc/GMT').toDate())
// 2018-06-13T07:30:00.000Z

**Comment by danderson00** [comment]
Thanks for the clarification. This is extremely unintuitive. Are you sure this isn't a bug?
