### ISSUE TITLE
outbrpmin

### ISSUE THREAD

**Issue by douglasnoronha** [moment/moment-timezone#637]
Hello guys
I have a problem when I convert the time zone.
I'm using this function.

function formatTimeZone (data, timezone) {
     var d = moment.tz (date, "America / Sao_Paulo");
     return moment (d) .tz (timezone) .format (format);
};

On a client sometimes the time returned shows this way: outbrpmin

moment.js
//! version: 2.10.3
moment-timezone.js
//! version: 0.4.0

**Comment by ellenaua** [comment]
Could you pls use a newer version of moment-timezone?

**Comment by douglasnoronha** [comment]
I have already updated to the new version, until I verified that the browser was with the new version, but the problem continues.

**Comment by mj1856** [comment]
The code given is incomplete.  If you are still having this problem then please provide a complete repro.  Thanks.
