### ISSUE TITLE
moment-timezone v0.5.20, the NPM package is missing data/unpacked/latest.json

### ISSUE THREAD

**Issue by zrecore** [moment/moment-timezone#638]
Heads up, installing from NPM, the moment-timezone package (0.5.20) does not ship with the data/unpacked/latest.json file, even though it's shown in this git repo.

Edit: It appears v0.5.18 and v0.5.19 NPM packages are missing the unpacked latest.json data, too.

**Comment by ellenaua** [comment]
@zrecore it was done after this pull request
https://github.com/moment/moment-timezone/pull/610
do you use unpacked data?

**Comment by SeBassFox** [comment]
I'am also missing this file. I'am using that file in combination with filterLinkPack (moment-timezone-utils) to create a custom data file (restrict the years to get a smaller webpack build).
Would be helpful if this file can be available through npm.

**Comment by zrecore** [comment]
A client I worked with needed the unpacked data. They've since reworked their time zone data packer script to manually unpack the packed data and manually reassemble what they need.

**Comment by Tanner-Stults** [comment]
As far as I can tell, without the unpacked data subseting becomes more difficult, requiring the developers to unpack and unlink the data. While you can unpack the packed/latest.json file (like @zrecore mentioned) vai moment.tz.unpack, there doesn't seem to be a provided utility function to unlink the existing links in the packed latest.json file. Merely unpacking the provided packed/latest.json file isn't enough to recreated the unpacked version, you also have to unlink all of the links. Providing the unpacked file or a utility function that does the unlinking will allow devs to subset properly. 

For reference, this is how one might work around not having access to the unpacked data:
`
const packedLatest = require('moment-timezone/data/packed/latest.json');

function unpackAndUnlink(latest) {
    const unpacked = {
        ...latest,
        zones: latest.zones.map(moment.tz.unpack),
        links: []
    };

    latest.links.forEach(link => {
        const [ leadTzName, alias ] = link.split('|');
        const leadTzData = unpacked.zones.find(zone => zone.name === leadTzName);

        unpacked.zones.push({
            ...leadTzData,
            name: alias
        });
    });

    return unpacked;
}

const unpackedLatest = unpackAndUnlink(packedLatest);
`

Clearly, parsing through the link strings to unlink the existing links is not ideal, and could be provided by moment-timezone-utils.js. Perhaps there is a better way that I am missing.

**Comment by palashkaria** [comment]
Hey,
I'm facing this issue, & I need the original unpacked file, because we are not adding `countries` to zones while packing. This leads to loss of array order info when unpacking.
Please add this back if possible.

**Comment by gilmoreorless** [comment]
With the full 64-bit data range, the unpacked JSON file is at least 11MB in size. Given that some people aren't happy with a package size of just under 1MB (#999), I can't see the unpacked file being included any time soon.
