### ISSUE TITLE
Moment Timezone Works Locally, Not in Production

### ISSUE THREAD

**Issue by mackenzienolan** [moment/moment-timezone#639]
For some reason when testing locally the below code returns correctly, however on dev or prod it returns as GMT.

Locally
`moment().tz("America/Toronto").format() // 2018-06-22 00:00:00-04 `

Production
`moment().tz("America/Toronto").format() // 2018-06-22 00:00:00+00`

Does anyone know why this may be occurring?

**Comment by ellenaua** [comment]
@mackenzienolan check please:
- which version of moment-timezone is installed on prod
- what is the value of `moment().format()` (without timezone change)

**Comment by mackenzienolan** [comment]
Version: 0.5.14

*Locally*
`moment().format() // 2018-06-22 00:00:00-04`

*Production*
`moment().format() // 2018-06-22 00:00:00+00`

**Comment by mackenzienolan** [comment]
I have been able to get it where it prints out correctly, except that it changes the offset and the time.

`moment().startOf("day").tz("America/Toronto").format() // 2018-06-23 20:00:00-04`

I've created a hack for now, but if anyone knows what I'm doing wrong that would be extremely helpful.

**Comment by marneborn** [comment]
I'm having the same problem. I've tracked down my issue to using moment@0.5.13 but there is a dependency that is using moment@0.5.25. Both use the same moment@2.18.0.

So when the dependency is loaded moment.tz is changed to be the 0.5.25 version.
This causes things to not work.

To reproduce
```
mkdir moment-tz-problem
cd moment-tz-problem
npm init --force
yarn add moment-timezone@0.5.13
yarn add ical-generator@1.7.1
```
yarn list v1.9.4
├─ ical-generator@1.7.1
│  ├─ moment-timezone@^0.5.25
│  └─ moment-timezone@0.5.25
│     └─ moment@>= 2.9.0
├─ moment-timezone@0.5.13
│  └─ moment@>= 2.9.0
└─ moment@2.24.0
```

```
$ node -e "const moment = require('moment-timezone'); console.log(moment().tz('US/Eastern').format('z'));"
EDT
$ node -e "require('ical-generator'); const moment = require('moment-timezone'); console.log(moment().tz('US/Eastern').format('z'));"
UTC
```

**Comment by GORA-SAG** [comment]
For the same code segment 
`moment().tz('Asia/Kolkata').format('z')`
am getting IST locally but in prod getting UTC.

Am using version 0.5.28 any solution or workaround is available??

**Comment by gilmoreorless** [comment]
This looks like a potential problem with dependency chains, which is very hard to debug. I suggest following the advice at https://github.com/moment/moment-timezone/issues/982#issuecomment-1119540905 to resolve conflicts in dependency versions.
