### ISSUE TITLE
moment().toDate() is returns the Date with the system Time Zone

### ISSUE THREAD

**Issue by SathyaChenniappan** [moment/moment-timezone#644]
moment().toDate() is returns the Date with the system timezone.
Is there any other way to get date object with custom timezone.

**Comment by ellenaua** [comment]
```
moment().tz('America/New_York').toString()
```
will return you date & time for New York timezone
but .toDate() returns JavaScript Date object which has no timezone information and is always displayed in system timezone.

**Comment by SathyaChenniappan** [comment]
Thanks @ellenaua . I want to create a Date object with particular timezone is it possible?
Ex. 
  static Convert_UTCDate_To_LocalDate(utcTime: Date, localTimeZone: string) {
    if (utcTime == undefined) return;

    var utcMoment = moment(utcTime);    
    var localDateTime = utcMoment.tz(localTimeZone);

    return new Date(localDateTime.format('lll')); 
//returns java script date it contains system time zone not 'localTimeZone'
  }

**Comment by ellenaua** [comment]
It's impossible, JavaScript Date object does not store any timezone information (it contains unix timestamp inside, and when you call .getMinutes (), getHours (), toString () it uses system timezone). That's why moment-timezone was created: to have Date objects which also have timezone info.

**Comment by SathyaChenniappan** [comment]
Thanks for your time @ellenaua
