### ISSUE TITLE
Resolve an offset to a timezone name

### ISSUE THREAD

**Issue by tsheaff** [moment/moment-timezone#651]
Related to https://github.com/moment/moment-timezone/issues/371

I understand that, with Daylight Savings or other time-changing laws, a particular time zone does not have a stable offset over time. But if I just need to convert `+09:00` to a timezone name for the next few milliseconds while I respond to a single request, and I don't want to update all of my `moment().tz(timezone)` parsers, I'd love to be able to convert `+09:00` into a timezone name (e.g. `America/New_York`) that has that offset right now.

The naive approach of iterating through them all until I find one that matches would work, but wondering if there's a better way.

**Comment by tsheaff** [comment]
Or if there's an elegant way to extend moment-timezone's functionality to support parsing timezones with offset of style `-07:30` or `+09:00` (regex `[+|-]\d\d:\d\d`)

**Comment by tsheaff** [comment]
@ellenaua @timrwood any thoughts on this?

**Comment by nVitius** [comment]
@tsheaff What you're looking for can be accomplished using [`moment.utcOffset()`](http://momentjs.com/docs/#/manipulating/utc-offset/)

**Comment by tsheaff** [comment]
@nVitius can you clarify? I don't think that's sufficient. I need to go the other direction, from the offset (e.g. -7) to the name (e.g. `America/Los_Angeles`)

**Comment by nVitius** [comment]
Ah, okay. I didn't read your question right the first time. I thought you wanted to set a timezone on a date given just the offset.

I agree that this functionality would be useful though. Maybe something like `moment.tz.guess(moment())` could be implemented.

**Comment by tsheaff** [comment]
Yeah something like that. But `guess()` on the browser is implemented by changing the clock several times quickly. Almost all server systems I've used are just on UTC time and would not appreciate global clock changes.

**Comment by pedro-mass** [comment]
Wondering the same...The docs say there is a [zone object](https://momentjs.com/timezone/docs/#/zone-object/) that we shouldn't need to use, but maybe we could use that?

Not much documentation though, and the type files aren't showing anything either

**Comment by tsheaff** [comment]
By the way this is working for me (`timezoneOffset` is like `+05:00` or `-10:30` and declared in the outer scope)

```
_.find(moment.tz.names(), (timezoneName) => {
    return timezoneOffset === moment.tz(timezoneName).format('Z');
});
```

**Comment by prakis** [comment]
@tsheaff  That's a clean solution. Thanks for sharing.
