### ISSUE TITLE
Create config to use or not LMT

### ISSUE THREAD

**Issue by diogozanella** [moment/moment-timezone#659]
It would be interesting to be able to configure the library to use the LMT type or not.
In cases where only time records in the database are recorded with random dates, the LMT may generate some undesirable calculation differences.
This is the case of timezone "America / Sao_Paulo", which uses LMT 36.s when, in some cases, it would be better to use 30.

**Comment by gilmoreorless** [comment]
This isn't going to be supported, given Moment Timezone's current [maintenance-only status](https://momentjs.com/docs/#/-project-status/).
