### ISSUE TITLE
Moment returning day and time string as NaN

### ISSUE THREAD

**Issue by SachinSharmaEarthport** [moment/moment-timezone#660]
Hello,

I call the following method in my Angualr app.

`momentTimezone.tz('TUE 23:59', 'ddd HH:mm', 'Europe/Berlin'))`

This returns the result NaN.  This happens when the time is set as from 23:00 to 23:59 only.  The timezone used does not matter as this happens for other timezones as well.  I am using moment-timezone version 0.5.21.  Can you look into this please?

Kind Regards,

Sachin Sharma

**Comment by gilmoreorless** [comment]
I can't reproduce this with the latest `moment-timezone` version, or with `0.5.21`. If you have further details to reproduce the error, feel free reopen this issue.
