### ISSUE TITLE
moment.tz.guess() not using manual timezone on mobile devices

### ISSUE THREAD

**Issue by sam1463** [moment/moment-timezone#664]
I'm calling `moment.tz.guess(true)` to get the device timezone in a react-native app, and it seems to be returning the timezone the device is currently in, rather than the device that is being used by the mobile device (i.e. the manually set timezone of the device). I'm not sure if this is expected behavior or if this is a bug.

**Comment by jitenshah19** [comment]
I am facing similar issue. How did you fix it ?

**Comment by sam1463** [comment]
I used this library instead:

https://github.com/zoontek/react-native-localize#gettimezone

**Comment by gilmoreorless** [comment]
React Native problems can be hard to solve in a JS library that was built for browsers. It's probably best to use that package instead. 👍
