### ISSUE TITLE
Different output in local and production

### ISSUE THREAD

**Issue by Karneey** [moment/moment-timezone#665]
Note : Both local and production are on moment-timezone version **0.5.21**

```
var start_time = moment("6:30", "hh:mm").tz("America/Los_Angeles");
var end_time = moment("9:30", "hh:mm").tz("America/Los_Angeles");
console.log(start_time.format(), end_time.format());
```

> Local Output: "2018-08-06T06:30:00-07:00 2018-08-06T09:30:00-07:00"
> Production Output: "2018-08-05T23:30:00-07:00 2018-08-06T02:30:00-07:00"

The local output is what I expect. For some reason on production it is parsing the time in UTC first and then converting it to PDT.

**Comment by felipou** [comment]
When you create a moment object like this `moment("9:30", "hh:mm")`, is uses the current timezone of your operating system (which seems to be UTC). After that you are converting it to your desired timezone.

I'm guessing what you want is this: `moment.tz("9:30", "hh:mm", "America/Los_Angeles")`. This will parse the given time considering the timezone specified.
