### ISSUE TITLE
charCodeToInt returning the wrong value

### ISSUE THREAD

**Issue by msaetre** [moment/moment-timezone#673]
The method charCodeToInt in moment-timezone.js appears to be under the assumption that 'a' represents 10 in base60 rather than 'A' and is therefore returning the wrong value. The current method is:

`	function charCodeToInt(charCode) {
		if (charCode > 96) {
			return charCode - 87;
		} else if (charCode > 64) {
			return charCode - 29;
		}
		return charCode - 48;
	}`

When I think it should be:

`	function charCodeToInt(charCode) {
		if (charCode > 96) {
			return charCode - 61;
		} else if (charCode > 64) {
			return charCode - 55;
		}
		return charCode - 48;
	}`

**Comment by gilmoreorless** [comment]
Moment Timezone defines its own character set for encoding base60, so the code is fine: https://github.com/moment/moment-timezone/blob/a05c66832900e756425df8a0841cd830cff2c99e/moment-timezone-utils.js#L29
