### ISSUE TITLE
Library throws Invalid Date Error while parsing a valid date string.

### ISSUE THREAD

**Issue by asadshakeel101** [moment/moment-timezone#675]
I am trying to create a moment object using correct datetime string but when I try to format it it will throw Invalid Date error. However simple moment library is parsing it and give proper format. I am doing like following moment('2018-10-09T4:12:12').format('MMM DD h:mm A');

**Comment by gilmoreorless** [comment]
To properly match the ISO format, the hour value needs two digits.

```js
moment('2018-10-09T4:12:12').format('MMM DD h:mm A');
// "Invalid date"

moment('2018-10-09T04:12:12').format('MMM DD h:mm A');
// "Oct 09 4:12 AM" 
```

**Comment by asadshakeel101** [comment]
I figured it out a long ago. Thanks anyway.
