### ISSUE TITLE
Release 0.5.17 moment-timezone.min.js "TypeError: s is undefined"

### ISSUE THREAD

**Issue by jonfen** [moment/moment-timezone#678]
` [Show/hide message details.] TypeError: s is undefined[Learn More] moment-timezone.min.js:6:44
<anonymous>
http://localhost:5000/static/v1193/js/libs/moment-timezone.min.js:6:44
<anonymous>
http://localhost:5000/static/v1193/js/libs/moment-timezone.min.js:3:159
<anonymous>
http://localhost:5000/static/v1193/js/libs/moment-timezone.min.js:1:2`

**Comment by gilmoreorless** [comment]
This issue doesn't give enough detail to be able to debug the problem.
