### ISSUE TITLE
Time Doesn't Update Upon Changing Timezone and Upon Refresh in Firefox

### ISSUE THREAD

**Issue by nsahmed** [moment/moment-timezone#680]
We are using Moment library for our app. We have noticed that upon changing the Timezone and upon refresh, Moment library does not update as a result our app is not updating as well. Only after restarting Firefox, we see the time getting updated in both the Moment library and our app. (We are using Firefox version 62.0.3 and Moment version 2.21.0) 

Please note that in Chrome, Safari and Edge browser, the Moment library and our app is updating the time upon changing the timezone and upon refresh i.e. these browsers are showing the correct behavior.

**Comment by gilmoreorless** [comment]
This is Firefox's normal behaviour, there's nothing that can be done within Moment. There's an open Firefox issue to update the browser time zone at runtime: https://bugzilla.mozilla.org/show_bug.cgi?id=1343826

**Comment by gilmoreorless** [comment]
According to the linked bug, this has been fixed in Firefox 103.
