### ISSUE TITLE
Brazil DST date change

### ISSUE THREAD

**Issue by epimeth** [moment/moment-timezone#683]
Hi guys!

First of all, just wanted to say thank you for this great tool.  I have been using it for... well... forever.  It has been an absolute god-send.

However, we seem to have a problem.  Apparently, Brazil has decided to go cuckoo (again, apparently) and change their DST date.  It looks like IANA has updated their database (2018f) so if you would please package up the new one that we be really really great!

See [here](https://androidcommunity.com/brazils-dst-change-inadvertently-affects-millions-of-android-phones-20181022/) and [in portuguese](https://veja.abril.com.br/brasil/relogios-de-celulares-se-adiantam-mas-horario-de-verao-nao-comecou/)

Thanks again!

**Comment by chrisirhc** [comment]
Related to https://github.com/moment/moment-timezone/issues/672#issuecomment-432267665

**Comment by epimeth** [comment]
Actually, I don't think it is.  If 0.5.17 works then that issue was related to a different DST change than the one that was recently done.  I really think that all that needs doing is whatever conversion process you folks do with the IANA files to the JSON that is in the `data` folders for 2018f ... much like the update 6 months ago to 2018e

**Comment by aman123006** [comment]
@epimeth 
I think you got the issue right. 2018f was updated on Oct 18, 

Moment.js Please fix this asap. In meantime, what can be a workaround? Please suggest

**Comment by mariotsi** [comment]
The change has been cancelled by the government.

IANA reverted the change before 2018f and the Brazil DST change is not there https://github.com/eggert/tz/commit/580cd39fe23448de5113ecb869960b28dfa9894d

Redhat also closed the relative bug https://bugzilla.redhat.com/show_bug.cgi?id=1636163 
https://www.timeanddate.com/news/time/brazil-postpones-dst-2018.html

Media announcement (link in Portuguese):


https://g1.globo.com/politica/noticia/2018/10/15/planalto-informa-que-nao-havera-adiamento-e-que-horario-de-verao-comecara-no-proximo-dia-4.ghtml

**Comment by lfreneda** [comment]
@aman123006 moment-timezone 0.5.17 is working for me in production.

**Comment by mj1856** [comment]
Because Brazil backed out of the short-notice change, the only update that matters for Brazil is 2018a (release later with 2018c).  You don't need 2018f for Brazil.
