### ISSUE TITLE
Moment Timezone has no data for "America/New_York" in NodeJS AWS Lambda

### ISSUE THREAD

**Issue by khanh-nguyen** [moment/moment-timezone#686]
I have a lambda function written in NodeJS used for my alexa skill. I use `moment-timezone@0.5.21`.

```
const moment = require('moment-timezone');
...
const now = moment().tz('America/New_York');
```

According to [the doc](http://momentjs.com/timezone/docs/#/data-loading/), 

> In Node.js, all the data is preloaded. No additional code is needed for loading data.

However, I keep seeing this in the lambda log

> Moment Timezone has no data for "America/New_York". See http://momentjs.com/timezone/docs/#/data-loading/.

Although, everything seems to work just fine.

**Comment by rosemarystanley** [comment]
Same here. If I replace America/New_York with America/Los_Angeles I don't get the error.

**Comment by mj1856** [comment]
Sorry, I don't have any ideas about this.  I haven't done much with AWS Lambda.  Maybe there is a general issue with module loading in that environment that might apply?

Also, I assume this is you as well?
https://stackoverflow.com/questions/53588237/moment-timezone-cant-load-data-in-aws-lambda

That's fine - perhaps someone will answer there.

**Comment by mj1856** [comment]
Oh, and if this is a new application, you might want to try [Luxon](https://moment.github.io/luxon/) instead.  It has full time zone support, without needing a separate data file - as it takes it from the environment.

**Comment by khanh-nguyen** [comment]
Thanks for responding, @mj1856. This was red hearing. I just figured out the problem. 
Turned out in the actual code, I passed in the timezone code which is a string with escaped quotes. There's no problem with `moment-timezone` loading data in lambda.
I'll try out Luxon too.

Thanks,
