### ISSUE TITLE
Incorrect time transformation for specific timezone 

### ISSUE THREAD

**Issue by userbig** [moment/moment-timezone#688]
After DTS shift moment-timezone show incorrect time for my current time zone. Other timezones show correctly

`var time = '13/10/2018 19:18'`
var changetime =  moment(`${time} +00`, "DD/MM/YYYY HH:mm ZZ");
`changetime.tz(moment.tz.guess()).format('DD/MM/YYYY HH:mm')`
`"13/10/2018 22:18"  <--- supposed to be 21:18`
`moment.tz.guess()`
`"Europe/Kiev"`

**Comment by mj1856** [comment]
Thanks for reporting.  Please supply output of:
```js
console.log(moment.version);
console.log(moment.tz.version);
console.log(navigator.userAgent);
```

Also please let us know what your operating system time zone is set to.

Thanks.

**Comment by userbig** [comment]
```console.log(moment.version);
2.22.2
console.log(moment.tz.version);
0.5.23
console.log(navigator.userAgent);
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36```
Also, this happend only on locale dev server, on production all works fine.

**Comment by gilmoreorless** [comment]
The data for many zones has become more accurate in the past few releases. If this issue is still happening with the latest release, feel free to re-open the issue and we can try to diagnose the problem.
