### ISSUE TITLE
Wrong offset for timezone 'Europe/Volgograd' 

### ISSUE THREAD

**Issue by devdemi** [moment/moment-timezone#694]
There is wrong offset +3 for timezone 'Europe/Volgograd' but after 28.10 they changed offset to +4
https://time.is/ru/Volgograd

**Comment by mj1856** [comment]
This is already reflected in the latest version, 0.5.23, released yesterday.  Please upgrade.

```js
moment.tz.version // => "0.5.23"
moment.tz.dataVersion // => "2018g"
moment.tz('Europe/Volgograd').format() // => "2018-10-29T18:01:19+04:00"
```
