### ISSUE TITLE
How to add the datas for different timezone's like for 

### ISSUE THREAD

**Issue by siva-7112** [moment/moment-timezone#696]

**Comment by siva-7112** [comment]
For Los Angels i have added moment.tz.add('America/Los_Angeles|PST PDT|80 70|0101|1Lzm0 1zb0 Op0');
Like wise i have to add for New York,India,China and EU

**Comment by ichernev** [comment]
Well, it seems like you just did. You can check the docs and the grunt tasks that handle the tzdata pipeline, if you want to achieve something specil https://momentjs.com/timezone/docs/#/data-utilities/
