### ISSUE TITLE
New data file size.

### ISSUE THREAD

**Issue by RodionNikolaev** [moment/moment-timezone#697]
Why new data file so big?

Package| Minified|latest.json
-------|-------|-------
0.5.21 |407.8kB |176kB
0.5.23 | 1.1mB |903kB

**Comment by prantlf** [comment]
The new data are 8 times (!) greater. I think, that applications will demand other limited data sets, than the quite short 2012-2022. These numbers I measured with the pure JSON (packed) data. Showing not-minified sizes would be too scary ;-)

```
Full IANA TZ data:  923 KB minified, 33.3 KB gzipped
Data for 1000-2050: 203 kB minified, 24.9 gzipped
Data for 1650-2050: 203 kB minified, 24.9 gzipped
Data for 1900-2050: 200 KB minified, 23.3 KB gzipped
Data for 1970-2018: 106 KB minified, 13.1 KB gzipped
Data for 2012-2022:  27 KB minified,  6.5 KB gzipped
```

The huge difference between the full data amd 1000-2050 makes it difficult for me not to doubt, if the limited data are really correct. Isn't the `filterLinkPack` dropping some "good stuff"? ;-)

```js
const tz = require('./moment-timezone-utils')
const fullData = require('./data/unpacked/2018g.json')
const groupLeaders = require('./tasks/group-leaders.json')
const limitedData = tz.filterLinkPack(fullData, 1900, 2050, groupLeaders)
```

**Comment by sbrandwoo** [comment]
My biggest concern here is that the file size has frequently updated as a patch release and not a minor/major release. `0.5.13` was 190 KB and now  `0.5.23` is 1.4 MB, these are patch releases and you could expect any application to happily update to them - but this leads to a breaking change in the size of the resulting application.

**Comment by yurikuzn** [comment]
I use a script to build timezone data for custom ranges https://github.com/yurikuzn/moment-timezone-data-build

File size is 123KB for 1970 - 2030 range.

**Comment by Colkadome** [comment]
I have noticed a lot of the data (from the 'indices' and 'untils' arrays) has a lot of repeat data, so I've written a script that takes chunks of 'indices' and the 'untils' values and replaces them with indexes to an array of global values. I managed to reduce the main JSON file from 903K to 377K. I have included an example of reducing the file size, and at the bottom an example of decoding the values:

https://gist.github.com/Colkadome/7cd3c8111ba13f804908dcb6d06d2dab

This is just experimental, and will hopefully give some ideas.

**Comment by Colkadome** [comment]
I ended up filtering the dates in the range 1970 - 2030, then replacing the 'indices' and 'untils' data with indexes to an array of values (as a lot of that data is repeated):

https://gist.github.com/Colkadome/7cd3c8111ba13f804908dcb6d06d2dab

**Comment by mj1856** [comment]
I plan to publish a 1970-2030 file in the next release.  See comments in #614.  Thanks.

**Comment by mj1856** [comment]
This is completed in version 0.5.24.  Thanks.
