### ISSUE TITLE
Breaking change in 0.5.23

### ISSUE THREAD

**Issue by leider** [moment/moment-timezone#699]
Since 0.5.23 there is breaking behaviour compared to 0.5.21:

```
var moment = require('moment-timezone');
var result = moment.tz('2.8.2113' + ' ' + '3:04', 'D.M.YYYY H:m', 'Europe/Berlin');
console.log('Actual "0.5.23" is: ' + result.format());
console.log('Actual "0.5.21" was: ' + '2113-08-02T03:04:00+01:00');
```

The first line now returns `2113-08-02T03:04:00+02:00`

**Comment by mj1856** [comment]
You're asking what the time in Berlin will be 95 years in the future?  Nobody can tell you that!

**Comment by mj1856** [comment]
To clarify - time zone rules are set by governments.  The data changes all the time.  `Europe/Berlin` alternates between UTC+1 for standard time and UTC+2 for summer time.

Indeed, by the current rule, UTC+2 would be correct for a date in August.  There's no guarantee that rule won't change though.

If anything, I'm surprised that we bother projecting the rule so far forward.

**Comment by leider** [comment]
Hi, thanks for the quick answer. You're completely right in that I cannot know what politics will decide to be the timezone in the future.

My issue was about changing behaviour of the library in a minor update without even documenting that in the release notes.

It is completely okay if you have a documented statement telling that the timezone resolution may change from one version to the other. But, afaik this is not the case.

One simple question: Do you acknowledge the fact that there is a change in the behaviour?

Would be glad if you see my point.

**Comment by mj1856** [comment]
Somewhat agree with you.  Though note that although moment-timezone is popular, it's 0.x for a reason.

Personally, I would recommend using Luxon for new projects.  Its time zone support is taken from the browser directly, which wasn't possible when moment-timezone was originally created.
