### ISSUE TITLE
Timezone Offset

### ISSUE THREAD

**Issue by cptolemy** [moment/moment-timezone#700]
Hi,

I'm having a proble regarding a date, in the America/Chicago Timezone, at Lubock Texas (US). For the date May 30 1965, 8 am, I'm getting a time zone offset of -5 hours regarding UTC (GMT). Here is the code:

`var tz = "America/Chicago";
var zone = moment.tz.zone(tz);
var off = zone.parse(Date.UTC(1965,5,30,8,0,0,0)); //result: 300

or

var sec = Date.UTC(1965,5,30,8,0,0,0);
var z = moment.tz.zone(tz).utcOffset(sec); //result 300`

Also tryed with the month equal to 4.
Apparently, with dst and all, the offset should be of 6 hours (360)

Can you verify?

Kind regards

**Comment by macqbat** [comment]
Two timezones have probably incorrect utcOffset() result:

```javascript

moment().tz('Africa/El_Aaiun').utcOffset() // gives 60 should be 0
moment().tz('Africa/Casablanca').utcOffset() // gives 60 should be 0

```
Could anybody looks at it soon? We have redness in tests :-(

**Comment by mj1856** [comment]
`America/Chicago` is for US Central time, which it UTC-6 during *standard time* and UTC-5 during *daylight time*.  The code is giving the correct result.
