### ISSUE TITLE
May I ask what components are used in your world map?

### ISSUE THREAD

**Issue by q869939686** [moment/moment-timezone#702]
![image](https://user-images.githubusercontent.com/29123332/48815743-7d5f7100-ed7a-11e8-96aa-f9acb06ae46c.png)
May I ask what components are used in your world map?

**Comment by mj1856** [comment]
The source repo for the docs site is here: https://github.com/moment/momentjs.com

The world map is not a component we offer, but rather just a pretty thing to show off the time zone data.
