### ISSUE TITLE
Missing configs for certain timezones (Europe/Berlin,....)

### ISSUE THREAD

**Issue by kurtt** [moment/moment-timezone#704]
Is it possible that for certain timezones (Europe/Berlin, Europe/Brussels), an entry in the links array of 
moment-timezone/data/packed/latest.json is missing ? Hence, I can't use those timezones.

**Comment by mj1856** [comment]
![image](https://user-images.githubusercontent.com/1396388/49306837-3bc07b80-f488-11e8-8f19-636d5ee9a621.png)

Seems to be working fine for me.  They're in the zone entries:

[Europe/Berlin](https://github.com/moment/moment-timezone/blob/0.5.23/data/packed/latest.json#L306)

[Europe/Brussels](https://github.com/moment/moment-timezone/blob/0.5.23/data/packed/latest.json#L308)
