### ISSUE TITLE
Issue creating date with timezone.

### ISSUE THREAD

**Issue by MrMagnificent** [moment/moment-timezone#705]
When creating a date with a time zone if the month and/or day is not in the 2 character format (YYYY-MM-DD) and is instead just a single character (YYYY-M-D) like "2018-3-1", the date is created and correct but it is then converted to the time zone rather than created with the time zone.
For instance: 
moment.tz("2018-3-18 11:55", "America/Chicago"); 
returns 2018-03-18T06:55:00-05:00.
but 
moment.tz("2018-03-18 11:55", "America/Chicago"); 
returns 2018-03-18T11:55:00-05:00.

**Comment by ichernev** [comment]
https://github.com/moment/moment-timezone/issues/707#issuecomment-1229227937
