### ISSUE TITLE
How can i use Moment Timezone in React

### ISSUE THREAD

**Issue by ashifa454** [moment/moment-timezone#706]

**Comment by ashifa454** [comment]
I have installed Moment and Moment-Timezone, but when i am importing in my project, there is an error 
![image](https://user-images.githubusercontent.com/13622867/49724688-c0489200-fc1e-11e8-9bbc-2c92fe7e7ad0.png)
![image](https://user-images.githubusercontent.com/13622867/49724801-0aca0e80-fc1f-11e8-9d9f-968f87b35f57.png)

**Comment by x-cold** [comment]
```js
import moment from 'moment-timezone/builds/moment-timezone-with-data';
```

**Comment by gilmoreorless** [comment]
You can also just use `import moment from 'moment-timezone';`

I've updated the docs to add some ES6 examples.
