### ISSUE TITLE
Parsing a timestamp with 12 hours format converts hour to UTC

### ISSUE THREAD

**Issue by boaz-amit** [moment/moment-timezone#707]
When parsing a timestamp that contains an hour in 12 hours format, the time value is converted to UTC while the rest of the timestamp is parsed according to the timezone argument.

For example (fiddle here: http://jsfiddle.net/cx1u0pv4/1/):
```
// 2018-12-15 09:00: 2018-12-15T09:00:00-05:00
moment.tz('2018-12-15 09:00'. 'America/New_York').format()

// 2018-12-15 9:00: 2018-12-15T04:00:00-05:00
moment.tz('2018-12-15 9:00'. 'America/New_York').format() 
```

Note how in the second call, the result is in the expected time difference `-05:00` but the time value has actually been interpreted as if it's in `+00:00`, in other words `04:00` instead of `09:00`.

Now, it's true that the time value is ambiguous as `moment` would have to either default to `AM` or `PM`, but defaulting to AM in UTC seems unexpected.

**Comment by ichernev** [comment]
Yes, because the first one is parsed by ISO regex, the other one is parsed by Date. Either pass the format of your string when parsing, or use ISO/RFC2822
