### ISSUE TITLE
Format Does not work correctly for 52 week years

### ISSUE THREAD

**Issue by billywhizz** [moment/moment-timezone#714]
We have come across an issue that seems to me would be best fixed inside the moment-timezone or the moment library rather than end users having to implement their own logic to handle it.

Is related to this issue: https://stackoverflow.com/questions/25631682/moment-js-thinks-that-2013-12-31-is-week-1-not-week-53

Here is a gist that shows what happens when we do .format('YYYY-w') when current date is in previous year but the week ends in the following year and the previous year is a 52 week year: https://gist.github.com/billywhizz/1b5affc4b3d915039c03f510b0a04e8b

I think it would be more correct if the library return "2019-01" when operating on 2018-12-31. In this case it currently returns '2018-01' which is not correct. it rolls the week over from 52 to 1 but does not roll the year in same way.

**Comment by billywhizz** [comment]
If agress this is a bug let me know and i should be able to put together a PR to fix.

**Comment by billywhizz** [comment]
FYI I have also uncovered another issue with moment library which is along the same lines. If you run this code:

**Comment by ichernev** [comment]
I think the "bug" is that you use `YYYY` with `w`. There is `GGGG` (iso week year) for this particular reason: https://momentjs.com/docs/#/displaying/format/
