### ISSUE TITLE
Update to tzdb 2018i

### ISSUE THREAD

**Issue by casper5822** [moment/moment-timezone#718]
Hello,
there is a new update for iana db (2018i). When  will this update be available in moment?

Thank you in advance for your work. It's a great lib.

**Comment by MGPalmer** [comment]
+1 ... been waiting for this. Our app uses timezones heavily and needs the definitions to be correct. Luckily, the last two IANA updates were not relevant to our users (yet).

Can we somehow help in expediating the release cycle?

**Comment by mj1856** [comment]
Will be adding this soon (along with the update for 2019a).   Thanks.

**Comment by mj1856** [comment]
This is completed in version 0.5.24.  Thanks.
