### ISSUE TITLE
BUG--> add months return wrong result when time zone set to Asia/Jerusalem

### ISSUE THREAD

**Issue by korengal** [moment/moment-timezone#724]
When a month has 31 days, the "add month" method returns the wrong result

For example:

1)Set moment time zone to "Asia/Jerusalem":
`moment.tz.setDefault('Asia/Jerusalem')`
2)check result for:
`moment('1994-03-01').add(1,'M').format('YYYY-MM-DD');`

The result is: "1994-03-31"
Need to be:  "1994-04-01"

Thanks.

**Comment by mathematicode** [comment]
This seems to work fine for me as I am getting "1994-04-01". I think this issue should be closed.

**Comment by ichernev** [comment]
This timezone has a DST jump forward on 00:00 on first of month:

```
Asia/Jerusalem  Thu Mar 31 21:59:59 1994 UT = Thu Mar 31 23:59:59 1994 IST isdst=0 gmtoff=7200
Asia/Jerusalem  Thu Mar 31 22:00:00 1994 UT = Fri Apr  1 01:00:00 1994 IDT isdst=1 gmtoff=10800
```

Still, it work for me for some reason but that could explain it :)
