### ISSUE TITLE
Diff between startOf('day') and endOf('day') is wrong the day the DST shift occurs

### ISSUE THREAD

**Issue by probablyup** [moment/moment-timezone#726]
March 10, 2019 is when DST starts for the USA.

```js
import moment from 'moment-timezone';

moment.tz.setDefault('America/Chicago');

let b = moment('3/10/2019', 'L').startOf('day');
let c = b.clone().endOf('day');

c.diff(b, 'hours'); // 22, should be 23
```

**Comment by ashsearle** [comment]
`endOf` sets an instance to the last millisecond of the period, meaning you're taking a diff between these two points in time:
2019-03-10T00:00:00.000-06:00
2019-03-10T23:59:59.999-05:00

[From the docs](https://momentjs.com/docs/#/i18n/):
> By default, moment#diff will truncate the result to zero decimal places, returning an integer

i.e. 22 hours 59 minutes 59 seconds and 999 milliseconds gets rounded down to 22 hours.

You should find replacing `c` with `b.clone().add(1, 'day')` gets you the answer you want.

**Comment by probablyup** [comment]
Interesting, thanks this does fix the issue for me.
