### ISSUE TITLE
moment().tz('timezone selected here') shows tomorrow's date

### ISSUE THREAD

**Issue by lynnchin** [moment/moment-timezone#730]
Hello,

 I am using the moment and moment-timezone library together here.

 I noticed there is something weird happening over here.
 
 What I tried to achieve is getting the current date and apply it with the timezone difference.

 e.g. moment() returns today's date, moment().tz('Australia/Melbourne') should return today's date with timezone applied

 However, I am getting the tomorrow's date with timezone applied.... e.g. moment().tz('Australia/Melbourne') now returns tomorrow's date

PS: moment() returns today's date. (Which is correct)

 I would like to know if anyone has similar issue as well. If so, how did you guys resolve this problem?

**Comment by mj1856** [comment]
The idea of "today" is not the same all over the world at the same time.  The visualization at https://everytimezone.com/ does a good job at showing this effect.

- `moment()` returns "now" in a Moment object in local mode
- `moment().tz('Australia/Melbourne')` converts that local object to the given time zone for the same simultaneous point in time.  They may indeed be on different dates.
- `moment.tz('Australia/Melbourne')` is the preferred shorthand, as it eliminates the conversion step.
