### ISSUE TITLE
moveAmbiguousForward / moveInvalidForward  issue in NodeJS for DST case

### ISSUE THREAD

**Issue by ghost** [moment/moment-timezone#731]
I am on NodeJs using moment-timezone 0.5.23 ie latest version right now. I have verified the below code in both GMT+5 and UTC0. 
I have also tried to set property ```moveAmbiguousForward``` and ```moveInvalidForward``` but it won't effect the result. can your team please help me out ?
FYI: the code below is an example when DST is going to apply on US ie on 10th March 2:00 AM
```
var date = moment('2019-03-10').tz("America/Anchorage").startOf('day').add(1,'d') // "2019-03-10T00:00:00-09:00"
date.hours(2,'h').format() // "2019-03-10T01:00:00-09:00"
// required : "2019-03-10T03:00:00-08:00"
```

thanks in advance

**Comment by ichernev** [comment]
hm, I can't reproduce this on latest (0.5.37), it might have been fixed ;-)
