### ISSUE TITLE
Convert deprecated timezones to supported ones?

### ISSUE THREAD

**Issue by RobertGary1** [moment/moment-timezone#734]
Given "US/Pacific" how can I programmatic convert to supported "US/Los_Angeles"? I see in the code there are links that point to the correct timezone but I"m not sure if I should be accessing _underscore functions.

**Comment by RobertGary1** [comment]
For better or worse I'm doing this and it seems to work. I have devices that report their timezones in deprecated names and JavaScript just errors out so I have to convert them. Note that I had to use internal interfaces of moment-timezone to access this data...

      const tzKey = Object.keys(momentTime.tz._names).filter(key => (momentTime.tz._names[key] === getDeviceTz()));
      const tzAlternative = tzKey ? momentTime.tz._links[tzKey] : undefined;

      const newTz = tzAlternative ? momentTime.tz._names[tzAlternative] : undefined;

**Comment by mj1856** [comment]
Unfortunately, moment-timezone does not currently provide this functionality.  All zones with the same data are considered equal when moment-timezone derives its "links".  They aren't the same as the links in the tzdb.
