### ISSUE TITLE
Timezone off for "America/Phoenix" 

### ISSUE THREAD

**Issue by kmkingdon** [moment/moment-timezone#735]
I noticed this bug when working with a client in Phoenix. I was using moment-timezone to return the timezone abbreviation. 

Date: 3/21/2019

Code: 
moment.tz("America/Phoenix").format('z');
//MST

Daylight savings time has already occurred in the USA at this point and Phoenix is now on Pacific time. Did I miss something in my implementation or is this a bug?

**Comment by pstjean** [comment]
Most of Arizona (including Phoenix) does not observe Daylight Savings Time: https://www.transportation.gov/regulations/daylight-saving-time

**Comment by chrisbrownnwyc** [comment]
If anyone comes across this trying to figure out why time is off in Arizona, check if your user is on an Amazon-based device (Kindle, FireHD, etc.).  There's a bug in some versions of their browser that sends America/Denver for people in Arizona giving them DST when they shouldn't have it.  This took me forever to figure out so hopefully, this helps someone else!
