### ISSUE TITLE
upgrade to iana tz2019a?

### ISSUE THREAD

**Issue by casper5822** [moment/moment-timezone#737]
Hello, a new version of tz iana db is available.
Does moment and moment-timezone will be updated?

Best regards

**Comment by mj1856** [comment]
Yes.  I mean to do this soon.  Thanks.

**Comment by mj1856** [comment]
This is completed in version 0.5.24.  Thanks.

**Comment by mj1856** [comment]
Actually, be sure to take 0.5.25.  See #742
