### ISSUE TITLE
`moment.local()` fails to clear the timezone

### ISSUE THREAD

**Issue by thefliik** [moment/moment-timezone#738]
Similar to issue #86, a call to `momentDate.local()` fails to clear the timezone associated with `momentDate.tz()`.

At the, *ahem*, moment, the only (supported) way I've found to clear the timezone is to use both `momentdate.utc()` and `momentDate.local()`. The first call clears the timezone and the second sets the moment to local time. I.e. `momentDate.utc().local()`

**Comment by mj1856** [comment]
Agreed that `_z` should be cleared when `.local()` is called, but it shouldn't have any effect if it doesn't since local mode functions don't use `_z`.  Can you give an example where it matters?

**Comment by thefliik** [comment]
I'm working from memory at the moment, but I believe that currently, `moment-timezone` exhibits the following, undesired behavior:

```typescript
const date = moment.tz('America/Los_Angeles');
date.tz() // => 'America/Los_Angeles'
date.local()
date.tz() // => 'America/Los_Angeles'
```

The following is what I expected to happen:

```typescript
const date = moment.tz('America/Los_Angeles');
date.tz() // => 'America/Los_Angeles'
date.local()
date.tz() // => undefined
```

Specifically, once set, there is no straightforward way of clearing a moment's timezone info.

**Comment by mj1856** [comment]
Agreed.  Also, the same is true when setting the offset explicitly with `.utcOffset(offset)`.

Will fix shortly.

**Comment by thefliik** [comment]
Thanks!
