### ISSUE TITLE
Consider formatting option to show entire time zone.

### ISSUE THREAD

**Issue by newtang** [moment/moment-timezone#739]
I'd love to see something like "ZZZZ" be used in `format()` to show the long time zone.

```
moment.tz("America/New_York").format("HH:mm ZZZZ"); //17:15 America/New_York 
```

**Comment by mj1856** [comment]
No new features are being added to moment-timezone. 

If you need this feature, I recommend using [Luxon](https://moment.github.io/luxon) instead.  It already exists as the `z` token.

https://moment.github.io/luxon/docs/manual/formatting.html#table-of-tokens

Thanks.
