### ISSUE TITLE
Node 11 failing one guess

### ISSUE THREAD

**Issue by mattjohnsonpint** [moment/moment-timezone#743]
https://travis-ci.org/moment/moment-timezone/jobs/521575597

```
Error: 'America/Caracas' == 'America/Santo_Domingo'
```

Both are UTC-4 with no DST, so it's not urgent.  Still would be worth looking into why this fails under Node 11.14.0.  Probably an `Intl` issue.

**Comment by ssskip** [comment]
https://github.com/moment/moment-timezone/pull/711#issuecomment-452742670_
