### ISSUE TITLE
create a method to validate tz string

### ISSUE THREAD

**Issue by meash-nrel** [moment/moment-timezone#747]
When providing an invalid tz string to moment.tz(), you get a console warning but it still results in a valid moment object.

`let x = moment.tz("2013-06-01", "America/Bad_TZ_str")`
>Moment Timezone has no data for America/Bad_TZ_str. See http://momentjs.com/timezone/docs/#/data-loading/.`   logError global.js:15263

x then equals a moment object set to the default zone of the origin, so it amounts to a silent error in the case of an invalid zone.  I guess that behavior should be expected.

Instead of reworking the error handling, perhaps we need a better method for validating that a provided tz string is valid? I don't see an existing mechanism within moment.tz to validate a tz string, such as `moment.tz.isValid(tz_string)`

I've got my own now via this mechanism...
`// if bad tz string (aka if tz_string is not within names moment.tz.names array)`
`if (!~moment.tz.names().indexOf(tz_string))`

If this was put into a .isValid() method, developers could at least build their own error handling mechanism around it instead of the silent error and using the default tz.

**Comment by thiagozampieri** [comment]
You tried to use
`var isValid = moment.tz.zone ("America / New_York");`

If it is different from null, you may consider it to exist.

**Comment by marnixhoh** [comment]
Would indeed be nice to have an isValid() method on moment.tz. Has this ever been implemented or are there plans to do so?

**Comment by ellenaua** [comment]
There is a method .zoneExists(name) but by some reason it's marked as deprecated in 2014. No idea why, it's pretty useful method.

**Comment by Bartewicz** [comment]
You can use `moment.tz.names` method that returns a list of all available time zone names to validate yours like this:
```javascript
// moment.tz.names(); // ["Africa/Abidjan", "Africa/Accra", "Africa/Addis_Ababa", ...]
const isValid = moment.tz.names().includes(timeZone)
