### ISSUE TITLE
Bug - Converting PM time string to moment is not working correctly when setting the global locale to 'he' or 'ar'

### ISSUE THREAD

**Issue by bayanAbuawad** [moment/moment-timezone#751]
I am trying to parse Time String to moment object, for AM string as '09:00 am' is working very well, but for PM string as '06:00 pm' it is not.

using this code:
```
moment.tz.setDefault('Asia/Jerusalem');
moment.locale('he')

const _startTime = moment("09:00 am", "hh:mm a");
const _endTime = moment("06:00 pm", "hh:mm a");
```
**the 6 PM result is returned as AM** 
![diyhT](https://user-images.githubusercontent.com/14339561/57831117-e7eaea00-77bc-11e9-803e-9f4894458e2e.png)

**Comment by ichernev** [comment]
```
        isPM: function (input) {
            return /^(אחה"צ|אחרי הצהריים|בערב)$/.test(input);
        },
```

Well maybe if you want moment to speak Hebrew, don't be surprised it doesn't speak English any more :)
