### ISSUE TITLE
Which moment to use?

### ISSUE THREAD

**Issue by Waltari10** [moment/moment-timezone#752]
I have an app where I want to display time in either Finnish timezone or UTC time zone. There are some operations that I need to do on the data within a 48 hour period.

Does this require me to use moment-timezone module or could I just use moment? also if I use moment-timezone is the one with "no-data" fitting for this purpose? Also is the one installed with "npm i moment-timezone"  the "no-data" version, or do I just have to copy the file into my project?

Sorry if this is the wrong place to ask, I just have a bit of a hard time understanding this.

**Comment by MartinManev** [comment]
By default, the vanilla javascript Date can work only with the browser's local time zone or in UTC. This is also true for moment. moment-timezone includes a whole database of timezones, which can allow you to work with dates in any timezone you need on the client. no-data means that it is up to you to provide your own database to moment-timezone so the magic can happen.

The answer really depends on the particular use case:
- If you are simply going to display a date in whatever timezone the browser is using, then just moment (or plain JS Date) would suffice.
- Your server app should have access to a timezone database so it can correctly process and store dates in your server-side database.
- In the client app, If you need to work with a particular timezone, no matter what the browser's local timezone is, and especially if you need to validate time restriction rules, then you need a library that provides a timezone database on the client.

moment-timezone comes with a huge (in size) database, that can be modified by additional tools to strip unnecessary timezones and locales.
Also, there are other alternatives. For example - Luxon, which relies on the relatively new INTL API that the browsers implement for timezone and locale information. it is up to you to decide whether it fits your project.
