### ISSUE TITLE
Intl.DateTimeFormat().resolvedOptions().timeZone returns wrong value of timezone

### ISSUE THREAD

**Issue by vsharmaMitel** [moment/moment-timezone#754]
I want to fetch timezone in IANA form for a user using javascript function `Intl.DateTimeFormat().resolvedOptions().timeZone`. But this function gives incorrect IANA time zone value.

I have used moment.js library's function `moment.tz.guess(true)`. But this also gives same incorrect value. On further analysis, I came to know that this also uses same native js function `Intl.DateTimeFormat().resolvedOptions().timeZone` internally

`var timeZone = moment.tz.guess(); // "America/Los_Angeles"`

or

`var timeZone = Intl.DateTimeFormat().resolvedOptions().timeZone; // "America/Los_Angeles"`

Though the user has set system time to (UTC - 07:00) Mountain Time (US & Canada), but still this function gives value as "America/Los_Angeles" which is Pacific standard/daylight timezone. Whereas expected value should be "America/Denver". 
Another thing is that this issue started occurring after the daylight savings adjustment came into picture i.e. around mid of March. Beforehand it worked fine. The user is located in Utah, USA.

Can anyone suggest probable root causes of this issue? Also please suggest any workaround, would be very helpful..

**Comment by ellenaua** [comment]
@vsharmaMitel this is the best way to detect user timezone - 
```Intl.DateTimeFormat().resolvedOptions().timeZone```

Which value did it return to you? 
This function may not work in some browsers, but if it works - it should return a correct value.

**Comment by vsharmaMitel** [comment]
@ellenaua I guess this problem is related to chromium version. In older version of chromium based on which I have created my desktop application, it shows value of `Intl.DateTimeFormat().resolvedOptions().timeZone` as `"America/Los_Angeles"` whereas in latest version of chromium (which is available in my chrome browser), the value is coming correctly as `"America/Denver"`. So it seems there was some chromium bug which got fixed later on.

**Comment by ellenaua** [comment]
I see, it's resolved then

**Comment by steele-cjf** [comment]
so，what is the solution？

**Comment by hyphen81** [comment]
I'm seeing this issue. I'm in America/Chicago but Intl.DateTimeFormat().resolvedOptions().timeZone returns America/NewYork

**Comment by andyyou** [comment]
Is there a solution? I get the totally wrong timezone on windows 11 with all browsers. Chrome, Firefox, Brave all got Etc/GMT-8 but  Asia/Taipei is the right one.

**Comment by vsharmaMitel** [comment]
> Is there a solution? I get the totally wrong timezone on windows 11 with all browsers. Chrome, Firefox, Brave all got Etc/GMT-8 but Asia/Taipei is the right one.

Can you tell me your windows system zone?

**Comment by andyyou** [comment]
@vsharmaMitel UTC+8.  Thanks for reply I reset and set timezone again. Finially solved it.

**Comment by vsharmaMitel** [comment]
> @vsharmaMitel UTC+8. Thanks for reply I reset and set timezone again. Finially solved it.

Not a problem. I checked by setting system time to UTC+8 Taipei, and i am able to get the timezone as 'Asia/Taipei' in browser.

**Comment by rodrigochapeta** [comment]
I'm getting `America/Buenos_Aires` when the INAI it´s `America/Argentina/Buenos_Aires`

**Comment by tafelnl** [comment]
@rodrigochapeta Seems to be a bug in Chromium. Firefox actually returns the correct value `America/Argentina/Buenos_Aires`. But Chrome returns `America/Buenos_Aires`

Tested on:
System: `Linux 5.15.0-48-generic x86_64` with `Ubuntu 20.04.5 LTS`

Firefox `104.0 (64-bit)`
Chrome `Version 106.0.5249.61 (Official Build) (64-bit)`

**Comment by Chakit22** [comment]
May I know how exactly to test if this works correctly Intl.DateTimeFormat().resolvedOptions().timeZone ? How exactly does this fetch the location of the user?
