### ISSUE TITLE
IE/Edge - formatting of timezoned dates may not take historical changes into account

### ISSUE THREAD

**Issue by LoneRifle** [moment/moment-timezone#755]
The following [JSFiddle](https://jsfiddle.net/t2fuc4h5/6/) correctly takes historical timezone changes into account when formatting dates into strings in most browsers, but on later builds of Microsoft Internet Explorer and Edge the formatting fails to do so, giving the historical date with the correct timezone but the time calculated using the modern-day utc offset for Singapore Time:
![image](https://user-images.githubusercontent.com/10572368/58677426-73a07100-838e-11e9-80aa-43e656909050.png)

Note that Singapore changed its timezone to +8 UTC on [1 January 1982](https://en.wikipedia.org/wiki/Singapore_Standard_Time#History_of_Singapore_Standard_Time)

**Comment by ichernev** [comment]
This is very likely related to parsing string without format, and IE/Edge being different (i.e not handling your particular format). Also, prefer using `moment.tz(..., timezone)` than `moment(...).tz(timezone)`.
