### ISSUE TITLE
npm version 0.5.25 Build:failing   is it healthy and safe for production environment

### ISSUE THREAD

**Issue by UqamProvencherRobert** [moment/moment-timezone#756]
Moment-timezone 0.5.25 in npm, the current version as this issue is created,  shows build status = failing

Is this version healthy and safe to use in production environments? 
If so, 
     is it documented somewhere that we should ignore the build status? 
If not (healthy and safe),
      is there another version with build status = passed that would be safe to use in a production 
     environment?

**Comment by ellenaua** [comment]
It's fixed now
