### ISSUE TITLE
start Of Month when setting timezone

### ISSUE THREAD

**Issue by AnirudhVyas** [moment/moment-timezone#758]
Versions used:
```
"moment": "^2.24.0",
 "moment-timezone": "^0.5.25",
```

When using timezone like this - 
```javascript
moment('2019-01-31').tz('America/Los_Angeles').startOf('month).format('YYYY-MM-DD')
```
gives . -  2018-12-01  as opposed to 2019-01-01

Note that the above result is what I get when running inside docker with base image of Centos 7.

However the above works for Mac OS X (local machine). 
Either I am doing something wrong (in which case let me know or point me to documentation) or the behavior is incorrect.

Thanks

**Comment by ellenaua** [comment]
@AnirudhVyas did you find a reason?
