### ISSUE TITLE
moment.tz.guess is caching even with ignoreCaching set to true

### ISSUE THREAD

**Issue by ChakirMrabet** [moment/moment-timezone#769]
Running in node.js + express, Ubuntu, and:

```json
 "moment": "^2.24.0",
 "moment-timezone": "^0.5.26",
```

This route whenever is called, it responds back with the same timezone, even when it's changed from the OS terminal. Only when restarting the application, the route responds with the correct timezone, and then caches again:

```javascript
router.get("/time", (req, res) => {
  const now = moment();
  const timeZone = moment.tz.guess(true);

  res.status(200).json({
    date: now.format("YYYY-MM-DD"),
    timestamp: now.valueOf(),
    timeZone
  });
});

```

How can I force it to not cache?

**Comment by ellenaua** [comment]
@ChakirMrabet This code tries to guess timezone on your server. How do you change timezone? I mean, do you change timezone on server?
