### ISSUE TITLE
webpack bundle itself

### ISSUE THREAD

**Issue by HosseinAlipour** [moment/moment-timezone#770]
I don't know if the problem is with my Webpack configuration or the moment. but it only happens when I add moment-timezone(not moment) and suddenly webpack bundle itself as well, apart from horror stories I heard about moment bundle sizes ...
here's the screenshot
![Screenshot (19)](https://user-images.githubusercontent.com/5198502/61120388-27c70880-a4b2-11e9-96e4-c2c8a5fecde8.png)

**Comment by ellenaua** [comment]
=( this is because we need to move moment to "peerDependencies" otherwise you have 2 moment-s installed

**Comment by ichernev** [comment]
Closing this in favor of #799
