### ISSUE TITLE
Moment Timezone not parse correct time

### ISSUE THREAD

**Issue by ChronoSIDA** [moment/moment-timezone#773]
Hello all, somehow i tried to get the timezone of America/New_York (my locale time is -1 hour from EST). But im always getting the same time when i use moment(new Date()).tz("America\New_York"). Am i using the wrong method or what happened? Can someone help me out please?

Here is a jsFiddle to it:https://jsfiddle.net/Lgr3qdjf/

**Comment by ellenaua** [comment]
@ChronoSIDA there should be '/' instead of '\'
Change "America\New_York" to "America/New_York" )
