### ISSUE TITLE
Invalid DST for Morocco timezones in 2019

### ISSUE THREAD

**Issue by bardzusny** [moment/moment-timezone#774]
Fiddle: https://jsfiddle.net/yos84pev/1

**AS IS:**
`Africa/Casablanca` timezone is showing as being on DST for following time periods in 2019:
- First 8 days (1-8) of every calendar month except May and June
- First 4 days (1-4) of May

**TO BE:**
`Africa/Casablanca` timezone is on DST all of 2019, except for 5 May - 9 Jun: https://www.timeanddate.com/time/change/morocco?year=2019

**Comment by ODAVING** [comment]
I can take a look into this issue

**Comment by cusalvi** [comment]
We are also experiencing the same issue for "Africa/Casablanca".

**Comment by ichernev** [comment]
If you're refering to `isDST` it is a hack. Read more here: https://github.com/moment/moment-timezone/issues/968

Also it's part of the docs now: https://github.com/moment/momentjs.com/commit/b4ddfdd3acc5b8926d114985b5ead5ca8ed4ef43
