### ISSUE TITLE
Incorrect UTC for getting the Swedish time

### ISSUE THREAD

**Issue by stnight** [moment/moment-timezone#778]
My code is currently deployed to an EU-West region, and i got a bug on converting that local UTC timezone to Swedish time. I expected that the result from this method: `moment.tz.zone(timezone).utcOffset(Date.parse(new Date().toISOString()));` will be `+120` in minutes, but I got `-120`.

**Comment by vigneshb17** [comment]
I have an issue.

moment("2014-12-01T12:00:00Z").tz('America/New_York').format('ha z'); // "7am EST"  ,
it shows time zone's  abbreviation  for America/New_York. 

In another example,
moment("2014-12-01T12:00:00Z").tz('Asia/Riyadh').format('ha z'); // "3pm +03" ,
In this example , It shows time zone's offset for Asia/Riyadh . 
Is there any solution for this thing?

**Comment by ellenaua** [comment]
@stnight this is not a bug:
```
moment.tz.zone('America/New_York').utcOffset(Date.parse(new Date().toISOString()))
// 240
moment.tz.zone('America/New_York').utcOffset(Date.parse(new Date().toISOString()))
// -120
```
try to do `new Date().getTimezoneOffset()` in your browser it will return -120
because this is intended behavior

**Comment by ellenaua** [comment]
@vigneshb17 You expect Asia/Riyadh timezone abbreviations to be AST right?

**Comment by vigneshb17** [comment]
@ellenaua Yes

**Comment by ellenaua** [comment]
We use a timezone database published by an international organization IANA https://www.iana.org/ and in 2017 they changed some timezone abbreviations to something like +03, +04 because 

> many abbreviations were ambiguous. In the US, AST is commonly used for Standard Alaska Time, 10h west of GMT.

**Comment by stnight** [comment]
i undertaking now, this clears the confusion. Thanks
