### ISSUE TITLE
Moment timezone is not correctly showing the zone abbreviation for Pacific/Nauru.

### ISSUE THREAD

**Issue by shweshi** [moment/moment-timezone#780]
Moment timezone is not correctly showing the zone abbreviation for Pacific/Nauru.

Example:

``
moment.tz('America/New_York').zoneAbbr();  // "EDT"
``
``
moment.tz('Pacific/Nauru').zoneAbbr(); // +12
``

It should give the zone abbreviation.

**Comment by ellenaua** [comment]
There has been big change in 2017 when IANA (Internet Assigned Numbers Authority) changed some time zone abbreviations to numeric representations. And this one was also changed because `NRT` was considered as `self-invented` abbreviation

https://mm.icann.org/pipermail/tz/2017-January/024769.html

**Comment by NoureldeanSaed** [comment]
Same for `America/Santiago`.

**Comment by dustinsgoodman** [comment]
Same for `America/Sao_Paulo`https://codesandbox.io/s/objective-pasteur-znco2

**Comment by ellenaua** [comment]
In december 2016, IANA (https://www.iana.org/) deprecated these abbreviations and many others

America/Sao_Paulo - BRT (-03) BRST (-02)
America/Santiago - CLT (-04) CLST (-03)

https://mm.icann.org/pipermail/tz/2016-December/024645.html

This is international standartization organization. So, abbreviations like BRST, BRT are considered deprecated. Could you please tell me what do you see when do console.log(new Date()) in browser console - `Sat Mar 14 2020 07:38:18 GMT-0300 (-03)` or `Sat Mar 14 2020 07:38:18 GMT-0300 (BRT)`?

**Comment by dustinsgoodman** [comment]
<img width="420" alt="Screen Shot 2020-03-14 at 2 41 43 PM" src="https://user-images.githubusercontent.com/1815379/76687365-91775380-65f9-11ea-986f-8b60dde8e2da.png">

**Comment by dustinsgoodman** [comment]
@ellenaua I was reporting based on an investigation from a user of my site. I set my system's timezone to Brazil and ran the command and got the following output:

<img width="420" alt="Screen Shot 2020-03-14 at 2 41 43 PM" src="https://user-images.githubusercontent.com/1815379/76687369-9b00bb80-65f9-11ea-861d-2ddc93602f82.png">

Hope that's helpful!

**Comment by ichernev** [comment]
moment-timezone is not in a position to maintain timezone offset names outside of IANA/tzdb. Please redirect your anger there, you might manage to convince them to bring some of the offset names back (if enough people complain).
