### ISSUE TITLE
Wrong spelling of timezone

### ISSUE THREAD

**Issue by KingR1** [moment/moment-timezone#781]
In the timezones is present next one : `Europe/Kiev`, which isn't totally correct. Better will be Kyiv.
Can you fix this?
Thanks.

#KyivNotKiev

**Comment by bodia-uz** [comment]
https://mfa.gov.ua/en/page/open/id/5418

**Comment by ellenaua** [comment]
@KingR1 `moment-timezone` is just a JavaScript library that extracts information from IANA database, and in the IANA database it's still named Europe/Kiev.

**Comment by zuker** [comment]
Could alias `Europe/Kyiv|Europe/Kiev` be added into the lib?
@bodia-uz btw I use alias as workaround for now.

**Comment by bodia-uz** [comment]
@zuker
Here is discussion about alias:
https://github.com/eggert/tz/commit/b2eede3d1b62c43d0121dd2f6e790b97f29da7b7

Long story short: they don't want to add an alias

**Comment by Coffee-Tea** [comment]
Damn, it is still not right in May 2022.

**Comment by gilmoreorless** [comment]
The rename has been done in the IANA source ([see commit](https://github.com/eggert/tz/commit/e13e9c531fc48a04fb8d064acccc9f8ae68d5544)) and will be in the next release of the database. Then it can be brought into Moment Timezone.
