### ISSUE TITLE
2019c release of tz code and data available

### ISSUE THREAD

**Issue by casper5822** [moment/moment-timezone#782]
Hello,
2019c release of tz code and data  is available.
Is there any update on this?

Thank you
Best regards

**Comment by ellenaua** [comment]
Released 👍

**Comment by casper5822** [comment]
I see that last release for moment-timezone is 0.5.26 with 2019b, not 2019, is it right?

**Comment by jed-pike13** [comment]
It seems like the release tag has been one behind the actual release lately.

**Comment by casper5822** [comment]
Release 0.2.57 is available. Thank you
