### ISSUE TITLE
requesting formal Github Release package for 0.5.26

### ISSUE THREAD

**Issue by cantremember** [moment/moment-timezone#784]
sorry to bother you guys,. i know that you've released 0.5.26 into the wild, but there's no package for it in the [Releases](https://github.com/moment/moment-timezone/releases) section

this new version hasn't made it over into the `bower` registry yet, we need to upgrade to the IANA TZDB `2019b`, and the (theoretically volatile) [release_0.5.26](https://github.com/moment/moment-timezone/tree/release_0.5.26) branch is the only reference point that i have to the new code

thanks for all your hard work, team

**Comment by ellenaua** [comment]
Done, thanks
