### ISSUE TITLE
Brazil-America/Sao_Paulo datetime offset problem (they don't use DST anymore)

### ISSUE THREAD

**Issue by IonutOprescu** [moment/moment-timezone#785]
According to https://www.timeanddate.com/time/change/brazil?year=2019 Brazil does not use the DST from the beginning of 2019. 
I'm using the version 0.5.13 and it seems that the timezone offset is still changed based on DST this October.

When will the timezone for Brazil be changed?

**Comment by ssherman** [comment]
The data that is used by moment-timezone is from the official time zones database that IANA manages: https://www.iana.org/time-zones

They will need to update their data for it to be fixed in moment-timezone

**Comment by ssherman** [comment]
this seems to be working fine for me. I wrote a little test file:
https://gist.github.com/ssherman/6da636c64eb2905d7abef6c9a35cfa96

you can see that the dates switch from daylight savings to normal time on Feb 16th, 2019
2019-02-16T23:00:00-02:00
2019-02-16T23:00:00-03:00

and you can see that in 2020, there is no daylight savings. The offset stays 03:00.

**Comment by ellenaua** [comment]
1) please ensure that you're using moment-timezone version 0.5.26 or later
2) see how it works:

```
console.log(moment(`2018-11-18`).tz("America/Sao_Paulo").format());
// returns 2018-11-17T20:00:00-02:00
console.log(moment(`2019-11-18`).tz("America/Sao_Paulo").format());
// returns 2019-11-17T19:00:00-03:00 - because no DST change anymore
console.log(moment(`2020-11-18`).tz("America/Sao_Paulo").format());
// returns 2020-11-17T19:00:00-03:00  - because no DST change anymore
```

**Comment by dotpegaso** [comment]
@ellenaua it's not working for me.

I'm using:
 `moment-timezone: 0.5.27`
 `console.log(moment('2020-11-18').tz("America/Sao_Paulo").format())` 

but it returns `2020-11-17T19:00:00-02:00`

Even in the chrome's devtools console of [moment-timezone website](https://momentjs.com/timezone/) this doesn't work, I can't figure out why tho.

**Comment by savioserra** [comment]
@dotpegaso Did you manage to get this working? Im experiencing this issue too.

`"moment-timezone": "^0.5.27"`

**Comment by dotpegaso** [comment]
> @dotpegaso Did you manage to get this working? Im experiencing this issue too.
> 
> `"moment-timezone": "^0.5.27"`

I did using [react-native-v8](https://github.com.cnpmjs.org/Kudo/react-native-v8). Just follow the readme, very straightforward.
