### ISSUE TITLE
support beijing time

### ISSUE THREAD

**Issue by yukie1412** [moment/moment-timezone#787]
looking at the [meta file](https://github.com/moment/moment-timezone/blob/2445c798ae30a75af6137774048aeb61db99d451/data/meta/2016f.json#L2851), i see `Asia/Shanghai` listed with comment "Beijing Time"
but the actual `Asia/Beijing` time isn't found anywhere in the list.

was this intentional?
although shanghai & beijing belong to the same timezone, when referring to timezone in China, "beijing time" is the first thing come to mind. except i had some trouble getting the correct time, using the [`moment.tz.names()`](https://momentjs.com/timezone/docs/#/data-loading/getting-zone-names/) function, as it did not exist.

**Comment by ellenaua** [comment]
Hi, moment-timezone library is getting its information from international database released by IANA organization. And they call it `Asia/Shanghai` see here oficial names of timezones https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

**Comment by yukie1412** [comment]
thanks for the info. that's quite surprising.
closing this.
