### ISSUE TITLE
Wrong DST for Brazil after presidential decree

### ISSUE THREAD

**Issue by guizero** [moment/moment-timezone#794]
The current brazilian president has decided to cancel DST in Brazil this year. This means that since November 4th the timezone is being returned incorrectly (UTC -2 instead of -3) for SaoPaulo_Americas.

https://www.business-standard.com/article/news-ians/bolsonaro-ends-daylight-savings-time-in-brazil-119042600163_1.html

What would be the best way to manually adjust this?

**Comment by dotpegaso** [comment]
@guizero did you solve this already?
