### ISSUE TITLE
Time is off by -1 hour on a 2099 date when switching from 0.5.25 to 0.5.27

### ISSUE THREAD

**Issue by bdavis-tc** [moment/moment-timezone#798]
Simplified reproduction code:
https://runkit.com/bdavis-tc/5dc43803b63326001b4f6f53

Dates after year 2037 the 0.5.27 version misses the time by an hour.
My test date is in the year 2099.
Testing against timezone: EST (with Daylight Savings Time)

The 0.5.25 version seems to have accurate time all the way to year 2499.

Not sure if the 0.5.26 and 0.5.27 version introduced a bug, or just changed default behavior for how much data to include.

For now we will stick with 0.5.25, looking to improve my understanding and/or implementation to allow us to use the latest version again.

Thank you!

**Comment by gilmoreorless** [comment]
This is probably due to the (accidentally?) reduced data size due to a change in release process from 0.5.26 onwards (#768).

**Comment by micheleangioni** [comment]
Hi guys, I've lost around 3 hours today due to this :| 
One of our test dates is 2060 and since v0.5.26 the offset of dates with `Europe/Berlin` timezone is wrong. It seems to be indeed related to (#768).

**Comment by andywu0408** [comment]
Following up on this - This problem still persists as of now for me.

**Comment by eramitmittal** [comment]
Please look at #921 
Fork available at: https://github.com/eramitmittal/moment-timezone

**Comment by ichernev** [comment]
Latest moment-timezone (0.5.37) has extended range. In the future we'll release on Linux :) check https://github.com/moment/moment-timezone/issues/999#issuecomment-1229214980
