### ISSUE TITLE
Wildly different filesize between /builds/ and website

### ISSUE THREAD

**Issue by mappu** [moment/moment-timezone#800]
Hi,

There is a big discrepancy between the two versions of `moment-timezone-with-data` available from https://momentjs.com/timezone/ versus from the `/builds/` directory.

For 0.5.27:

|File|`builds/`|momentjs.com|
|---|---|---|
|moment-timezone-with-data.js|**192 KB**|**920 KB**
|moment-timezone-with-data.min.js|**182 KB**|**909 KB**
|moment-timezone-with-data-10-year-range.js|43 KB|43 KB
|moment-timezone-with-data-10-year-range.min.js|33 KB|33 KB
|moment-timezone-with-data-1970-2030.js|138 KB|138 KB
|moment-timezone-with-data-1970-2030.min.js|128 KB|128 KB
|moment-timezone-with-data-2012-2022.js|43 KB|n/a
|moment-timezone-with-data-2012-2022.min.js|33 KB|n/a

- Why doesn't the `moment-timezone-with-data` file match? What is the difference?

It doesn't match any of the other build artefacts neither.

- Where can i get the ~900KB version of the previous 0.5.26 release?

**Comment by gilmoreorless** [comment]
This seems related to #768.

**Comment by ellenaua** [comment]
Size of latest builds 

203K Feb 21 19:59 moment-timezone-with-data.js
191K Feb 21 19:59 moment-timezone-with-data.min.js

54K Feb 21 19:59 moment-timezone-with-data-10-year-range.js
42K Feb 21 19:59 moment-timezone-with-data-10-year-range.min.js

55K Feb 21 19:59 moment-timezone-with-data-2012-2022.js
42K Feb 21 19:59 moment-timezone-with-data-2012-2022.min.js

150K Feb 21 19:59 moment-timezone-with-data-1970-2030.js
137K Feb 21 19:59 moment-timezone-with-data-1970-2030.min.js
