### ISSUE TITLE
npm install v0.5.27 missing /data/packed/latest.json file

### ISSUE THREAD

**Issue by abolia83** [moment/moment-timezone#802]
We have moment-timezone as one of the dependencies in our nodejs project. When deploying this on jenkins server, npm install does not download the ./data/packed/latest.json . The build is successful however when trying to run the code error is:
Unable to import module 'src/app/app': Error
at Function.Module._load (module.js:474:25)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/var/task/src/node_modules/moment-timezone/index.js:2:16)

The same project when installed on local using npm install, loads the data file correctly. 
How to get the data file loaded on jenkins ? Thanks.

**Comment by ellenaua** [comment]
is it resolved already?
