### ISSUE TITLE
Conversion to Brazil timezone is 1 hour ahead

### ISSUE THREAD

**Issue by rjpedrosa** [moment/moment-timezone#804]
Hi,

Brazil decided to abolish Daylight Saving Time. In the current version of Moment Timezone, returned converted time for e.g. `America/Sao_Paulo` timezone is always 1 hour ahead of the real time in Sao Paulo. Any plans to fix this soon?

Thank you!

**Comment by Duarte007** [comment]
For me, when I use the moment with the America/Sao_Paulo time zone on the node, it's always an hour late

**Comment by rjpedrosa** [comment]
By one hour ahead I mean when e.g. is 6pm in Sao Paulo, moment converts to 7pm.

**Comment by fabiomello** [comment]
Same problem here @rjpedrosa

**Comment by amorenopbsc** [comment]
I believe this has been addressed within the last three versions of moment-timezone. I suggest to update to the latest version 
https://github.com/moment/moment-timezone/issues/797

**Comment by fabiomello** [comment]
I forgot to put here, i update to verson .27 and it works. Thanks
