### ISSUE TITLE
Sao Paulo timezone is ahead by 1 hour

### ISSUE THREAD

**Issue by fazeela-veolia** [moment/moment-timezone#805]
We are using moment.js and HighCharts library to plot the data points on the graphs. When we try to plot the data points with other timezone, it is plotting correctly. Where as when we change the timezone to Sao Paulo, it is showing the data points as one hour ahead of the current time. We have updated the moment.js to the latest as of reference with the thread opened at https://github.com/moment/moment-timezone/issues/399. But it was of no help. The code we have used to convert to the user time zone is as follows, 

```
time: {
          timezone: $('#user-timezone').val()
        },
```

**Comment by pimfeltkamp** [comment]
We also still have this issue after upgrading to the latest version. Sao Paulo time is one hour ahead, probably due to DST.

Example code:

```
function toTimeZone(utc_date, format){
       var zone = 'America/Sao_Paulo';
       return moment(utc_date).tz(zone).format(format);
}

function getDateTime(){
	var time = moment.utc().format();
	return toTimeZone(time, 'L LTS');
}

console.log(getDateTime());
```

**Comment by rafaelsales** [comment]
@fazeela-veolia I just tried the latest version and America/Sao_Paulo looks ok
