### ISSUE TITLE
Antarctica/Casey timezone wrong offset format

### ISSUE THREAD

**Issue by warrify** [moment/moment-timezone#806]
```javascript
moment.tz('Antarctica/Casey').format('Z')
```

gives `+08:00` but it should be `+11:00`

see [wikipedia](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)

**Comment by ellenaua** [comment]
It's wrong information on that Wikipedia page.

Casey Station in Antarctica changed from +11 to +08 on 2018-03-11 at 04:00.  

And on this page info is correct:
https://en.wikipedia.org/wiki/Casey_Station
https://www.worldtimeserver.com/time-zones/cast/
