### ISSUE TITLE
[request] allow multi moment instance

### ISSUE THREAD

**Issue by bluelovers** [moment/moment-timezone#808]
hope can allow create a tz instance not share to global moment

A
---
```ts
import _moment from 'moment-timezone';
// ... something
export const momentA = _moment.tz.instance().setDefault("Asia/Taipei")
```

B
---
```ts
import _moment from 'moment-timezone';
// ... something
export const momentB = _moment.tz.instance().setDefault("America/Los_Angeles")
```

C
---
```ts
import { momentA } from './A';
import { momentB } from './B';

let input = `2020-01-01`;

import { deepEqual } from 'assert';

notDeepEqual(momentA(input).unix(), momentB(input).unix())
```

**Comment by ellenaua** [comment]
@bluelovers Wondering: do you need it for server-side or frontend code?
I know how to do this for server-side, but no ideas (yet) how to implement it for frontend. 
Moment.js is a singleton.

**Comment by ichernev** [comment]
It could be done, but the only useful thing to do with `instance` is to make a new moment, and for that you can have a factory method which can be primed with a timezone, just part of your own code.

```
function momentTzInstance(timezone) {
  return function () {
    var args = Array.prototype.slice.call(arguments, 0, -1);
    args.push(timezone);
    return moment.tz.apply(moment.tz, args);
  };
}

momentTzBerlin = momentTzInstance("Europe/Berlin");
momentTzBerlin("2020-01-01");
momentTzLondon = momentTzInstance("Europe/London");
momentTzLondon("2020-01-01");
```

This could be put in a plugin, but I'm not a fan of 3 line dependencies, I don't want to be part of the next leftpad emergency.
