### ISSUE TITLE
Moment Timezone found Asia/Calcutta from the Intl api, but did not have that data loaded.

### ISSUE THREAD

**Issue by VictorMW** [moment/moment-timezone#810]
Hey guys,
I tried looking into the momentjs.com website but it's blocked by our Indian government for no good reason. Is there any workaround to load the data for Asia/Calcutta locally.

**Comment by ellenaua** [comment]
@VictorMW but data for Asia/Calcutta is there. Which version of moment-timezone do you use?

```
const result = moment.tz.zone('Asia/Calcutta');
console.log(result)
```
