### ISSUE TITLE
Bug first week of 2019 (nodejs)

### ISSUE THREAD

**Issue by LebonNic** [moment/moment-timezone#811]
Hi!

I am facing a strange issue with moment. In one of my unit tests, I have the following case:

```javascript
"use strict";
const expect = require("chai").expect;
const moment = require("moment-timezone");

describe("Rapid test runner", function() {
  it("Should return the first and last day of week 1 in 2019 for France", function(done) {
    
    // The test works if I put 2020-01-20T15:38:32+01:00 instead of 2018-12-30T11:48:00+01:00
    let now = moment("2018-12-30T11:48:00+01:00").tz("Europe/Paris");

    let firstDayOfTheWeek = now
      .clone()
      .locale("fr")
      .year(2019)
      .week(1)
      .startOf("week");

    let lastDayOfTheWeek = now
      .clone()
      .locale("fr")
      .year(2019)
      .week(1)
      .endOf("week");

    console.log("now:", now.format());
    console.log("firstDayOfTheWeek:", firstDayOfTheWeek.format());
    console.log("lastDayOfTheWeek:", lastDayOfTheWeek.format());

    expect(firstDayOfTheWeek.format()).equal("2018-12-31T00:00:00+01:00");
    expect(lastDayOfTheWeek.format()).equal("2019-01-06T23:59:59+01:00");

    done();
  });
});
```

The output is:

> now: 2018-12-30T11:48:00+01:00
> firstDayOfTheWeek: 2019-12-30T00:00:00+01:00
> lastDayOfTheWeek: 2020-01-05T23:59:59+01:00

Instead of:

> now: 2018-12-30T11:48:00+01:00
> firstDayOfTheWeek: 2018-12-31T00:00:00+01:00
> lastDayOfTheWeek: 2019-01-06T23:59:59+01:00

Maybe I am missing something in the way I use moment but after many (many) hours of research I cannot figure it out. I use:

* node: v10.16.3
* moment-timezone: 0.5.27

Is it a bug ?

Best regards,
Nicolas

**Comment by frankorama** [comment]
I just found the same bug in our code.
```
const date1 = moment('2020-02-18T09:44:00.000-05:00').tz('america/montreal')
const date2 = date1.clone().tz('America/Montreal') // 2020-02-18T00:00:00.0000-05:00
```

**Comment by ellenaua** [comment]
@LebonNic problem in here: 

1) when you do .year(2019) date changes to 2019-12-30T11:48:00+01:00
2) 2019-12-30 is a 1st week of 2020
2) when you call .week(1) it does nothing because week is number 1 already
3) because of that, you get first and last day of first week of 2020

```
console.log("Week number:", moment("2019-12-30T11:48:00+01:00").format('W'));

let firstDayOfTheWeek = moment("2019-12-30T11:48:00+01:00")
    .locale("fr")
    .week(1)
    .startOf("week");

console.log("firstDayOfTheWeek:", firstDayOfTheWeek.format());
```

It's problem in **moment** library, not in **moment-timezone** 
They recommend to use "weekYear" to explicitly specify which year do you mean - 2019 or 2020

https://github.com/moment/moment/issues/5321
https://momentjs.com/docs/#/get-set/week-year/

**Comment by LebonNic** [comment]
Hi @ellenaua,

Thank you very much for the explanations! It's much clearer now!

Best regards,
Nicolas
