### ISSUE TITLE
Offset value issue for "Europe/Moscow"

### ISSUE THREAD

**Issue by cusalvi** [moment/moment-timezone#812]
As we see Europe/Moscow has offset value -180 i.e. UTC+3.
https://www.zeitverschiebung.net/en/timezone/europe--moscow

In this time zone there is no Daylight Saving Time in use. But when we get zone object using 
`moment.tz.zone('Europe/Moscow')`
for "Europe/Moscow", we get offset value as -240 as first value which is equal to UTC+4 from zone object.
Due to which output time is converted into one hour earlier than my input time.

Getting offset for Europe/Moscow(MSK) : -240
Expected offset for Europe/Moscow(MSK) : -180

**Comment by ellenaua** [comment]
Please, check which moment-timezone version do you use?
Daylight saving time in Moscow was canceled in 2014, and moment-timezone was updated, you probably use some very old version.

```
console.log(moment.tz.zone('Europe/Moscow').utcOffset(new Date('2013-01-01'))) // -240
console.log(moment.tz.zone('Europe/Moscow').utcOffset(new Date('2017-01-01'))) // - 180 
console.log(moment.tz.zone('Europe/Moscow').utcOffset(new Date('2019-01-01'))) // - 180 
console.log(moment.tz.zone('Europe/Moscow').utcOffset(new Date())) // - 180 
```

**Comment by cusalvi** [comment]
We are using moment-timezone version 0.5.27.
Yeah above values are correctly given.But we are using following to get standard offset from zone object;
`console.log(moment.tz.zone('Europe/Moscow').offsets[0]);` which gives us -240.

We are using 10 year range data(i.e. 2012-22);
Will you please help us to get it always -180 using zone object method i.e.
moment.tz.zone('Europe/Moscow');
i.e. To get standard offset of any timezone.

**Comment by ellenaua** [comment]
80% of timezones have multiple offsets: summer offset (daylight saving) and winter offset.
You can get those offsets this way:

const winterOffset = moment.tz.zone(timeZone).utcOffset(new Date("2020-01-01"));
const summerOffset = moment.tz.zone(timeZone).utcOffset(new Date("2020-07-01"));

But - for example - in Brazil daylight saving time was canceled in 2019, so for 2018 you'll get two different offsets but for 2020 the same offset for any day.
