### ISSUE TITLE
Building the data from scratch

### ISSUE THREAD

**Issue by guyisra** [moment/moment-timezone#814]
using `grunt data` eventually creates temp/collect/latest.json which as far as I understand, is not the same format as data/packed/latest.json which is the format needed to manually added a new tzdb version (in the scenario where it takes time to officially update the package to the latest release) 

Is there a way to create a packed version of the latest.json so it can be added with the .add / .load functions? 

thanks

**Comment by ellenaua** [comment]
`grunt data` also creates or updates file `data/packed/latest.json` and this is what you need!

```
var moment = module.exports = require("./moment-timezone");
moment.tz.load(require('./data/packed/latest.json'));
```
