### ISSUE TITLE
Unable to get timezone abbreviation 

### ISSUE THREAD

**Issue by crashspringfield** [moment/moment-timezone#815]
It seems like it was once possible to get a user's timezone abbreviation:

- [https://stackoverflow.com/questions/24174807/using-moment-js-to-display-the-users-local-zone-abbreviation](https://stackoverflow.com/questions/24174807/using-moment-js-to-display-the-users-local-zone-abbreviation)
-[https://stackoverflow.com/questions/40494995/how-to-get-timezone-name-pdt-est-etc-in-javascript](https://stackoverflow.com/questions/40494995/how-to-get-timezone-name-pdt-est-etc-in-javascript)

but this no longer works. Instead I get the error `TypeError: C is undefined`.

How does one get a user's timezone abbreviation when the date isn't known ahead of time?

**Comment by ellenaua** [comment]
Please provide a piece of code which does not work for you (throws that TypeError)
because this works perfectly 
```
moment().tz(moment.tz.guess()).format('z')
```
or 
```
moment.tz(moment.tz.guess()).zoneAbbr(); 
```
