### ISSUE TITLE
Is it necessary to update timezone data when using Node.js?

### ISSUE THREAD

**Issue by marnixhoh** [moment/moment-timezone#816]
I've been searching for the answer to this question for quite some time, but I can't seem to find it: Does the timezone data get updated with every new release of the moment-timezone library or should I somehow update the timezone data myself?

Thanks!

**Comment by ellenaua** [comment]
Timezone data is inside moment-timezone package. You only need to update moment-timezone version in your package.json and reinstall it (install newer version)

**Comment by marnixhoh** [comment]
Thank you! That's what I figured
