### ISSUE TITLE
countries() returns no results for 'America/Cordoba'

### ISSUE THREAD

**Issue by maxhawkins** [moment/moment-timezone#821]
While testing different time zones, I found an issue with the "America/Cordoba" zone and the countries() method.

`moment.tz.guess()` returned "America/Cordoba", which is in Argentina. However:

```ts
moment.tz.zone("America/Cordoba").countries() === []
```

**Comment by ichernev** [comment]
```
		test.deepEqual(tz.zone('America/Argentina/Cordoba').countries(), ["AR"]);
		test.deepEqual(tz.zone('America/Cordoba').countries(), []);
```

This is because `America/Cordoba` is deprecated in favor of `America/Argentina/Cordoba` and some browsers (via Intl) return the deprecated timezone.

Close in favor of #873
