### ISSUE TITLE
Moment returns daylight time instead of Standard time. 

### ISSUE THREAD

**Issue by davinderxav** [moment/moment-timezone#822]
Hi,

I have use case in which I have to show timeZone abbreviation like IST,MST. 
When I use moment format ('Z') for abbreviations, It gives me time in daylight time. 
Like:  8 AM MDT 
Instead, we want the output to be like this: 7 AM MST

How can we do this?  

> 
8AM MDT to 7AM MST

`
const moment = require("moment-timezone")
let timeSlot = {
    "startDate": "2020-04-28T08:00:00.000-0600",
}
let timeZone = "America/Edmonton"
let startDate= moment.tz(timeSlot.startDate, timeZone).format('h A z');
console.log(startDate); // 8 AM MDT

 `

**Comment by ellenaua** [comment]
It shows offset abbreviation, which was active in given day (2020-04-28).
DST in America/Edmonton began on Sun 8-Mar-2020 at 02:00:00 A.M.

So, for dates upto 2020-03-07 it will return MDT.
For dates after 2020-03-07 it will return MST.
It's definitely not a bug, but you want some 'workaround'?

I can only tell that you can get offsets and abbreviations using these methods

```
const winterOffset = moment.tz.zone(timeZone).utcOffset(new Date("2020-01-01T00:00:00.000Z")); // 480
const summerOffset = moment.tz.zone(timeZone).utcOffset(new Date(timeSlot.startDate)); // 420

const winterAbbr = moment.tz.zone(timeZone).abbr(new Date("2020-01-01T00:00:00.000Z")); // PST
const summerAbbr = moment.tz.zone(timeZone).abbr(new Date(timeSlot.startDate)); // PDT
```
