### ISSUE TITLE
moment.tz.names() still lists all names despite loading a smaller data bundle?

### ISSUE THREAD

**Issue by xingped** [moment/moment-timezone#831]
I slimmed down the packed latest time zone data ( https://github.com/moment/moment-timezone/blob/develop/data/packed/latest.json ) into a smaller file with just the time zones I care about using in my application.

If I do the following:

    import('./my-timezone-data.json')
      .then(timeZoneData => {
        moment.tz.load(timeZoneData);
        console.log(moment.tz.names());
      }

Why does `moment.tz.names()` still return all the timezone names instead of just the ones I loaded with a slimmed down data bundle?

I'm looking to avoid displaying/handling/loading all of the time zones and including the large timezone file in my bundled web app, since that is unnecessary for my use-case, and only handling the handful that I care about.

**Comment by neomi2428** [comment]
I still have the same issue. Is there anyone who take a look at it?

**Comment by ichernev** [comment]
Probably you loaded a moment-timezone-with-data and now you have everything. You should be able to load only what you need, that is the whole point of the load method.

**Comment by xingped** [comment]
@ichernev Can you explain what you mean by "loaded a moment-timezone-with-data"? And what is the alternative thing I should load in order to use `moment.tz.load()` and only load what I need?
