### ISSUE TITLE
What's wrong with this date? Europe/Brussels, early 1900's

### ISSUE THREAD

**Issue by postb99** [moment/moment-timezone#840]
Hello,

I use a VueJS project with latest moment and moment-timezone. However I could reproduce the behavior with a simple html page opened in the browser (see below).

My timezone is set to Europe/Brussels.
I display UTC dates in local format. OK for dates in the 1960's, 1950's...

Now... I expect 1939-12-31T23:00:00Z to be 1940-01-01 in local time since we're in UTC+1, is this wrong?

The same with a date like 1902-12-31T23:00:00Z, I expect 1903-01-01 local time.

Where can I find the relevant information for this timezone? Was Belgium ever not in UTC+1 timezone in early 1900's ?

Thanks,

```
<html>
  <head>
    <title>Moment timezone test - open the html page directly</title>
    <script src="../node_modules/moment/min/moment.min.js"></script>
    <script src="../node_modules/moment-timezone/builds/moment-timezone-with-data.js"></script>
  </head>
  <body>
    <p id="p2020"></p>
    <p id="p1940"></p>
  </body>
  <script type="text/javascript">
    // var now = moment().format('MMM DD h:mm A')
    // alert(now)
    moment.tz.setDefault('Europe/Brussels')

    const testDate = moment(new Date('1939-12-31T23:00:00Z'))
    document.getElementById('p1940').innerHTML = testDate.format('DD MM YYYY')

    const testDate2 = moment(new Date('2019-12-31T23:00:00Z'))
    document.getElementById('p2020').innerHTML = testDate2.format('DD MM YYYY')
  </script>
</html>
```

**Comment by robin-karlsson** [comment]
Search for Brussels in this url (which is an extract of the database compiled for use in moment-timezone); https://data.iana.org/time-zones/tzdb-2020a/europe

Seems like Brussels had an offset of 0 from time to time. Could possibly explain the results you experience.

**Comment by robin-karlsson** [comment]
Also, if you look here, at the historical dates; https://www.timeanddate.com/time/zone/belgium/brussels

It seems Brussels was on UTC for both your examples.
