### ISSUE TITLE
moment.tz('America/Los_Angeles') returns time 30min behind

### ISSUE THREAD

**Issue by emclab** [moment/moment-timezone#843]
Here is the code to retrieve current time in nodejs (11.16.0) and moment-timezone (0.5.26):
       
           const moment = require("moment-timezone");
        if (tz) {
                 nowStr = moment().tz(tz).format("YYYY-MM-DD  HH:MM");
                 nowDateStr = moment().tz(tz).format("YYYY-MM-DD");
               } else {
                 nowStr = moment().format("YYYY-MM-DD  HH:MM");
                 nowDateStr = moment().format("YYYY-MM-DD");
             };
           console.log(`Time now in ${tz} is `, nowStr);

Here is the console output:

            Time now in America/Los_Angeles is  2019-07-22  10:07

But my clock shows the time@10:47. The time returned by moment is 30min behind. The time remains the same even the app is re-launched multiple times. Is it a bug?

**Comment by ellenaua** [comment]
@marwahaha uppercase MM is a month, and lowercase mm - minutes.

you should use "YYYY-MM-DD HH:mm" not YYYY-MM-DD HH:MM"

**Comment by marwahaha** [comment]
Thanks @ellenaua 

@emclab Please re-open if you have other questions!
