### ISSUE TITLE
Momentjs without internet connection.

### ISSUE THREAD

**Issue by ee11131** [moment/moment-timezone#846]
I have a webapp that should work normally in a local network, without an internet connection. I use moment-timezone to set the time time according to the server timezone. This works fine with internet. But I was wondering, how does it work without? Where does it get the timezone info to perform the conversion from local to server timezone? Can I be sure that there won't be a scenario where an internet connection will be required to perform momentjs operations?

**Comment by ellenaua** [comment]
Hi @marwahaha it works well without internet because it has timezone information in "packed" format inside. https://github.com/moment/moment-timezone/blob/develop/data/packed/latest.json

**Comment by marwahaha** [comment]
Thanks @ellenaua 

@ee11131 Please re-open if you have other questions!
