### ISSUE TITLE
Egypt now respects DST

### ISSUE THREAD

**Issue by ghost** [moment/moment-timezone#85]
A few weeks ago, [the interim Egyptian government reinstated DST](http://news.yahoo.com/egypt-government-restores-daylight-saving-time-185236399.html) in that country, after it had abolished it three years ago. This means that Egypt now suddenly respects DST, and that the tzdata files for moment-timezone need to be updated to reflect this. (☹)

As confirmation, here's Linux vs. moment-timezone:

```
$ grep '"version"' node_modules/moment-timezone/package.json
  "version": "0.0.6",
$ node
> require("moment-timezone")().tz("Africa/Cairo").toString()       
'Wed May 21 2014 14:50:52 GMT+0200'  
> ^C
$ TZ=Africa/Cairo date
Wed May 21 15:50:56 EEST 2014
```

(That is, Africa/Cairo should currently be GMT+0300, rather than GMT+0200.)

Thanks as always, folks—I know how frustrating this stuff can be.

**Comment by davidpatters0n** [comment]
@timrwood - I'm calling for this to be re-opened, and updated again. As it has recently been announced that Egypt has now decided to scrap DST. More detail can can be found here: http://mm.icann.org/pipermail/tz/2016-July/023855.html and the associated links.
