### ISSUE TITLE
[Question] Range of data

### ISSUE THREAD

**Issue by acagastya** [moment/moment-timezone#851]
Hi.  Could you please tell me if `moment-timezone-with-data-10-year-range.js` is dynamic -- in the sense if I am using it on Jan 1, 2021, will it show predictable results till Jan 1, 2031?

And more importantly, what is the range of `moment-timezone-with-data.js`?  How far into future does it give accurate predictable results?

**Comment by ellenaua** [comment]
File moment-timezone-with-data-10-year-range.js is re-created during each release. 

For example, release of version 0.5.30 was done today so now moment-timezone-with-data-10-year-range.js contains data from May 16 2015 to May 16 2025

For dates outside that range it may give you wrong values. 

File moment-timezone-with-data.js contains information for date range from 1901 to 2038. For dates after 2038 it may give wrong values. 

We get information about daylight saving time changes from IANA - international organization - and  it's hard to predict how DST rules will change in that far future.

**Comment by acagastya** [comment]
@ellenaua So, if I am using `moment-timezone-with-data.js`, I can be sure the time till Dec 31, 2038 is correct to the best of IANA's predictions?

**Comment by ellenaua** [comment]
@acagastya - yes

**Comment by acagastya** [comment]
Okay.  Thank you, @ellenaua!

**Comment by acagastya** [comment]
@ellenaua Until when (in the past) does both `moment-timezone-with-data-10-year-range.js` and  `moment-timezone-with-data.js` give accurate predictable results?

**Comment by ichernev** [comment]
@acagastya as @ellenaua pointed out the range is computed during release, so it depends on which version of moment-timezone do you use. -with-data will have a longer range (sometimes until 2038, sometimes ~2500, and going as back to infinity (begining of time/data)), the other one is -5,+5 years from now (i.e release time).

```
'moment-timezone-with-data-10-year-range' : [currentYear - 5, currentYear + 5]
```
