### ISSUE TITLE
Cannot redeclare block-scoped variable 'tz'.

### ISSUE THREAD

**Issue by ellenaua** [moment/moment-timezone#858]
Hi @all if you have this issue with moment-timezone version 0.5.30 or higher just un-install @types/moment-timezone. Now .dts files are inside moment-timezone.

I sent a pull request to @types/moment-timezone to deprecate it but that PR is in progress
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44823

**Comment by ichernev** [comment]
I'm putting that in the changelog.
