### ISSUE TITLE
Missing copyright information for file copied from DefinitelyTyped.

### ISSUE THREAD

**Issue by pristinesource** [moment/moment-timezone#859]
The file at
https://github.com/moment/moment-timezone/blob/0.5.31/index.d.ts
is taken from
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/moment-timezone/moment-timezone.d.ts
but does not display the required copyright notice.

The DefinitelyTyped license (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/LICENSE) is the MIT License and states that the individual types are copyright their respective contributors and that copies (event partial) must include the copyright notice.  Since the file is authored by the individuals as shown in 
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/moment-timezone/index.d.ts
you should include a copyright notice for each of these authors.

**Comment by ellenaua** [comment]
Sorry, will update that

**Comment by ellenaua** [comment]
Added it - see if that comment is enough?

https://github.com/moment/moment-timezone/blob/develop/index.d.ts
https://github.com/moment/moment-timezone/blob/master/index.d.ts
