### ISSUE TITLE
ionic3 zonesForCountry<T extends true>(country: string, with_offset: T): T extends true ? MomentZoneOffset[] : never;?

### ISSUE THREAD

**Issue by kapilSoni101** [moment/moment-timezone#863]
Hi Team,
I got above issue from 2 days but nothing worked for me.i have tried each and everything but nothing worked for me.can anybody tell me how to fix above issue?
below i have upload package.json file plz check and let me know what i am wrong or how to fix above issue?

**Tried solution**
Downgrade appp-script version from 3.2.4 to 3.2.2, 3.2.3
Delete node module then install again
{
  "name": "Demo_App",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "start": "ionic-app-scripts serve",
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint"
  },
  "dependencies": {
    "@angular/animations": "5.2.11",
    "@angular/common": "5.2.11",
    "@angular/compiler": "5.2.11",
    "@angular/compiler-cli": "5.2.11",
    "@angular/core": "5.2.11",
    "@angular/forms": "5.2.11",
    "@angular/http": "^7.2.16",
    "@angular/platform-browser": "5.2.11",
    "@angular/platform-browser-dynamic": "5.2.11",
    "@ionic-native/app-version": "^4.20.0",
    "@ionic-native/calendar": "^4.20.0",
    "@ionic-native/camera": "^4.20.0",
    "@ionic-native/core": "4.20.0",
    "@ionic-native/date-picker": "^4.20.0",
    "@ionic-native/device": "^4.20.0",
    "@ionic-native/facebook": "^4.20.0",
    "@ionic-native/fcm": "^4.20.0",
    "@ionic-native/file": "^4.20.0",
    "@ionic-native/file-path": "^4.20.0",
    "@ionic-native/file-transfer": "^4.20.0",
    "@ionic-native/google-analytics": "^4.20.0",
    "@ionic-native/google-plus": "^4.20.0",
    "@ionic-native/image-picker": "^4.20.0",
    "@ionic-native/in-app-browser": "^4.20.0",
    "@ionic-native/keyboard": "^4.20.0",
    "@ionic-native/network": "^4.20.0",
    "@ionic-native/social-sharing": "^4.20.0",
    "@ionic-native/splash-screen": "4.20.0",
    "@ionic-native/status-bar": "4.20.0",
    "@ionic-native/youtube-video-player": "^4.20.0",
    "@ionic/storage": "2.2.0",
    "@ngx-translate/core": "^9.1.1",
    "@ngx-translate/http-loader": "^3.0.1",
    "@types/moment-timezone": "^0.5.13",
    "angular-moment-timezone": "^1.7.1",
    "cordova-android": "^8.0.0",
    "cordova-fabric-plugin": "^1.1.14-dev",
    "cordova-ios": "^5.1.1",
    "cordova-plugin-app-version": "^0.1.9",
    "cordova-plugin-calendar": "^5.1.5",
    "cordova-plugin-camera": "^4.1.0",
    "cordova-plugin-datepicker": "^0.9.3",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-facebook4": "^6.4.0",
    "cordova-plugin-fcm-with-dependecy-updated": "^6.4.0",
    "cordova-plugin-file": "^6.0.2",
    "cordova-plugin-file-transfer": "^1.7.1",
    "cordova-plugin-filepath": "^1.5.8",
    "cordova-plugin-google-analytics": "^1.9.0",
    "cordova-plugin-googleplus": "^8.5.0",
    "cordova-plugin-inappbrowser": "^3.2.0",
    "cordova-plugin-ionic-keyboard": "^2.2.0",
    "cordova-plugin-ionic-webview": "^4.2.1",
    "cordova-plugin-network-information": "^2.0.2",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-telerik-imagepicker": "^2.3.3",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-plugin-x-socialsharing": "^5.6.8",
    "cordova-plugin-youtube-video-player": "^2.4.0",
    "es6-promise-plugin": "^4.2.2",
    "ionic-angular": "3.9.9",
    "ionicons": "3.0.0",
    "moment": "^2.26.0",
    "node-sass": "^4.14.1",
    "rxjs": "5.5.11",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.29"
  },
  "devDependencies": {
    "@ionic/app-scripts": "^3.2.3",
    "typescript": "2.6.2"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {
        "ANDROID_SUPPORT_ANNOTATIONS_VERSION": "27.+"
      },
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-fcm-with-dependecy-updated": {
        "FCM_VERSION": "19.0.0",
        "GRADLE_TOOLS_VERSION": "3.5.3",
        "GOOGLE_SERVICES_VERSION": "4.3.3",
        "SUPPORT_LIBRARY_VERSION": "28.0.0",
        "ANDROID_DEFAULT_NOTIFICATION_ICON": "@mipmap/ic_launcher"
      },
      "cordova-plugin-network-information": {},
      "cordova-plugin-inappbrowser": {},
      "cordova-plugin-camera": {
        "ANDROID_SUPPORT_V4_VERSION": "27.+"
      },
      "cordova-plugin-youtube-video-player": {},
      "cordova-plugin-file": {},
      "cordova-plugin-app-version": {},
      "cordova-plugin-datepicker": {},
      "cordova-plugin-calendar": {
        "CALENDAR_USAGE_DESCRIPTION": " ",
        "CONTACTS_USAGE_DESCRIPTION": " "
      },
      "cordova-plugin-google-analytics": {
        "GMS_VERSION": "11.0.1"
      }
    },
    "platforms": [
      "android",
      "ios"
    ]
  }
}
team can you please team me how to above issue i have stugged above issue from 2 days?

**Comment by ichernev** [comment]
Next time say what is "not working", don't just paste tons of crap.
