### ISSUE TITLE
File size huge with node

### ISSUE THREAD

**Issue by RWOverdijk** [moment/moment-timezone#865]
I've googled around a bit and found suggestions to reduce the file size with webpack.

I'm using this lib with node and so I don't really use webpack. Installing this lib comes in at 6.3M (as it includes moment, too).

Any suggestions on how to reduce this?
89%(!) of our entire codebase is now moment(-timezone).

**Comment by gilmoreorless** [comment]
There's definitely a lot of repetition in the `builds/` directory when installing `moment-timezone` in Node. This is a side-effect of having to support a lot of different use cases in one package.

I'm curious though, does the file size have a noticeable impact on your Node app?

**Comment by RWOverdijk** [comment]
It does for startup times with firebase function and storage. But I'm not using this anymore.

**Comment by RWOverdijk** [comment]
@web-programmer-here I'm not using this, so nah.
