### ISSUE TITLE
Get a list of timezones for given time

### ISSUE THREAD

**Issue by jaschaio** [moment/moment-timezone#866]
It might not be the right place for this, but I couldn't find an answer to it.

Is it possible to get a list of all timezones where it's currently `9:00 am`? Or even `Friday, 12th of June 9:00 am`?

Use case:

I would like to send a notification to all users at the same time in their local timezone. I currently do that using the `new Date().getTimezoneOffset()` method which returns the UTC offset – but of course that might change around the year with daylight saving time so my notifications are sometimes off for an hour. It would be better if I could just get a list of timezones for a given time instead.

A workaround I just thought about is as well getting a list of all timezones that are at a specific UTC offset for a given time. But I think neither of those functionalities is actually possible using `moment timezone`

**Comment by ellenaua** [comment]
It's good feature request, @jaschaio. This is how you can achieve that:

```
const moment = require('moment-timezone');

const zones = moment.tz.names().filter(tinezoneName => {
    return moment().tz(tinezoneName).format('HH') === '09';
})

console.log(zones)
```

**Comment by jaschaio** [comment]
Thanks a lot for your reply @ellenaua. As always the solution is quite simple once you see it :)
