### ISSUE TITLE
Imported third-party library is redefining the tz from moment

### ISSUE THREAD

**Issue by rafaelmaiolla** [moment/moment-timezone#868]
It seems that if there is a library in the application which includes a different `moment-timezone` version, once that is loaded it is going to replace the already loaded `moment-timezone` and reset any configuration.

This is what is going to happen:
```js
const moment = require('moment-timezone'); // moment-timezone@0.5.31
moment.tz.setDefault('America/Los_Angeles');
console.log(moment().tz()); // prints 'America/Los_Angeles'

const thirdPartyLibrary = require('some-third-party-library'); // which includes moment-timezone@0.5.27
console.log(moment().tz()); // prints 'undefined'
```

Shouldn't moment-timezone check if 'moment.tz' is already defined before defining it again?

I had to solve that by making all my dependencies to use the same moment version to avoid the issue, which doesn't seem to be ideal...

**Comment by C0ZEN** [comment]
Here a Stacktrace I have on an Angular 10 project.

```
ERROR in node_modules/moment-timezone/index.d.ts:63:11 - error TS2451: Cannot redeclare block-scoped variable 'tz'.

63     const tz: MomentTimezone;
             ~~

  node_modules/@types/moment-timezone/moment-timezone.d.ts:66:9
    66   const tz: MomentTimezone;
               ~~
    'tz' was also declared here.
node_modules/@types/moment-timezone/moment-timezone.d.ts:66:9 - error TS2451: Cannot redeclare block-scoped variable 'tz'.

66   const tz: MomentTimezone;
           ~~

  node_modules/moment-timezone/index.d.ts:63:11
    63     const tz: MomentTimezone;
                 ~~
    'tz' was also declared here.
```

Dunno for now but the project is no longer working.
Using the latest moment/moment-tz and types versions.

**Comment by ichernev** [comment]
I mean if you have 2 different versions of the same library I don't know what you'd expect, especially if it has "state" (not pure methods etc). Fix your dependencies :)
