### ISSUE TITLE
Moment.js returns invalid date when using timezone with format zz or z and strict mode

### ISSUE THREAD

**Issue by pvelez-bp3** [moment/moment-timezone#876]
The library returns invalid-date error when using a valid date with the the timezone in format zz or z and strict mode.

This is the fiddle that shows the example [https://jsfiddle.net/ub2v6gak/](https://jsfiddle.net/ub2v6gak/)

We are working on a project that uses [boostrap-datetimepicker v4.17.47](http://eonasdan.github.io/bootstrap-datetimepicker/) , moment.js v: 2.21.0 and moment-timezone 0.5.14,  and when we set the following parameters:
- month format MMM or MMMM
- strict mode
- timezone z or zz

It is returning an invalid date error.

Thanks for your attention.

**Comment by mongoose700** [comment]
According to the docs, `z`/`zz` are not available for parsing. They're just available for formatting.

**Comment by pvelez-bp3** [comment]
Well, if you use z/zz and the month format is M/MM it works fine. It fails when the month format is MMM or MMMM. And that is when it becomes weird.

**Comment by mongoose700** [comment]
I'm not seeing that behavior. When I modify your example in the fiddle to use `MM` (and `06`) instead, it's still invalid.

**Comment by ichernev** [comment]
```
// now returns true
console.log(moment.tz('17-Jun-2020 10:25:52', 'DD-MMM-YYYY HH:mm:ss', true, 'America/Chicago').isValid());

// now returns true
console.log(moment.tz('17-June-2020 10:25:52', 'DD-MMMM-YYYY HH:mm:ss', true, 'America/Chicago').isValid());

// returns EDT
console.log(moment.tz('17-Jun-2020 10:25:52', 'DD-MMM-YYYY HH:mm:ss', true, 'America/New_York').format('z'));
```
Well if you want to use strict parsing you still need to use `moment.tz` if you want to pass the timezone as a last argument. Also, drop the `z` in the parse string and it's all good.
