### ISSUE TITLE
Unexpected toJSON result

### ISSUE THREAD

**Issue by NormanV41** [moment/moment-timezone#880]
hi guys, I get an unexpected result with toJSON(), I share the [jsfiddle](https://jsfiddle.net/nrvasquez41/kshjLrgm/4/).

**Comment by mongoose700** [comment]
This has nothing to do with `toJSON`. According to the docs,`zz` is not supported for parsing, only for formatting. So it's using `Sun, 26 Jul 2020 17:38:18` as a local time in the specified time zone.
