### ISSUE TITLE
moment.tz.setDefault(..) negated after some time

### ISSUE THREAD

**Issue by simplecommerce** [moment/moment-timezone#882]
Hi,

I am having a weird issue that I am not sure how to debug.
In my app, I set the default timezone to `America/Toronto` when the server starts.
After that, all my calls to moment have the correct timezones.

But for some reason, the timezone seems to reset itself to `null` after a while and I don't know why.

I did a test by logging all my calls and see that after a while `moment().tz()` returns `null`.

I only have one instance of `moment.tz.setDefault(timezone);` set when my app starts.

I am trying to find out how I can debug this, and find out what makes it reset.

I would appreciate any hint on how I could debug this to find out if its a bug?

I am using 0.5.31 and moment 2.7.0.

Any help is appreciated, thanks!

**Comment by gongAll** [comment]
I believe you're using moment@2.27.0 correct? If so, try it out with moment@2.24.0. After that version, timezone stopped mysteriously working.

**Comment by simplecommerce** [comment]
@gongAll What is weird is that it does work most of the time but eventually stops working or is intermittent.

In one site, I had to do `if (!moment().tz()) moment.tz.setDefault(timezone);` in order to prevent it from causing issues.
All my sites have the same code and versions and only one seem to be affected which is very odd and why I haven't been able to reproduce the error.

Unless I know how to debug it I can't be sure its 100% fixed.

**Comment by ichernev** [comment]
Well, you can wrap all calls to moment in a few functions of yours, which will let you A) log all uses of moment and B) check which use has tz == null, so you can know which thing breaks it (the one before).

I mean, you mention server, I'm not sure why don't you just set the timezone in the middlewere (i.e on every request), so you don't have to deal with this crap, but if you find the bug we'll be happy to fix it :)

**Comment by simplecommerce** [comment]
I will close this since I "patched" the issue to move on a long time ago.
Thanks!
