### ISSUE TITLE
moment-timezone  ECMAScript module

### ISSUE THREAD

**Issue by Eraldo** [moment/moment-timezone#883]
I am using moment-timezone in an angular project right now.

I get the following warning/trace:
```
component.ts depends on 'moment-timezone'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

I search for this warning and found a statement suggesting to prompt the maintainers to feature an  ECMAScript module for the dependency in question.

Angular version:  10.0.3

**Comment by nealyip** [comment]
I got this warning message too

**Comment by Michael-Ziluck** [comment]
Big +1 from me. I did not realize this was a problem before Angular started warning me about it. Would be nice to get a reply from the maintainers of this project if possible.

**Comment by msklvsk** [comment]
There was a PR 4y ago: https://github.com/moment/moment-timezone/pull/310.
Maintainers’ answer is basically ”Use [Luxon](https://moment.github.io/luxon/).“

**Comment by jaequery** [comment]
man, that is sad ...

**Comment by Eraldo** [comment]
> man, that is sad ...
I agree.

**Comment by ricardosaracino** [comment]
if you wind up here might be worth noting how to get rid of the warning

![image](https://user-images.githubusercontent.com/759253/96287618-3737da00-0fb0-11eb-95c0-208e8087177f.png)

**Comment by ichernev** [comment]
Eh, I guess we could bundle 2 versions of moment(-timezone), one with require and the other with the module syntax, now that this is the de-facto way to ship JS libs. It just felt wrong back in the day when JS folks introduced modules with zero oversight about existing code. When we spend a lot of time about backwards compatibility, supporting shit that is more than 10y old and they just broke the entire ecosystem... it's sad.  Move fast and break things, or just break them...
