### ISSUE TITLE
moment.tz(moment.tz.guess()).format('z') works differently in prod environment

### ISSUE THREAD

**Issue by GORA-SAG** [moment/moment-timezone#884]
Hi,
Am using moment-timezone version 0.5.28. And for the below code snippet

`moment.tz(moment.tz.guess()).format('z') or moment.tz(moment.tz.guess()).zoneAbbr()`

am getting Asia/Kolkata for moment.tz.guess() and IST as the result locally.
But using the same code snippet in prod gives me UTC.

Any solution or workaround is available for this issue.

Regards,
Gokul Raj S

**Comment by ellenaua** [comment]
Hi @GORA-SAG do you do that on backend or on frontend?

On back-end (in Node.js) usually production servers are set to use UTC timezone.
