### ISSUE TITLE
Offset instead of abbreviation?

### ISSUE THREAD

**Issue by acagastya** [moment/moment-timezone#885]
Hi, I tried doing `moment.tz([2012, 0], 'Asia/Kathmandu').format('z');`, and instead of getting `NST` (Nepal Standard Time), I get the offset `0545`.  It also does not work with `.format('Z')`.  And also for `Asia/Krasnoyarsk`.  Is it deliberate?  Can you please add it?

**Comment by ichernev** [comment]
Yes, according to IANA the name of the zone is 0545. If you feel this is wrong please write to them:
```
Zone	Asia/Kathmandu	5:41:16 -	LMT	1920
			5:30	-	+0530	1986
			5:45	-	+0545
```

Also check https://github.com/moment/moment-timezone/issues/723
