### ISSUE TITLE
Parse and Convert PDT to UTC

### ISSUE THREAD

**Issue by axi92** [moment/moment-timezone#886]
I need to parse two variants of dates:
1. "18 Aug @ 7:18am"
2. "31 Dec, 2015 @ 10:49am"

These are in PT and I need to convert them to the local time.

I was able to parse the first and add 9 hours. But I dont know if this works out with summer and winter time.
`console.log(moment('18 Aug @ 7:18am PDT', 'DD MMM @ h:mm').add(9, 'hours'));`

How do I parse it in PT and then convert it to UTC or any local time?

**Comment by nathansollenberger-penguinpay** [comment]
Do not manually adjust the hours, let moment-timezone handle it for you.

```
> moment.tz("2020-08-18 07:18", "America/Los_Angeles").utc()
Moment<2020-08-18T14:18:00Z>
> moment.tz("2015-12-31 10:49", "America/Los_Angeles").utc()
Moment<2015-12-31T18:49:00Z>
```

Note that you'll need to use a string format that moment can parse (see moment docs for more on that).
