### ISSUE TITLE
SGT not showing in timezone

### ISSUE THREAD

**Issue by apcheung** [moment/moment-timezone#888]
When use (UTC+08:00) Kuala Lumpur, Singapore, the time zone displayed "+08" instead of SGT.

**Comment by evantobin** [comment]
+1 I am experiencing this as well

**Comment by zeel91297** [comment]
Can anyone suggest an alternative for this? @apcheung @evantobin

**Comment by gilmoreorless** [comment]
To clarify the back story here...

All time zone data in Moment Timezone comes from the [IANA time zone database](https://www.iana.org/time-zones). Many years ago, the database maintainers invented abbreviations for time zones that didn't have a well-defined one in common use. This was later regarded as a mistake, and they've been progressively removing these inventions.

There's now more diligence about only using abbreviations that were in common use _before_ the database was created. The [tzdb theory documentation](https://data.iana.org/time-zones/theory.html#abbreviations) has more details about which time zone abbreviations are in use and why.

The "SGT" abbreviation for Singapore was removed from the database 4 years ago in release `2017a`.
