### ISSUE TITLE
offset wrong on Berlin after year 2499

### ISSUE THREAD

**Issue by hieplq** [moment/moment-timezone#891]
before last sun of Mar and before last sun of Oct Berlin offset should be +2
but from 2500 it always return +1

https://jsfiddle.net/hieplq/ozr2ytak/40/

======== 
https://github.com/eggert/tz/blob/2020a/europe
Rule	EU	1981	max	-	Mar	lastSun	 1:00u	1:00	S
Rule	EU	1996	max	-	Oct	lastSun	 1:00u	0

# Zone	NAME		STDOFF	RULES	FORMAT	[UNTIL]
Zone	Europe/Berlin	0:53:28 -	LMT	1893 Apr
			1:00	C-Eur	CE%sT	1945 May 24  2:00
			1:00 SovietZone	CE%sT	1946
			1:00	Germany	CE%sT	1980
			1:00	EU	CE%sT

**Comment by gilmoreorless** [comment]
This is a limitation of the tzdb itself — the compiled data files only encode the actual transition times. They have to stop _somewhere_, and currently the chosen upper limit is the year 2500.

This can be seen by the output of `zdump` from the `tz` project (on machines with the 64-bit data installed):

```sh
$ zdump -V Europe/Berlin
Europe/Berlin  Fri Mar 31 23:06:31 1893 UT = Fri Mar 31 23:59:59 1893 LMT isdst=0 gmtoff=3208
Europe/Berlin  Fri Mar 31 23:06:32 1893 UT = Sat Apr  1 00:06:32 1893 CET isdst=0 gmtoff=3600
Europe/Berlin  Sun Apr 30 21:59:59 1916 UT = Sun Apr 30 22:59:59 1916 CET isdst=0 gmtoff=3600
Europe/Berlin  Sun Apr 30 22:00:00 1916 UT = Mon May  1 00:00:00 1916 CEST isdst=1 gmtoff=7200
[... snipped for clarity ...]
Europe/Berlin  Sun Oct 26 00:59:59 2498 UT = Sun Oct 26 02:59:59 2498 CEST isdst=1 gmtoff=7200
Europe/Berlin  Sun Oct 26 01:00:00 2498 UT = Sun Oct 26 02:00:00 2498 CET isdst=0 gmtoff=3600
Europe/Berlin  Sun Mar 29 00:59:59 2499 UT = Sun Mar 29 01:59:59 2499 CET isdst=0 gmtoff=3600
Europe/Berlin  Sun Mar 29 01:00:00 2499 UT = Sun Mar 29 03:00:00 2499 CEST isdst=1 gmtoff=7200
Europe/Berlin  Sun Oct 25 00:59:59 2499 UT = Sun Oct 25 02:59:59 2499 CEST isdst=1 gmtoff=7200
Europe/Berlin  Sun Oct 25 01:00:00 2499 UT = Sun Oct 25 02:00:00 2499 CET isdst=0 gmtoff=3600
```

I don't think any system that's based on the IANA database will have the correct values for 2500 and beyond, unless they're doing extra tricks. But it's important to note that time zones are based almost entirely on politics, and any data for long-future events is a pure guess. The likelihood that the current data will actually be correct even 50 years from now is very low (especially given the [EU is planning on changing all the rules soon](https://www.timeanddate.com/time/europe/eu-dst.html)).

**Comment by hieplq** [comment]
> unless they're doing extra tricks

seem Java don't use compiled data, it use rule calculate so after 2500 follow latest rule

thanks for your comment so I know how to adjust value from javascript on java world
