### ISSUE TITLE
moment-timezone: Parsing in given time zone interface gets overridden if timezone identifier present

### ISSUE THREAD

**Issue by iyerusad** [moment/moment-timezone#895]
[Documentation ](https://momentjs.com/timezone/docs/#/using-timezones/) states:

> `moment.tz(..., String)` does _parsing in given time zone_

But if you provide a time that has a timezone identifier, it overrides this behavior (as I understand it):

```
moment.tz("1950-03-01T00:00:00.000Z", "America/Los_Angeles").toISOString() // "1950-03-01T00:00:00.000Z"
moment.tz("1950-03-01T00:00:00.000", "America/Los_Angeles").toISOString() // "1950-03-01T08:00:00.000Z" #expected result
```

When its clearly presented, its easy to see. It becomes a bit more convoluted when doing something like this:
```
moment.tz(new Date("Mar 01, 1950"), "America/Los_Angeles").toISOString() // "1950-03-01T07:00:00.000Z" #MST localtimezone
```
which behaves alot closer to `moment().tz(String)`:
```
moment("1950-03-01T00:00:00.000").tz("America/Los_Angeles").toISOString() // "1950-03-01T07:00:00.000Z"
```

Is it possible the documentation could be updated in to reflect that `moment.tz(..., String)` may behave unexpectedly if the provided datetime includes timezone identifier? Perhaps I'm a little slow, but it seemed like this would be relevant in this section: https://momentjs.com/timezone/docs/#/using-timezones/

**Comment by ichernev** [comment]
I don't think there is anything unclear about the behavior.

If you do `moment.tz(new Date("Mar 01, 1950"), "America/Los_Angeles")` or `moment("1950-03-01T00:00:00.000").tz("America/Los_Angeles")`, you essentially give a local-zone zoned moment object and THEN change the timezone. If you want to keep "the timestamp" (i.e day, hour, etc), you can pass `true`, as a second argument to `tz`: https://momentjs.com/timezone/docs/#/using-timezones/converting-to-zone/

The canonical way to use it is to parse a string in a given timezone (your first examples). If you already have a date (moment or js Date), then you have to decide what you want to keep -- the time it represents (the UTC timestamp) or the local-time digits (Local timestamp).

Keeping UTC timestamp is default -- you made a local date about midnight 1st Mar, 1950, and you convert to LA time, it would likely not be midnight.
Keeping Local requires passing true -- you want the timestamp string to be 1950-03-01T00:00:00(ignoring the zone offset of course), so it can become LA time 1st Mar at midnight (keep in mind that this midnight is at a different time than the original date object).

**Comment by ichernev** [comment]
I mean, it's even documented right now...

```
Unix timestamps and `Date` objects refer to specific points in time, thus it doesn't
make sense to use the time zone offset when constructing. Using `moment.tz(Number|Date, zone)`
is functionally equivalent to `moment(Number|Date).tz(zone)`.
```
