### ISSUE TITLE
Add abbrs on -3 timezone

### ISSUE THREAD

**Issue by rhapsodygirl** [moment/moment-timezone#897]
Hi,

I found an issue, if you want to display the timezone name it will only display the numer "-3"

It's working for a lot of timezones like:
AEST, CET, PDT

But If I want to use any timezone under -3 or -4 it won't work.

I've tried every city under -3 and it's not working
(moment.tz('2020-10-06T14:30:00.000-07:00'), 'America/Sao_Paulo').format('MMMM D, YYYY hh:mmA zz'));
(moment.tz('2020-10-06T14:30:00.000-07:00'), 'America/Buenos_Aires').format('MMMM D, YYYY hh:mmA zz'));

You can go to https://momentjs.com/timezone/ and click on the map there and see the issue.

Thanks

**Comment by gilmoreorless** [comment]
All time zone data in Moment Timezone comes from the [IANA time zone database](https://www.iana.org/time-zones). Many years ago, the database maintainers invented abbreviations for time zones that didn't have a well-defined one in common use. This was later regarded as a mistake, and they've been progressively removing these inventions.

There's now more diligence about only using abbreviations that were in common use _before_ the database was created. The [tzdb theory documentation](https://data.iana.org/time-zones/theory.html#abbreviations) has more details about which time zone abbreviations are in use and why.
