### ISSUE TITLE
Zone Data Builder

### ISSUE THREAD

**Issue by mattjohnsonpint** [moment/moment-timezone#9]
The online zone data builder is pretty cool.  But it needs a few things:
- Something at the top of the builder, and in the generated data file, that show the version of the TZDB that was used to generated the data, (i.e., "2013d")
- An easy way to select all zones - or a quick link to download the file containing all zones.  (limiting the data may help for browser scenarios, but node.js apps will probably want the whole thing)
- A link to download the generated output as a .js or .json file.  Perhaps with an option to minify.
- Instructions for running the builder yourself offline.  Often people will want to build the file directly from the IANA/Olson sources.  Sometimes there are fixes in eggert/tz that aren't yet in a release and people need to get them out to customers in a hurry.

**Comment by plimpton** [comment]
I've heard that the data builder is no longer needed as of version 0.1.0 but that may be old news. I'm assuming it's still waiting to be re-fixed?

**Comment by mj1856** [comment]
@timrwood  - Are you still working on a new data builder?  If not, we could make this up for grabs

**Comment by gilmoreorless** [comment]
Closing this given the maintenance mode status of the project.
