### ISSUE TITLE
any update to IANA tzdb 2020d?

### ISSUE THREAD

**Issue by casper5822** [moment/moment-timezone#900]
Hello,
there is a new release about IANA tz for timezone: 2020d 
https://www.iana.org/time-zones/repository/tzdb-latest.tar.lz

Is there any update in progress for the lib?

Antonio.

**Comment by probbinswork** [comment]
Hello,

The moment-timezone library currently supports the timezone US/Pacific-New whereas the IANA database doesn't seem to support it. Any plans to remove this? It has caused compatibility problems for us, as other libraries do not support it.
These are supported:
  tzdb-2020d/usr/bin/zdump -v America/Los_Angeles
  tzdb-2020d/usr/bin/zdump -v US/Pacific

This is not:
  usr/bin/zdump -v US/Pacific-New -> No such file or directory

Thanks!

**Comment by casper5822** [comment]
the 2020d has an empty pacificnew file. I read that in the 2020a this file was removed and this create the problem so an empty file was created for compatibility and the 2020d was released. So my question is, does it work or do you have no such file execption?

**Comment by probbinswork** [comment]
Hi!

We use this library, in our javascript frontend, but it ultimately causes a problem in our Java backend, as it isn't supported. 

What we need it for these libraries to be in sync. So, I think the best solution for us would be for moment-timezone not to support it, so our customers do not select it. Then, we will not be storing a value that our Java backend may not support.

**Comment by ellenaua** [comment]
Hi all. I just released version 0.5.32 with 2020d - you can try it, please report about any issues

**Comment by Schnark** [comment]
Where is the released version? Both the files in the builds folder and the files on https://momentjs.com/timezone/ still use 2020a.
