### ISSUE TITLE
Moment time zone not have all short code time zone name

### ISSUE THREAD

**Issue by suryansh54** [moment/moment-timezone#902]
Moment time zone does not have all abbreviations
**List of time zone abbreviations**: https://en.wikipedia.org/wiki/List_of_time_zone_abbreviations
**Examples**
UTC+5:30 is IST
UTC+5 is +5
and many more.

**Comment by ichernev** [comment]
Please check https://github.com/moment/moment-timezone/issues/723

If you feel strongly about timezone abbreviations, write to IANA with supporting evidence. We just use the data they carefully assemble and curate.
