### ISSUE TITLE
Please consider removing US/Pacific-New

### ISSUE THREAD

**Issue by probbinswork** [moment/moment-timezone#903]
Hello,

The moment-timezone library currently supports the timezone US/Pacific-New whereas the IANA database doesn't seem to support it. Any plans to remove this? It has caused compatibility problems for us, as other libraries do not support it.
These are supported:
tzdb-2020d/usr/bin/zdump -v America/Los_Angeles
tzdb-2020d/usr/bin/zdump -v US/Pacific

This is not:
usr/bin/zdump -v US/Pacific-New -> No such file or directory

Thanks!

PS: The comments on the following issues suggest that you are attempting to stay in sync with IANA: https://github.com/moment/moment-timezone/issues/498

**Comment by ellenaua** [comment]
I just released version 0.5.32 - it has no US/Pacific-New anymore

**Comment by ichernev** [comment]
2022c also
