### ISSUE TITLE
 Property 'tz' does not exist on type 'Moment'  Error

### ISSUE THREAD

**Issue by rama41222** [moment/moment-timezone#906]
nodejs version: `12.18.4`
moment-timezone version:` 0.5.31`
moment version: `^2.29.0`
ts-node version: happens both in 9.0.0(latest), `8.6.2`
command: `ts-node --files server/app.ts --project server/tsconfig.build.json`

usage

```
import moment from 'moment-timezone'
moment(somedate).tz(sometimezone)
```
No `@types/moment or @types/moment-timezone` installed since deprecated.

What could be the reason ? 

PS: Already checked this [Issue]( https://github.com/moment/moment-timezone/issues/385)

**Comment by sliceofcode** [comment]
I'm having exactly the same issue.

node version: `12.14.1`
moment version: `2.24.0`
moment-timezone version: `0.5.31`
ts-node version: `8.3.0`

Usages:
```
import * as moment from 'moment';
import 'moment-timezone';
moment.tz.setDefault('UTC');
```
```
import * as moment from 'moment-timezone';
moment.tz.setDefault('UTC');
```
They yield same result:
```
TS2339: Property 'tz' does not exist on type 'typeof moment'.
```

**Comment by rama41222** [comment]
Any update regarding this ?

**Comment by sliceofcode** [comment]
I resolved this by downgrading the `moment-timezone` package to `0.5.28` (instead of `0.5.31`). 

I found that the offending lines in `0.5.31` with my setup are:

`index.d.ts`:
```
zonesForCountry<T extends true>(country: string, with_offset: T): T extends true ? MomentZoneOffset[] : never;
zonesForCountry<T extends false>(country: string, with_offset?: T): T extends false ? string[] : never;
```

**Comment by ConneXNL** [comment]
Using the latest version at this time of writing:
 `moment-timezone@0.5.33` and `@types/moment-timezone@0.5.30` I do not have the issue:

```
import 'moment-timezone';
import moment from 'moment';
```

`moment().tz('CEST')`  <- no errors..

So I think this is issue is resolved.

**Comment by manuel-di-iorio** [comment]
No issues after installing @types/moment-timezone@0.5.30
Thanks @ConneXNL

**Comment by rama41222** [comment]
I'm closing this since the issue is resolved.

**Comment by vishal21-onelife** [comment]
i sove this problem
1. install package
npm i moment-timezone

2.import time-zone in app.component.ts file
import 'moment-timezone';

3.save and run

-check some moment-timezone not work

**Comment by AbdelrahmanHafez** [comment]
This issue re-occured again with the following versions:
```json
"moment": "2.29.3",
"moment-timezone": "0.5.34"
```

Downgrading moment to 2.29.2 fixes the issue.

**Comment by masimpson123** [comment]
I was having this problem in just my test environment. I had to add `moment-timezone` to the types array in `tsconfig.spec.ts`. If no types array is present, all @types packages are visible. If a types array is present, only the listed packages are used by the compiler.

TSConfig and Types array documentation:
https://www.typescriptlang.org/tsconfig#types

Refactoring the app to use moment-timezone rather than moment also fixed the problem, but I decided that the tsconfig solution was simpler and less risky.

**Comment by MonstraG** [comment]
In my case, had to downgrade to 2.29.1 (2.29.2 still failed to build), resulting in 
```
		"moment": "2.29.1",
		"moment-locales-webpack-plugin": "^1.2.0",
		"moment-timezone": "^0.5.34",
```

my failing usecase:

```ts
import moment, { Moment } from "moment";
import "moment-timezone";

const func1 = (day: Moment, seconds: number, timeZone: string): Moment =>
	day.clone().add(seconds, "seconds").tz(timeZone, true).local();
```

**Comment by aailyin** [comment]
The same issue with versions:
```
"moment": "^2.29.3",
"moment-timezone": "^0.5.34",
"@types/moment-timezone": "^0.5.30"
```
Downgraded to 2.29.1, but it contains vulnerabilities.

**Comment by DiRover** [comment]
I'm having the same issue.

moment version: 2.24.3
moment-timezone version: 0.5.34

When I wrote the next code, the issue is gone:

`import moment from 'moment-timezone';
 moment.tz.setDefault();`

**Comment by gilmoreorless** [comment]
This is generally caused by having multiple versions of `moment` imported at the same time, due to different dependency trees. I've written a full description at https://github.com/moment/moment-timezone/issues/982#issuecomment-1119540905

As noted by @DiRover, importing from _only_ `moment-timezone` should fix the issue in most cases.

**Comment by shnigi** [comment]
Solved by @gilmoreorless comments. Changed my import to
import moment, { tz } from "moment-timezone";
And working code
const timeOffset = moment().tz(timezone).format("Z")

**Comment by sahilSOLT** [comment]
import 'moment-timezone';
moment.tz.setDefault('UTC');

//then---------

var currentTimEzone = moment.tz.guess();
console.log('timezone here',currentTimEzone)
