### ISSUE TITLE
...and Pacific/Honolulu is not adjusting correctly to Daylight Savings either :(

### ISSUE THREAD

**Issue by wykananda** [moment/moment-timezone#907]
In addition to the other incorrect Daylight Savings adjustments posted in the last few days, Pacific/Honolulu is now hour earlier than it should be (Daylight Savings should **not** be affecting it but it is).  A fix soon would be greatly appreciated!

Current known timezones with issues
----
Pacific/Honolulu
America/Dawson
America/Tijuana
America/Vancouver
Pacific/Fiji

**Comment by holson1** [comment]
Adding America/Sao_Paulo to this list :/

> moment.tz('America/Sao_Paulo').dayOfYear(314).format()
'2020-11-09T22:33:52-02:00'

When currently Sao Paulo time should be 9:33 (GMT -3)

**Comment by bramski** [comment]
Apparently this should be fixed according to this SO post:
https://stackoverflow.com/questions/56527380/moment-timezone-america-sao-paulo-wrong-timezone-offset/56527498#56527498

**Comment by holson1** [comment]
You're correct @bramski - upgrading fixed it. Thank you!

**Comment by ellenaua** [comment]
@wykananda is it fixed for you if you use the latest moment-timezone?
This is my test with latest version:

```
console.log('Pacific/Honolulu', moment('2020-11-14T00:00:00Z').tz('Pacific/Honolulu').format())
console.log('America/Dawson', moment('2020-11-14T00:00:00Z').tz('America/Dawson').format())
console.log('America/Tijuana', moment('2020-11-14T00:00:00Z').tz('America/Tijuana').format())
console.log('America/Vancouver', moment('2020-11-14T00:00:00Z').tz('America/Vancouver').format())
console.log('Pacific/Fiji', moment('2020-11-14T00:00:00Z').tz('Pacific/Fiji').format())
```

Pacific/Honolulu 2020-11-13T14:00:00-10:00     --- correct offset
America/Dawson 2020-11-13T17:00:00-07:00    ---  correct offset
America/Tijuana 2020-11-13T16:00:00-08:00   ---  correct offset
America/Vancouver 2020-11-13T16:00:00-08:00   ---  correct offset
Pacific/Fiji 2020-11-14T12:00:00+12:00    ---  correct offset

**Comment by wykananda** [comment]
Yes, all seems to be good with the latest.  Thank you so much!
