### ISSUE TITLE
moment-timezone does not support America/Bogota timezone abbreviation name

### ISSUE THREAD

**Issue by abaruah1** [moment/moment-timezone#909]
Timezone abbreviation for bogota timezone is not being returned. 

moment().tz('America/Bogota').format('z') => '-05'

**Comment by ellenaua** [comment]
Hi @abaruah1 you expect COT or COST there right?

**Comment by ichernev** [comment]
IANA data (note `-05/-04` on last line):
```
Zone	America/Bogota	-4:56:16 -	LMT	1884 Mar 13
			-4:56:16 -	BMT	1914 Nov 23 # Bogotá Mean Time
			-5:00	CO	-05/-04
```

Also check https://github.com/moment/moment-timezone/issues/723
