### ISSUE TITLE
Timezone list does not contain Beijing

### ISSUE THREAD

**Issue by wangweiu** [moment/moment-timezone#913]
### Moment-timezone version which you use:

Version:  0.5.31

_Note: many issues are resolved if you just upgrade to the latest version_

### Issue description:

moment.tz.names() return a timezone list. But the list does not include Beijing, the capital and the largest city in China with 21 million people.  The standard time in China is called Beijing time.  It is not convenient for users in China without Beijing in timezone list.

**Comment by ellenaua** [comment]
Hi @wangweiu - official name for Beijing timezone is Asia/Shanghai
Or you think that does not suit your needs and you need Asia/Beijing timezone?

**Comment by wangweiu** [comment]
@ellenaua  Yes. I'd like Asia/Beijing in timezone.

**Comment by gilmoreorless** [comment]
All time zone data in Moment Timezone comes from the [IANA time zone database](https://www.iana.org/time-zones). The unique identifiers used for time zones have quite a few rules and restrictions, as listed in the [tzdb theory documentation](https://data.iana.org/time-zones/theory.html#naming). They _can_ be changed, but only under specific circumstances. This particular case is already mentioned in that document:

> * Use the most populous among locations in a region, e.g., prefer `Asia/Shanghai` to `Asia/Beijing`. Among locations with similar populations, pick the best-known location, e.g., prefer `Europe/Rome` to `Europe/Milan`. 
> * Do not change established names if they only marginally violate the above guidelines. For example, do not change the existing name `Europe/Rome` to `Europe/Milan` merely because Milan's population has grown to be somewhat greater than Rome's. 

(Although all the statistics I can find say that Shanghai still has a larger population than Beijing.)

However, the most important thing is that the identifiers are human-readable only for ease of using the database. They're not intended to be shown directly to end users of applications…

> Inexperienced users are not expected to select these names unaided. Distributors should provide documentation and/or a simple selection interface that explains each name via a map or via descriptive text like "Czech Republic" instead of the timezone name "`Europe/Prague`". If geolocation information is available, a selection interface can locate the user on a timezone map or prioritize names that are geographically close. For an example selection interface, see the `tzselect` program in the `tz` code. The [Unicode Common Locale Data Repository](http://cldr.unicode.org/) contains data that may be useful for other selection interfaces; it maps timezone names like `Europe/Prague` to locale-dependent strings like "Prague", "Praha", "Прага", and "布拉格".

**Comment by ichernev** [comment]
@gilmoreorless even I learned a few things :) The ubuntu installer had a nice timezone selector, which shows a map and a green area that "covers" the selected timezone. I know IANA has lat/lng for each zone, but i don't think it has country/zone outlines. Writing a decent interface is hard.

**Comment by n0099** [comment]
FYI
2008 https://bugs.launchpad.net/ubuntu/+source/libgweather/+bug/228554

https://lists.iana.org/hyperkitty/search?count=200&q=asia%2Fbeijing&page=11&sort=date-desc
2001 https://lists.iana.org/hyperkitty/list/tz@iana.org/message/LQ74CEY2M4DJDD6RN3G55RJASC5T6YKH/
2001 https://lists.iana.org/hyperkitty/list/tz@iana.org/thread/NDLKPXKL6KNOANX5TT3TMFYWHRADDUIO/
2006 https://lists.iana.org/hyperkitty/list/tz@iana.org/thread/RVT67KYGI66QAGQ23RIA2RHCBPSKKRPZ/
2006 https://lists.iana.org/hyperkitty/list/tz@iana.org/thread/X2444ZHZUUWOXDLQOSW3GG4JX47YHWTB/
2010 https://lists.iana.org/hyperkitty/list/tz@iana.org/thread/UYD4U6DB7UILXHJYYQBSMJKDRRLW2YFB/
2011 https://lists.iana.org/hyperkitty/list/tz@iana.org/thread/D365V2YRME2VXK3GKCSXBGWT4I37HLBP/
2011 https://lists.iana.org/hyperkitty/list/tz@iana.org/thread/YIXSIYE3HYEGNWSK334M3OIL3QCAQR7P/
2012 https://lists.iana.org/hyperkitty/list/tz@iana.org/thread/3NEFJUO35YG2CHW4O74L5X67Y5AUYJ5F/
2017 https://lists.iana.org/hyperkitty/list/tz@iana.org/thread/3JERDTC5LC7UK4A2XJVKSIURFDYIROGE/

**Comment by gilmoreorless** [comment]
Linking to issues from other projects from 12 years ago doesn't change the facts posted above. Especially since the other project also pointed out that the rules from the IANA tzdb haven't changed.
