### ISSUE TITLE
Incorrect conversion of DST

### ISSUE THREAD

**Issue by vladigubler** [moment/moment-timezone#914]
### Moment-timezone version which you use:

Version: 0.5.32

_Note: many issues are resolved if you just upgrade to the latest version_

### Issue description:
The following date 1985-04-12T04:00:00.000Z when converted to New York time zone results in 1985-04-11 11:00 PM. The correct value is 1985-04-12 12:00 AM. Apparently, DST rules are not applied correctly. Dates in 1986 and after work correctly.

**Comment by ichernev** [comment]
According to zdump:
```
...
America/New_York  Sun Oct 28 06:00:00 1984 UT = Sun Oct 28 01:00:00 1984 EST isdst=0 gmtoff=-18000
America/New_York  Sun Apr 28 06:59:59 1985 UT = Sun Apr 28 01:59:59 1985 EST isdst=0 gmtoff=-18000
...
```
As you can see 12th Apr 1985 has a gmtoff of -5:00 (-18000 / 60 / 60), so moment correctly reports that:
```
> moment.tz('1985-04-12T04:00:00.000Z', 'America/New_York').format()
'1985-04-11T23:00:00-05:00'
```
