### ISSUE TITLE
trying to format ES month 

### ISSUE THREAD

**Issue by aharon-vish** [moment/moment-timezone#915]
I am using moment-timezone Version 0.5.32

and I am trying to format the date
like this: 
`moment('dic. 23 2020  11:00').format('YYYY-MM-DD HH:mm');
`
I am getting that it's not valid.

any idea why?

**Comment by ellenaua** [comment]
What is 'dic.' here? Did you mean December?

**Comment by aharon-vish** [comment]
yes it's in Spanish

I have set 

```
require('moment/locale/es-us');
moment.tz.setDefault('es-us');
```
and then for display, I format the date 

`moment('Sun Dec 22 2020 18:00:18').format('MMM DD YYYY  HH:mm');
`
this line will give me :
`dic. 22 2020  18:00`

and this string I try to format (for sending to server)
`moment('dic. 22 2020  18:00').format('YYYY-MM-DD HH:mm');
`
result will be 
"Invalid date"

**Comment by gilmoreorless** [comment]
This looks like Moment doesn't know how to parse the string properly, and will need to be given a hint. As described in the [parsing guide](https://momentjs.com/guides/#/parsing/known-formats/):

> If you know the format of the date string that you will be parsing, it is always the best choice to explicitly specify that format.

So for your example, you should try adding a second argument of the format you're trying to parse.

```js
require('moment/locale/es-us');

// Result: 'Invalid date'
moment('dic. 23 2020 11:00').format('YYYY-MM-DD HH:mm');
/*
The line above also shows a warning for me...
"Deprecation warning: value provided is not in a recognized RFC2822 or ISO format.
moment construction falls back to js Date(), which is not reliable across all browsers and versions.
Non RFC2822/ISO date formats are discouraged.
Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info."
*/

// Providing the parsing format works.
// Result: '2020-12-23 11:00'
moment('dic. 23 2020 11:00', 'MMM DD YYYY HH:mm').format('YYYY-MM-DD HH:mm');
```

Also, the line `moment.tz.setDefault('es-us');` isn't needed. `moment.tz.setDefault()` changes the default time zone (something like `America/New_York`) but doesn't change the language being used for formatting and parsing.

**Comment by ichernev** [comment]
@aharon-vish as a start, learn the difference between a timezone (a set of rules specifying DST (daylight saving time) changes and fixed offsets) and a locale (a set of rules for representing things (dates in our case) as strings).

You can be located in Spain but might want to work with American timezones or whatever, so the two are not related much. Sure, there are countries for timezones for convenience, and countries have languages (locales) but the link is weak and moment/moment-timezone won't help you much with that.
