### ISSUE TITLE
Pre-built bundles have data mismatch with data files

### ISSUE THREAD

**Issue by Etchelon** [moment/moment-timezone#924]
### Moment-timezone version which you use:

Version: 0.5.32 (latest right now)

_Note: many issues are resolved if you just upgrade to the latest version_

### Issue description:

node_modules/moment-timezone/builds/moment-timezone-with-data.js

contains, for the "GL" country, the America/Godthab timezone, which has been deprecated, in fact all data files (metadata, unpacked and package latest) contain America/Nuuk instead (which has replaced Godthab).

I have seen that the entry point (index.js) loads the metadata files, but since the package.json tells bundlers to use builds/moment-timezone-with-data.js as the package's entry point, my Angular app contains the deprecated timezone hardcoded in the .js bundle.

Seems like a new version is needed with rebuilt bundles to fix the issue.

**Comment by gilmoreorless** [comment]
This is most likely caused by an issue where the data compilation process loses information about which zones are links: #835
