### ISSUE TITLE
Can't get timezone name using "z" format.

### ISSUE THREAD

**Issue by joemarieandres** [moment/moment-timezone#926]
### 0.5.32

Version:

_Note: many issues are resolved if you just upgrade to the latest version_

### Issue description:
I am going to get timezone name like "PST" etc.
But when I use format('z'), it gives me only offset not timezone name
How can I get the timezone name?

**Comment by gilmoreorless** [comment]
Which time zone(s) are you trying to get the abbreviation for? Not all time zones have proper abbreviations assigned. There's a small note about this in the [formatting documentation](https://momentjs.com/timezone/docs/#/using-timezones/formatting/):

> Please note that the `z` formatting token will not always show the abbreviated time zone name, instead, will show the time offsets for each region.

**Comment by ichernev** [comment]
@joemarieandres please check https://github.com/moment/moment-timezone/issues/723
