### ISSUE TITLE
dataVersion - type definition

### ISSUE THREAD

**Issue by andrewvsk** [moment/moment-timezone#930]
Please add `moment.tz.dataVersion` type definition.

https://github.com/moment/moment-timezone/blob/ffc41900fed9efa9a31e87f0eadd66ec86b5046a/moment-timezone.js#L574
https://github.com/moment/moment-timezone/blob/ffc41900fed9efa9a31e87f0eadd66ec86b5046a/moment-timezone.js#L532
https://github.com/moment/moment-timezone/blob/ffc41900fed9efa9a31e87f0eadd66ec86b5046a/index.d.ts#L32

**Comment by ichernev** [comment]
Next time submit a PR: f5b8769
