### ISSUE TITLE
get zoneName not match

### ISSUE THREAD

**Issue by do-ift** [moment/moment-timezone#932]
**Describe the bug**
result of function moment().zoneName() not match.

**To Reproduce**
I have `time` with 
```
_z:{
  abbrs: ["LMT", "PLMT", "+07", "+08", "+09", "+07", "+08", "+07", "+08", "+07"] (10)
  name: "Asia/Ho_Chi_Minh"
  offsets: [-426.6666666666667, -426.5, -420, -480, -540, -420, -480, -420, -480, -420] (10)
  population: 9000000
  untils: [-2004073600000, -1851577590000, -852105600000, -782643600000, -767869200000,
}
```

console.log(moment(time).zoneName()); // +07
console.log(moment(time).zoneAbbr()); // +07

**Expected behavior**
I think when I using console.log(moment(time).zoneName()), the result has been Asia/Ho_Chi_Minh

**Additional context**
I found on moment-timezone.js file 
`     fn.zoneName  = abbrWrap(fn.zoneName);`

but 

```
function abbrWrap (old) {
	return function () {
		if (this._z) { return this._z.abbr(this); }
			return old.call(this);
		};
	}
```

it return to abbr name.

moment-timezone version: 0.5.33

**Comment by ichernev** [comment]
As you can see in the source (IANA) data:
```
Zone Asia/Ho_Chi_Minh	7:06:30 -	LMT	1906 Jul  1
			7:06:30	-	PLMT	1911 May  1 # Phù Liễn MT
			7:00	-	+07	1942 Dec 31 23:00
			8:00	-	+08	1945 Mar 14 23:00
			9:00	-	+09	1945 Sep  2
			7:00	-	+07	1947 Apr  1
			8:00	-	+08	1955 Jul  1
			7:00	-	+07	1959 Dec 31 23:00
			8:00	-	+08	1975 Jun 13
			7:00	-	+07
```
Everything after May 1911 is using numeric offsets, not names (like LMT/PLMT). Check here: https://github.com/moment/moment-timezone/issues/723
