### ISSUE TITLE
Asia/Kolkata vs Asia/Calcutta

### ISSUE THREAD

**Issue by sovanjana** [moment/moment-timezone#934]
### Moment-timezone version which you use:

Version: latest

_Note: many issues are resolved if you just upgrade to the latest version_

### Issue description:
moment.tz.guess() gives us the result as **Asia/Calcutta** but in all other case I am getting **Asia/Kolkata** which is causing a mismatch in many places.

**Comment by ichernev** [comment]
The way guess works is pretty remarkable. If you can troubleshoot it and provide concrete fixes we might merge them in. Just don't expect me to travel to Calcutta to test this :) Evidently it depends on OS, Browser, user configuration etc etc. If you know what the zone is why bother with guess?

Docs: https://momentjs.com/timezone/docs/#/using-timezones/guessing-user-timezone/
