### ISSUE TITLE
Timezone guess with limited options

### ISSUE THREAD

**Issue by nikochiko** [moment/moment-timezone#941]
### Moment-timezone version which you use:

Version: 0.5.33

_Note: many issues are resolved if you just upgrade to the latest version_

### Issue description:

Is it possible to make moment guess a timezone but with limited options for timezones?

Something like this

```js
var timezones = ['UTC', 'America/Los_Angeles', 'Asia/Tokyo', 'Asia/Kolkata', 'Australia/Sydney', ... some more];
moment.setTimezones(timezones);

var guess = moment.tz.guess(); // must be from the list
```

**Comment by ichernev** [comment]
@nikochiko you can write it as a plugin, and possibly at some point merge it in (after writing a PR). But don't expect somebody else to do it for you :)

Keep in mind that moment and moment-timezone are in maintenace mode.
