### ISSUE TITLE
moment-timezone does not support abbreviation for America/Lima timezone

### ISSUE THREAD

**Issue by achrefBoukhili** [moment/moment-timezone#943]
### Moment-timezone version which you use:

Version: 0.5.33

_Note: many issues are resolved if you just upgrade to the latest version_

### Issue description:
`moment().tz('America/Lima').zoneAbbr()` return `-5` instead of `PE`
https://codesandbox.io/s/moment-timezone-test-forked-mt3l7?file=/src/index.js

**Comment by ichernev** [comment]
Check this: https://github.com/moment/moment-timezone/issues/723
