### ISSUE TITLE
How to disable and enable DST date conversion

### ISSUE THREAD

**Issue by ajit-soman** [moment/moment-timezone#950]
### Moment-timezone version which you use:

Version: 0.5.33

_Note: many issues are resolved if you just upgrade to the latest version_

### Issue description:

I am converting date & time from one timezone to another . In some of the dates, I notice 1 Hr difference in dates after conversion . I googled it , i found it is because of day light saving (DST). 

```
moment.tz('2021-10-18 12:00 am', 'YYYY-MM-DD hh:mm a', 'Asia/Kolkata')
            .tz('America/Toronto')
            .format('YYYY-MM-DD hh:mm a');
```
output: `2021-10-17 02:30 pm`

```
moment.tz('2021-11-18 12:00 am', 'YYYY-MM-DD hh:mm a', 'Asia/Kolkata')
            .tz('America/Toronto')
            .format('YYYY-MM-DD hh:mm a');
```

output: `2021-11-17 01:30 pm`

In the above code , i just changed the month and other date component are same but there is 1 Hr time difference in output because of DST.

Is there any way i can disable this DST conversion . so that i can get data & time without any hour change (like above) for all month ?

**Comment by gilmoreorless** [comment]
I'm not sure I understand this question. Handling daylight saving conversions is a large part of what this library is for. If the time zone you're converting into has DST active at that time, then that's the correct answer. 

What's your use case for needing the incorrect calculation without DST?

**Comment by ajit-soman** [comment]
@gilmoreorless I am going to close this issue because i found answer for my question. We can pass time zone code which does not support DST . For example `America/Creston`  and `America/Chihuahua` is UTC-07:00 . `America/Creston` does not support DST & `America/Chihuahua`  does . So when i want to convert a date to UTC-07:00 without DST , i can use `America/Creston` 

Here is a link which has information about DST & NON-DST timezone: https://appler.dev/time-zone-table
