### ISSUE TITLE
TimeZone always showing UST

### ISSUE THREAD

**Issue by hupad85** [moment/moment-timezone#951]
### Moment-timezone version which you use:

Version:
0.5.33

_Note: many issues are resolved if you just upgrade to the latest version_

### Issue description:
When I try to format a date with a given timezone, it's not displaying the correct timezone. Instead, it's always displaying UTC.

Example:
https://jsfiddle.net/pq9t4wf0/

**Comment by gilmoreorless** [comment]
Your example link is only loading the Moment Timezone functionality, but isn't loading any data. The browser console is showing a warning of `Moment Timezone has no data for America/Chicago. See http://momentjs.com/timezone/docs/#/data-loading/.` See the "with data" links at https://momentjs.com/timezone/

Additionally, you're using a fairly old version of the base Moment library that won't work with the latest version of Moment Timezone. When I run your JSFiddle example with `moment v2.29.1` and `moment-timezone-with-data.min.js`, it works correctly.
