### ISSUE TITLE
Stop supporting terrorists: REMOVE "Europe/Simferopol" from Russia.

### ISSUE THREAD

**Issue by Ilyahas** [moment/moment-timezone#954]
### Moment-timezone version which you use:

Version: since 2014b.json

### Issue description:

Accidentally, "Europe/Simferopol" was placed in MSK Time Zone. We need to remove "Europe/Simferopol" from RU and keep it only for UA.

In 2014 russia attacked independent country once again. But this time it affected the whole world. USA, Europe and other civilised world punished russia and imposed sanctions. Google, Valve and most other big Inc. blocked users from Crimea because this territory was illegally occupied by russian military. Recently Google announced that some services (e.g. console.cloud.google.com) won't support russian language anymore because russia violated world agreements about fixed territories and continue violate a lot of other agreements.
Today, "russia empire" continue hybrid war against Ukraine, Georgia and other Civilised Democracy World. Unfortunately, moment-timezone was influenced by russian propaganda. Look at your source in IANA (file: europe, line: 2826). It says that some russian Alexander Krivenyshev (who specialises mostly on russian time zones) based on russian news concluded that switching timezone to MSK for Simferopol it is fine because Crimea was occupied via "legitimate referendum". Hm, "yes", "legitimate" with military and weapons. And another not very smart guy Paul Eggert said: "the discrepancies are small enough to not worry about" (discrepancies between EEST and MSK). NOT WORRY ABOUT? Are you kidding? It's fundamental thing. The whole world didn't accept this annexation and talking about cruel occupation.
We don't have to stay outside and looking how criminal dictators killing peaceful people. We have to make our contribution to protection freedom, democracy world or at least do not create places for their propaganda.

So, we have to fix this misunderstanding and remove "Europe/Simferopol" from RU and keep it only for UA.
Or, we can remove "Europe/Simferopol" completely in order to block opportunity to develop something for Crimea until Ukraine resumes control of the territory.

Also we have to pay IANA's attention on this issue.

P.S. Read this document about russian war: https://mfa.gov.ua/en/10-facts-you-should-know-about-russian-military-aggression-against-ukraine

**Comment by Ilyahas** [comment]
Why? It was not solved!

**Comment by Ilyahas** [comment]
Considering

**Comment by ichernev** [comment]
Exactly, tell these guys to solve it, not us: https://www.iana.org/time-zones
