### ISSUE TITLE
Formatting Inconsistency with Date Type `M/D/YY`

### ISSUE THREAD

**Issue by ZainAmjad68** [moment/moment-timezone#957]
### Moment-timezone version which you use:
moment-timezone: `0.5.33`

### Issue description:
Some inconsistency between the century when formatting date is of type `M/D/YY`:
`moment(date, "M/D/YY").format("YYYY-MM-DD")` returns a different century if the provided year falls either side of 68.

Example:
`moment("4-15-69", "M/D/YY").format("YYYY-MM-DD")` returns `1969-04-15`
but
`moment("4-15-68", "M/D/YY").format("YYYY-MM-DD")` returns `2068-04-15`

There should be consistent behavior; same century for all the values OR there should be an option to choose the century of the date.

**Comment by gilmoreorless** [comment]
This behaviour is documented at https://momentjs.com/docs/#/parsing/string-format/:

> #### Parsing two digit years
>
> By default, two digit years above 68 are assumed to be in the 1900's and years 68 or below are assumed to be in the 2000's. This can be changed by replacing the `moment.parseTwoDigitYear` method. The only argument of this method is a string containing the two years input by the user, and should return the year as an integer.
> ```js
> moment.parseTwoDigitYear = function(yearString) {
>     return parseInt(yearString) + 2000;
> }
> ```
