### ISSUE TITLE
tzdata-2021b is available

### ISSUE THREAD

**Issue by lhorie** [moment/moment-timezone#958]
### Moment-timezone version which you use:

Version: 0.5.33

### Issue description:

There's an update to tzdata. See [this](https://www.mail-archive.com/package-announce@lists.fedoraproject.org/msg286093.html) for more info.

As far as I can tell, the latest moment-timezone build uses [2021a](https://github.com/moment/moment-timezone/blob/develop/builds/moment-timezone-with-data-2012-2022.js#L694) and needs to be updated

**Comment by gilmoreorless** [comment]
More than that, [2021d was released a few hours ago](http://mm.icann.org/pipermail/tz-announce/2021-October/000068.html) thanks to Fiji's late announcement about DST.

I'd create a PR to update the data, but the past few community PRs for data releases haven't got a response from maintainers (#834, #899).

**Comment by lhorie** [comment]
it appears 0.5.34 has tzdata 2021e
