### ISSUE TITLE
Brazilian timezone (America/Sao_Paulo) - Daylight saving issue is back

### ISSUE THREAD

**Issue by pedroh2604** [moment/moment-timezone#967]
### Moment-timezone version which you use:

Version: 0.5.34

### Issue description:
Daylight saving is permanently cancelled in Brazil, but it is still being considered for 2021 dates.
If I run `moment().format()` it returns me `2021-11-24T18:36:39-02:00`, but it should return me `-03:00`

Apparently the [issue](https://github.com/moment/moment-timezone/issues/797) solved on version `0.5.27` only solved the problem for 2020 dates.

**Comment by gask** [comment]
Up

**Comment by gilmoreorless** [comment]
If you're calling `moment()` directly instead of `moment.tz()`, then the Moment Timezone data isn't being used at all, only the core Moment module. Calling `moment().format()` defaults to the user's local time, which is environment-dependent.

1. Which browser (or other environment such as NodeJS) are you running when you get this result? Which version?
2. What result do you get when you run `new Date().toString()`? Does it have the correct offset?
3. If you run `moment.tz('America/Sao_Paulo').format()`, do you get the correct offset?

**Comment by yechielby-nice** [comment]
`moment.tz.guess()`
**'America/Sao_Paulo'**

`date = new  Date()   `
Tue Jan 04 2022 07:07:53 GMT-0300 **(Brasilia Standard Time)**

`moment(date).format()`
'2022-01-04T07:07:53-03:00' ✔️

`moment(date).utcOffset()`
-180 ✔️

============================================================

`moment.tz(moment.tz.guess()).utcOffset()` //moment('America/Sao_Paulo').utcOffset()
-120 ❌

`moment(moment.tz(moment.tz.guess()).format()).utcOffset()`
-180 ✔️

============================================================

```
m = moment(date)
m.utcOffset()
```
-180 ✔️

`m.format()`
'2022-01-04T07:07:53-03:00' ✔️
```
m.tz('America/Sao_Paulo')
m.utcOffset()
```
-120 ❌

`m.format()`
'2022-01-04T**08**:07:53-**02:00**' ❌

**Comment by rhuangabrielsantos** [comment]
Up

**Comment by gilmoreorless** [comment]
I haven't been able to reproduce the same results using Moment Timezone `0.5.34`, even when setting my computer's local time to `America/Sao_Paulo`. For example:

```js
$ TZ=America/Sao_Paulo node
> moment = require('moment-timezone')
> moment.tz.guess()
'America/Sao_Paulo'
> date = new Date()
'Sun Jan 23 2022 08:05:14 GMT-0300 (Brasilia Standard Time)'
> moment(date).format()
'2022-01-23T08:05:14-03:00'
> moment(date).utcOffset()
-180
> moment.tz(moment.tz.guess()).utcOffset()
-180
> moment(moment.tz(moment.tz.guess()).format()).utcOffset()
-180
> m = moment(date)
> m.utcOffset()
-180
> m.tz('America/Sao_Paulo')
> m.utcOffset()
-180
> m.format()
'2022-01-23T08:05:14-03:00'
> moment.tz.dataVersion
'2021e'
> moment.tz.version
'0.5.34'
```

According to the data files, the updates made for `0.5.27` are still in effect, and `America/Sao_Paulo` is permanently on the `-03:00` offset. What do you get if you run `moment.tz.dataVersion`? Which browser (or other environment such as NodeJS) are you running when you get this result, and which version?

----

On another note (for other commenters), posting a comment of just "Up" is not constructive or helpful. It doesn't get the issue looked at any faster, it just spams the ~100 people watching this repository.
