### ISSUE TITLE
JSON data as Javascript for Bower

### ISSUE THREAD

**Issue by shaqq** [moment/moment-timezone#97]
When bower installing `moment-timezone`, the data is installed as json files. While for some projects that's fine to get the data asynchronously with AJAX, it's not as useful for projects like ours where we minify/concatenate a front-end application and deploy it. This build process, I imagine, is pretty common as well.

Is there a way to have a separate github repository for the bower package ([Angular does it](https://github.com/angular/bower-angular)) where the json data is wrapped with

```
moment.tz.add("zones_in_latest.json");moment.tz.link("links_in_latest.json");
```

And then include the data file in the `main` property in your `bower.json`. This way, projects that are front-end clients can easily install and manage this awesome tool with bower.

**Comment by shadesoflight** [comment]
@timrwood As of version 0.3.1, when I bower install moment-timezone, there does not exist a moment-timezone-with-data.js in my moment-timezone folder.

*Edit* Oh, there's a 'builds' folder!  Yup.  That's where they are...

**Comment by stephent** [comment]
The bower spec as of 0.5.0 defaults to using "moment-timezone-with-data-2010-2020.min.js" at present. If I want "moment-timezone-with-data.min.js" instead, what's the best approach to achieving that? Editing .bower after running 'bower install'? (That seems potentially fragile if the module was ever installed and reinstalled.)

Appreciate any guidance.

**Comment by chadfurman** [comment]
@stephent fork

**Comment by stephent** [comment]
@chadfurman seems like a drastic step for what is essentially configuration...

**Comment by chadfurman** [comment]
You're changing a dependency.  You can fork and send a PR, or you can change the dependency in the cloned down repo w/o a PR and worry about it getting erased.

**Comment by Zemke** [comment]
Another problem with forking is that it cannot be easily applied to all releases. One would need to update the own fork when willing to update moment-timezone.
