### ISSUE TITLE
Why there is 1 hour difference with Fiji Time, FJT

### ISSUE THREAD

**Issue by nilesh-spinx** [moment/moment-timezone#970]
### Moment-timezone version which you use:

Version: 2.22.2
https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js
https://cdnjs.cloudflare.com/ajax/libs/moment-timezone/0.5.31/moment-timezone-with-data-2012-2022.min.js

Issue:
12 Hours: https://drive.google.com/file/d/1rL3wZoZuhMJ93erTc_iWtTtVQSVm090N/view?usp=sharing
13 hours: https://drive.google.com/file/d/1D7yz09F9XwY03ccXRG6zrFfqtpgC_bRU/view?usp=sharing

We are using Moment timezone JS, client has registered an issue that there is an hour issue, please check with the above two screenshots, where you can see that Moment is having 13+ hours where the client's time zone is having +12 hours.

Can you please guide us on why there is an hours difference?

**Comment by gilmoreorless** [comment]
The Fijian government made [a fairly late announcement](https://www.timeanddate.com/news/time/fiji-no-dst-2021.html) that they were cancelling daylight saving time for 2021/22. This meant a delay in time zone libraries picking up the change.

The underlying IANA database released the update in [version 2021d](https://data.iana.org/time-zones/tzdb-2021d/NEWS), which is included in `moment-timezone` version `0.5.34`. If you upgrade to that version you should get the correct data.

**Comment by ichernev** [comment]
:cherries: :cake: @gilmoreorless thank you!
