### ISSUE TITLE
moment.tz inadequately handles ISO string passed in without timezone as second argument

### ISSUE THREAD

**Issue by jayarjo** [moment/moment-timezone#971]
### Moment-timezone version which you use:

Version: 0.5.34

### Issue description:

CodePen: https://codepen.io/david-barbakadze/pen/BamKPMO

### What happens

`moment.tz` accepts ISO string as a single argument, but outputs current local time in UTC

### Expected beahvior

When timezone is not passed as a second argument `moment.tz` should either throw an error or assume that timezone to be users local timezone and adequately parse the passed ISO string and convert it to users current local timezone.

**Comment by gilmoreorless** [comment]
The CodePen example is calling `moment().tz(isoString)`. This is constructing a Moment object with the current local time (`moment()`), then trying to convert it to a named time zone called `'2022-01-31T16:22:10.899+02:00'`. That's an invalid zone name, so Moment Timezone logs an error in the browser console:

```
Moment Timezone has no data for 2022-01-31T16:22:10.899+02:00. See http://momentjs.com/timezone/docs/#/data-loading/.
```

Additionally, it looks like the CodePen setup is loading the base Moment Timezone library, but not a version with data included (which would also be affecting any example calculations).
