### ISSUE TITLE
Regarding wrong time for uk

### ISSUE THREAD

**Issue by ChetancodeDrill** [moment/moment-timezone#980]
### Moment-timezone version which you use:

Version:0.5.33

_Note: many issues are resolved if you just upgrade to the latest version_

Hey ,
   In winter UK (London) time coming perfect but now in summer data is not coming correct for uk time 
   Like in uk in there is 2 timezone GMT and BST In winter they both are same but in Winter there is difference between data I think so moment-timezone picking up GMT time zone in summer also
   
   Thanks,
   Please try to REPLY ASAP

**Comment by gilmoreorless** [comment]
There's not quite enough information here to be able to work out the problem.

Do you have a code sample that returns the wrong time zone? When I check the data for `Europe/London` it looks correct for the winter/summer switch:

```js
moment.tz('2022-05-01T12:00', 'Europe/London').format('LT Z z')
// "12:00 PM +01:00 BST"

moment.tz('2022-02-01T12:00', 'Europe/London').format('LT Z z')
// "12:00 PM +00:00 GMT"
```
