### ISSUE TITLE
[TypeScript] moment 2.29.3 Property 'tz' does not exist on type 'typeof moment' 

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [moment/moment-timezone#981]
### Versions:
* moment-timezone: 0.5.34
* moment: 2.29.3
* TypeScript: 4.6.3
* Node: 16.14.2

### Issue description:
```ts
import 'moment-timezone';
import moment from 'moment';
moment.tz.setDefault('UTC');
```

Gives the following  TypeScript compilation error:
```
Property 'tz' does not exist on type 'typeof moment' 
```

Downgrading to moment 2.9.2 fixes the issue, I **don't** have @types/moment-timezone installed.

Seems similar to #385

**Comment by AbdelrahmanHafez** [comment]
@aailyin 
For what it's worth, you don't need @types/moment-timezone anymore, the [`moment-timezone`](https://www.npmjs.com/package/moment-timezone) is shipped with its own types.

**Comment by aailyin** [comment]
@AbdelrahmanHafez Ah, you're right. Removed. Thanks!

**Comment by gilmoreorless** [comment]
This is probably caused by having multiple versions of `moment` in your package dependencies somewhere. See https://github.com/moment/moment-timezone/issues/982#issuecomment-1119540905 for a more detailed explanation.

**Comment by AbdelrahmanHafez** [comment]
I ended up removing `import moment from 'moment'` altogether in favor of `import moment from 'moment-timezone'.
I also removed `moment` from package.json.

The expectation here is to have the same exact behavior, and `moment.tz.setDefault('UTC');` will reflect on everywhere as it was before with moment. Correct? @gilmoreorless

**Comment by gilmoreorless** [comment]
@AbdelrahmanHafez that sounds right to me.

**Comment by AbdelrahmanHafez** [comment]
@gilmoreorless Thank you 👍
