### ISSUE TITLE
Package Release with distribution content only

### ISSUE THREAD

**Issue by gamma** [moment/moment-timezone#984]
### Moment-timezone version which you use:

Version: any

_Note: many issues are resolved if you just upgrade to the latest version_

### Issue description:

Please create a publishing package that only contains the distribution files, not the source, test, and build scripts files. All other files should reside in the sources package. I'm referring to release to e.g. https://repo1.maven.org/maven2/org/webjars/moment-timezone/

**Comment by gilmoreorless** [comment]
As far as I know, Moment Timezone is only officially published to the `npm` package registry. There are no build or test files in the package contents (as can be seen at https://unpkg.com/browse/moment-timezone@0.5.34/).

The link you've posted is for a Java Maven package, which hasn't been updated in over 5 years. I don't know who published that package, but I doubt it came from the Moment Timezone maintainers.
