### ISSUE TITLE
KyivNotKiev

### ISSUE THREAD

**Issue by IrinaMatviichuk** [moment/moment-timezone#986]
### Moment-timezone version which you use:

Version:

_Note: many issues are resolved if you just upgrade to the latest version_

### Issue description:

The name of the capital of Ukraine is incorrect in timezone Europe/Kiev

https://en.wikipedia.org/wiki/KyivNotKiev

**Comment by gilmoreorless** [comment]
Moment Timezone gets its data from the IANA time zone database (tzdb). The rename has been done in the IANA source ([see commit](https://github.com/eggert/tz/commit/e13e9c531fc48a04fb8d064acccc9f8ae68d5544)) and will be in the next release of the database. Then it can be brought into Moment Timezone.

**Comment by gilmoreorless** [comment]
There's now an open PR (#996) to update Moment Timezone to use tzdb 2022b as well. I suspect that it might take a while to be merged and released, though. Ironically for this issue, the primary maintainer of Moment Timezone (@ellenaua) lives in Ukraine, so this open source work is probably low on their priority list at the moment.

**Comment by ichernev** [comment]
Yep, this is now released as 0.5.36 using 2022c.
