### ISSUE TITLE
moment().add() -> days is not working

### ISSUE THREAD

**Issue by TheFreeman** [moment/moment-timezone#990]
### Moment-timezone version which you use:

Version: 0.5.34

_Note: many issues are resolved if you just upgrade to the latest version_

### Issue description:

add() in addition with 'days' is not working anymore.
not `add(1, 'days')` nor `add({ days: 1})` nor `add(1, 'd')`

Example:
```
let moment = moment();
moment.add(1, 'days');
console.log(moment.format('W');
```

**Comment by ichernev** [comment]
Works for me... also why report it here.

**Comment by TheFreeman** [comment]
I`m sorry for that.
We are using "timezone", and this was causing that problem. :-)
