### ISSUE TITLE
Abbreviation missing for multiple zones

### ISSUE THREAD

**Issue by kiran-pathe** [moment/moment-timezone#992]
### Moment-timezone version which you use:

Version: 0.5.34

### Issue description:

I have changed my system time to (UTC-09:00) Coordinated Universal Time
When i try to print zone abbr it's showing number as -09.
`
moment.tz(moment.tz.guess()).zoneAbbr();
`

I have created demo [link ](https://angular-ivy-deyvki.stackblitz.io) for which zoneAbbr are missing.
I have found some old issues link below. Did we get any workaround for this.
https://github.com/moment/moment-timezone/issues/500
https://github.com/fossasia/open-event-frontend/pull/5798 (will this resolve my issue? is it merged in master?)
https://github.com/moment/moment-timezone/issues/841

**Comment by ichernev** [comment]
check https://github.com/moment/moment-timezone/issues/723
