### ISSUE TITLE
Iana update August 2022

### ISSUE THREAD

**Issue by moranza** [moment/moment-timezone#995]
### Moment-timezone version which you use:

Version:

_Note: many issues are resolved if you just upgrade to the latest version_

### Issue description:

Hi,
there is a new release about IANA tz for timezone: 2022d
[iana.org/time-zones/repository/tzdb-latest.tar.lz](https://data.iana.org/time-zones/releases/tzdb-2022b.tar.lz)

Is there any update in progress for the lib?

Moran.

**Comment by dcxn** [comment]
Indeed, `2022b (Released 2022-08-10)` https://www.iana.org/time-zones

Can we expect an update?

**Comment by jasonmobley** [comment]
Pull request #996 covers this
